// Round 22: the tile maps of the holds in the four act regions (pure data, so shots/holdcheck.mjs can test them).
// 3 m tiles, laid out by hand. The legend (holds.js reads it):
//   # wall (rock, brick, reed or timber, by the hold's kit)   . floor   ~ drop (a chasm, a pit or deep water)
//   = plank bridge   w low wall   p pillar   x cracked wall   h loose stones (a hidden way, only a glint shows it)
//   g barred gate (opens from its far side)   L lever   D portcullis (the lever lifts it)
//   b sunken bridge (a drop until the lever raises it)   K pressure plate (a trap)   o shallows (wade, slowed)
//   E entrance   C campfire   m foes   a archers   M the captain halfway   B the master   T his chest   S hidden chest
export const MAPS22 = {
  // the Sawad (Acts I-III) ------------------------------------------------------------------------------------
  // a caravanserai left to the sand: broken courtyards, a well shaft, a sunken bridge over the old cistern
  caravan: [
    '##############################',
    '########..............########',
    '#######..p....B.....p..#######',
    '#######................#######',
    '#######..p..........p..#######',
    '########......T.......########',
    '###########...C...############',
    '###########.......############',
    '#######~~~~~~~b~~~~~~~########',
    '#######~~~~~~~b~~~~~~~########',
    '#######...a...b.....a.########',
    '#######.......K.......########',
    '#######..w.........w..x..S####',
    '#######.......m.......#...####',
    '########.............#########',
    '##########...M...#############',
    '#########.........############',
    '#########..p...p..L###########',
    '##########.......#############',
    '###########.....##############',
    '############...###############',
    '###########..m..##############',
    '##########.......#############',
    '#########....a....############',
    '#########.........############',
    '##########...C...#############',
    '###########.....##############',
    '############.E.###############',
    '############...###############',
    '##############################',
  ],
  // the clay pits under the kilns: deep pits, plank ways, vents of hot smoke; Hisham's men hold the bottom
  kilnpits: [
    '##############################',
    '#########............#########',
    '########..p........p..########',
    '########......B.......########',
    '########..p........p..########',
    '#########.....T......#########',
    '############..C..#############',
    '############.....#############',
    '#######~~~~~~=~~~~~~##########',
    '#######~~~~~~=~~~~~~##########',
    '#######..a...=....K.h..S######',
    '#######..............###.#####',
    '########....m.....m..#########',
    '#########...........##########',
    '##########...KK....###########',
    '###########...M...############',
    '##########.........###########',
    '#########..p.....p..g.....####',
    '##########.........##.....####',
    '###########.......###..m..####',
    '#####~~~=~~~~.....###.....####',
    '#####~~~=~~~~.....####...#####',
    '#####...=...~~~.....w....#####',
    '#####..m....~~~..........#####',
    '######.......~~...a...########',
    '#######...........############',
    '########....C....#############',
    '#########.......##############',
    '##########..E..###############',
    '##############################',
  ],
  // the Nahrawan marshes (Act IV) -------------------------------------------------------------------------------
  // Sahl's reed islands: mudhif halls on mounds, causeways and wading channels, a sunken plank way
  reedisle: [
    '##############################',
    '#####~~~~...........~~~~######',
    '#####~~~..p.......p..~~~######',
    '#####~~~......B.......~~######',
    '#####~~~..p.......p..~~~######',
    '#####~~~~.....T.....~~~~######',
    '#####~~~~~~...C...~~~~~~######',
    '#####~~~~~~~ooooo~~~~~~~######',
    '#####~~~~~~~ooooo~~~~~~~######',
    '#####~~...a..ooo.....a.~######',
    '#####~~........m........######',
    '#####~~~~...w.....w..~~~######',
    '#####~~~~~~.......~~~~~~######',
    '#####~~~~~~~~=~~~~~~~~~~######',
    '#####~~~~~~~~=~~~~~~~~~~######',
    '#####~~~~~.......~~~~~~~######',
    '#####~~~~...p.p...~~~~~~######',
    '#####~~~~....M....bbbb..S#####',
    '#####~~~~...p.p...~~~~..######',
    '#####~~~~~.......~~~~~~~######',
    '#####~~~~~~~ooo~~~~~~~~~######',
    '#####~~~~~~~ooo~~~~~~~~~######',
    '#####~~~..m..o..a...L~~~######',
    '#####~~~............~~~~######',
    '#####~~~~~...m....~~~~~~######',
    '#####~~~~~~~ooo~~~~~~~~~######',
    '#####~~~~~~.....~~~~~~~~######',
    '#####~~~~~~..C..~~~~~~~~######',
    '#####~~~~~~..E..~~~~~~~~######',
    '##############################',
  ],
  // the old Sasanian weir: a broken dam of fired brick, the race below it, sluice gates on a lever
  weir: [
    '##############################',
    '########..............########',
    '#######..p....B.....p..#######',
    '#######................#######',
    '#######..p..........p..#######',
    '########......T.......########',
    '###########...C...############',
    '############.....#############',
    '#############D################',
    '####~~~~~~~~~=~~~~~~~~~~######',
    '####~~~~~~~~~=~~~~~~~~~~######',
    '####~~~~...a.....a...~~~######',
    '####~~~~.....m........x...S###',
    '####~~~~~~.......~~~~~#####.##',
    '####~~~~~~~~=~~~~~~~~~########',
    '####~~~~~~~~=~~~~~~~~~########',
    '#######...........############',
    '######..p...M...p..###########',
    '######.............g......L###',
    '#######...........##.......###',
    '########...KK....###...m...###',
    '#########.......####.......###',
    '####~~~~~~=~~~~~~~~##.....####',
    '####~~~~~~=~~~~~~~~###...#####',
    '####~~ooo.....m.ooo~~~...#####',
    '####~~~oo.........o~~~...#####',
    '#####~~~~...a...~~~~~...######',
    '#######......C.........#######',
    '########.....E.....###########',
    '##############################',
  ],
  // al-Karkh (Act V) --------------------------------------------------------------------------------------------
  // the burned lanes behind the paper-sellers: gutted houses, fallen-in cellars, a courtyard Layth holds
  lanes: [
    '##############################',
    '#######...............########',
    '#######..p.........p..########',
    '#######.......B.......########',
    '#######..p.........p..########',
    '########......T......#########',
    '###########...C...############',
    '###########.......############',
    '###########...K...############',
    '#####.......w...w.....h..S####',
    '#####..a.............##..#####',
    '#####......m.....m...#########',
    '#####~~~~~.......~~~~#########',
    '#####~~~~~~=~~~~~~~~~#########',
    '#####~~~~~~=~~~~~~~~~#########',
    '######.....=......############',
    '######..p.....p...############',
    '######.....M......g......#####',
    '######..p.....p...#..m...#####',
    '#######..........##......#####',
    '########...KK...###...a..#####',
    '#########......####......#####',
    '########.......#####....######',
    '#######...m.....####....######',
    '######......w....###...#######',
    '#######..a........w....#######',
    '########.....C.......#########',
    '#########.........############',
    '###########..E..##############',
    '##############################',
  ],
  // the merchants' undercroft: brick vaults under the burned khans, a cistern floor, a portcullis on a lever
  undercroft: [
    '##############################',
    '#######...............########',
    '#######..p....B....p..########',
    '#######...............########',
    '#######..p.........p..########',
    '########......T......#########',
    '###########...C...############',
    '###########.......############',
    '##############D###############',
    '#######..p.........p..########',
    '#######......a........x...S###',
    '#######..p.........p..####.###',
    '#######oooooo...oooooo########',
    '#######oooooo.m.oooooo########',
    '########ooooo...ooooo#########',
    '###########...M...############',
    '##########..p...p..###########',
    '###########.......#####...L###',
    '############.....g.......#####',
    '###########.......####...#####',
    '##########..K...K..###.m.#####',
    '#########...........##...#####',
    '########.....m.......#...#####',
    '#######..p.........p.....#####',
    '#######.......a......#########',
    '########.............#########',
    '##########....C....###########',
    '###########.......############',
    '#############.E.##############',
    '##############################',
  ],
  // the river quays (Act VI) ------------------------------------------------------------------------------------
  // a beached river hulk: down the gangplank, through the hold, along the deck; Mus'ab waits at the stern
  hulk: [
    '##############################',
    '~~~~~~~#..............#~~~~~~~',
    '~~~~~~~#..p...B....p..#~~~~~~~',
    '~~~~~~~#..............#~~~~~~~',
    '~~~~~~~#..p........p..#~~~~~~~',
    '~~~~~~~##.....T......##~~~~~~~',
    '~~~~~~~~###...C...###~~~~~~~~~',
    '~~~~~~~~~##.......##~~~~~~~~~~',
    '~~~~~~~~~~~##~b~##~~~~~~~~~~~~',
    '~~~~~~~~~~~~#~b~#~~~~~~~~~~~~~',
    '~~~~~~~##...........##~~~~~~~~',
    '~~~~~~##..a.......a..h..S#~~~~',
    '~~~~~~#.....w...w....####~~~~~',
    '~~~~~~#.......m......#~~~~~~~~',
    '~~~~~~##...........##~~~~~~~~~',
    '~~~~~~~##..p...p..##~~~~~~~~~~',
    '~~~~~~~#.....M.....#~~~~~~~~~~',
    '~~~~~~~#...........#~~~~~~~~~~',
    '~~~~~~~##.........L#~~~~~~~~~~',
    '~~~~~~~~##.KK.KK.##~~~~~~~~~~~',
    '~~~~~~~~#....m....#~~~~~~~~~~~',
    '~~~~~~~##.a.....a.##~~~~~~~~~~',
    '~~~~~~~#...........#~~~~~~~~~~',
    '~~~~~~~##.........##~~~~~~~~~~',
    '~~~~~~~~##...C...##~~~~~~~~~~~',
    '~~~~~~~~~###...###~~~~~~~~~~~~',
    '~~~~~~~~~~~#.=.#~~~~~~~~~~~~~~',
    '~~~~~~~~~~~#.E.#~~~~~~~~~~~~~~',
    '~~~~~~~~~~~#...#~~~~~~~~~~~~~~',
    '##############################',
  ],
  // the warehouse maze: bales, crates and stacked timber; crossbowmen on the bales, a cracked brick wall
  warehouse: [
    '##############################',
    '#######...............########',
    '#######..p.........p..########',
    '#######.......B.......########',
    '#######..p.........p..########',
    '########......T......#########',
    '###########...C...############',
    '###########.......############',
    '#######..w....K....w..x..S####',
    '#######.a...........a.#..#####',
    '#######....m.....m....########',
    '########..w.......w..#########',
    '##########.........###########',
    '#########...p...p...##########',
    '#########.....M.....##########',
    '#########...p...p...g......###',
    '##########.........##..m...###',
    '###########.......###......###',
    '####......w...w....###...a.###',
    '####.a....KK..........##...###',
    '####...w......w...m...##..####',
    '#####..........########...####',
    '######...m....#########...####',
    '#######.......L########..#####',
    '########.....##########..#####',
    '#########....C............####',
    '##########.......#############',
    '###########..E..##############',
    '###########.....##############',
    '##############################',
  ],
};

// the holds themselves: where each one opens (near a site of its region), its kit, its men and its two captains.
// story: 'second' = the act's second lieutenant waits at its end while his quest is open (then its own master holds it)
export const HOLDS22 = {
  caravan: { region: 'sawad', kit: 'brick', drop: 'pit', title: 'The Sand-Choked Khan', sub: 'A caravan station the dunes took back', rock: 0xc8a882, wall: 0xb89870, floor: [0xa89070, 'sand'], pool: ['bandit', 'deserter', 'spearman'], ranged: ['archer', 'crossbow'], mid: 'jasir', boss: 'daghfal', codex: 'khans', level: 3, light: 'golden', near: ['serai', 14, -24], door: 'arch', hpK: 0.45 },
  kilnpits: { region: 'sawad', kit: 'brick', drop: 'pit', title: 'The Kiln Pits', sub: 'Clay pits under the kilns, where the Pages burn', rock: 0x9a6a4a, wall: 0x8a5a3a, floor: [0x7a5a40, 'earth'], pool: ['deserter', 'spearman', 'naffat'], ranged: ['archer'], mid: 'kurz', boss: 'khalaf', story: 'second', codex: 'claypits', level: 4, light: 'dusk', near: ['kiln', -14, -12], door: 'pit', hpK: 0.5 },
  reedisle: { region: 'marsh', kit: 'reed', drop: 'water', title: 'The Reed Islands', sub: 'Reed halls on mounds above the channels', rock: 0xb09a68, wall: 0x8a7a5a, floor: [0x6a5a40, 'earth'], wet: 0.6, pool: ['reedman', 'netter', 'bandit', 'spearman'], ranged: ['slinger'], mid: 'ruhm', boss: 'bakkar', story: 'second', codex: 'reedisles', level: 9, light: 'mist', near: ['kiln', 6, -16], door: 'reed', hpK: 0.6 },
  weir: { region: 'marsh', kit: 'rock', drop: 'water', title: 'The Sunken Weir', sub: 'The broken Sasanian dam and the race below it', rock: 0xa89a84, wall: 0x8a7a64, floor: [0x8a7a62, 'flag'], wet: 0.4, pool: ['spearman', 'netter', 'bandit'], ranged: ['slinger', 'crossbow'], mid: 'qanab', boss: 'jahdar', codex: 'weirs', level: 9, light: 'mist', near: ['arch', -22, 12], door: 'arch', hpK: 0.65 },
  lanes: { region: 'karkh', kit: 'brick', drop: 'pit', title: 'The Burned Lanes', sub: 'Gutted houses behind the paper-sellers', rock: 0x8a7462, wall: 0x6a5a4a, floor: [0x6a5a4a, 'road'], pool: ['guard', 'deserter', 'naffat'], ranged: ['archer', 'crossbow'], mid: 'nawfal', boss: 'dirgham', story: 'second', codex: 'lanes', level: 12, light: 'haze', near: ['kiln', -10, 12], door: 'arch', hpK: 0.75 },
  undercroft: { region: 'karkh', kit: 'brick', drop: 'pit', title: 'The Merchants\' Undercroft', sub: 'Brick vaults under the burned khans', rock: 0x9a846a, wall: 0x7a6a58, floor: [0x7a6a58, 'flag'], wet: 0.5, pool: ['guard', 'spearman', 'deserter'], ranged: ['crossbow', 'archer'], mid: 'musawir', boss: 'raddad', codex: 'vaults', level: 12, light: 'underground', near: ['serai', 20, -14], door: 'pit', hpK: 0.8 },
  hulk: { region: 'docks', kit: 'timber', drop: 'water', wallH: 2.2, title: 'The Beached Hulk', sub: 'A river hulk run aground by the boatyard', rock: 0x7a5a3a, wall: 0x6a5040, floor: [0x6a5038, 'road'], water: 0x2a4048, pool: ['guard', 'crossbow', 'deserter'], ranged: ['crossbow'], mid: 'shuja', boss: 'thalaba', story: 'second', codex: 'hulks', level: 15, light: 'dusk', near: ['kiln', 18, 6], door: 'plank', hpK: 0.85 },
  warehouse: { region: 'docks', kit: 'timber', drop: 'water', title: 'The Bale Stores', sub: 'Warehouses of bales and timber on the quay', rock: 0x8a6a48, wall: 0x7a6048, floor: [0x7a6a58, 'road'], pool: ['guard', 'engineer', 'spearman'], ranged: ['crossbow', 'crossbow'], mid: 'hurmuz', boss: 'marzuq', codex: 'bales', level: 15, light: 'haze', near: ['serai', -18, 14], door: 'arch', hpK: 0.9 },
};
// their captains (moves from holds.js MOVES); look: built like any captain, each in his own colour
export const BOSS22 = {
  jasir: { name: 'Jasir', sub: 'Who strips the caravans', type: 'deserter', look: { scale: 1.4, crest: 'hat', sash: 0x8a5a2a }, hp: 10, dmg: 1.4, moves: ['swing', 'charge', 'sweep'], p2: { at: 0.5, line: 'Bring the roof down on him!', add: ['rockfall'] } },
  daghfal: { name: 'Daghfal', sub: 'Master of the sand-choked khan', type: 'spearman', look: { scale: 1.5, crest: 'plume', sash: 0xa86a2a }, hp: 14, dmg: 1.5, moves: ['swing', 'sweep', 'arrows', 'charge'], p2: { at: 0.5, line: 'Up on the walls! Shoot!', add: ['summon', 'rockfall'], summon: ['archer', 'bandit', 'bandit'] } },
  kurz: { name: 'Kurz', sub: 'Foreman of the kiln fires', type: 'naffat', look: { scale: 1.45, crest: 'hat', sash: 0x7a2a10 }, hp: 10, dmg: 1.4, moves: ['swing', 'firepots', 'fireline'], p2: { at: 0.5, line: 'Feed the fires!', add: ['summon'], summon: ['naffat', 'deserter'] } },
  khalaf: { name: 'Khalaf', sub: 'Keeper of the clay pits', type: 'spearman', look: { scale: 1.5, crest: 'heavy', sash: 0x5a2a1a }, hp: 14, dmg: 1.5, moves: ['swing', 'slam', 'crack', 'charge'], p2: { at: 0.5, line: 'Break the ground under him!', add: ['stomp', 'rockfall'] } },
  ruhm: { name: 'Ruhm', sub: 'Who nets the channels', type: 'netter', look: { scale: 1.4, crest: 'mantle', sash: 0x3a5a3a, cloak: 0x3a5a3a }, hp: 12, dmg: 1.4, moves: ['swing', 'net', 'sweep'], p2: { at: 0.5, line: 'Into the water with him!', add: ['summon'], summon: ['reedman', 'reedman', 'netter'] } },
  bakkar: { name: 'Bakkar', sub: 'Headman of the reed islands', type: 'spearman', look: { scale: 1.5, crest: 'banner', sash: 0x4a6a3a }, hp: 16, dmg: 1.5, moves: ['swing', 'net', 'charge', 'arrows'], p2: { at: 0.5, line: 'Burn the reeds behind him!', add: ['fireline', 'summon'], summon: ['slinger', 'reedman', 'netter'] } },
  qanab: { name: 'Qa\'nab', sub: 'Keeper of the sluices', type: 'bandit', look: { scale: 1.45, crest: 'hat', sash: 0x2a4a5a }, hp: 12, dmg: 1.4, moves: ['swing', 'charge', 'crack'], p2: { at: 0.5, line: 'Open the sluice!', add: ['stomp'] } },
  jahdar: { name: 'Jahdar', sub: 'Master of the weir', type: 'guard', look: { scale: 1.55, crest: 'heavy', sash: 0x1a3a4a, offhand: 'shield' }, hp: 16, dmg: 1.5, block: 0.85, moves: ['swing', 'charge', 'slam', 'arrows'], p2: { at: 0.5, line: 'Men of the weir, to me!', add: ['summon', 'rockfall'], summon: ['spearman', 'slinger', 'crossbow'] } },
  nawfal: { name: 'Nawfal', sub: 'Who torched the lane', type: 'guard', look: { scale: 1.45, crest: 'mantle', sash: 0x6a1a14, cloak: 0x4a120e }, hp: 14, dmg: 1.5, moves: ['swing', 'firepots', 'charge'], p2: { at: 0.5, line: 'Let it all burn again!', add: ['fireline'] } },
  dirgham: { name: 'Dirgham', sub: 'Captain of the burned lanes', type: 'guard', look: { scale: 1.55, crest: 'banner', sash: 0x3a1a1a, cloak: 0x2a0e0a }, hp: 18, dmg: 1.6, moves: ['swing', 'sweep', 'arrows', 'slam'], p2: { at: 0.5, line: 'Bring the house down!', add: ['rockfall', 'summon'], summon: ['guard', 'archer', 'naffat'] } },
  musawir: { name: 'Musawir', sub: 'Who keeps the vault keys', type: 'spearman', look: { scale: 1.45, crest: 'hat', sash: 0x5a4a2a }, hp: 14, dmg: 1.5, moves: ['swing', 'charge', 'sweep'], p2: { at: 0.5, line: 'Bar the doors!', add: ['summon'], summon: ['guard', 'guard'] } },
  raddad: { name: 'Raddad', sub: 'Master of the undercroft', type: 'guard', look: { scale: 1.55, crest: 'plume', sash: 0x2a2a5a, offhand: 'shield' }, hp: 18, dmg: 1.6, block: 0.85, moves: ['swing', 'slam', 'charge', 'arrows'], p2: { at: 0.5, line: 'Drop the vault on him!', add: ['rockfall', 'stomp'] } },
  shuja: { name: 'Shuja\'', sub: 'Bosun of the hulk', type: 'deserter', look: { scale: 1.45, crest: 'hat', sash: 0x2a3a5a }, hp: 14, dmg: 1.5, moves: ['swing', 'net', 'charge'], p2: { at: 0.5, line: 'Cut him loose into the river!', add: ['sweep'] } },
  thalaba: { name: 'Tha\'laba', sub: 'Master of the hulk', type: 'guard', look: { scale: 1.55, crest: 'heavy', sash: 0x1a2a4a }, hp: 18, dmg: 1.6, moves: ['swing', 'sweep', 'arrows', 'charge'], p2: { at: 0.5, line: 'Crossbows, from the rail!', add: ['summon', 'stomp'], summon: ['crossbow', 'crossbow', 'guard'] } },
  hurmuz: { name: 'Hurmuz', sub: 'Keeper of the bale stores', type: 'engineer', look: { scale: 1.45, belly: 0.4, crest: 'hat', sash: 0x6a4a1a }, hp: 14, dmg: 1.5, moves: ['swing', 'crack', 'slam'], p2: { at: 0.5, line: 'Bring the stacks down!', add: ['rockfall'] } },
  marzuq: { name: 'Marzuq', sub: 'Master of the warehouses', type: 'guard', look: { scale: 1.55, crest: 'banner', sash: 0x4a2a1a }, hp: 18, dmg: 1.6, moves: ['swing', 'charge', 'sweep', 'firepots'], p2: { at: 0.5, line: 'Fire the bales!', add: ['fireline', 'summon'], summon: ['crossbow', 'engineer', 'guard'] } },
};
