// Arabic text for the story: dialogue, cutscene lines, tasks and the codex. Keyed by the English text with any
// markup removed (see t() in i18n.js). Missing keys simply fall back to English.
export const STORY_AR = {
  // ---------------------------------------------------------------- names
  'Salim': 'سالم', 'Ishaq': 'إسحاق', 'Ghassan': 'غسّان', 'Ziyad': 'زياد', 'Hisham': 'هشام', 'Yusuf': 'يوسف', 'Bishr': 'بشر', '\'Amr': 'عمرو',
  'Act I · The Caravan': 'الفصل الأول · القافلة', 'The Sawad, outside Baghdad, in the year 813': 'السواد، خارج بغداد، سنة ٨١٣',
  'Act II · The Kilns': 'الفصل الثاني · الأتون', 'Hisham\'s knife-men wait among the brick stacks': 'رجال هشام بسكاكينهم يتربّصون بين أكوام الآجرّ',
  'Act III · The Broken Arch': 'الفصل الثالث · الطاق المكسور', 'Ghassan holds the road beneath the ruined Persian arch': 'غسّان يمسك الطريق تحت الطاق الفارسي المهدّم',
  'Renegade commander of the siege': 'قائد المتمرّدين من أيام الحصار', 'Renegade commander of the siege of Baghdad': 'قائد المتمرّدين من أيام حصار بغداد',
  'Sands of Baghdad': 'رمال بغداد', 'Here ends the first chronicle of Salim': 'هنا تنتهي السيرة الأولى لسالم',
  'By nightfall the grain road was open again.': 'ومع حلول الليل عاد طريق الحَبّ مفتوحًا.',

  // ---------------------------------------------------------------- prologue and briefing
  'Too quiet. Even the frogs in the canal have stopped.': 'هدوء مريب. حتى ضفادع النهر سكتت.',
  'Salim! You live. When your caravan did not reach the gate, I feared the worst. I am Ishaq, astronomer of the House of Wisdom, and those were my instruments on your camels.': 'سالم! أنت حيّ. لمّا لم تبلغ قافلتك الباب خشيت الأسوأ. أنا إسحاق، فلكيّ في بيت الحكمة، وتلك كانت آلاتي على جمالكم.',
  'Salim! You live. When your caravan did not reach the gate, I feared the worst. I am Ishaq, astronomer of the Bayt al-Hikma — and those were my instruments on your camels.': 'سالم! أنت حيّ. لمّا لم تبلغ قافلتك الباب خشيت الأسوأ. أنا إسحاق، فلكيّ في بيت الحكمة، وتلك كانت آلاتي على جمالكم.',
  'The siege is over, but its soldiers did not all go home. A renegade named Ghassan gathers deserters at the ruined Persian arch to the south. He means to choke the grain road.': 'انتهى الحصار، لكنّ جنوده لم يعودوا كلّهم إلى بيوتهم. متمرّد اسمه غسّان يجمع الفارّين عند الطاق الفارسي المهدّم في الجنوب، ويريد أن يخنق طريق الحَبّ.',
  'The siege is over, but its soldiers did not all go home. A renegade named Ghassan gathers deserters at the ruined Persian arch to the south, and he means to choke the grain road.': 'انتهى الحصار، لكنّ جنوده لم يعودوا كلّهم إلى بيوتهم. متمرّد اسمه غسّان يجمع الفارّين عند الطاق الفارسي المهدّم في الجنوب، ويريد أن يخنق طريق الحَبّ.',
  'Break his lieutenants first. Ziyad holds the old caravanserai to the east, and Hisham hides his knife-men in the brick kilns across the canal. Keep your sword arm loose.': 'اكسر قادته أوّلًا. زياد يمسك الخان القديم في الشرق، وهشام يخبّئ رجاله في أفران الآجرّ عبر النهر. وأبقِ ساعدك ليّنًا.',
  'Break his lieutenants first: Ziyad holds the old caravanserai to the east, and Hisham hides his knife-men in the brick kilns across the canal. Take this sherbet, and keep your sword arm loose.': 'اكسر قادته أوّلًا: زياد يمسك الخان القديم في الشرق، وهشام يخبّئ رجاله في أفران الآجرّ عبر النهر. خذ هذا الشراب، وأبقِ ساعدك ليّنًا.',
  'Then I will bring them back. All of them.': 'إذن سأعيدها. كلّها.',
  'Hisham holds the kilns... he will not kneel as I did.': 'هشام يمسك الأفران... ولن يجثو كما جثوت.',
  'Ghassan waits at the arch. You will break on it.': 'غسّان ينتظر عند الطاق. ستتحطّم عليه.',
  'The siege fed my men for two years. Your grain road will feed them now.': 'أطعم الحصار رجالي عامين. والآن سيطعمهم طريق حَبّك.',
  'Engines! Burn the road!': 'المجانيق! أحرقوا الطريق!',
  'My instruments are home, and the House of Wisdom will hear how a caravan guard held the grain road.': 'عادت آلاتي إلى بيتها، وسيسمع بيت الحكمة كيف حمى حارس قافلة طريق الحَبّ.',
  'The Raiders Scatter': 'تفرّق الغزاة', 'Ziyad falls among the ruins of the caravanserai': 'سقط زياد بين أطلال الخان',
  'The Kilns Fall Silent': 'سكتت الأفران', 'Hisham\'s deserters flee into the dunes': 'فرّ رجال هشام إلى الكثبان',
  'The Renegade Falls': 'سقط المتمرّد', 'The grain road to Baghdad is open again': 'عاد طريق الحَبّ إلى بغداد مفتوحًا',
  'Ghassan is fallen. The caravans of the Sawad move freely once more.': 'سقط غسّان. وعادت قوافل السواد تسير آمنة.',

  // ---------------------------------------------------------------- Ishaq
  'Salim! Is that... the brass glints in your pack!': 'سالم! أهذا... النحاس يلمع في متاعك!',
  'The stars do not hurry, Salim, but Ghassan does. What do you need?': 'النجوم لا تعجل يا سالم، لكنّ غسّان يعجل. ماذا تحتاج؟',
  'Your astrolabe, teacher. Recovered from the kiln tunnels.': 'أسطرلابك يا معلّم. استعدته من أنفاق الأفران.',
  'You seem troubled. What did the raiders take?': 'تبدو مهمومًا. ماذا أخذ الغزاة؟',
  'Tell me about the House of Wisdom.': 'حدّثني عن بيت الحكمة.',
  'How did the siege come to this?': 'كيف انتهى الحصار إلى هذا؟',
  'Who were the men fighting in the streets?': 'من كان أولئك الذين قاتلوا في الشوارع؟',
  'Farewell.': 'وداعًا.', 'Farewell': 'وداعًا', 'Back.': 'رجوع.',
  'My best astrolabe, with a rete cut like lace. I made it myself over three winters. The raiders will have dragged it to their tunnels under the kilns. Hisham\'s men hoard brass to melt.': 'أفضل أسطرلاب عندي، عنكبوته مخرّمة كالدانتيل. صنعته بيدي في ثلاثة شتاءات. لا بدّ أنّ الغزاة جرّوه إلى أنفاقهم تحت الأفران؛ رجال هشام يكدّسون النحاس ليصهروه.',
  'I will find it.': 'سأجده.', 'Another time, teacher.': 'في وقت آخر يا معلّم.',
  'A library that became a workshop. We copy, we translate Ptolemy and the Indian tables, and we argue about them. The caliph pays for paper; we pay with sleep.': 'خزانة كتب صارت ورشة. ننسخ ونترجم بطليموس والأزياج الهندية ونتجادل فيها. الخليفة يدفع ثمن الورق، ونحن ندفع من نومنا.',
  'Two brothers, one throne. Tahir\'s Khurasanis came from the east. The city was burned street by street. Now al-Amin is dead, and men who learned to loot do not unlearn it.': 'أخوان وعرش واحد. جاء خراسانيّو طاهر من المشرق، وأُحرقت المدينة شارعًا شارعًا. والآن مات الأمين، ومن تعلّم النهب لا ينساه.',
  'The \'ayyarun: boys from the poor quarters with reed shields and slings, holding alleys against armoured men. Some of them are on the roads now too. Not all of them are Ghassan\'s.': 'العيّارون: فتيان من الأحياء الفقيرة بتروس من قصب ومقاليع، يمسكون الأزقّة في وجه رجال مدرّعين. بعضهم على الطرق الآن أيضًا، وليسوا كلّهم من رجال غسّان.',
  'It was in a chest, among Hisham\'s brass. Not a scratch.': 'كان في صندوق بين نحاس هشام. بلا خدش واحد.',
  'Three winters... and the rete is whole. Look, the star-pointers still sit true. You have saved more than brass, Salim.': 'ثلاثة شتاءات... والعنكبوت سليمة. انظر، مؤشّرات النجوم ما زالت في مواضعها. لقد أنقذت أكثر من نحاس يا سالم.',
  'I have little coin. But take this: a sky-chart I drew of the Sawad. With it, no road at night will lose you.': 'ليس معي مال كثير. لكن خذ هذا: خريطة سماء رسمتها للسواد. بها لن يضيّعك طريق في الليل.',
  'Or, if you would rather, I can pay you in dinars from the House\'s purse.': 'أو إن شئت، أدفع لك دنانير من كيس البيت.',
  'The chart. I would rather know the stars.': 'الخريطة. أفضّل أن أعرف النجوم.',
  'Dinars, teacher. The road is expensive.': 'الدنانير يا معلّم. الطريق مكلف.',
  'Ishaq\'s Sky-Chart': 'خريطة سماء إسحاق', 'Ishaq\'s Astrolabe': 'أسطرلاب إسحاق',

  // ---------------------------------------------------------------- Yusuf
  'The galleries are quiet. Whoever was fouling the channel will not be back.': 'الأروقة هادئة. من كان يفسد القناة لن يعود.',
  'Then the cisterns will fill sweet by the end of the week. The suq does not forget: from today my prices are yours at a discount.': 'إذن ستمتلئ الصهاريج عذبة قبل آخر الأسبوع. السوق لا ينسى: من اليوم لك أسعاري مخفّضة.',
  'Peace on your road, guard. Buying, selling... or listening? There is trouble in the water.': 'سلامة في طريقك يا حارس. تشتري أم تبيع... أم تسمع؟ في الماء مشكلة.',
  'Spices from Basra, steel from the Yemen, silk thread from Merv. What will it be?': 'توابل من البصرة، وفولاذ من اليمن، وخيوط حرير من مرو. ماذا تريد؟',
  'Show me your wares.': 'أرني بضاعتك.', 'Trouble in the water?': 'مشكلة في الماء؟', 'How does a merchant pay, out here?': 'كيف يدفع التاجر هنا؟',
  'The qanat under the well feeds this whole suq. Renegades camp in its galleries, and the water comes up foul. Clear them out, and I will remember it.': 'القناة تحت البئر تسقي السوق كلّه. المتمرّدون يخيّمون في أروقتها، فيصعد الماء فاسدًا. أخرجهم وسأحفظ لك ذلك.',
  'I will go down.': 'سأنزل.', 'Not now.': 'ليس الآن.',
  'Gold dinars for the great deals, silver dirhams for bread. And for long roads, a suftaja: a letter my cousin in Basra will honour. Paper weighs less than gold, and bandits cannot spend it.': 'دنانير الذهب للصفقات الكبيرة، ودراهم الفضّة للخبز. وللطرق الطويلة سُفتجة: كتاب يصرفه ابن عمّي في البصرة. الورق أخفّ من الذهب، واللصوص لا يستطيعون إنفاقه.',

  // ---------------------------------------------------------------- 'Amr
  'Three captains! I watched you from the walls, and I have lost good silver. Here. And take my old bayda. It turned a Khurasani lance once.': 'ثلاثة قادة! رأيتك من الأسوار، وخسرت فضّة طيّبة. خذ. وخذ بيضتي القديمة؛ ردّت رمحًا خراسانيًّا ذات مرّة.',
  'A soldier rests his arm between fights, not his mind. Train, change your way, or make a wager?': 'الجنديّ يريح ذراعه بين المعارك لا عقله. تتدرّب، أم تغيّر طريقتك، أم تراهن؟',
  'Training.': 'التدريب.', 'What wager?': 'أيّ رهان؟', 'You fought in the siege?': 'قاتلت في الحصار؟',
  'Ghassan\'s captains ride with a golden ring of men around them. Kill three of them in the field, and my purse is yours.': 'قادة غسّان يسيرون وحولهم حلقة ذهبيّة من الرجال. اقتل ثلاثة منهم في الميدان، وكيسي لك.',
  'Done.': 'اتّفقنا.', 'Not today.': 'ليس اليوم.',
  'On Tahir\'s side. Khurasani archers, mangonels, naft... and still the \'ayyarun held the Harbiyya for weeks. I do not boast about that year.': 'في صفّ طاهر. رماة خراسانيّون ومجانيق ونفط... ومع ذلك أمسك العيّارون الحربيّة أسابيع. لا أفخر بتلك السنة.',
  '\'Amr\'s Dented Bayda': 'بيضة عمرو المثلومة',

  // ---------------------------------------------------------------- tasks
  'The Lost Astrolabe': 'الأسطرلاب الضائع', 'Sweet Water': 'الماء العذب', '\'Amr\'s Wager': 'رهان عمرو',
  'Ishaq\'s finest astrolabe was taken with the caravan. Search the kiln tunnels beneath Hisham\'s yard.': 'أُخذ أفضل أسطرلاب لإسحاق مع القافلة. فتّش أنفاق الأفران تحت ساحة هشام.',
  'You found the astrolabe. Bring it back to Ishaq.': 'وجدت الأسطرلاب. أعده إلى إسحاق.',
  'Ishaq has his astrolabe again.': 'استعاد إسحاق أسطرلابه.',
  'Renegades are fouling the qanat that feeds the suq. Clear a descent of the ruined qanats.': 'المتمرّدون يفسدون القناة التي تسقي السوق. طهّر نزولًا في القنوات المهدّمة.',
  'The galleries are quiet. Tell Yusuf.': 'الأروقة هادئة. أخبر يوسف.',
  'The water runs clean, and the suq owes you.': 'الماء يجري صافيًا، والسوق مدين لك.',
  '\'Amr wagers you cannot defeat three captains of the renegades (elite foes) in the field.': 'يراهن عمرو أنّك لا تقدر على هزيمة ثلاثة من قادة المتمرّدين (أعداء النخبة) في الميدان.',
  'Three captains have fallen. Collect your winnings from \'Amr.': 'سقط ثلاثة قادة. خذ ربحك من عمرو.',
  'You won the wager.': 'ربحت الرهان.',
  'Task complete': 'اكتملت المهمّة', 'New task': 'مهمّة جديدة',

  // ---------------------------------------------------------------- codex
  'History': 'التاريخ', 'Places': 'الأماكن', 'Learning': 'العلم', 'War': 'الحرب', 'Craft': 'الصنعة', 'Trade': 'التجارة', 'People': 'الناس',
  'The Siege of Baghdad, 812–813': 'حصار بغداد، ٨١٢–٨١٣',
  'After Harun al-Rashid died in 809, his sons al-Amin (in Baghdad) and al-Ma\'mun (in Khurasan) fought for the caliphate. Al-Ma\'mun\'s general Tahir ibn al-Husayn besieged Baghdad from August 812. The fighting wrecked whole quarters of the city. It ended in September 813 with al-Amin\'s death. Soldiers of both sides were left loose in the countryside.': 'بعد وفاة هارون الرشيد سنة ٨٠٩ تنازع ابناه الأمين (في بغداد) والمأمون (في خراسان) على الخلافة. حاصر طاهر بن الحسين، قائد المأمون، بغداد من آب ٨١٢، فخرّب القتال أحياء كاملة من المدينة. وانتهى في أيلول ٨١٣ بمقتل الأمين، وبقي جنود الفريقين طلقاء في الريف.',
  'The Round City': 'المدينة المدوّرة',
  'Madinat al-Salam, the "City of Peace", was founded by the caliph al-Mansur in 762 on the west bank of the Tigris. Its plan was a perfect circle about two kilometres across, with double walls, a moat and four gates: the Kufa, Basra, Khurasan and Syria gates. Markets were later moved out to the suburb of al-Karkh. Much of the siege\'s damage fell on these outer quarters.': 'مدينة السلام، أسّسها الخليفة المنصور سنة ٧٦٢ على الضفّة الغربية لدجلة. كان مخطّطها دائرة تامّة قطرها نحو كيلومترين، بسورين وخندق وأربعة أبواب: باب الكوفة وباب البصرة وباب خراسان وباب الشام. ثمّ نُقلت الأسواق إلى ضاحية الكرخ، ووقع كثير من خراب الحصار على هذه الأحياء الخارجية.',
  'The House of Wisdom': 'بيت الحكمة',
  'Bayt al-Hikma began as a palace library under Harun al-Rashid. After al-Ma\'mun entered Baghdad in 819 it grew into a centre for translating Greek, Persian and Indian works on astronomy, mathematics, medicine and philosophy into Arabic. Scholars such as al-Khwarizmi worked in this circle, and in the 820s and 830s his astronomers made observations to check the tables of Ptolemy.': 'بدأ بيت الحكمة خزانةَ كتب في القصر أيام هارون الرشيد. وبعد دخول المأمون بغداد سنة ٨١٩ صار مركزًا لنقل كتب اليونان والفرس والهند في الفلك والرياضيات والطبّ والفلسفة إلى العربية. وعمل في هذه الدائرة علماء مثل الخوارزمي، ورصد فلكيّو المأمون في العشرينيّات والثلاثينيّات من القرن التاسع ليمتحنوا جداول بطليموس.',
  'The Astrolabe': 'الأسطرلاب',
  'A brass instrument that models the sky on a flat plate. By sighting a star or the sun and turning the rete, an astronomer can find the time, latitude and the heights of stars. Abbasid makers refined the Greek design. Treatises on its use, such as the one attributed to Masha\'allah, were among the early scientific works written in Arabic.': 'آلة من النحاس تمثّل السماء على صفيحة مسطّحة. برصد نجم أو الشمس وتدوير العنكبوت يعرف الفلكيّ الوقت والعرض وارتفاع النجوم. وقد أتقن صنّاع العصر العباسي التصميم اليوناني، وكانت رسائل العمل به، كالرسالة المنسوبة إلى ما شاء الله، من أوائل الكتب العلمية بالعربية.',
  'The Sawad': 'السواد',
  '"The Black Land": the dark, irrigated plain of central and lower Iraq between the Tigris and Euphrates, so called for its green fields against the desert. Its canals, date palms and grain fed Baghdad. Its taxes were the treasury\'s backbone, so keeping its roads open mattered to whoever held the city.': '«الأرض السوداء»: سهل العراق الأوسط والأسفل المرويّ بين دجلة والفرات، سُمّي كذلك لخضرة حقوله في وجه الصحراء. قنواته ونخيله وحبوبه أطعمت بغداد، وخراجه عماد بيت المال، فكان فتح طرقه يهمّ كلّ من ملك المدينة.',
  'Qanats': 'القنوات',
  'Underground channels that carry groundwater by gravity over many kilometres. They are marked on the surface by a line of access shafts. The technique came from Iran and spread across the Islamic world. Building and cleaning them took specialists who worked deep below ground by lamplight.': 'مجارٍ تحت الأرض تحمل الماء الجوفيّ بانحدارها كيلومترات كثيرة، وتدلّ عليها فوق الأرض صفوف من الآبار. جاءت التقنية من إيران وانتشرت في البلاد، وكان بناؤها وتنظيفها عمل حذّاق يشتغلون في عمق الأرض على ضوء السُّرُج.',
  'Naft and the Naffatun': 'النفط والنفّاطون',
  'Crude oil from seeps in Iraq and Persia was distilled into "white naft", a fierce incendiary. Specialist troops called naffatun threw it in clay pots or projected it from tubes. They wore protective clothing of felt and leather. Chroniclers record fire and mangonels wrecking whole streets in the siege of Baghdad.': 'كان النفط الخام من منابعه في العراق وفارس يُقطَّر إلى «النفط الأبيض»، وهو حارق شديد. ورماه جنود مختصّون يسمّون النفّاطين في قدور من فخّار أو قذفوه من أنابيب، ولبسوا ثيابًا واقية من اللبّاد والجلد. ويذكر الإخباريّون أنّ النار والمجانيق خرّبت شوارع كاملة في حصار بغداد.',
  'The \'Ayyarun': 'العيّارون',
  'Bands of young men from Baghdad\'s poorer quarters. During the siege of 812–813 they fought for al-Amin, often nearly naked, with little armour, makeshift shields and stones. They were brave street fighters who knew every alley. Chroniclers describe them with a mix of scorn and admiration.': 'جماعات من فتيان أحياء بغداد الفقيرة. قاتلوا للأمين في حصار ٨١٢–٨١٣، وكثيرًا ما كانوا شبه عراة، بلا دروع تقريبًا، بتروس مرتجلة وحجارة. كانوا مقاتلي شوارع شجعانًا يعرفون كلّ زقاق، ويصفهم الإخباريّون بمزيج من الازدراء والإعجاب.',
  'The Khurasani Regiments': 'الفرق الخراسانية',
  'Troops from Khurasan in the far east of the empire, the heartland of the Abbasid revolution of 750. Under Tahir they formed the core of al-Ma\'mun\'s army. They were known for mounted archery and disciplined infantry.': 'جنود من خراسان في أقصى شرق الدولة، موطن الثورة العباسية سنة ٧٥٠. شكّلوا تحت قيادة طاهر قلب جيش المأمون، وعُرفوا برماية الفرسان وانضباط المشاة.',
  'Baked Brick': 'الآجرّ',
  'Mesopotamia has little stone and timber, so it has built in brick for thousands of years. Sun-dried mud brick served for ordinary walls. Kiln-fired brick, harder and costlier, faced palaces, bridges and the gates of the Round City. Kiln yards outside the city burned day and night.': 'قلّ الحجر والخشب في بلاد الرافدين، فبنى أهلها باللبن منذ آلاف السنين. اللبن المجفّف في الشمس للجدران العاديّة، والآجرّ المشويّ في الأتون، وهو أصلب وأغلى، لواجهات القصور والجسور وأبواب المدينة المدوّرة. وكانت ساحات الأفران خارج المدينة تشتعل ليل نهار.',
  'Caravanserais': 'الخانات',
  'Walled inns along the trade roads, built around a courtyard ringed with rooms, storerooms and stables. A single gate could be shut at night. Merchants, couriers and their animals rested in them, roughly a day\'s march apart.': 'نُزُل مسوّرة على طرق التجارة، مبنيّة حول صحن تحيط به الغرف والمخازن والإسطبلات، لها باب واحد يُغلق في الليل. ينزلها التجّار والسعاة ودوابّهم، وبين الواحد والآخر نحو مسيرة يوم.',
  'The Barid': 'البريد',
  'The caliphal post and intelligence service. Relays of horses and couriers carried official letters along the main roads. Its local masters also sent the capital reports on governors, prices and unrest.': 'بريد الخلافة وعيونها. كانت مراحل الخيل والسعاة تحمل الكتب الرسمية على الطرق الكبرى، وكان أصحاب البريد في الأقاليم يرفعون إلى العاصمة أخبار الولاة والأسعار والاضطرابات.',
  'Dinars and Dirhams': 'الدنانير والدراهم',
  'The gold dinar (about 4.25 g) and the silver dirham were the coins of the caliphate. After the reform of the 690s they carried only inscriptions, with no images. Bills of exchange (suftaja) and cheques (sakk) let merchants move money without carrying coin across the empire.': 'الدينار الذهبيّ (نحو ٤٫٢٥ غرام) والدرهم الفضّيّ عملتا الخلافة. وبعد إصلاح التسعينيّات من القرن السابع صارت تحمل كتابة فقط بلا صور. وأتاحت السفاتج والصكوك للتجّار نقل المال دون حمل النقود عبر الدولة.',
  'Paper in Baghdad': 'الورق في بغداد',
  'Papermaking reached the Islamic world from Central Asia. Later writers credit the Barmakid al-Fadl ibn Yahya with founding a paper mill in Baghdad in the 790s. Cheaper than parchment or papyrus, paper fed the bureaucracy, the book markets of the city and, soon, the translators of the House of Wisdom.': 'وصلت صناعة الورق من آسيا الوسطى. وينسب كتّاب متأخّرون إلى البرمكيّ الفضل بن يحيى إنشاء مصنع للورق في بغداد في التسعينيّات من القرن الثامن. وكان الورق أرخص من الرقّ والبرديّ، فغذّى الدواوين وأسواق الورّاقين، ثمّ مترجمي بيت الحكمة.',
  'The Barmakids': 'البرامكة',
  'A family of Persian administrators from Balkh. As viziers under Harun al-Rashid they ran the empire\'s government and patronised scholars and poets. In 803 Harun abruptly had them arrested and their leader Ja\'far executed. The reasons are still debated.': 'أسرة من الكتّاب الفرس من بلخ. تولّوا الوزارة لهارون الرشيد فأداروا الدولة ورعوا العلماء والشعراء. وفي سنة ٨٠٣ قبض عليهم هارون فجأة وقتل جعفرًا كبيرهم، وما زالت أسباب ذلك موضع خلاف.',
  'No tasks yet. The people of the suq may have work.': 'لا مهامّ بعد. لعلّ عند أهل السوق عملًا.',
  '— undiscovered —': '— لم يُكتشف —',

  // ---------------------------------------------------------------- tutorial hints
  'Click the ground to walk. Hold the button to keep moving.': 'انقر الأرض لتمشي. أبقِ الزرّ مضغوطًا لتواصل السير.',
  'Drag on the left of the screen to walk.': 'اسحب على يسار الشاشة لتمشي.',
  'Click a foe to attack. Your discipline sets the weapon.': 'انقر عدوًّا لتهاجمه. فنّك يحدّد سلاحك.',
  'Tap the large button (or a foe) to attack.': 'انقر الزرّ الكبير (أو عدوًّا) لتهاجم.',
  'Space to evade. Evade just as a blade glints and you will parry.': 'المسافة للمراوغة. راوغ لحظة يلمع النصل فتصدّ الضربة.',
  'The curved arrow evades. Evade just as a blade glints and you will parry.': 'السهم المنحني للمراوغة. راوغ لحظة يلمع النصل فتصدّ الضربة.',
  'Right-click and 1, 2, 3 use your skills. Each costs your resource.': 'الزرّ الأيمن و١ و٢ و٣ لمهاراتك. لكلّ منها كلفة من مَددك.',
  'The ring of buttons holds your skills. Each costs your resource.': 'حلقة الأزرار تحمل مهاراتك. لكلّ منها كلفة من مَددك.',
  'Wounded: press Q to drink pomegranate sherbet.': 'جريح: اضغط Q لتشرب شراب الرمّان.',
  'Wounded: tap the red flask to drink sherbet.': 'جريح: انقر القارورة الحمراء لتشرب.',
  'The suq: talk (E) to Yusuf, Bishr and \'Amr. The well leads to the qanats.': 'السوق: كلّم (E) يوسف وبشرًا وعمرًا. والبئر تقود إلى القنوات.',
  'The suq: walk up to Yusuf, Bishr and \'Amr and tap the prompt. The well leads to the qanats.': 'السوق: اقترب من يوسف وبشر وعمرو وانقر الدعوة. والبئر تقود إلى القنوات.',
  'A discipline point to spend: press K.': 'نقطة فنّ لتنفقها: اضغط K.',
  'A discipline point to spend: Menu ☰, then Disciplines.': 'نقطة فنّ لتنفقها: القائمة ☰ ثمّ المهارات.',

  // ---------------------------------------------------------------- Round 10
  'Rafi\'': 'رافع', 'Qays': 'قيس', 'Thabit': 'ثابت', 'Mundhir': 'المنذر', '\'Uqba': 'عقبة', 'Nasr': 'نصر', 'Bakr': 'بكر', 'Hamdan': 'حمدان', 'Rabi\'a': 'ربيعة', 'Jarir': 'جرير',
  'Captain slain': 'سقط قائد', 'Engines burned': 'المجانيق المحروقة', 'New Game+': 'لعبة جديدة+', 'foes are stronger': 'الأعداء أشدّ',
  'Keep your hero, gear and disciplines. The Sawad resets, and its foes grow stronger.': 'احتفظ ببطلك وعتاده وفنونه. يعود السواد من جديد، ويشتدّ أعداؤه.',
  'Go down into the storerooms': 'انزل إلى المخازن', 'Climb down into the clay pits': 'انزل إلى حفر الطين', 'Enter the Sasanian vaults': 'ادخل الأقبية الساسانية', 'Set the engine alight': 'أضرم النار في المنجنيق',
  'The Caravanserai Storerooms': 'مخازن الخان', 'Vaulted stores beneath Ziyad\'s camp': 'مخازن مقبّبة تحت معسكر زياد',
  'The Clay Pits': 'حفر الطين', 'Where the kiln yard digs its clay': 'حيث تحفر ساحة الأفران طينها',
  'The Sasanian Vaults': 'الأقبية الساسانية', 'Brick halls older than Baghdad': 'قاعات من الآجرّ أقدم من بغداد',
  'The Courier\'s Satchel': 'حقيبة الساعي', 'Indian Steel': 'الفولاذ الهندي', 'Ash for the Engines': 'رماد للمجانيق',
  'Qays took a barid courier\'s satchel into the storerooms under the caravanserai. Recover it.': 'أخذ قيس حقيبة ساعٍ من البريد إلى المخازن تحت الخان. استعدها.',
  'You have the satchel. Return it to Rafi\' in the suq.': 'معك الحقيبة. أعدها إلى رافع في السوق.',
  'The letters reached Baghdad.': 'بلغت الكتب بغداد.',
  'Thabit\'s men carried off Bishr\'s Indian steel ingots to the clay pits by the kilns. Bring them back.': 'حمل رجال ثابت سبائك الفولاذ الهندي لبشر إلى حفر الطين قرب الأفران. أعدها.',
  'You have the ingots. Take them to Bishr.': 'معك السبائك. خذها إلى بشر.',
  'Bishr has his steel again.': 'استعاد بشر فولاذه.',
  'Ghassan has three mangonels on the approach to the arch. Burn them before you face him (0/3).': 'لغسّان ثلاثة مجانيق على الطريق إلى الطاق. أحرقها قبل أن تواجهه (٠/٣).',
  'The engines are ash. Tell \'Amr.': 'صارت المجانيق رمادًا. أخبر عمرًا.',
  'Ghassan fights without his engines.': 'يقاتل غسّان بلا مجانيقه.',
  'The Courier\'s Satchel': 'حقيبة الساعي', 'Indian Steel Ingots': 'سبائك الفولاذ الهندي',
  'Your satchel. The seals are unbroken.': 'حقيبتك. الأختام سليمة.',
  'Unbroken! Then the postmaster in Baghdad will have his reports by tomorrow, and I will keep my post. Take this, and my thanks.': 'سليمة! إذن يصل صاحبَ البريد في بغداد أخبارُه غدًا، وأحفظ أنا عملي. خذ هذا، ولك شكري.',
  'Forgive me, I cannot stand for long. Brigands ran down my horse on the Khurasan road and took my satchel.': 'اعذرني، لا أقدر على الوقوف طويلًا. صدم اللصوص فرسي على طريق خراسان وأخذوا حقيبتي.',
  'The relay horses run again. If you ever need a letter carried, ask for Rafi\'.': 'عادت خيل المراحل تجري. إن احتجت يومًا إلى حمل كتاب فاسأل عن رافع.',
  'Qays and his archers hide in the storerooms under the caravanserai. Be careful.': 'يختبئ قيس ورماته في المخازن تحت الخان. احذر.',
  'What was in it?': 'ماذا كان فيها؟', 'What is the barid?': 'ما البريد؟', 'I will bring it back.': 'سأعيدها.',
  'Letters for the postmaster in Baghdad: reports on prices and governors, sealed. If they are opened or lost, I lose my post. Qays took them into the storerooms under the caravanserai.': 'كتب لصاحب البريد في بغداد: أخبار الأسعار والولاة، مختومة. إن فُتحت أو ضاعت فقدت عملي. أخذها قيس إلى المخازن تحت الخان.',
  'The caliph\'s post. Relays of horses along the great roads, a fresh mount at every station. We carry the state\'s letters, and the postmasters write to Baghdad about everything they see.': 'بريد الخليفة. مراحل من الخيل على الطرق الكبرى، وفرس جديدة عند كلّ محطّة. نحمل كتب الدولة، وأصحاب البريد يكتبون إلى بغداد بكلّ ما يرون.',
  'Your ingots, from the clay pits. Thabit will not need them.': 'سبائكك، من حفر الطين. لن يحتاج إليها ثابت.',
  'Ha! Feel the weight of that. I will forge you something worthy of it, and your next tempering is on my anvil, free.': 'ها! تحسّس ثقلها. سأطرق لك شيئًا يليق بها، وسقيُك القادم على سندانـي بلا أجر.',
  'Mind the sparks. You have the look of someone who could do me a favour.': 'احذر الشرر. تبدو كمن يقدر أن يسدي إليّ معروفًا.',
  'The forge is hot. What do you need?': 'الكور حامٍ. ماذا تحتاج؟',
  'Show me the forge.': 'أرني الكور.', 'What favour?': 'أيّ معروف؟', 'I will get them back.': 'سأستعيدها.',
  'Six ingots of Indian steel, come up from Basra, and Thabit\'s men took them off the cart at the kilns. They will be hiding in the clay pits. Steel like that does not come twice a year.': 'ستّ سبائك من الفولاذ الهندي جاءت من البصرة، وأنزلها رجال ثابت عن العربة عند الأفران. لا بدّ أنّهم يختبئون في حفر الطين. فولاذ كهذا لا يأتي مرّتين في السنة.',
  'I saw the smoke from here. Without his engines, Ghassan is just a big man with a sword. Here, for the road.': 'رأيت الدخان من هنا. بلا مجانيقه ليس غسّان إلّا رجلًا ضخمًا بسيف. خذ، للطريق.',
  'One more thing, before you go south. Ghassan has mangonels on the road to the arch. If he gets them loosing naft at you, you will burn. Burn them first.': 'أمر آخر قبل أن تمضي جنوبًا. لغسّان مجانيق على طريق الطاق. إن رمتك بالنفط احترقت. أحرقها أنت أوّلًا.',
  'Consider it done.': 'اعتبره منتهيًا.', 'Later.': 'لاحقًا.',
  'My engines are ash. Then it is steel, guard. Just you and me.': 'مجانيقي رماد. إذن هو الحديد يا حارس. أنا وأنت فقط.',
  'Enough. No more men, no more engines. Just you and me.': 'كفى. لا رجال ولا مجانيق. أنا وأنت فقط.',
  'Fire rings the broken arch.': 'النار تطوّق الطاق المكسور.',
  'The Arch of Ctesiphon': 'إيوان المدائن',
  'The Sasanian kings\' palace at Ctesiphon, downriver from where Baghdad would rise, was crowned by a vast brick vault, the Taq Kasra, built in the 6th century. Its single span of about 25 metres made it one of the largest brick vaults ever raised. Later writers tell that al-Mansur thought of pulling it down for bricks for his new city, and gave up when the cost of demolition outran the value of the bricks.': 'كان قصر الملوك الساسانيين في المدائن، أسفل النهر من موضع بغداد، يعلوه قبو عظيم من الآجرّ هو طاق كسرى، بُني في القرن السادس. وجعله امتداده الواحد البالغ نحو خمسة وعشرين مترًا من أكبر الأقبية الآجرّية التي رُفعت. ويروي كتّاب متأخّرون أنّ المنصور همّ بهدمه ليأخذ آجرّه لمدينته الجديدة، ثمّ عدل لمّا زادت كلفة الهدم على قيمة الآجرّ.',
  'Mangonels': 'المجانيق',
  'The manjaniq was a beam sling engine worked by teams pulling ropes. It threw stones and pots of naft over walls. Both sides set them up in Baghdad in 812–813, and the chroniclers blame them for much of the damage to houses and markets.': 'المنجنيق آلة رمي بذراع ومقلاع يشغّلها فريق يشدّ الحبال، ترمي الحجارة وقدور النفط فوق الأسوار. نصبها الفريقان في بغداد سنة ٨١٢–٨١٣، ويحمّلها الإخباريّون كثيرًا من خراب البيوت والأسواق.',
  'Crucible steel came west from India and Sri Lanka as small ingots. Smiths prized it for blades that took a hard, keen edge, and its watered pattern became famous. Merchants carried it through the Gulf ports to Basra and up to Baghdad.': 'جاء فولاذ البوتقة غربًا من الهند وسرنديب سبائك صغيرة. وقدّره الحدّادون لنصال تقبل حدًّا صلبًا ماضيًا، واشتهر فرنده المموّج. وحمله التجّار عبر موانئ الخليج إلى البصرة ثمّ إلى بغداد.',
  'You burned my engines? Then my men will do it by hand!': 'أحرقت مجانيقي؟ إذن يفعلها رجالي بأيديهم!',
  'Swift': 'خاطف', 'Ironclad': 'مدرّع', 'Volley': 'رشق', 'Firebrand': 'مُشعِل', 'Rallying': 'مُستنفِر',
};
