// Round 31: Arabic for the siege mines, the sapper, the Wanted board and the polish pass (merged last in story_ar.js)
export const AR31 = {
  // the siege mines
  'The Siege Mines': 'أنفاق الحصار', 'The Counter-Mines': 'الأنفاق المضادّة',
  'Sappers dug these under the walls. Strike a cracked prop to bring the roof down on your foes.': 'حفرها النقّابون تحت الأسوار. اضرب دعامة متصدّعة ليسقط السقف على أعدائك.',
  'The defenders dug to meet the sappers here. Strike a cracked prop to bring the roof down on your foes.': 'حفر المدافعون هنا ليلاقوا النقّابين. اضرب دعامة متصدّعة ليسقط السقف على أعدائك.',
  'Go down into the siege mines': 'انزل إلى أنفاق الحصار', 'Go down into the counter-mines': 'انزل إلى الأنفاق المضادّة',
  'The prop gives way!': 'الدعامة تنهار!', 'The roof is shedding earth: step out of the marks': 'السقف يتساقط ترابًا: ابتعد عن العلامات',
  'Bring down the roof!': 'أسقطوا السقف!',
  'Sapper': 'نقّاب', 'Gabrades': 'غابراديس', 'Tzykes': 'تزيكيس',
  'A sapper digs toward you: keep moving, then hit him as he comes up': 'نقّاب يحفر نحوك: ابقَ متحرّكًا، ثم اضربه حين يخرج',
  // the Wanted board
  'WANTED': 'مطلوب', 'Wanted': 'مطلوب', 'Read the Wanted board': 'اقرأ لوح المطلوبين', 'Taken': 'أُسِر', 'Hunting': 'في المطاردة', 'Hunt him': 'طارِده',
  'Beat the one before': 'اهزم الذي قبله', 'Beat all five': 'اهزم الخمسة', 'One hunt at a time': 'مطاردة واحدة في كلّ مرّة', 'Reward': 'المكافأة', 'This week': 'هذا الأسبوع', 'Rank': 'المرتبة',
  'Beat the captain at the bottom of the board and the next is posted.': 'اهزم القائد في أسفل اللوح فيُعلَّق الذي يليه.',
  'His camp is marked on the map.': 'معسكره معلَّم على الخريطة.',
  'Every captain on this board is down. A new one is posted each week.': 'سقط كلّ قائد على هذا اللوح. يُعلَّق واحد جديد كلّ أسبوع.',
  'A rare weapon': 'سلاح نادر', 'A rare coat or cap': 'درع أو خوذة نادرة', 'A rare ring and three gems': 'خاتم نادر وثلاثة أحجار كريمة', 'A legendary': 'قطعة أسطورية', 'The legendary of this land': 'أسطورية هذه الأرض', 'A legendary and a large purse': 'قطعة أسطورية وصرّة كبيرة',
  'Posted this week by the camp. Bring him in.': 'علّقه المعسكر هذا الأسبوع. أحضِره.',
  'Kaminas': 'كاميناس', 'Patzes': 'باتزيس', 'Kalokyres': 'كالوكيريس', 'Lykastes': 'ليكاستيس', 'Taronas': 'تاروناس',
  'Phokinos': 'فوكينوس', 'Lekkas': 'ليكاس', 'Gongyles': 'غونغيليس', 'Synadenos': 'سينادينوس', 'Kinnamos': 'كينّاموس',
  'Sklerenos': 'سكليرينوس', 'Mesopotamites': 'ميسوبوتاميتيس', 'Xiphilinos': 'كسيفيلينوس', 'Hikanatos': 'هيكاناتوس', 'Pakourianos': 'باكوريانوس',
  'Glabas': 'غلاباس', 'Kastamonites': 'كاستامونيتيس', 'Laskaris': 'لاسكاريس', 'Vatatzes': 'فاتاتزيس', 'Choirosphaktes': 'خويروسفاكتيس',
  'Philanthropenos': 'فيلانثروبينوس', 'Strategopoulos': 'ستراتيغوبولوس', 'Tzamplakon': 'تزامبلاكون', 'Botaneiates': 'بوتانياتيس', 'Kantakouzenos': 'كانتاكوزينوس',
  'Opsaras': 'أوبساراس', 'Mouzakios': 'موزاكيوس', 'Lampardas': 'لامبارداس', 'Petraliphas': 'بيتراليفاس', 'Branas': 'براناس', 'Asanes': 'أسانيس', 'Zygabenos': 'زيغابينوس',
  'Robs the grain carts on the canal road.': 'يسلب عربات الحبوب على طريق القناة.',
  'Shoots at the men who mend the dykes.': 'يرمي الرجال الذين يرمّمون السدود.',
  'Holds the ford and takes a toll from everyone who crosses.': 'يمسك المخاضة ويأخذ إتاوة من كلّ عابر.',
  'Burned three threshing floors before the harvest was in.': 'أحرق ثلاثة بيادر قبل أن يُجمَع الحصاد.',
  'Leads what is left of the foragers. His men would scatter without him.': 'يقود من بقي من الجبّائين. يتفرّق رجاله من دونه.',
  "Nets the fishermen's boats and sells the catch back to them.": 'يصطاد قوارب الصيّادين بالشباك ويبيعهم صيدهم.',
  'Stones the boats that carry reeds to the city.': 'يرجم القوارب التي تحمل القصب إلى المدينة.',
  'Waits in the reeds on the causeways. Nobody sees him first.': 'يكمن في القصب على الجسور. لا يراه أحد أوّلًا.',
  'Hunts the buffalo herders with his dogs.': 'يطارد رعاة الجواميس بكلابه.',
  'Holds the sluice gates and lets the water out when the villages will not pay.': 'يمسك بوّابات السدّ ويطلق الماء حين لا تدفع القرى.',
  'Shakes down the bakers of the Karkh lanes every morning.': 'يبتزّ خبّازي أزقّة الكرخ كلّ صباح.',
  'Shoots from the rooftops at anyone carrying water.': 'يرمي من فوق السطوح كلّ من يحمل الماء.',
  "Set fire to the paper-sellers' lane.": 'أشعل النار في زقاق الورّاقين.',
  'Digs under the houses and robs them from below.': 'يحفر تحت البيوت ويسرقها من أسفل.',
  'Holds the burned suq with a company of his own.': 'يمسك السوق المحروق بسريّة له.',
  'Shoots the boatmen from the warehouse roofs.': 'يرمي الملّاحين من سطوح المخازن.',
  'Runs the press-gang on the quays.': 'يسوق الناس إلى الخدمة قسرًا على الأرصفة.',
  'Burns the boats he cannot steal.': 'يحرق القوارب التي لا يقدر على سرقتها.',
  'Cuts purses on the quays and is gone before anyone turns.': 'يقطع الأكياس على الأرصفة ويختفي قبل أن يلتفت أحد.',
  "Holds the customs house and takes the river's tolls for himself.": 'يمسك دار المكوس ويأخذ رسوم النهر لنفسه.',
  'Shoots down at the shepherds from the high paths.': 'يرمي الرعاة من الدروب العالية.',
  'Holds the wells in the dry valley.': 'يمسك الآبار في الوادي اليابس.',
  'Gathers deserters from every broken company.': 'يجمع الفارّين من كلّ سريّة مكسورة.',
  'Raids the salt caravans and is back in the hills by dark.': 'يغير على قوافل الملح ويعود إلى التلال قبل الظلام.',
  'Means to burn the passes behind the army when it goes.': 'ينوي إحراق الممرّات خلف الجيش حين يرحل.',
  'Cap of the Canal Roads': 'خوذة طرق القنوات', 'Reed-Cutter': 'قاطع القصب', 'Weight of the Karkh Market': 'صَنجة سوق الكرخ', 'Rope of the Bridge of Boats': 'حبل جسر السفن', 'Coat of the Hamrin Passes': 'درع ممرّات حمرين',
  '"The last road captain of the Sawad wore it. The farmers sleep now."': '«لبسها آخر قادة الطرق في السواد. الفلّاحون ينامون الآن.»',
  '"It cleared a way through the reeds for the fishing boats."': '«شقّ طريقًا في القصب لقوارب الصيد.»',
  '"A market inspector\'s brass weight, honest to the grain."': '«صَنجة نحاس لمحتسب السوق، صادقة حتّى الحبّة.»',
  '"Cut from the cables that held the boats in line across the Tigris."': '«قُطع من الحبال التي شدّت السفن صفًّا عبر دجلة.»',
  '"Taken from the last captain in the hills, and patched where he was beaten."': '«أُخذ من آخر قائد في التلال، ورُقِع حيث هُزِم.»',
};
