// Round 25: Arabic for the new combat hints, encounters, choices, story lines, banter and letters (merged last in story_ar.js)
export const AR25 = {
  // ---- combat and the tutorial
  'He reels: strike now!': 'إنه يترنّح: اضرب الآن!',
  'Tap the large button (or a foe) to attack.': 'انقر الزرّ الكبير (أو عدوًّا) لتهاجم.',
  'Click a foe to attack. Your discipline sets the weapon.': 'انقر عدوًّا لتهاجمه. سلاحك يتبع صنعتك.',
  'A blade glints: press Space now to evade. Timed with the glint, it parries.': 'نصلٌ يلمع: اضغط المسافة الآن لتتفادى. إن وافقتَ اللمعة صددتَ الضربة.',
  'A blade glints: tap the curved arrow now. Timed with the glint, it parries.': 'نصلٌ يلمع: انقر السهم المنحني الآن. إن وافقتَ اللمعة صددتَ الضربة.',
  'Many foes: right-click or 1, 2, 3 for your skills. Each costs your resource.': 'أعداء كُثُر: الزرّ الأيمن أو ١ و٢ و٣ لمهاراتك. لكلٍّ منها كلفة.',
  'Many foes: use the skill buttons around the attack button. Each costs your resource.': 'أعداء كُثُر: استعمل أزرار المهارات حول زرّ الهجوم. لكلٍّ منها كلفة.',
  'Parried! Your next blow is a sure critical.': 'صدّ! ضربتك التالية حاسمة لا محالة.',
  // ---- encounters
  'Ambush!': 'كمين!',
  'More on the flank!': 'المزيد على الجناح!',
  'The road is clear.': 'خلا الطريق.',
  'Down. His purse is yours.': 'سقط. وكيسه لك.',
  'Rhaptes': 'رابتيس', 'Kontos': 'كونتوس', 'Mylonas': 'ميلوناس', 'Karykes': 'كاريكيس', 'Champion': 'بطل',
  'Rhaptes · Champion': 'رابتيس · بطل', 'Kontos · Champion': 'كونتوس · بطل', 'Mylonas · Champion': 'ميلوناس · بطل', 'Karykes · Champion': 'كاريكيس · بطل',
  'Arsaber pays by the head. Yours will do.': 'أرسابر يدفع بالرأس. ورأسك يكفي.',
  'The reeds are ours now, Baghdadi.': 'القصب لنا الآن يا بغدادي.',
  'Your city burned before we came. We only warm our hands.': 'احترقت مدينتكم قبل أن نأتي. نحن ندفّئ أيدينا فحسب.',
  'One more crate for the ship. You will fit in it.': 'صندوق آخر للسفينة. وأنت تتّسع فيه.',
  // ---- the choices
  'Photeinos is beaten. What becomes of him?': 'هُزم فوتينوس. فما مصيره؟',
  'Bind him for the qadi in Baghdad.': 'قيّده واحمله إلى القاضي في بغداد.',
  'Let him go. He has confessed.': 'أطلقه. لقد اعترف.',
  'The qadi will hear the rest of it.': 'سيسمع القاضي بقيّة الحكاية.',
  'Then I will tell it. All of it.': 'إذن سأرويها. كلّها.',
  'Go. If I see you with a sword again, I will not ask twice.': 'اذهب. إن رأيتك بسيف ثانيةً فلن أسأل مرّتين.',
  'You will not. I read one page, guard. One was enough.': 'لن تراني. قرأتُ صفحة واحدة يا حارس. وكانت تكفي.',
  'Behind the weir, the reed village is burning.': 'خلف السدّ، قرية القصب تحترق.',
  'Chase the bundle up the canal tonight.': 'الحق بالرزمة في القناة الليلة.',
  'Stay and fight the fire with the marsh-folk.': 'ابقَ وأطفئ النار مع أهل الهور.',
  'Ishaq. Find us a boat.': 'إسحاق. جِد لنا قاربًا.',
  'The Pages can wait one night. These people cannot.': 'الصحائف تنتظر ليلة. أمّا هؤلاء فلا.',
  'They fought the fire until dawn. Then the marsh-folk poled Salim and Ishaq up the canal to Baghdad.': 'قاتلوا النار حتى الفجر. ثم دفع أهل الهور بسالم وإسحاق في القناة إلى بغداد.',
  'The Pages were still on the pyre. The edges of a few had caught. Hakam\'s copyists would mend them from memory.': 'كانت الصحائف ما تزال على المحرقة. احترقت حواشي بعضها، وسيرمّمها نسّاخ الحكم من الذاكرة.',
  'Arsaber turns to go.': 'يستدير أرسابر ليمضي.',
  'Refuse him.': 'ارفض عرضه.',
  'Promise him a copy, freely given.': 'عِده بنسخة، هبةً لا غنيمة.',
  'Wait. When the copying is done, one copy goes north. Freely given. My word on it.': 'انتظر. حين يتمّ النسخ، تذهب نسخة إلى الشمال. هبةً. لك كلمتي.',
  'A caravan guard\'s word. My orders are the originals, but I will remember it.': 'كلمة حارس قافلة. أوامري هي الأصول، لكنّي سأذكرها.',
  'And I keep my word. The first copy that is not spoken for goes north, with you.': 'وأنا أفي بكلمتي. أوّل نسخة لا صاحب لها تذهب معك إلى الشمال.',
  'Then I go home with a book, and not a theft.': 'إذن أعود إلى بلادي بكتاب، لا بسرقة.',
  'Arsaber went home that winter, in an exchange of prisoners on the Lamis river. In his baggage was a copy of the Pages, freely given.': 'عاد أرسابر إلى بلاده ذلك الشتاء، في فداء الأسرى على نهر اللامس. وفي متاعه نسخة من الصحائف، هبةً لا غنيمة.',
  'Photeinos told the qadi everything. His testimony put the envoy\'s name before the court.': 'أخبر فوتينوس القاضي بكلّ شيء. ووضعت شهادته اسم الرسول أمام المحكمة.',
  'Photeinos never carried a sword again. A scribe in Wasit took on a Greek assistant that spring.': 'لم يحمل فوتينوس سيفًا بعدها. وفي ذلك الربيع اتّخذ ورّاق في واسط مساعدًا روميًّا.',
  'In the Nahrawan the reed village was rebuilt before the floods. They named a boat for Salim.': 'في النهروان أُعيد بناء قرية القصب قبل الفيضان. وسمّوا قاربًا باسم سالم.',
  'In the Nahrawan the burned village was a long time rebuilding.': 'في النهروان طال بناء القرية المحترقة.',
  'Jabir wanted to see Baghdad. Not like this.': 'كان جابر يريد أن يرى بغداد. لا هكذا.',
  'Arsaber\'s men hold the Pages here. Their captain is Krateros. Start with Narses, in the burned quarter.': 'رجال أرسابر يحملون الصحائف هنا، وقائدهم كراتيروس. ابدأ بنارسيس في الحيّ المحترق.',
  'I chose his road. I will not forget it.': 'أنا اخترتُ طريقه. ولن أنسى ذلك.',
  'Neither will I. Light the next one, Ishaq.': 'ولا أنا. أشعل السراج التالي يا إسحاق.',
  // ---- what the choices change in play
  'The qadi\'s men will take Photeinos to Baghdad.': 'سيحمل رجال القاضي فوتينوس إلى بغداد.',
  'Renown': 'الصيت',
  'From the reed village, for the night you stayed.': 'من قرية القصب، لليلة التي بقيتَ فيها.',
  'A boatman from the Nahrawan brought a gift: the reed village remembers the night you stayed.': 'جاء ملّاح من النهروان بهدية: قرية القصب تذكر الليلة التي بقيتَ فيها.',
  'Someone left a purse at the khan for you, with a note signed only "P.": "One page was enough."': 'ترك أحدهم لك كيسًا في الخان، ومعه ورقة موقّعة بحرف «ف» فقط: «صفحة واحدة كانت تكفي».',
  // ---- Ishaq's confession
  'Salim. Before we go on, there is something I owe you.': 'سالم. قبل أن نمضي، لك عليّ دَين.',
  'I put the chest in your caravan because no one searches a caravan guard\'s mules. I chose your brother\'s road for the Pages.': 'وضعتُ الصندوق في قافلتكم لأنّ أحدًا لا يفتّش بغال حرّاس القوافل. اخترتُ طريق أخيك للصحائف.',
  'I did not know about the envoy. But I chose, and Jabir paid for it.': 'لم أكن أعلم بالرسول. لكنّي اخترت، ودفع جابر الثمن.',
  'Say what you need to say.': 'قل ما تريد قوله.',
  'You should have told us.': 'كان عليك أن تخبرنا.',
  'He would have carried it anyway. That was Jabir.': 'كان سيحمله على أيّ حال. هكذا كان جابر.',
  'Yes. I should have. I will carry that with the rest of the account.': 'نعم. كان عليّ. سأحمل هذا مع بقيّة الحساب.',
  'Then we carry it together.': 'إذن نحمله معًا.',
  'Perhaps. It is kind of you to say it. It does not make it lighter.': 'ربّما. لطفٌ منك أن تقولها. لكنّها لا تخفّفه.',
  'It is not meant to.': 'وليس المقصود أن تخفّفه.',
  // ---- Salim remembers
  'Two more days to Baghdad, he said. Two more days.': 'يومان إلى بغداد، قال. يومان فقط.',
  'Jabir hated boats. He said water keeps no promises.': 'كان جابر يكره القوارب. كان يقول إنّ الماء لا يفي بوعد.',
  'He wanted to see the paper-sellers\' lane. He said I should learn to read.': 'كان يريد أن يرى سوق الورّاقين. وكان يقول إنّ عليّ أن أتعلّم القراءة.',
  'Jabir would have counted every barge on this river, and argued the tolls.': 'كان جابر سيعدّ كلّ مركب في هذا النهر، ويجادل في المكوس.',
  'Tatzates is up here somewhere. The one who loosed the arrow.': 'تاتزاتيس هنا في مكان ما. هو من أطلق السهم.',
  // ---- the hired guards
  'That is the last of them. Breathe.': 'هذا آخرهم. التقط أنفاسك.',
  'Shield up next time. You took one on the arm.': 'ارفع الترس في المرّة القادمة. أصابتك واحدة في الذراع.',
  'Ambush! Back to back!': 'كمين! ظهرًا لظهر!',
  'They were waiting for us. Close up!': 'كانوا ينتظروننا. تقاربوا!',
  'A big one. I\'ll keep his men off you.': 'ضخم هذا. سأُبعد رجاله عنك.',
  'That one wants you, not me. Good.': 'ذاك يريدك أنت، لا أنا. حسنًا.',
  'You are bleeding badly. Drink!': 'تنزف كثيرًا. اشرب!',
  'Fall back to me!': 'تراجع إليّ!',
  'That is their captain. Watch his shoulders before he swings.': 'ذاك قائدهم. راقب كتفيه قبل أن يضرب.',
  'When he staggers, go in. Not before.': 'حين يترنّح، ادخل عليه. لا قبل ذلك.',
  'Clear. I count no more.': 'خلا المكان. لا أعدّ أحدًا.',
  'Quiet again. I don\'t trust it.': 'هدوء من جديد. لا أثق به.',
  'In the cover, there! I\'ll take the far ones.': 'هناك، في المخبأ! سأتولّى البعيدين.',
  'Archers on the flank. Mine.': 'رماة على الجناح. هم لي.',
  'He is armoured. I\'ll aim for the joints.': 'إنّه مدرّع. سأصوّب على المفاصل.',
  'Keep him busy. I have a clear line.': 'أشغِله. خطّي مكشوف.',
  'Get out of there! Drink!': 'اخرج من هناك! اشرب!',
  'You are hit. Back off, I\'ll cover you.': 'أُصبت. تراجع، سأحميك.',
  'Their captain. Make him turn, I\'ll find his back.': 'قائدهم. اجعله يستدير، وأنا أجد ظهره.',
  'He leaves himself open after the big swing.': 'يكشف نفسه بعد الضربة الكبيرة.',
  'Done. Mind the embers.': 'انتهى. احذر الجمر.',
  'Smoke clears, and so do they.': 'ينقشع الدخان، وينقشعون معه.',
  'Down! Let me throw first!': 'انخفض! دعني أرمي أوّلًا!',
  'Keep them bunched. Bunched burns.': 'أبقِهم متجمّعين. المتجمّع يحترق.',
  'Pull him onto the fire, guard.': 'اسحبه إلى النار يا حارس.',
  'Big men burn the same.': 'الضخام يحترقون مثل غيرهم.',
  'Drink, guard! Now!': 'اشرب يا حارس! الآن!',
  'You are no good to me dead. Drink.': 'لا نفع لي بك ميتًا. اشرب.',
  'That one has fire of his own. Keep moving.': 'لذاك ناره الخاصّة. لا تتوقّف.',
  'Watch the ground. Where it\'s marked, don\'t stand.': 'راقب الأرض. حيث العلامة لا تقف.',
  'Over. They never saw me.': 'انتهى. لم يروني قطّ.',
  'Clean work. Mostly yours.': 'عمل نظيف. معظمه لك.',
  'Hah. They think they ambush us.': 'ها. يظنّون أنّهم يكمنون لنا.',
  'I\'ll go round. Keep their eyes on you.': 'سألتفّ عليهم. أبقِ أعينهم عليك.',
  'Make him angry. I like them angry.': 'أغضِبه. أحبّهم غاضبين.',
  'I\'ll find his back. You find his front.': 'أنا أجد ظهره، وأنت وجهه.',
  'Drink, brother. Quickly.': 'اشرب يا أخي. بسرعة.',
  'Out of the press! Drink!': 'اخرج من الزحام! اشرب!',
  'Their master. Every master has a slow hand.': 'سيّدهم. ولكلّ سيّد يدٌ بطيئة.',
  'Parry him once and he is ours.': 'صدّه مرّة واحدة ويصبح لنا.',
  // ---- the hub people
  'Prices are up. Everything is up. The war, you understand.': 'الأسعار ارتفعت. كلّ شيء ارتفع. إنّها الحرب، كما تفهم.',
  'Fish, reed mats and rumours. The rumours are cheapest.': 'سمك وحُصر قصب وشائعات. والشائعات أرخصها.',
  'I sold paper on this lane once. Now I sell what did not burn.': 'كنتُ أبيع الورق في هذا الزقاق. الآن أبيع ما لم يحترق.',
  'Every barge that leaves takes my best customers with it.': 'كلّ مركب يغادر يأخذ معه خير زبائني.',
  'Bring me iron and I will make it worth something.': 'هات لي حديدًا وأجعله ذا قيمة.',
  'The damp gets into everything here. Oil your blade, guard.': 'الرطوبة تدخل كلّ شيء هنا. ادهن نصلك يا حارس.',
  'The fire tempered half the iron in this quarter. Badly.': 'سقت النار نصف حديد هذا الحيّ. سقيًا رديئًا.',
  'Ships\' nails. Good iron, if you can pry it out.': 'مسامير السفن. حديد جيّد، إن استطعت انتزاعه.',
  'You fight like your brother. Too straight. Learn to step aside.': 'تقاتل مثل أخيك. مستقيمًا أكثر ممّا ينبغي. تعلّم أن تتنحّى.',
  'Mud is a teacher. Lift your feet.': 'الطين معلّم. ارفع قدميك.',
  'In the lanes, watch the roofs, not the street.': 'في الأزقّة راقب السطوح، لا الطريق.',
  'On the jetties, keep your back off the water.': 'على الأرصفة، لا تجعل ظهرك إلى الماء.',
  // ---- Leaves and Letters
  'Leaves and Letters': 'أوراق ورسائل',
  'A leaf of the Pages': 'ورقة من الصحائف', 'A soldier\'s letter': 'رسالة جندي', 'Arsaber\'s dispatch': 'رسالة أرسابر',
  'Every word you found, kept.': 'كلّ كلمة وجدتَها، محفوظة.',
  'All twelve found. The Teacher\'s Inkwell is yours.': 'وجدتَها الاثنتي عشرة كلّها. محبرة المعلّم لك.',
  'The Teacher\'s Inkwell': 'محبرة المعلّم',
  'A burned leaf of the Pages. One line survives: "A man who will not share water with his enemy has already lost the argument."': 'ورقة محترقة من الصحائف. بقي منها سطر واحد: «من أبى أن يقاسم عدوَّه الماء فقد خسر الحجّة».',
  'A letter, never sent: "Mother, this country is flat and hot and the bread is good. The officers say we go home by spring. Tell Eirene I have not forgotten her. Doukitzes."': 'رسالة لم تُرسَل: «أمّاه، هذه البلاد منبسطة حارّة والخبز طيّب. يقول الضبّاط إنّنا نعود في الربيع. قولي لإيريني إنّي لم أنسَها. دوكيتزيس».',
  'Arsaber to the Logothete: "The brothers\' war serves us. No one guards the roads. They say the Teacher\'s Pages are worth more than all the astronomer\'s brass. I will see for myself."': 'من أرسابر إلى اللوغوثيت: «حرب الأخوين تخدمنا. لا أحد يحرس الطرق. يقولون إنّ صحائف المعلّم أثمن من كلّ نحاس الفلكي. سأرى بنفسي».',
  'A water-stained leaf of the Pages: "Write down what you saw before you write down what you think."': 'ورقة من الصحائف بلّلها الماء: «اكتب ما رأيت قبل أن تكتب ما تظنّ».',
  'A marine\'s note, pushed into a tally stick: "Three days in the reeds. Kallinikos says the fire on the water frightens them more than it hurts them. It frightens me."': 'ورقة بحّار دُسّت في عود حساب: «ثلاثة أيام في القصب. يقول كالينيكوس إنّ النار على الماء تخيفهم أكثر ممّا تؤذيهم. أمّا أنا فتخيفني».',
  'Arsaber to the Logothete: "Kallinikos burns too freely. I told him we came for books, not for a burned country. He laughed at me."': 'من أرسابر إلى اللوغوثيت: «كالينيكوس يحرق بلا حساب. قلت له إنّا جئنا للكتب لا لبلاد محروقة. فضحك منّي».',
  'A scorched leaf of the Pages: "A city is its copyists. Burn the copyists and you have only walls."': 'ورقة لفحتها النار من الصحائف: «المدينة نسّاخها. احرق النسّاخ فلا يبقى لك إلا الأسوار».',
  'A dice score scratched on a board, and under it: "Krateros says if it comes to it we burn everything. Then what did we march all this way for?"': 'حساب نَرد محفور على لوح، وتحته: «يقول كراتيروس إنّنا إن اضطررنا أحرقنا كلّ شيء. فلِمَ سرنا كلّ هذه المسافة إذن؟».',
  'Arsaber, unsent: "I walked the paper-sellers\' lane today. Ash to the ankle. If my own city burned like this, I would want someone to carry its books away. Perhaps that is all I am doing."': 'من أرسابر، لم تُرسَل: «مشيت اليوم في سوق الورّاقين. الرماد حتى الكاحل. لو احترقت مدينتي هكذا لتمنّيت أن يحمل أحدٌ كتبها بعيدًا. لعلّ هذا كلّ ما أفعله».',
  'A leaf of the Pages, folded small: "Teach the one who will forget you. The lesson stays."': 'ورقة من الصحائف مطويّة صغيرة: «علّم من سينساك. فالدرس يبقى».',
  'A ship\'s manifest: "Cedar chest, one. Brass instruments, eleven. Copyists, none." In another hand: "The envoy asked for copyists. Not one would come."': 'قائمة حمولة سفينة: «صندوق أرز، واحد. آلات نحاس، أحد عشر. نسّاخ، لا أحد». وبخطّ آخر: «طلب الرسول نسّاخًا. فلم يأتِ أحد».',
  'Arsaber\'s last dispatch, never sent: "The guard who hunts us does not want gold. I have nothing else to offer a man like that."': 'آخر رسائل أرسابر، لم تُرسَل: «الحارس الذي يطاردنا لا يريد ذهبًا. وليس عندي ما أعرضه على رجل مثله».',
};
