// Round 28: Arabic for the new boss moves' callouts and hints (merged last in story_ar.js)
export const AR28 = {
  'Blades!': 'النصال!',
  'Ground slam!': 'ضربة الأرض!',
  'Arrow rain!': 'مطر السهام!',
  'Ring of fire!': 'حلقة النار!',
  'To me!': 'إليّ!',
  'Net!': 'الشبكة!',
  'Pinned': 'مقيَّد',
  'From the reeds!': 'من بين القصب!',
  'Open the sluice!': 'افتحوا الهويس!',
  'The vents!': 'المنافس!',
  'Bring the stacks down!': 'أسقطوا الأكوام!',
  'Fire the huts!': 'أحرقوا الأكواخ!',
  'Salt in your eyes!': 'الملح في عينيك!',
  'The tiles!': 'البلاط!',
  'Captains have a second trick now. Watch the ground.': 'للقادة حيلة ثانية الآن. راقب الأرض.',
  'This captain knows his ground. Watch for the marks.': 'هذا القائد يعرف أرضه. راقب العلامات.',
  'Javelins!': 'المزاريق!',
  'The siphon!': 'الزرّاقة!',
  'Behind you!': 'خلفك!',
  'Flurry!': 'وابل الطعنات!',
  'His last stand: watch for a new move.': 'صموده الأخير: ترقّب حركة جديدة.',
  'Pull the props!': 'اسحبوا الدعائم!',
  'Loose!': 'أطلقوا!',
  'The gorge path!': 'درب الخانق!',
  'Three shafts': 'ثلاثة أسهم',
};
