// Round 32: Arabic for story everywhere (scenes32.js, story32.js and the Round 32 lines in scenes.js and epilogue29.js); merged last in story_ar.js
export const AR32 = {
  "Voices across the water. Salim keeps low in the reeds.": "أصوات عبر الماء. سالم ينخفض بين القصب.",
  "The fishermen talk. Burn one village and the rest stop talking.": "الصيّادون يتكلّمون. أحرِق قرية واحدة يسكت الباقون.",
  "We came for books, Kallinikos. Not for a burned country.": "جئنا من أجل الكتب يا كالينيكوس، لا من أجل بلاد محروقة.",
  "Your books burn the same as their reeds, envoy.": "كتبك تحترق كما يحترق قصبهم أيها السفير.",
  "Then keep your fire on the water. That is an order.": "إذن أبقِ نارك على الماء. هذا أمر.",
  "Orders. From a man who reads at night.": "أوامر. من رجل يقرأ في الليل.",
  "Two of them. One wants the Pages. One wants the fire.": "اثنان منهم. واحد يريد الأوراق، وواحد يريد النار.",
  "In the ash of the paper-sellers' lane, a man stands alone, unarmed.": "في رماد درب الورّاقين، رجل يقف وحده بلا سلاح.",
  "Peace, guard. For an hour. I came to see what your war did to this street.": "سلام يا حارس. لساعة واحدة. جئت أرى ما فعلت حربكم بهذا الشارع.",
  "Your men helped burn it.": "رجالك أعانوا على حرقه.",
  "Krateros did. I sent for books, and he sent me smoke.": "كراتيروس فعلها. أرسلت أطلب الكتب، فأرسل إليّ الدخان.",
  "In Constantinople the libraries are cold and half empty. Here they burn. Tell me which is worse.": "في القسطنطينية المكتبات باردة نصف فارغة، وهنا تحترق. قل لي أيّهما أسوأ.",
  "Here, at least, someone is still copying.": "هنا على الأقل ما زال أحد ينسخ.",
  "Then hurry. Krateros will not wait for your copyists.": "إذن أسرِع. كراتيروس لن ينتظر نسّاخك.",
  "He walked away into the smoke. He did not look back.": "مشى مبتعدًا في الدخان، ولم يلتفت.",
  "He warned me. Why would he warn me?": "حذّرني. لماذا يحذّرني؟",
  "A rider comes up the frontier road with the barid's satchel.": "فارس يصعد طريق الثغر بحقيبة البريد.",
  "A letter for the guard Salim. It came through three hands and one exchange of prisoners.": "رسالة للحارس سالم. مرّت بثلاث أيدٍ وبتبادل أسرى واحد.",
  "\"To the guard Salim. The copy you gave me sits in the palace library, and young men wait in line to read it. I did not bring back a theft. I brought back a question.\" Arsaber.": "\"إلى الحارس سالم. النسخة التي أعطيتني في مكتبة القصر، والشبّان يقفون صفًّا ليقرؤوها. لم أرجع بسرقة، رجعت بسؤال.\" أرسابر.",
  "\"To the guard Salim. I came home with nothing, and I find I am glad of it. A book carried off in a chest is a prisoner. Yours are free.\" Arsaber.": "\"إلى الحارس سالم. رجعت إلى بلدي بلا شيء، وأجدني مسرورًا بذلك. الكتاب المحمول في صندوق أسير، وكتبكم حرّة.\" أرسابر.",
  "\"My bowman did not come home with me. He says he owes you a debt he cannot pay. Do not let him pay it in blood.\"": "\"رامي لم يرجع معي. يقول إنّ عليه لك دَينًا لا يقدر على وفائه. لا تدَعه يفِه بالدم.\"",
  "Even the envoy writes letters now.": "حتى السفير يكتب الرسائل الآن.",
  "Everyone writes letters now, guard. The roads are open. That is your fault.": "الكلّ يكتب الرسائل الآن يا حارس. الطرق مفتوحة. وهذا ذنبك.",
  "Salim (a boy)": "سالم (صبيًّا)",
  "Salim knows this gate. He slept in it as a boy, on the caravans.": "سالم يعرف هذه البوّابة. نام فيها صبيًّا أيام القوافل.",
  "Twelve years ago. The same gate, the same road.": "قبل اثنتي عشرة سنة. البوّابة نفسها، والطريق نفسه.",
  "Hold the lead rope, little brother. If the camel bolts, let it go. Never let a rope take your hand.": "أمسك حبل القياد يا أخي الصغير. إن جمح الجمل فاتركه. لا تدَع حبلًا يأخذ يدك.",
  "And if it runs off with the load?": "وإن هرب بالحمل؟",
  "Then we find it. Loads come back. Hands do not.": "نجده. الأحمال ترجع، والأيدي لا ترجع.",
  "He was always saying things like that. I never wrote any of them down.": "كان يقول أشياء كهذه دائمًا. ولم أكتب منها شيئًا.",
  "Muhalhil": "مُهلهِل",
  "Guard. Before you chase the Rum through my reeds, count with me.": "يا حارس. قبل أن تطارد الروم في قصبي، عُدّ معي.",
  "In spring, soldiers of al-Amin, running from the city. In summer, Tahir's men, chasing them. Now the Rum, with fire on the water.": "في الربيع جنود الأمين هاربين من المدينة. في الصيف رجال طاهر يطاردونهم. والآن الروم، ومعهم النار على الماء.",
  "Every one of them took a boat. Not one brought it back.": "كلّهم أخذوا قاربًا، ولم يُرجع واحد منهم قاربًا.",
  "I will bring back what I can.": "سأرجع ما أستطيع.",
  "Then you will be the first. I will count that too.": "إذن تكون الأول. وسأعدّ ذلك أيضًا.",
  "He taught in a prison yard, at the end. Four of us at the bars, every evening the guard allowed it.": "كان يعلّم في ساحة سجن في آخر أمره. أربعة منّا عند القضبان، كلّ مساء يأذن فيه الحارس.",
  "His last lesson was about lamps. A lamp does not argue with the dark, he said. It only stays lit.": "كان درسه الأخير عن السُّرُج. قال: السراج لا يجادل الظلام، إنّما يبقى مضيئًا.",
  "Is that in the Pages?": "أهذا في الأوراق؟",
  "No. I never wrote it down. I was afraid it would sound small on paper.": "لا. لم أكتبه قطّ. خفت أن يبدو صغيرًا على الورق.",
  "Write it down. Jabir's words are going already. I cannot keep them all.": "اكتبه. كلمات جابر تضيع منّي، ولا أقدر أن أحفظها كلّها.",
  "Then tonight we both write. You tell me his, and I will tell you mine.": "إذن نكتب الليلة كلانا. تحكي لي كلماته، وأحكي لك كلماته.",
  "Sumayr": "سُمَير",
  "You have his face. You are Jabir's brother.": "لك وجهه. أنت أخو جابر.",
  "At Ukbara, two years ago, he lent me eight dirhams for a new oar. He said, pay it to whoever needs it more.": "في عُكبَرا قبل سنتين أقرضني ثمانية دراهم لمجداف جديد. قال: أدِّها إلى من هو أحوج.",
  "I never found anyone who needed it more than me. Until today.": "لم أجد قطّ من هو أحوج منّي. حتى اليوم.",
  "Give it to the copyists' barge. For lamp oil. They work all night.": "أعطها لقارب النسّاخ، ثمنًا لزيت السُّرُج. إنّهم يعملون الليل كلّه.",
  "For lamp oil. He would have liked that. He always argued my tolls down, you know.": "لزيت السُّرُج. كان سيحبّ ذلك. كان دائمًا يساومني على أجرتي، أتعلم؟",
  "An old soldier of the Rum sits against a wall, his spear broken across his knees.": "جنديّ عجوز من الروم جالس إلى جدار، ورمحه مكسور على ركبتيه.",
  "Do not trouble yourself, guard. I threw it down at the kilns. I am too old for Arsaber's road.": "لا تُتعب نفسك يا حارس. رميته عند الأتون. أنا أكبر من طريق أرسابر.",
  "Thirty years I marched for Constantinople. They never once asked me where I wanted to go.": "ثلاثين سنة سرت للقسطنطينية، ولم يسألوني مرّة إلى أين أريد أن أذهب.",
  "Where do you want to go?": "إلى أين تريد أن تذهب؟",
  "Somewhere with sheep. Sheep never ask whose side you are on.": "إلى مكان فيه غنم. الغنم لا تسأل في أيّ صفّ أنت.",
  "An old deserter of the Rum. What do you do with him?": "جنديّ هارب عجوز من الروم. ماذا تفعل به؟",
  "Hand him to 'Amr's men, for the qadi.": "سلّمه لرجال عمرو، للقاضي.",
  "Tell no one. Let him hide.": "لا تخبر أحدًا. دَعه يختبئ.",
  "The qadi will hear you. If you are telling the truth, you have nothing to fear from him.": "سيسمعك القاضي. إن كنت صادقًا فلا تخشَ منه شيئًا.",
  "A court that listens. I will believe it when I see it.": "محكمة تسمع. أصدّق حين أرى.",
  "I did not see you. Keep off the roads.": "لم أرَك. ابتعد عن الطرق.",
  "Off the roads. Yes. I know a few things about the roads, guard. I may repay you.": "عن الطرق. نعم. أعرف عن الطرق أشياء يا حارس. قد أردّ لك الجميل.",
  "You again. The marsh people feed me if I mend their nets. I mend nets badly. They feed me anyway.": "أنت مرّة أخرى. أهل الأهوار يطعمونني إن رقعت شباكهم. أرقعها رديئًا، ويطعمونني على كلّ حال.",
  "The qadi's men make me carry water for the camp until my case is heard. It is the most useful thing I have done in thirty years.": "رجال القاضي يجعلونني أحمل الماء للمخيّم حتى تُسمع قضيتي. هذا أنفع ما فعلته في ثلاثين سنة.",
  "Kallinikos used to be a decent engineer. Then someone gave him the fire, and he forgot what else he knew.": "كان كالينيكوس مهندسًا لا بأس به. ثم أعطاه أحدهم النار، فنسي كلّ ما سواها.",
  "Arsaber reads at night and does not sleep. A man like that is dangerous, or he is sorry. Usually both.": "أرسابر يقرأ في الليل ولا ينام. مثله إمّا خطِر وإمّا نادم. وغالبًا الاثنان.",
  "Guard. Listen, I have little time. Arsaber's ship sails at dawn whatever happens.": "يا حارس. اسمع، وقتي قليل. سفينة أرسابر تُبحر عند الفجر مهما حدث.",
  "If he is pressed, he will fire the bridge of boats behind him. I heard him give the order.": "إن ضُيّق عليه أحرق جسر السفن وراءه. سمعته يعطي الأمر.",
  "And they wait for you on the quay road, past the warehouses. Go round by the slips. That is my repayment.": "وهم ينتظرونك على طريق الرصيف بعد المخازن. دُر من ناحية المزالق. هذا جميلي.",
  "The qadi heard me yesterday. He sent me here to tell you myself. He said you had earned it.": "سمعني القاضي أمس، وأرسلني إليك لأخبرك بنفسي. قال إنّك استحققت ذلك.",
  "And you? Where do you go now?": "وأنت؟ إلى أين الآن؟",
  "North. The hills. Someone there must have sheep.": "إلى الشمال. التلال. لا بدّ أنّ هناك أحدًا عنده غنم.",
  "Lubna": "لُبنى",
  "A woman and a boy with a handcart, its wheel off in the dust.": "امرأة وصبيّ مع عربة يد، وعجلتها ملقاة في الغبار.",
  "We left Baghdad when the fires started. Now they say it is over. We are going home.": "خرجنا من بغداد حين بدأت النيران. الآن يقولون انتهى الأمر. نحن راجعون إلى بيتنا.",
  "Is that a real sword? Have you killed a Rum?": "هل هذا سيف حقيقيّ؟ هل قتلت روميًّا؟",
  "Real enough. Hold the cart, not the sword.": "حقيقيّ بما يكفي. أمسك العربة، لا السيف.",
  "Salim lifts the cart while Shabib knocks the wheel back onto its axle.": "سالم يرفع العربة وشبيب يدقّ العجلة في محورها.",
  "Al-Karkh. The lane of the cotton-sellers, by the Sarat bridge. If it is still there, there will be bread for you.": "الكرخ. درب القطّانين عند قنطرة الصراة. إن بقي قائمًا فلك عندنا خبز.",
  "Every boat up the canal is taken by soldiers. We have waited four days.": "كلّ قارب صاعد في النهر أخذه الجنود. ننتظر منذ أربعة أيام.",
  "I counted the soldiers' boats. Twenty-two. One was on fire.": "عددت قوارب الجنود. اثنان وعشرون. واحد كان يحترق.",
  "A boatman will take them for thirty dinars.": "ملّاح يحملهم بثلاثين دينارًا.",
  "Pay their passage (30 dinars).": "ادفع أجرتهم (30 دينارًا).",
  "Speak to the boatman for them.": "كلّم الملّاح من أجلهم.",
  "Thirty dinars. I will owe you this until I am old.": "ثلاثون دينارًا. سأبقى مدينة لك بها حتى أشيخ.",
  "He listens to you. Men with swords are always listened to. Thank you.": "إنّه يسمع لك. أصحاب السيوف يُسمَع لهم دائمًا. شكرًا لك.",
  "You owe me nothing. Find your lane.": "لا تدينين لي بشيء. اذهبي إلى دربك.",
  "The lane of the cotton-sellers. A doorway stands, and nothing behind it.": "درب القطّانين. باب ما زال قائمًا، ولا شيء خلفه.",
  "This was the door. My husband carved the latch.": "هذا كان الباب. زوجي نحت المزلاج.",
  "He went to the wall with the 'ayyarun when Tahir came. He did not come back.": "خرج إلى السور مع العيّارين حين جاء طاهر، ولم يرجع.",
  "I found the latch, mother. It is not even burned.": "وجدت المزلاج يا أمّي. لم يحترق حتى.",
  "Do not say anything, guard. Help me carry the bricks that are still good.": "لا تقل شيئًا يا حارس. ساعدني أحمل الطوب الذي ما زال صالحًا.",
  "Salim carried bricks until dark. Nobody said anything, and it helped.": "حمل سالم الطوب حتى الظلام. لم يقل أحد شيئًا، وكان ذلك عونًا.",
  "Hakam's copyists are teaching me letters! I can write my name. And yours. Look.": "نسّاخ الحكم يعلّمونني الحروف! أكتب اسمي، واسمك. انظر.",
  "My brother always said I should learn to read.": "كان أخي يقول دائمًا إنّ عليّ أن أتعلّم القراءة.",
  "Then I will teach you. It is easy. The letters are only small roads.": "إذن أعلّمك أنا. إنّها سهلة. الحروف ليست إلا طرقًا صغيرة.",
  "I bake for the copyists now. Bread for letters. It is a good trade.": "أخبز للنسّاخ الآن. خبز مقابل حروف. تجارة طيّبة.",
  "The copies belong in the House of Wisdom. Behind walls, in good hands, where they can be guarded.": "النسخ مكانها بيت الحكمة. خلف الجدران، في أيدٍ أمينة، حيث تُحرَس.",
  "Guarded copies are only a smaller prison, Hakam. Give some to the paper-sellers. Let them be sold for bread.": "النسخ المحروسة ليست إلا سجنًا أصغر يا حكم. أعطِ بعضها للورّاقين. دَعها تُباع بثمن الخبز.",
  "Sold for bread, and copied badly, and argued over in every market.": "تُباع بثمن الخبز، وتُنسخ رديئًا، ويُتجادَل فيها في كلّ سوق.",
  "Yes. Exactly that.": "نعم. هذا بالضبط.",
  "Where should the first copies go?": "إلى أين تذهب النسخ الأولى؟",
  "To the House of Wisdom, where they are safe.": "إلى بيت الحكمة، حيث هي آمنة.",
  "To the paper-sellers' market as well.": "إلى سوق الورّاقين أيضًا.",
  "Keep them safe first. They have been burned enough.": "احفظوها أولًا. احترقت بما يكفي.",
  "Safe first. Very well. But I will hold you to \"first\".": "آمنة أولًا. حسنًا. لكنّي سأحاسبك على كلمة \"أولًا\".",
  "Let the market have them. Nobody can burn every stall in Baghdad.": "دَع السوق يأخذها. لا أحد يقدر أن يحرق كلّ دكّان في بغداد.",
  "You sound like him. Very well. Two copies for the lane, and may they be argued over.": "تتكلّم مثله. حسنًا. نسختان للدرب، وليتجادلوا فيهما.",
  "Arsaber to the Logothete, on the gold": "أرسابر إلى اللوغوثيت، عن الذهب",
  "\"Bardanes asks why we trouble with the astronomer's chest when there is gold in every village. I told him gold is spent in a year.\"": "\"يسأل بردانس لماذا نتعب بصندوق الفلكيّ وفي كلّ قرية ذهب. قلت له: الذهب يُنفَق في سنة.\"",
  "Arsaber, a note to himself": "أرسابر، مذكّرة لنفسه",
  "\"The guard's brother died on the dune. Tatzates says he does not remember the face. I believe him, and I wish I did not.\"": "\"مات أخو الحارس على الكثيب. يقول تاتزاتيس إنّه لا يذكر الوجه. أصدّقه، وليتني لم أصدّقه.\"",
  "A mended clay camel": "جمل من طين مرمَّم",
  "A child's clay camel with one leg broken off, found by the canal. Someone has mended it with bitumen, twice.": "جمل طفل من طين انكسرت ساقه، وُجد عند النهر. رمّمه أحدهم بالقار، مرّتين.",
  "The water tally board": "لوح حصص الماء",
  "A canal village's tally board: who drew water, and when. Since Bardanes cut the canal, the last column is empty.": "لوح قرية على النهر: من استقى الماء ومتى. منذ قطع بردانس النهر، والعمود الأخير فارغ.",
  "Arsaber to the Logothete, on the siphon oil": "أرسابر إلى اللوغوثيت، عن زيت السيفون",
  "\"Kallinikos asks for more siphon oil. I have asked him what he means to burn with it. He has not answered.\"": "\"يطلب كالينيكوس مزيدًا من زيت السيفون. سألته ماذا يريد أن يحرق به، ولم يجب.\"",
  "Arsaber, on the marsh people": "أرسابر، عن أهل الأهوار",
  "\"The marsh people paddle out to watch our boats at night. They do not hide. They only watch. It is worse than arrows.\"": "\"أهل الأهوار يجدّفون في الليل ليشاهدوا قواربنا. لا يختبئون، يشاهدون فقط. وهذا أسوأ من السهام.\"",
  "A toy mashuf": "مشحوف لعبة",
  "A reed toy boat, sealed with bitumen like the real ones, with a tiny mast. Scratched on the hull: Saqr.": "قارب لعبة من القصب، مطليّ بالقار كالقوارب الحقيقية، بصارٍ صغير. محفور على جانبه: صقر.",
  "The knotted cord": "الحبل المعقود",
  "A fisherman's cord with a knot for every boat taken this year. Nineteen knots.": "حبل صيّاد فيه عقدة لكلّ قارب أُخذ هذه السنة. تسع عشرة عقدة.",
  "Arsaber to the Logothete, on the pyre": "أرسابر إلى اللوغوثيت، عن المحرقة",
  "\"Krateros has built a pyre in the square and calls it insurance. If it burns, I will answer for it myself.\"": "\"بنى كراتيروس محرقة في الساحة ويسمّيها ضمانًا. إن احترقت فسأُسأل عنها أنا بنفسي.\"",
  "Arsaber, on a book bought in the ash": "أرسابر، عن كتاب اشتراه من الرماد",
  "\"I bought a book in the ash today, a treatise on the astrolabe with its corners burned. I paid the boy twice what he asked. He looked at me as if I were mad.\"": "\"اشتريت اليوم كتابًا من الرماد، رسالة في الأسطرلاب محترقة الأطراف. دفعت للصبيّ ضعف ما طلب، فنظر إليّ كأنّي مجنون.\"",
  "A paper-seller's sign": "لافتة ورّاق",
  "A shop sign, half burned: \"...sellers of paper, pens and ink. Accounts kept.\"": "لافتة دكّان نصفها محترق: \"...باعة الورق والأقلام والحبر. تُحفَظ الحسابات.\"",
  "An arrow in a doorframe": "سهم في عتبة باب",
  "A siege arrow pulled from a doorframe, a strip of cloth tied to it: a family's ration list for the last week of the siege. Bread: none.": "سهم من أيام الحصار انتُزع من عتبة باب، مربوط به شريط قماش: قائمة مؤونة عائلة في الأسبوع الأخير من الحصار. الخبز: لا شيء.",
  "Arsaber, on the ship": "أرسابر، عن السفينة",
  "\"The ship is ready. I have room for one chest and eleven instruments, and I have the chest. Why does it feel empty?\"": "\"السفينة جاهزة. فيها مكان لصندوق واحد وأحد عشر آلة، والصندوق معي. فلماذا يبدو فارغًا؟\"",
  "Arsaber, on the guard": "أرسابر، عن الحارس",
  "\"If the guard reaches the bridge, I will fight him. I do not know which ending I would want to write home about.\"": "\"إن بلغ الحارس الجسر فسأقاتله. ولا أدري أيّ النهايتين أريد أن أكتب عنها إلى بلدي.\"",
  "A boatman's toll token": "عُملة أجرة ملّاح",
  "A toll token of fired clay, stamped with a fish. Jabir would have argued it down to half.": "عملة أجرة من الفخّار، مختومة بسمكة. كان جابر سيساوم عليها حتى النصف.",
  "The copyists' practice sheets": "أوراق تمرين النسّاخ",
  "Practice sheets floating in a crate: the same line of the Pages written forty times, by forty hands.": "أوراق تمرين طافية في صندوق: السطر نفسه من الأوراق مكتوبًا أربعين مرّة، بأربعين يدًا.",
  "Arsaber's last order": "آخر أوامر أرسابر",
  "\"To whoever commands what is left: the company is disbanded. Go home by the Lamis. Take nothing that was not yours.\" Signed with one letter: A.": "\"إلى من يقود ما بقي: الفرقة منحلّة. ارجعوا إلى بلادكم عن طريق اللامس. لا تأخذوا شيئًا ليس لكم.\" وتوقيعه حرف واحد: أ.",
  "Tatzates' answer": "جواب تاتزاتيس",
  "Scratched on the back of Arsaber's order, in another hand: \"Nothing was ever mine. I will stay.\"": "محفور على ظهر أمر أرسابر بخطّ آخر: \"لم يكن لي شيء قطّ. سأبقى.\"",
  "A shepherd's tally stick": "عصا عدّ راعٍ",
  "A tally stick, the notches worn smooth: two hundred sheep. Then a new notch, cut deep, and beside it: \"one Greek.\"": "عصا عدّ مَحَت الأيدي حزوزها: مئتا رأس من الغنم. ثم حزّ جديد عميق، وبجانبه: \"رومي واحد\".",
  "A cracked horn plate": "صفيحة قرن مشقوقة",
  "A cracked plate of horn from a bow, Armenian work. The maker's mark is a running fox.": "صفيحة قرن مشقوقة من قوس، صنعة أرمنية. علامة الصانع ثعلب يعدو.",
  "From a mother in Amorion": "من أمّ في عمّورية",
  "\"Eat what they give you, and do not volunteer for anything.\"": "\"كُل ما يعطونك، ولا تتطوّع لشيء.\"",
  "A pay chit": "صكّ أجر",
  "Four nomismata owed, unpaid since the Taurus. Someone has written under it: \"Ask the envoy.\"": "أربع نوميسمات مستحقّة لم تُدفع منذ جبال طوروس. وكتب أحدهم تحتها: \"اسأل السفير.\"",
  "A sergeant's list": "قائمة عريف",
  "A list of names in a sergeant's hand. Beside six of them, a small cut.": "قائمة أسماء بخطّ عريف. بجانب ستّة منها، شَقّ صغير.",
  "From a sister": "من أخت",
  "\"They say the Baghdad market has a street for every trade. Buy me a knife. A good one.\"": "\"يقولون إنّ لسوق بغداد شارعًا لكلّ صنعة. اشترِ لي سكّينًا. سكّينًا جيّدة.\"",
  "Orders, half burned": "أوامر نصفها محترق",
  "\"...take the grain from the canal villages, but leave them seed for the spring.\"": "\"...خذوا الحنطة من قرى النهر، لكن اتركوا لهم البذر للربيع.\"",
  "A tally of days": "عدّ الأيام",
  "A soldier's count of the days since he left home. Two hundred and twelve, and then nothing.": "عدّ جنديّ للأيام منذ ترك بيته. مئتان واثنا عشر، ثم لا شيء.",
  "An unfinished letter": "رسالة لم تكتمل",
  "\"Eirene, the river here is wider than the Bosporus, and the dates are\"": "\"إيريني، النهر هنا أعرض من البوسفور، والتمر\"",
  "A poultice, in two hands": "لزقة، بخطّين",
  "A recipe for a poultice for sword cuts, written in Greek, and copied again under it in Arabic.": "وصفة لزقة لجروح السيف، مكتوبة باليونانية، ومنسوخة تحتها بالعربية.",
  "A wager": "رهان",
  "\"If Krateros burns the books, I win the mule.\"": "\"إن أحرق كراتيروس الكتب، ربحتُ البغل.\"",
  "A deserter's note": "مذكّرة هارب",
  "Left on a pack: \"I have gone home. Tell the Logothete I drowned.\"": "تُركت على حِمل: \"رجعت إلى بيتي. قولوا للوغوثيت إنّي غرقت.\"",
  "A hill man's receipt": "إيصال رجل من الجبل",
  "In Armenian letters: \"For passage of forty men, twenty silver. Paid: nothing.\"": "بحروف أرمنية: \"أجرة عبور أربعين رجلًا، عشرون من الفضّة. المدفوع: لا شيء.\"",
  "A drawing of a horse": "رسم حصان",
  "A horse drawn in charcoal, very carefully, and under it a child's name.": "حصان مرسوم بالفحم بعناية شديدة، وتحته اسم طفل.",
  "An order of the day": "أمر اليوم",
  "\"No man is to read any book he carries. They are cargo.\"": "\"لا يقرأ أحد كتابًا يحمله. إنّها حمولة.\"",
  "A complaint to the quartermaster": "شكوى إلى أمين المؤن",
  "\"The bread here is better than ours. Send none.\"": "\"الخبز هنا أطيب من خبزنا. لا ترسلوا شيئًا.\"",
  "Arabic, practised": "عربيّة، للتمرين",
  "A few words of Arabic written ten times over, badly: \"Water, please. Bread, please. How much?\"": "كلمات عربية مكتوبة عشر مرّات بخطّ رديء: \"ماء من فضلك. خبز من فضلك. بكم؟\"",
  "From a captain to his son": "من قائد إلى ابنه",
  "\"Learn your letters. A man who can read is never only a soldier.\"": "\"تعلّم الحروف. الرجل الذي يقرأ لا يكون جنديًّا فحسب.\"",
  "Photeinos reached the qadi's court. He talks all day, they say. The clerks have run out of ink twice.": "وصل فوتينوس إلى مجلس القاضي. يقولون إنّه يتكلّم طوال النهار. نفد حبر الكتّاب مرّتين.",
  "A Greek was seen walking south toward Wasit, alone, with no sword. He asked a ferryman the way to the scribes' market.": "شوهد رجل من الروم يمشي جنوبًا نحو واسط، وحده بلا سيف. سأل ملّاحًا عن الطريق إلى سوق الكتّاب.",
  "That old Rum you sent to the qadi? 'Amr's men say he carries water without being asked. Nobody knows what to do with him.": "ذلك الرومي العجوز الذي أرسلته إلى القاضي؟ يقول رجال عمرو إنّه يحمل الماء دون أن يُطلب منه. لا أحد يدري ماذا يصنع به.",
  "From the Nahrawan: the reed village has its roof up. They asked me to find you and say so.": "من النهروان: القرية القصبية رفعت سقفها. طلبوا منّي أن أجدك وأخبرك.",
  "From the Nahrawan: the reed village burned to the water. They are building again on the other bank. They say you did what you had to.": "من النهروان: القرية القصبية احترقت حتى الماء. يبنون من جديد على الضفّة الأخرى. يقولون إنّك فعلت ما كان لا بدّ منه.",
  "The barid runs again from Wasit to the Round City. First time since the siege. Write to someone, guard.": "البريد يجري من جديد من واسط إلى المدينة المدوّرة. أوّل مرّة منذ الحصار. اكتب لأحد يا حارس.",
  "A woman named Lubna asked after you at the post. She says the bricks held.": "امرأة اسمها لُبنى سألت عنك في البريد. تقول إنّ الطوب صمد.",
  "Every boatman on the Tigris knows your name now. Half of them say you owe them money. That is fame.": "كلّ ملّاح على دجلة يعرف اسمك الآن. ونصفهم يقول إنّك مدين له بمال. هذه هي الشهرة.",
  "I was with Tahir's men at the siege. The winning side. It does not feel like winning.": "كنت مع رجال طاهر في الحصار. الجانب الغالب. ولا يشبه الغلبة.",
  "What does it feel like?": "وبماذا يشبه؟",
  "Like carrying water to a fire you started.": "بمن يحمل الماء إلى نار أشعلها هو.",
  "We threw fire over the walls into al-Karkh. Nobody asked who lived under the roofs.": "رمينا النار فوق الأسوار على الكرخ. لم يسأل أحد من يسكن تحت السقوف.",
  "Someone should have.": "كان يجب أن يسأل أحد.",
  "Yes.": "نعم.",
  "This lane. I stood on the wall above it with a pot of fire. I see it every night.": "هذا الدرب. وقفت على السور فوقه ومعي جرّة نار. أراه كلّ ليلة.",
  "Then help me carry the Pages out of it.": "إذن ساعدني أخرج الأوراق منه.",
  "That I can do.": "هذا أقدر عليه.",
  "When this is done I will join the river guard. Somebody has to stand between the city and the next fire.": "حين ينتهي هذا أنضمّ إلى حرس النهر. لا بدّ أن يقف أحد بين المدينة والنار القادمة.",
  "'Amr is looking for men who can hold a line.": "عمرو يبحث عن رجال يحفظون الصفّ.",
  "Then I will start with him.": "إذن أبدأ عنده.",
  "I grew up in the reeds. I can hit a duck in the dark. People are bigger than ducks.": "نشأت في القصب. أصيب البطّة في الظلام. والناس أكبر من البطّ.",
  "And they shoot back.": "ويردّون الرمي.",
  "Ducks don't. I miss ducks.": "البطّ لا يردّ. أشتاق إلى البطّ.",
  "My father says the river ends in a sea so wide you can't see the other side. I don't believe him.": "أبي يقول إنّ النهر ينتهي في بحر واسع لا يُرى طرفه الآخر. لا أصدّقه.",
  "Jabir saw it once, at Basra. He said it smells of salt and money.": "رآه جابر مرّة في البصرة. قال إنّ رائحته ملح ومال.",
  "When the copies go down to Basra, I want to be on the barge.": "حين تنزل النسخ إلى البصرة أريد أن أكون على القارب.",
  "Guarding books?": "تحرس الكتب؟",
  "Guarding books, and looking at the sea.": "أحرس الكتب، وأنظر إلى البحر.",
  "I'll hire on the Basra barge. If the sea is real, I'll send you a shell.": "سأعمل على قارب البصرة. إن كان البحر حقيقيًّا أرسلت لك صدفة.",
  "And if it isn't?": "وإن لم يكن؟",
  "Then I'll send you a duck.": "إذن أرسل لك بطّة.",
  "Naft is honest. It burns what you throw it at. It's the throwing that isn't.": "النفط صادق. يحرق ما ترميه عليه. الرمي هو الذي ليس صادقًا.",
  "Who did you throw it at?": "وعلى من كنت ترميه؟",
  "Whoever the captain pointed to. That's the dishonest part.": "على من يشير إليه القائد. هذا هو الجزء غير الصادق.",
  "In the siege I burned a bridge on the Sarat canal. A week later I had to swim home.": "في الحصار أحرقت قنطرة على نهر الصراة. وبعد أسبوع اضطررت أن أسبح إلى بيتي.",
  "Did you laugh?": "هل ضحكت؟",
  "Not then. Now, a little.": "ليس يومها. الآن، قليلًا.",
  "The Rum burn on water. I've heard of it all my life. Seeing it makes me want to put mine down.": "الروم يحرقون على الماء. سمعت بذلك طوال عمري. ورؤيته تجعلني أريد أن أضع ناري.",
  "You can.": "تستطيع.",
  "Not yet. Not while they have theirs.": "ليس بعد. ليس ما دامت نارهم معهم.",
  "When we're done, I'll sell lamp oil. Same stuff, smaller pots. Nobody gets hurt.": "حين ننتهي أبيع زيت السُّرُج. الشيء نفسه بجِرار أصغر. ولا يتأذّى أحد.",
  "Save me some. I have a lot of lamps to light.": "احفظ لي بعضه. عندي سُرُج كثيرة أوقدها.",
  "In the siege we fought with reed shields and stones. The Khurasanis laughed until we took their wall.": "في الحصار قاتلنا بتروس من القصب وبالحجارة. ضحك الخراسانيون حتى أخذنا سورهم.",
  "Did you keep it?": "وهل احتفظتم به؟",
  "For an afternoon. Best afternoon of my life.": "عصرًا واحدًا. أجمل عصر في حياتي.",
  "My quarter was the Harbiyya. I knew every roof in it. Now I know where every roof used to be.": "حيّي كان الحربية. كنت أعرف كلّ سطح فيه. والآن أعرف أين كان كلّ سطح.",
  "Will you build it again?": "هل تبنيه من جديد؟",
  "I'll steal the bricks for it, at least.": "أسرق له الطوب على الأقل.",
  "The Rum think the lanes are theirs because they hold the square. Lanes belong to whoever knows where they go.": "الروم يظنّون الدروب لهم لأنّهم يمسكون الساحة. الدروب لمن يعرف إلى أين تؤدّي.",
  "Do you?": "وأنت تعرف؟",
  "Every one. Even the burned ones.": "كلّها. حتى المحترقة.",
  "When it's done I'll teach the boys on the quays to climb. Better roofs than swords.": "حين ينتهي هذا أعلّم صبيان الرصيف التسلّق. السطوح خير من السيوف.",
  "'Amr will say the same about spears.": "عمرو سيقول الشيء نفسه عن الرماح.",
  "'Amr is wrong about most things. Not that.": "عمرو مخطئ في أكثر الأمور. ليس في هذا.",
  "Surround him!": "طوّقوه!",
  "That is the guard. The one from the dune!": "هذا هو الحارس. صاحب الكثيب!",
  "Shields together! Hold!": "التروس معًا! اثبتوا!",
  "Close the line!": "سدّوا الصفّ!",
  "Lock shields! Step!": "شبّكوا التروس! تقدّموا!",
  "To the standard! To me!": "إلى الراية! إليّ!",
  "Loose on him!": "ارموه!",
  "Aim low, at the legs!": "صوّبوا منخفضًا، إلى الساقين!",
  "Points down! Let him come!": "الأسنّة إلى أسفل! دعوه يأتي!",
  "Light the siphon!": "أشعلوا السيفون!",
  "Throw high, drag low!": "ارموا عاليًا، واسحبوا منخفضًا!",
  "Raise the engine!": "انصبوا الآلة!",
  "Steady. Breathe out.": "اثبت. أخرِج نفَسك.",
  "Bring the wounded to me!": "هاتوا الجرحى إليّ!",
  "Brace!": "تحصّنوا!",
  "Slip the dogs!": "أطلقوا الكلاب!",
  "Down into the earth!": "إلى باطن الأرض!",
  "Ride round him!": "دوروا حوله!",
  "Lances!": "الرماح!",
  "Spikes on the ground!": "الحسك على الأرض!",
  "Clear a lane for the lance!": "افسحوا طريقًا للرمح!",
  "Stones! On him!": "الحجارة! عليه!",
  "Now! Out of cover!": "الآن! اخرجوا من المكمن!",
  "From the reeds, now!": "من القصب، الآن!",
  "I know what is in that chest, guard. Do you?": "أعرف ما في ذلك الصندوق يا حارس. وأنت؟",
  "I sat at the Teacher's feet once. Come and see what I learned instead.": "جلست عند قدمي المعلّم يومًا. تعال وانظر ماذا تعلّمت بدلًا من ذلك.",
  "Every reed here is mine. Mind where you step.": "كلّ قصبة هنا لي. انتبه أين تخطو.",
  "The water is rising, guard. It always does.": "الماء يرتفع يا حارس. دائمًا يرتفع.",
  "This quarter burned once. It can burn again.": "هذا الحيّ احترق مرّة، ويمكن أن يحترق ثانية.",
  "You will not see me. No one ever does.": "لن تراني. لا أحد يراني أبدًا.",
  "The envoy pays well. Does your astronomer?": "السفير يدفع جيّدًا. وفلكيّك؟",
  "The copyists sing while they wait. It is starting to annoy me.": "النسّاخ يغنّون وهم ينتظرون. بدأ ذلك يزعجني.",
  "Every stone in this quarry has a man behind it.": "وراء كلّ حجر في هذا المقلع رجل.",
  "This fort has never fallen. Come and be the first to try.": "هذا الحصن لم يسقط قطّ. تعال وكن أوّل من يحاول.",
  "One bridge, guard, and I am standing on the far end of it.": "جسر واحد يا حارس، وأنا واقف على طرفه الآخر.",
  "You came. Good. I was tired of waiting.": "جئت. حسنًا. تعبت من الانتظار.",
  "Guard. You again. Every road I take, you are at the end of it.": "يا حارس. أنت مرّة أخرى. كلّ طريق أسلكه أجدك في آخره.",
  "You said somewhere with sheep.": "قلت مكانًا فيه غنم.",
  "And here they are. Walk me to the east road, and I will tell your shepherd where every ewe is penned.": "وها هي. امشِ معي إلى الطريق الشرقي، وأدلّ راعيك على مكان كلّ نعجة.",
  "That autumn the brothers' war was over. Baghdad began to count what it had lost: whole quarters, a caliph, and the paper-sellers' lane.": "في ذلك الخريف انتهت حرب الأخوين. وبدأت بغداد تعدّ ما خسرت: أحياء كاملة، وخليفة، ودرب الورّاقين.",
  "Hakam's copyists began that night, by one lamp. By dawn the first copies were bound for the river.": "بدأ نسّاخ الحكم تلك الليلة على سراج واحد. وعند الفجر كانت النسخ الأولى في طريقها إلى النهر.",
  "Arsaber's men throw down their bows. What becomes of his crews?": "رجال أرسابر يلقون أقواسهم. ما مصير بحّارته؟",
  "Send them home in the exchange on the Lamis.": "أرسِلهم إلى بلادهم في الفداء على اللامس.",
  "Put them to work mending the bridge of boats.": "شغّلهم في ترميم جسر السفن.",
  "His crews threw down their bows. The copyists' barge came down from the yard.": "ألقى بحّارته أقواسهم. ونزل قارب النسّاخ من دار الصناعة.",
  "In the spring exchange on the Lamis, forty men of the Rum walked east over the bridge, and forty men of Baghdad came home.": "في فداء الربيع على اللامس عبر أربعون من الروم الجسر شرقًا، ورجع أربعون من أهل بغداد إلى بيوتهم.",
  "Arsaber's sailors mended the bridge of boats all winter. Bishr said he had never seen better rope-work.": "رمّم بحّارة أرسابر جسر السفن طوال الشتاء. قال بشر إنّه لم يرَ قطّ عمل حبال أتقن.",
  "The House of Wisdom kept the Pages in its finest hand. Scholars came from Basra to read them.": "حفظ بيت الحكمة الأوراق بأجمل خطّ عنده. وجاء العلماء من البصرة ليقرؤوها.",
  "Within a year the Pages were sold on the paper-sellers' lane for the price of a week's bread, and argued over in every market.": "وفي أقلّ من سنة كانت الأوراق تُباع في درب الورّاقين بثمن خبز أسبوع، ويُتجادَل فيها في كلّ سوق.",
  "Six years later the new caliph came home to Baghdad, and the House of Wisdom became a place where the books of every people were copied into Arabic.": "بعد ست سنين رجع الخليفة الجديد إلى بغداد، وصار بيت الحكمة مكانًا تُنقَل فيه كتب كلّ الأمم إلى العربية.",
  "I wrote down the Teacher's lesson about lamps. And three of Jabir's sayings, the way you told them to me.": "كتبت درس المعلّم عن السُّرُج. وثلاثًا من كلمات جابر، كما حكيتها لي.",
  "Loads come back. Hands do not.": "الأحمال ترجع، والأيدي لا ترجع.",
  "That one is on the first page now. Before the Teacher's. I think he would have liked that.": "هذه في الصفحة الأولى الآن، قبل كلام المعلّم. أظنّه كان سيرضى بذلك.",
  "On the last lamp, in a boy's careful letters, Shabib had written Jabir's name.": "على السراج الأخير، بحروف صبيّ حريصة، كتب شبيب اسم جابر.",
  "North, in the Hamrin, an old Greek kept sheep for a shepherd, and never once asked whose side anyone was on.": "في الشمال، في حمرين، رعى روميّ عجوز غنمًا لراعٍ، ولم يسأل قطّ أحدًا في أيّ صفّ هو.",
  "Ma'n joined the river guard, and took 'Amr's boys out on their first watch.": "انضمّ معن إلى حرس النهر، وخرج بصبيان عمرو في أوّل نوبة حراسة لهم.",
  "Dirar hired on the Basra barge. A month later a shell came up the river, wrapped in a scrap of sail.": "عمل ضرار على قارب البصرة. وبعد شهر صعدت في النهر صدفة ملفوفة بقطعة شراع.",
  "Tamim sold lamp oil on the quays. Nobody was ever hurt by it again.": "باع تميم زيت السُّرُج على الرصيف. ولم يتأذّ به أحد بعد ذلك.",
  "Nahshal taught the boys of the quays to climb, and stole the bricks to rebuild the Harbiyya.": "علّم نهشل صبيان الرصيف التسلّق، وسرق الطوب ليعيد بناء الحربية.",
  "Somebody has been leaving mended nets by my tent. Badly mended. I think I know who.": "أحدهم يترك شباكًا مرقوعة عند خيمتي. مرقوعة رديئًا. أظنّني أعرف من.",
  "I sold a copy of the Pages from my stall yesterday. To a baker's boy. He paid in bread.": "بعت أمس نسخة من الأوراق في دكّاني لابن خبّازة. دفع خبزًا.",
  "Your Rum sailors tie a knot I have never seen. I made them teach it to me before they went home.": "بحّارتك الروم يعقدون عقدة لم أرَها قطّ. جعلتهم يعلّمونني إيّاها قبل أن يرجعوا.",
  "That old Greek you brought in? The qadi let him go. He carried water for my camp a month first. Best water-carrier I ever had.": "ذلك الرومي العجوز الذي جئت به؟ أطلقه القاضي. حمل الماء لمخيّمي شهرًا قبل ذلك. أفضل سقّاء عرفته.",
  "Jabir always took the room by the gate. First to hear trouble, he said.": "كان جابر يأخذ دائمًا الغرفة عند البوّابة. قال: أوّل من يسمع المتاعب.",
  "The kilns never stop. Even in a war, somebody needs bricks.": "الأتون لا يتوقّف. حتى في الحرب يحتاج أحد إلى الطوب.",
  "The old kings built this arch to last. It has outlasted them.": "بنى الملوك القدماء هذا الطاق ليبقى. وبقي بعدهم.",
  "A fort made of reeds. The marsh folk must laugh at it.": "حصن من القصب. لا بدّ أنّ أهل الأهوار يضحكون منه.",
  "A whole village under the water. The flood took it, or the war. Out here it is hard to tell.": "قرية كاملة تحت الماء. أخذها الفيضان أو الحرب. هنا يصعب أن تعرف.",
  "The weir is older than Baghdad. It has held back worse than Kallinikos.": "السِّكر أقدم من بغداد. وقد صدّ ما هو أسوأ من كالينيكوس.",
  "Every door on this lane had a name over it once.": "كلّ باب في هذا الدرب كان فوقه اسم يومًا.",
  "Ash to the ankle. All of it was paper.": "رماد حتى الكاحل. وكلّه كان ورقًا.",
  "Krateros chose the market square. He wanted the city to watch.": "اختار كراتيروس ساحة السوق. أراد أن تشاهد المدينة.",
  "The ribs of a ship nobody will finish this year.": "أضلاع سفينة لن يُتمّها أحد هذه السنة.",
  "Burned hulls, and the copyists' boat somewhere among them.": "هياكل محروقة، وقارب النسّاخ في مكان بينها.",
  "The bridge of boats. Half of Baghdad crosses here on an ordinary day.": "جسر السفن. نصف بغداد يعبر هنا في يوم عاديّ.",
  "Stone and wind. Jabir would have hated these hills.": "حجر وريح. كان جابر سيكره هذه التلال.",
  "The frontier road. Eight days to the Rum, the soldiers wrote.": "طريق الثغر. ثمانية أيام إلى الروم، كما كتب الجنود.",
  "Somewhere up here is the man who loosed the arrow.": "في مكان ما هنا الرجل الذي أطلق السهم.",
  "Things Found": "أشياء وُجدت",
  "Letters of the Rum": "رسائل الروم",
  "Something left behind": "شيء تُرك وراءه",
  "A letter of the Rum": "رسالة من الروم",
  "Rafi' the courier": "رافع ساعي البريد",
  "Rum": "رومي",
  "The Account Kept": "الحساب المحفوظ",
  "Every thing left behind, remembered.": "كلّ ما تُرك وراءه، محفوظ في الذاكرة.",
  "All twenty found. The Account Kept is yours.": "وُجدت العشرون كلّها. الحساب المحفوظ لك.",
  "Every letter read. Someone should send them home.": "قُرئت الرسائل كلّها. على أحد أن يرسلها إلى بيوتها.",
  "A leaf of the Pages": "ورقة من الأوراق",
  "A soldier's letter": "رسالة جنديّ",
  "Tatzates' quiver lid": "غطاء جعبة تاتزاتيس",
  "Mantle": "عباءة",
};
