// Round 32: Arabic for the story round (Arsaber's lane, the scenes inside each act, the guards' and the family's stories,
// deserters, soldiers' shouts and letters, finds, lines on the road, the epilogue's letter and closing captions).
// Merged last in story_ar.js. Backtick strings, so apostrophes and quotes stay as they are in the English.
export const AR32 = {
  // ---- names and titles
  [`Umayma`]: `أميمة`, [`Nadr`]: `النضر`, [`Qays`]: `قيس`, [`Nasim`]: `نسيم`, [`Shabib`]: `شبيب`,
  [`Doukitzes`]: `دوكيتزيس`, [`Leon`]: `ليون`, [`Zonaras`]: `زوناراس`, [`Kosmas`]: `كوزماس`, [`Soldier`]: `جندي`,
  [`Going home to al-Karkh`]: `عائدون إلى الكرخ`, [`'Amr's pupil`]: `تلميذ عمرو`, [`Deserter`]: `فارّ من الجند`,
  [`Examine`]: `تفحّص`, [`Finds`]: `لُقى`, [`Letters from the Company`]: `رسائل من الفرقة`, [`A soldier's letter`]: `رسالة جندي`,
  [`Finds and letters`]: `اللُّقى والرسائل`,
  [`Everything the war dropped, picked up and kept.`]: `كلّ ما أسقطته الحرب، التُقط وحُفظ.`,
  [`Every find and every letter. The Chronicler's Satchel is yours.`]: `كلّ لُقية وكلّ رسالة. حقيبة المؤرّخ لك.`,
  [`The Chronicler's Satchel`]: `حقيبة المؤرّخ`, [`Jabir's Spear-Grip`]: `مقبض رمح جابر`, [`Wound badly, held well.`]: `لُفّ رديئًا، وأُمسك جيّدًا.`,
  [`You do not have 100 gold.`]: `ليس معك مئة دينار.`,
  [`Go well, guard.`]: `في أمان، يا حارس.`, [`Mind the roads.`]: `احذر الطرق.`, [`Show me your sword again?`]: `تريني سيفك مرّة أخرى؟`,
  [`Deal with the men around first`]: `تخلّص من الرجال حولك أوّلًا`, [`He waits for your answer.`]: `ينتظر جوابك.`,
  [`Spare him. Let him go south.`]: `اعفُ عنه. دعه يمضي جنوبًا.`, [`Turn him in to the qadi's men.`]: `سلّمه إلى رجال القاضي.`,
  [`You let him go.`]: `تركته يمضي.`, [`He will answer before the qadi.`]: `سيقف أمام القاضي.`,
  [`The watch has posted Arsaber's face at every gate.`]: `علّق العسس صورة أرسابر على كلّ باب.`,
  [`Arsaber walked on. He will remember it.`]: `مضى أرسابر. سيذكر ذلك.`,
  [`Ma'n fights beside you with a lighter heart.`]: `يقاتل معن إلى جانبك بقلب أخفّ.`,
  [`Dirar will teach the camp boys to hunt.`]: `سيعلّم ضرار صبيان المعسكر الصيد.`,
  [`Tamim gives you two flasks of his uncle's good oil.`]: `يعطيك تميم قارورتين من زيت عمّه الجيّد.`,
  [`Talha gives back your purse, with interest.`]: `يردّ إليك طلحة كيسك، ومعه زيادة.`,

  // ---- Arsaber in the paper-sellers' lane
  [`In the ash of the paper-sellers' lane, a man in a plain cloak is reading a burned shop sign.`]: `في رماد سوق الورّاقين، رجل في عباءة بسيطة يقرأ لافتة دكّان محترقة.`,
  [`You are the guard. My captains describe your face in every report. They draw it badly.`]: `أنت الحارس. يصف قادتي وجهك في كلّ تقرير. ويرسمونه رسمًا رديئًا.`,
  [`Arsaber.`]: `أرسابر.`,
  [`No sword today. I came to see what your city did to itself. Forty paper shops on this lane, and not one roof.`]: `لا سيف اليوم. جئت لأرى ما فعلته مدينتكم بنفسها. أربعون دكّان ورق في هذا الزقاق، وليس فيه سقف واحد.`,
  [`Your men burned the Pages in the kilns.`]: `رجالك أحرقوا الأوراق في الأتون.`,
  [`Olbianos burned them, to buy his life. I wrote home that a man who burns books has no place in my company. They did not answer.`]: `أحرقها أولبيانوس ليشتري حياته. كتبت إلى بلادي أنّ رجلًا يحرق الكتب لا مكان له في فرقتي. لم يجيبوا.`,
  [`In a hundred years no one will remember the brothers' war. They will remember who kept the books. I would like it to be us.`]: `بعد مئة عام لن يذكر أحد حرب الأخوين. سيذكرون من حفظ الكتب. وأودّ أن نكون نحن.`,
  [`Arsaber turns to walk on down the lane, alone.`]: `يستدير أرسابر ليمضي في الزقاق، وحده.`,
  [`Let him walk.`]: `دعه يمضي.`, [`Call the watch.`]: `نادِ العسس.`,
  [`Go. Next time we meet, it will not be in the ash.`]: `امضِ. حين نلتقي مرّة أخرى، لن يكون ذلك في الرماد.`,
  [`No. It will be at the river. I will remember this, guard.`]: `لا. سيكون عند النهر. سأذكر هذا، يا حارس.`,
  [`Arsaber walked on down the lane and did not look back.`]: `مضى أرسابر في الزقاق ولم يلتفت.`,
  [`Watch! Here! The envoy of the Rum!`]: `يا عسس! هنا! رسول الروم!`,
  [`Of course. I would have done the same.`]: `طبعًا. كنت سأفعل مثلك.`,
  [`The watch came running. Arsaber was over the roofs before they reached the lane, but now every gate in al-Karkh knows his face.`]: `جاء العسس يركضون. كان أرسابر قد عبر السطوح قبل أن يبلغوا الزقاق، لكنّ كلّ باب في الكرخ يعرف وجهه الآن.`,
  [`And the guard. You let me walk in al-Karkh. So I come to you under a truce, and not with an army.`]: `والحارس. تركتني أمضي في الكرخ. لذلك آتيكم بهدنة، لا بجيش.`,
  [`And the guard who set the watch on me in al-Karkh. I came anyway. Under a truce, this time.`]: `والحارس الذي أطلق عليّ العسس في الكرخ. جئت على أيّ حال. بهدنة، هذه المرّة.`,
  [`No watch to call on this bridge, guard. Only the two of us.`]: `لا عسس تناديهم على هذا الجسر، يا حارس. نحن الاثنان فقط.`,
  [`You let me walk once, guard. I cannot do the same for you.`]: `تركتني أمضي مرّة، يا حارس. لا أستطيع أن أفعل مثلك.`,

  // ---- a scene inside each act
  [`The village asks for the names of the men who died on the road. They want to say them at the canal.`]: `أهل القرية يسألون عن أسماء الرجال الذين ماتوا على الطريق. يريدون أن يقولوها عند القناة.`,
  [`Ka'b, who sang badly. Sinan, and his brother 'Awf. Old Mazin, who walked that road for thirty years.`]: `كعب، الذي كان يغنّي رديئًا. سنان، وأخوه عوف. والشيخ مازن، الذي مشى ذلك الطريق ثلاثين عامًا.`,
  [`And Jabir.`]: `وجابر.`,
  [`Say them again tomorrow, and the day after. That is how the account is kept.`]: `قلها مرّة أخرى غدًا، وبعد غد. هكذا يُحفظ الحساب.`,
  [`That evening the village children learned five names, and said them at the water.`]: `في ذلك المساء حفظ أطفال القرية خمسة أسماء، وقالوها عند الماء.`,
  [`You do not like the water either, I think.`]: `وأنت أيضًا لا تحبّ الماء، فيما أظنّ.`,
  [`The year I was nine, the river came over the dykes. Our father had died of a fever that spring.`]: `في السنة التي بلغت فيها التاسعة، فاض النهر فوق السدود. وكان أبونا قد مات بالحمّى ذلك الربيع.`,
  [`Jabir was fourteen. He carried our mother's loom through water to his chest, and then he came back for me.`]: `كان جابر في الرابعة عشرة. حمل نول أمّنا في ماء يبلغ صدره، ثمّ عاد من أجلي.`,
  [`After that he was not only my brother. He was the one who came back.`]: `بعد ذلك لم يعد أخي فقط. صار الذي يعود.`,
  [`Then you have been doing the same for him, all this way.`]: `إذن فأنت تفعل مثله من أجله، طوال هذا الطريق.`,
  [`There was an instrument maker on this side of the canal, Nu'aym. He made the best astrolabes in Baghdad. I bought my first one from him, on credit.`]: `كان على هذا الجانب من القناة صانع آلات اسمه نُعيم. كان يصنع أجود الأسطرلابات في بغداد. اشتريت أوّل واحد منه، بالدَّين.`,
  [`Where is he?`]: `وأين هو؟`,
  [`The fire came down his lane in one night. His neighbours say he went back in for his brass plates.`]: `نزلت النار في زقاقه في ليلة واحدة. يقول جيرانه إنّه عاد إلى الداخل من أجل صفائحه النحاسية.`,
  [`Half of al-Karkh burned in one season. Every house was somebody's Nu'aym.`]: `احترق نصف الكرخ في موسم واحد. وكان في كلّ بيت نُعيمٌ لأحد ما.`,
  [`Then we finish this, and you make an instrument and give it his name.`]: `إذن ننهي هذا، وتصنع أنت آلة وتعطيها اسمه.`,
  [`Yes. That is how scholars remember. We put the name on the work.`]: `نعم. هكذا يتذكّر العلماء. نضع الاسم على العمل.`,
  [`All night in the khan, Hakam's copyists worked by lamplight: forty pens on the same Pages.`]: `طوال الليل في الخان، عمل نسّاخ الحكم على ضوء السُّرج: أربعون قلمًا على الأوراق ذاتها.`,
  [`Hakam has not slept in two days. He says if he sleeps, the ink will dry in the pot and he will have to answer for it.`]: `لم ينم الحكم منذ يومين. يقول إنّه إن نام جفّ الحبر في الدواة وصار عليه أن يُسأل عن ذلك.`,
  [`How many copies?`]: `كم نسخة؟`,
  [`Seven by tomorrow. Ten by the end of the month. Wasit, Basra, Merv, Fustat... Once they are on the water, no army can call them back.`]: `سبع بحلول الغد. عشر بنهاية الشهر. واسط، البصرة، مرو، الفسطاط... حين تصير على الماء، لا جيش يستطيع أن يستردّها.`,
  [`Jabir carried one chest. You are making ten cities carry it.`]: `حمل جابر صندوقًا واحدًا. وأنت تجعل عشر مدن تحمله.`,
  [`That is the whole art of it. A secret in one chest can be burned. A thing everyone knows cannot.`]: `هذا هو الفنّ كلّه. السرّ في صندوق واحد يمكن أن يُحرق. أمّا ما يعرفه الجميع فلا.`,
  [`We found this in the quarry, among their trophies. The men said it was taken on the caravan road, in the spring.`]: `وجدنا هذا في المقلع، بين غنائمهم. قال الرجال إنّه أُخذ على طريق القافلة، في الربيع.`,
  [`...That is Jabir's spear. He wound the grip himself. Badly.`]: `...هذا رمح جابر. لفّ المقبض بنفسه. لفًّا رديئًا.`,
  [`Then it is yours. A trophy belongs with the dead man's family, not with the men who killed him.`]: `إذن هو لك. الغنيمة مكانها عند أهل الميت، لا عند الذين قتلوه.`,
  [`He would want it carried, not hung on a wall.`]: `كان سيريده محمولًا، لا معلّقًا على جدار.`,
  [`Salim tied his brother's spear behind his saddle. It rode with him from then on.`]: `ربط سالم رمح أخيه خلف سرجه. ورافقه منذ ذلك اليوم.`,

  // ---- the hired guards' stories
  [`My village was on the Sarat canal. Tahir's Khurasanis camped in it for the siege. They burned the palms for firewood.`]: `كانت قريتي على نهر الصراة. عسكر فيها خراسانيّو طاهر أيام الحصار. أحرقوا النخل حطبًا.`,
  [`Your people?`]: `وأهلك؟`, [`Scattered. I took the first pay anyone offered.`]: `تفرّقوا. أخذت أوّل أجر عرضه عليّ أحد.`,
  [`A boatman says a woman from my village sells bread on the quays now. He did not know her name.`]: `يقول ملّاح إنّ امرأة من قريتي تبيع الخبز على الشطّ الآن. لم يعرف اسمها.`,
  [`Ask him again.`]: `اسأله مرّة أخرى.`, [`I asked him nine times. He thinks I am mad.`]: `سألته تسع مرّات. يظنّني مجنونًا.`,
  [`It was my sister. She has a husband, two children and a temper. She says palms grow back in seven years.`]: `كانت أختي. لها زوج وولدان وطبع حادّ. تقول إنّ النخل يعود في سبع سنين.`,
  [`Will you go?`]: `هل ستذهب؟`, [`When you are done with me. Seven years is a long time to plant. I should start.`]: `حين تنتهي منّي. سبع سنين وقت طويل للغرس. عليّ أن أبدأ.`,
  [`I hunted gazelle on the desert edge before the war. Then al-Amin's men paid better for shooting men.`]: `كنت أصيد الغزلان على طرف البادية قبل الحرب. ثمّ دفع رجال الأمين أكثر مقابل رمي الرجال.`,
  [`And now?`]: `والآن؟`, [`Now you pay. I count every arrow, guard. I know where each one went.`]: `الآن أنت تدفع. أعدّ كلّ سهم، يا حارس. أعرف أين ذهب كلّ واحد.`,
  [`In the siege I shot a man on a roof. In the smoke I took him for a Khurasani archer. He was a baker, putting out a fire.`]: `في الحصار رميت رجلًا على سطح. في الدخان حسبته راميًا خراسانيًا. كان خبّازًا يطفئ نارًا.`,
  [`...`]: `...`, [`I do not want an answer. I only wanted somebody to know.`]: `لا أريد جوابًا. أردت فقط أن يعرف أحد.`,
  [`A boy in the camp wants to learn the bow. I told him I teach gazelle, not men. He said that suited him.`]: `صبيّ في المعسكر يريد أن يتعلّم القوس. قلت له إنّي أعلّم صيد الغزلان، لا الرجال. قال إنّ هذا يناسبه.`,
  [`It suits you too.`]: `ويناسبك أنت أيضًا.`, [`Yes. I think it does.`]: `نعم. أظنّه كذلك.`,
  [`I was a naffat in the city's own ranks. In the siege they ordered us to burn the houses by the Harb gate, so Tahir's men could not use them.`]: `كنت نفّاطًا في صفوف المدينة نفسها. في الحصار أمرونا أن نحرق البيوت عند باب حرب، كي لا يتّخذها رجال طاهر.`,
  [`You did it?`]: `وفعلت؟`, [`I did it. One of them was my uncle's.`]: `فعلت. وكان واحد منها بيت عمّي.`,
  [`Naft is only oil from the ground, you know. It lights lamps as well as roofs. My grandfather sold it for lamps.`]: `النفط ليس إلّا زيتًا من الأرض، كما تعلم. يضيء السُّرج كما يُشعل السقوف. كان جدّي يبيعه للسُّرج.`,
  [`Why did you stop?`]: `ولماذا توقّفت؟`, [`Lamps pay less than wars.`]: `السُّرج تدفع أقلّ من الحروب.`,
  [`When this is done I will sell lamp oil on the quays. Clean oil, for reading by. My uncle says he will buy the first jar.`]: `حين ينتهي هذا سأبيع زيت السُّرج على الشطّ. زيتًا نظيفًا، للقراءة. يقول عمّي إنّه سيشتري أوّل جرّة.`,
  [`He forgave you?`]: `وسامحك؟`, [`He says the fire was the caliph's, and the house is ours to build again. I am helping him with the roof.`]: `يقول إنّ النار كانت نار الخليفة، والبيت بيتنا نبنيه من جديد. أساعده في السقف.`,
  [`In the siege we fought for al-Amin with reed helmets and tarred mats for shields, and no pay. The 'ayyarun of the Harbiyya.`]: `في الحصار قاتلنا من أجل الأمين بخوذ من القصب وحُصر مقيّرة دروعًا، وبلا أجر. عيّارو الحربيّة.`,
  [`Why?`]: `لماذا؟`, [`Because the generals had run, and somebody had to.`]: `لأنّ القادة كانوا قد هربوا، وكان على أحد أن يفعل.`,
  [`My band scattered when the city fell. Half went to Tahir for pay. Half went into the river.`]: `تفرّقت جماعتي حين سقطت المدينة. نصفهم ذهب إلى طاهر من أجل الأجر. ونصفهم ذهب إلى النهر.`,
  [`And you?`]: `وأنت؟`, [`I went to whoever paid next. You, guard. Do not make a speech of it.`]: `ذهبت إلى من دفع بعدهم. أنت، يا حارس. لا تجعل منها خطبة.`,
  [`Here. Your purse. I took it the first day you hired me, to see if you would notice.`]: `خذ. كيسك. أخذته أوّل يوم استأجرتني، لأرى إن كنت ستلاحظ.`,
  [`I noticed.`]: `لاحظت.`, [`I know. You never said a word. An 'ayyar keeps faith with whoever keeps faith with him. That is all the law we have.`]: `أعرف. لم تقل كلمة قطّ. العيّار يفي لمن يفي له. هذا كلّ ما لدينا من قانون.`,
  [`My sister's barge leaves at dawn. Seven years of palms, guard. Come and eat the first dates.`]: `مركب أختي يرحل عند الفجر. سبع سنين من النخل، يا حارس. تعال وكُل أوّل التمر.`,
  [`I will hold you to it.`]: `سأذكّرك بوعدك.`,
  [`The camp boy brought down his first gazelle yesterday. He cried, and then he ate it. A good start.`]: `أسقط صبيّ المعسكر أوّل غزال له أمس. بكى، ثمّ أكله. بداية حسنة.`,
  [`Teach him to count his arrows.`]: `علّمه أن يعدّ سهامه.`,
  [`My uncle has a roof again, and I have a stall by the water. Lamp oil, clean, for reading. The copyists buy it.`]: `صار لعمّي سقف من جديد، ولي دكّة عند الماء. زيت سُرج نظيف، للقراءة. يشتريه النسّاخ.`,
  [`Then every copy has a little of your fire in it.`]: `إذن في كلّ نسخة شيء من نارك.`,
  [`I go back to the Harbiyya. Somebody has to watch the lanes now the soldiers are leaving.`]: `أعود إلى الحربيّة. على أحد أن يحرس الأزقّة الآن والجند يرحلون.`,
  [`Keep faith, Talha.`]: `كن وفيًّا، يا طلحة.`, [`With you? Always. With the rest of them, we will see.`]: `معك؟ دائمًا. مع الباقين، سنرى.`,

  // ---- the family going home to al-Karkh
  [`Is this the road to Baghdad? We left al-Karkh when the fires started. A year in my cousin's village is long enough.`]: `أهذا طريق بغداد؟ تركنا الكرخ حين بدأت الحرائق. سنة في قرية ابن عمّي تكفي.`,
  [`My sister thinks our house is still standing. I have stopped arguing with her.`]: `أختي تظنّ أنّ بيتنا ما زال قائمًا. توقّفت عن مجادلتها.`,
  [`Is that a real sword? Have you killed anyone with it?`]: `أهذا سيف حقيقي؟ هل قتلت به أحدًا؟`,
  [`Too many. Carry your mother's bundle, Qays. That is the harder job.`]: `كثيرين جدًا. احمل صُرّة أمّك يا قيس. ذلك هو العمل الأصعب.`,
  [`The canals are foul from here to the river. We have not had clean water in two days.`]: `القنوات فاسدة من هنا إلى النهر. لم نشرب ماءً نظيفًا منذ يومين.`,
  [`The boy is looking at your water flask.`]: `الصبيّ ينظر إلى قربتك.`,
  [`Give them your water.`]: `أعطهم ماءك.`, [`Point them to the clean well in the village.`]: `دُلّهم على البئر النظيفة في القرية.`,
  [`It is cold! Mother, it is cold!`]: `إنّه بارد! يا أمّي، إنّه بارد!`,
  [`We will remember this, guard. Every one of us.`]: `سنذكر هذا يا حارس. كلّ واحد منّا.`,
  [`The village well. Good. Thank you, guard.`]: `بئر القرية. حسنًا. شكرًا يا حارس.`,
  [`The boatmen want three dirhams each to take us across. We have four between us.`]: `يريد الملّاحون ثلاثة دراهم عن كلّ واحد ليعبروا بنا. معنا أربعة كلّنا.`,
  [`Khalaf is teaching me to pole a boat. He says I am terrible.`]: `يعلّمني خلف أن أدفع القارب بالمردي. يقول إنّي سيّئ جدًا.`,
  [`You gave us your water on the canal road. Qays has told everyone in the marsh.`]: `أعطيتنا ماءك على طريق القناة. حكى قيس ذلك لكلّ من في الأهوار.`,
  [`We found the well, guard. And now we have found a marsh.`]: `وجدنا البئر يا حارس. والآن وجدنا هورًا.`,
  [`Khalaf owes me a favour. Tell him the guard said to take you across.`]: `لي عند خلف معروف. قولوا له إنّ الحارس أوصاه أن يعبر بكم.`,
  [`If that works, I will believe anything about you they say in the camp.`]: `إن نجح ذلك، سأصدّق كلّ ما يقولونه عنك في المعسكر.`,
  [`Umayma stood in what was left of a doorway, with ash to her ankles.`]: `وقفت أميمة فيما بقي من عتبة باب، والرماد إلى كاحليها.`,
  [`This was the door. You can still see where my husband cut the year we were married into the frame.`]: `هنا كان الباب. ما زلت ترى أين حفر زوجي في الإطار سنة زواجنا.`,
  [`The walls stand. Half the walls. We have built with less.`]: `الجدران قائمة. نصف الجدران. بنينا بأقلّ من هذا.`,
  [`Where will I sleep?`]: `أين سأنام؟`,
  [`Here, Qays. Under the sky until there is a roof, and then under the roof.`]: `هنا يا قيس. تحت السماء حتّى يكون سقف، ثمّ تحت السقف.`,
  [`Timber costs more than they have.`]: `الخشب يكلّف أكثر ممّا معهم.`,
  [`Pay for their timber (100 gold).`]: `ادفع ثمن خشبهم (مئة دينار).`, [`Wish them well.`]: `تمنَّ لهم الخير.`,
  [`That is a roof. That is a whole roof. I do not know what to say.`]: `هذا سقف. هذا سقف كامل. لا أعرف ماذا أقول.`,
  [`Say nothing. Build it.`]: `لا تقل شيئًا. ابنه.`,
  [`Then we build slowly. Go well, guard.`]: `إذن نبني على مهل. في أمان يا حارس.`,
  [`I carry bales on the quays now. Two copper a bale. My back has opinions about it.`]: `أحمل الأحمال على الشطّ الآن. فلسان عن كلّ حمل. ولظهري رأي في ذلك.`,
  [`The roof is up. Come and see it, when the war lets you go.`]: `ارتفع السقف. تعال وانظر إليه، حين تتركك الحرب.`,
  [`We have two walls and a cloth over them. It keeps the dew off. Mostly.`]: `لنا جداران وفوقهما قماش. يردّ الندى. في الغالب.`,
  [`I carry water for the copyists in the khan. Hakam gives me a copper and lets me watch them write.`]: `أحمل الماء للنسّاخ في الخان. يعطيني الحكم فلسًا ويتركني أشاهدهم يكتبون.`,
  [`Watch carefully, Qays. That is worth more than the copper.`]: `شاهد جيّدًا يا قيس. ذلك أثمن من الفلس.`,
  [`Hakam is teaching me my letters. I can write my name. And yours. Look.`]: `يعلّمني الحكم الحروف. أستطيع أن أكتب اسمي. واسمك. انظر.`,
  [`...That is my name. Badly, but that is my name.`]: `...هذا اسمي. مكتوب رديئًا، لكنّه اسمي.`,
  [`The first bread from the new oven. You do not get to refuse it.`]: `أوّل خبز من التنّور الجديد. لا يحقّ لك أن ترفضه.`,
  [`We have a roof now, at last. The neighbours raised it with us, one beam each.`]: `صار لنا سقف أخيرًا. رفعه الجيران معنا، كلّ واحد بعارضة.`,
  [`Half of al-Karkh is building. The other half is selling timber. It sounds like a city again.`]: `نصف الكرخ يبني. والنصف الآخر يبيع الخشب. صار لها صوت مدينة من جديد.`,
  [`Are you the guard who fights the Rum? 'Amr says you hold your spear like a stick.`]: `أأنت الحارس الذي يقاتل الروم؟ يقول عمرو إنّك تمسك رمحك كأنّه عصا.`,
  [`'Amr made me stand in the mud all morning. He says if I can hold a line in mud I can hold it anywhere.`]: `جعلني عمرو أقف في الطين طوال الصباح. يقول إن ثبتُّ في الصفّ في الطين ثبتُّ في أيّ مكان.`,
  [`I used to sell water in these lanes, before the fire. Now I am learning to guard the wells instead.`]: `كنت أبيع الماء في هذه الأزقّة، قبل الحريق. الآن أتعلّم أن أحرس الآبار بدلًا من ذلك.`,
  [`The copyists' boat is the most important boat on the river. 'Amr says so. He says we guard it with our lives. I said yes.`]: `قارب النسّاخ أهمّ قارب على النهر. هكذا يقول عمرو. يقول إنّنا نحرسه بأرواحنا. قلت نعم.`,
  [`'Amr says the hills are no place for a boy. I said I am not a boy, I am a line. He laughed for the first time.`]: `يقول عمرو إنّ التلال ليست مكانًا لصبيّ. قلت إنّي لست صبيًّا، أنا صفّ. فضحك لأوّل مرّة.`,

  // ---- the deserters
  [`Do not. I have no sword. I threw it in the canal the night Olbianos burned the books.`]: `لا تفعل. لا سيف معي. رميته في القناة ليلة أحرق أولبيانوس الكتب.`,
  [`I wrote to my mother every week. I never sent one. The officers read everything.`]: `كنت أكتب لأمّي كلّ أسبوع. لم أرسل رسالة واحدة. الضبّاط يقرؤون كلّ شيء.`,
  [`Where will you go?`]: `إلى أين ستذهب؟`,
  [`South, to the Gulf ports. A ship to anywhere that is not a war. If you let me.`]: `جنوبًا، إلى موانئ الخليج. سفينة إلى أيّ مكان ليس فيه حرب. إن تركتني.`,
  [`Kallinikos made us pour the fire on the reed houses. There were people in them. I heard them.`]: `جعلنا كالينيكوس نصبّ النار على بيوت القصب. كان فيها ناس. سمعتهم.`,
  [`I put my siphon in the water and walked into the reeds. I have been eating raw fish for six days.`]: `وضعت سيفوني في الماء ومشيت إلى القصب. آكل السمك نيئًا منذ ستّة أيّام.`,
  [`Now I am too tired to run from you. Do what you want.`]: `الآن أنا أتعب من أن أهرب منك. افعل ما تريد.`,
  [`Krateros says if we cannot keep the Pages, we burn the whole quarter with them.`]: `يقول كراتيروس إن لم نستطع أن نحتفظ بالأوراق، نحرق الحيّ كلّه معها.`,
  [`I have a city of my own, guard, and a wife in it. I would not want it burned for a book.`]: `لي مدينة أنا أيضًا يا حارس، وفيها زوجة. ما كنت لأرضى أن تُحرق من أجل كتاب.`,
  [`Then why are you hiding in its ash?`]: `فلماذا تختبئ في رمادها؟`,
  [`Because the watch hangs Rum on sight, and my own captain hangs deserters. This lane is the only place nobody looks.`]: `لأنّ العسس يشنقون الروم حين يرونهم، وقائدي يشنق الفارّين. هذا الزقاق هو المكان الوحيد الذي لا ينظر فيه أحد.`,
  [`I am a sailor, not a soldier. The envoy hired the ship, and us with it.`]: `أنا بحّار لا جندي. استأجر الرسول السفينة، واستأجرنا معها.`,
  [`He is not a bad man, the envoy. He talks to the books as if they could hear him. But he will not go home with empty hands.`]: `ليس رجلًا سيّئًا، الرسول. يكلّم الكتب كأنّها تسمعه. لكنّه لن يعود إلى بلاده بيدين فارغتين.`,
  [`I would go home with empty hands and be glad of them.`]: `أمّا أنا فأعود بيدين فارغتين وأفرح بهما.`,
  [`Go. Keep off the roads by day.`]: `امضِ. ابتعد عن الطرق في النهار.`,
  [`He went, without looking back, as fast as a tired man can.`]: `مضى، دون أن يلتفت، بأسرع ما يستطيع رجل متعب.`,
  [`You will answer to the qadi. He is fairer than your captain.`]: `ستقف أمام القاضي. هو أعدل من قائدك.`,
  [`The camp's men took him in. The qadi would hear him in Baghdad.`]: `أخذه رجال المعسكر. سيسمعه القاضي في بغداد.`,
  [`A deserter came down from the holds last night. He had heard of a guard who lets tired men go home. He told us where the gorge is watched.`]: `نزل فارّ من الحصون ليلة أمس. كان قد سمع بحارس يترك الرجال المتعبين يعودون إلى بيوتهم. أخبرنا أين يُراقَب الخانق.`,

  // ---- soldiers' shouts
  [`There! The guard!`]: `هناك! الحارس!`, [`Close the ring! He is one man!`]: `أطبقوا الحلقة! إنّه رجل واحد!`, [`For the envoy's silver!`]: `من أجل فضّة الرسول!`,
  [`Hold the line! Hold!`]: `اثبتوا في الصفّ! اثبتوا!`, [`Do not let him reach the captain!`]: `لا تدعوه يبلغ القائد!`, [`They told us this would be easy.`]: `قالوا لنا إنّ هذا سيكون سهلًا.`,
  [`Home by spring, they said.`]: `نعود قبل الربيع، قالوا.`, [`Archers! On him!`]: `يا رماة! عليه!`, [`It is him. The one from the caravan.`]: `إنّه هو. ذاك الذي من القافلة.`,
  [`Kill him and we all eat tonight!`]: `اقتلوه ونأكل كلّنا الليلة!`,

  // ---- soldiers' letters
  [`To Theodora, in Amorion: "The dates here are sweeter than honey. I will bring you a sack, if the officers do not eat them first."`]: `إلى ثيودورا، في عمّورية: "التمر هنا أحلى من العسل. سأحضر لك كيسًا، إن لم يأكله الضبّاط قبلي."`,
  [`A pay chit, torn: "Owed to the bearer: four months. Signed for the envoy." On the back: "Owed. Always owed."`]: `صكّ أجر ممزّق: "مستحقّ لحامله: أربعة أشهر. مختوم عن الرسول." وعلى ظهره: "مستحقّ. دائمًا مستحقّ."`,
  [`"Brother, do not join the army. Whatever they tell you about the east, it is mostly dust and the smell of burning."`]: `"يا أخي، لا تلتحق بالجيش. مهما قالوا لك عن الشرق، أكثره غبار ورائحة حريق."`,
  [`A list in a careful hand: "Things to say to Maria: that I am sorry about the goat. That I will mend the roof. That I am sorry about the goat."`]: `قائمة بخطّ متأنٍّ: "أشياء أقولها لماريا: أنّي آسف على العنزة. أنّي سأصلح السقف. أنّي آسف على العنزة."`,
  [`"Captain: the men ask why we burn the villages if we came only for books. I could not answer them. Can you?"`]: `"أيّها القائد: يسأل الرجال لماذا نحرق القرى إن كنّا جئنا من أجل الكتب فقط. لم أستطع أن أجيبهم. أتستطيع أنت؟"`,
  [`A child's drawing of a horse, folded small. Under it, in a soldier's hand: "From Niko, aged six. Keep it dry."`]: `رسم طفل لحصان، مطويّ صغيرًا. وتحته بخطّ جندي: "من نيكو، ستّ سنين. احفظه جافًّا."`,
  [`"The Arab guard killed Doukas at the kilns. He fought like a man with nothing to lose. They say his brother died on the road."`]: `"قتل الحارس العربي دوكاس عند الأتون. قاتل كرجل لا شيء لديه ليخسره. يقولون إنّ أخاه مات على الطريق."`,
  [`"Mother, I have learned some of their words. Water is maa. Bread is khubz. Enough is kafa. I say that one most."`]: `"يا أمّي، تعلّمت بعض كلماتهم. الماء: ماء. الخبز: خبز. كفى: كفى. هذه أقولها أكثر من غيرها."`,
  [`Orders, half burned: "...no copyist to be harmed. The envoy wants them living. Any man who..." The rest is ash.`]: `أوامر نصف محترقة: "...لا يُمسّ ناسخ بأذى. الرسول يريدهم أحياء. وكلّ رجل..." والباقي رماد.`,
  [`"If I do not come back, the vineyard goes to Kale, not to my cousin. He drinks."`]: `"إن لم أعد، فالكرم لكالي، لا لابن عمّي. إنّه يسكر."`,
  [`A tally of days scratched on a strip of leather: two hundred and twelve marks, and then none.`]: `عدّ أيّام محفور على شريط جلد: مئتان واثنتا عشرة علامة، ثمّ لا شيء.`,
  [`"We are paid in their own dirhams now, taken from their own markets. I buy bread with money from the bakery we burned."`]: `"صاروا يدفعون لنا بدراهمهم هم، المأخوذة من أسواقهم. أشتري الخبز بمال من المخبز الذي أحرقناه."`,
  [`"Tatzates shoots like a hawk and drinks like a fish, and never speaks of the caravan. Not once."`]: `"تاتزاتيس يرمي كالصقر ويشرب كالسمكة، ولا يتكلّم عن القافلة أبدًا. ولا مرّة."`,
  [`"The envoy reads every night. A book of their astronomers. He says they count the stars better than we do. The officers laugh behind his back."`]: `"الرسول يقرأ كلّ ليلة. كتابًا لفلكيّيهم. يقول إنّهم يعدّون النجوم أفضل منّا. والضبّاط يضحكون من خلف ظهره."`,
  [`"Eirene: I am not dead. I am only far away. Those are different things. Wait."`]: `"إيريني: لست ميتًا. أنا بعيد فقط. وهذان شيئان مختلفان. انتظري."`,
  [`A recipe for lentils, in a cook's scrawl, with a note: "As the woman in the Sawad made it. Better than ours. Do not tell the cook."`]: `وصفة عدس بخطّ طبّاخ، ومعها ملاحظة: "كما صنعته المرأة في السواد. أطيب من عدسنا. لا تخبروا الطبّاخ."`,

  // ---- finds
  [`A child's clay whistle`]: `صفّارة طين لطفل`, [`A clay whistle shaped like a bird, cracked down one wing. It still plays one note. Somebody in the village will miss it.`]: `صفّارة من طين على شكل طائر، مشقوقة على طول جناح. ما زالت تعزف نغمة واحدة. سيفتقدها أحد في القرية.`,
  [`A caravan bell`]: `جرس قافلة`, [`A bronze camel bell with the caravan's mark scratched inside: Jabir's mark. The clapper is gone.`]: `جرس جمل من البرونز، محفور في داخله وسم القافلة: وسم جابر. ضاع لسانه.`,
  [`A blocked sluice gate`]: `بوّابة سدّ مسدودة`, [`A canal sluice, jammed shut with a soldier's shield wedged in the slot. This is how Bardanes cut the village's water.`]: `بوّابة قناة مغلقة بترس جندي محشور في شقّها. هكذا قطع بردانس الماء عن القرية.`,
  [`A reed-house post`]: `عمود بيت قصب`, [`A reed bundle post from a burned house, charred to the waist. The marsh people build a whole house from reeds in four days, and lose it in four minutes.`]: `عمود من حزم القصب من بيت محترق، متفحّم حتّى منتصفه. أهل الأهوار يبنون بيتًا كاملًا من القصب في أربعة أيّام، ويخسرونه في أربع دقائق.`,
  [`A broken siphon nozzle`]: `فوهة سيفون مكسورة`, [`A bronze nozzle from one of Kallinikos's fire siphons, cast like an open mouth. It still smells of naft.`]: `فوهة برونزية من أحد سيفونات النار عند كالينيكوس، مصبوبة على شكل فم مفتوح. ما زالت تفوح منها رائحة النفط.`,
  [`A fisherman's tally stick`]: `عصا عدّ صيّاد`, [`A tally stick notched for each day's catch. After the spring the notches stop, and someone has cut a line across it.`]: `عصا عدّ محزوزة لصيد كلّ يوم. بعد الربيع تتوقّف الحزوز، وقد حزّ أحدهم خطًّا عبرها.`,
  [`A paper-seller's sign`]: `لافتة ورّاق`, [`A painted board, half burned: "...paper of Samarqand, Khurasan and Baghdad, by the ream or the leaf." Forty shops on this lane sold paper.`]: `لوح مدهون، نصفه محترق: "...ورق سمرقند وخراسان وبغداد، بالرزمة أو بالورقة." أربعون دكّانًا في هذا الزقاق كانت تبيع الورق.`,
  [`A melted inkwell`]: `دواة ذائبة`, [`A glass inkwell slumped in the fire into a green puddle, with the ink burned black inside it.`]: `دواة من زجاج انهارت في النار بركةً خضراء، والحبر محترق أسود في داخلها.`,
  [`An astrolabe plate`]: `صفيحة أسطرلاب`, [`A brass astrolabe plate, warped by heat, cut for the latitude of Baghdad. Signed: "Nu'aym made it."`]: `صفيحة أسطرلاب نحاسية، التوت من الحرّ، مقطوعة لعرض بغداد. وعليها: "صنعه نُعيم."`,
  [`A toll ledger`]: `دفتر مكوس`, [`A river toll ledger: barges, cargoes, dues. The last page is in a different hand: "No toll today. The bridge is burning."`]: `دفتر مكوس النهر: مراكب، وحمولات، ورسوم. الصفحة الأخيرة بخطّ آخر: "لا مكس اليوم. الجسر يحترق."`,
  [`A copyist's reed pen`]: `قلم قصب لناسخ`, [`A reed pen, cut fine and worn down to a stub. Whoever used it wrote until there was nothing left to hold.`]: `قلم من القصب، مبريّ رفيعًا وقد تآكل حتّى صار عقبًا. من كتب به ظلّ يكتب حتّى لم يبقَ ما يُمسك.`,
  [`A ship's lantern`]: `فانوس سفينة`, [`A Roman ship's lantern of horn and bronze. Arsaber's ship carried four of these. This one fell in the river and came back.`]: `فانوس سفينة رومية من القرن والبرونز. حملت سفينة أرسابر أربعة منها. هذا سقط في النهر ثمّ عاد.`,
  [`A frontier pass`]: `جواز الثغر`, [`A safe-conduct for the frontier road, sealed with the envoy's wax. The name on it has been scraped off and written over three times.`]: `أمان لطريق الثغر، مختوم بشمع الرسول. الاسم عليه كُشط وكُتب فوقه ثلاث مرّات.`,
  [`A broken bowstring`]: `وتر قوس مقطوع`, [`A silk bowstring, cut cleanly. Tatzates kept spares in every hold. This one he cut himself.`]: `وتر قوس من الحرير، مقطوع قطعًا نظيفًا. كان تاتزاتيس يحتفظ بأوتار احتياطية في كلّ حصن. هذا قطعه بنفسه.`,
  [`A soldier's game board`]: `رقعة لعب جندي`, [`A board scratched into a flat stone for a game of the Rum, with pebbles for pieces. One side was winning.`]: `رقعة محفورة في حجر مسطّح للعبة من ألعاب الروم، والحصى قطعها. كان أحد الطرفين يربح.`,
  [`A water-seller's cup`]: `كوب سقّاء`, [`A copper cup on a chain, the kind water-sellers hang from their skins. In the siege a cup of clean water cost a dirham.`]: `كوب نحاسي في سلسلة، من النوع الذي يعلّقه السقّاؤون في قربهم. في الحصار كان كوب الماء النظيف بدرهم.`,
  [`A brick maker's stamp`]: `ختم لبّان`, [`A wooden stamp for marking bricks with the yard's name. The yard made bricks for the Round City's walls, sixty years ago.`]: `ختم خشبي لوسم الآجرّ باسم المصنع. صنع هذا المصنع آجرّ أسوار المدينة المدوّرة، قبل ستّين عامًا.`,
  [`A grain measure`]: `مكيال حبوب`, [`A wooden qafiz measure, sealed with the market inspector's mark. In the siege the inspector set the price of grain every morning, and it rose every morning.`]: `مكيال قفيز من خشب، مختوم بعلامة المحتسب. في الحصار كان المحتسب يحدّد سعر الحبوب كلّ صباح، وكان يرتفع كلّ صباح.`,
  [`A reed helmet`]: `خوذة من القصب`, [`A helmet woven from reeds and tarred, the kind the 'ayyarun wore in the siege. It would not stop an arrow. They wore it anyway.`]: `خوذة منسوجة من القصب ومقيّرة، من النوع الذي لبسه العيّارون في الحصار. ما كانت لتردّ سهمًا. ولبسوها على أيّ حال.`,
  [`A salt cake`]: `قرص ملح`, [`A cake of rock salt stamped with a merchant's mark. Salt paid soldiers once. Here it paid for nothing but the men who dug it.`]: `قرص من الملح الصخري مختوم بعلامة تاجر. كان الملح أجر الجند يومًا. وهنا لم يدفع إلّا ثمن الرجال الذين حفروه.`,
  [`A drowned ledger`]: `دفتر غريق`, [`A merchant's ledger, swollen with water. On the last dry page: "Moved the good cloth to the undercroft. They will not look below the river."`]: `دفتر تاجر منتفخ بالماء. على آخر صفحة جافّة: "نقلت القماش الجيّد إلى القبو. لن يبحثوا تحت النهر."`,
  [`A sealed jar of dates`]: `جرّة تمر مختومة`, [`A jar of dates, still sealed, marked for Wasit. Somebody's whole season, waiting for a barge that never came.`]: `جرّة تمر ما زالت مختومة، موسومة إلى واسط. موسم كامل لأحدهم، ينتظر مركبًا لم يأتِ.`,
  [`A sapper's lamp`]: `سراج نقّاب`, [`A clay lamp black with soot, with tally marks scratched on its base. Each mark is a day underground.`]: `سراج طين أسود من السخام، محفور على قاعدته عدّ. كلّ علامة يوم تحت الأرض.`,
  [`A listening jar`]: `جرّة التنصّت`, [`A large jar set into the floor of the gallery. The defenders put their ears to it to hear the sappers digging toward them.`]: `جرّة كبيرة مغروسة في أرض الممرّ. كان المدافعون يضعون آذانهم عليها ليسمعوا النقّابين يحفرون نحوهم.`,
  [`A broken tile`]: `بلاطة مكسورة`, [`A glazed tile from a palace wall: blue and white vines. Somebody's grandfather fired it for al-Mansur's city.`]: `بلاطة مزجّجة من جدار قصر: كروم زرقاء وبيضاء. شواها جدّ أحدهم لمدينة المنصور.`,

  // ---- lines on the road
  [`We were meant to sleep at this khan the night Jabir died.`]: `كان يُفترض أن ننام في هذا الخان ليلة مات جابر.`, [`Then sleep here when this is over. Somebody has to.`]: `إذن نم هنا حين ينتهي هذا. على أحد أن يفعل.`,
  [`The kilns made bricks for the Round City once. Now they burn paper.`]: `كانت الأفران تصنع آجرّ المدينة المدوّرة يومًا. الآن تحرق الورق.`, [`Paper burns quicker than brick, at least.`]: `الورق يحترق أسرع من الآجرّ، على الأقلّ.`,
  [`The old Persian arch. Jabir said it was built by giants. He knew it was not.`]: `الطاق الفارسي القديم. قال جابر إنّ العمالقة بنوه. كان يعرف أنّهم لم يفعلوا.`, [`Big men, then. Big men with a lot of slaves.`]: `رجال كبار إذن. رجال كبار ومعهم عبيد كثيرون.`,
  [`Reed houses. They build one in four days, they say.`]: `بيوت القصب. يبنون الواحد في أربعة أيّام، كما يقولون.`, [`And lose it in an hour, if Kallinikos comes by.`]: `ويخسرونه في ساعة، إن مرّ كالينيكوس.`,
  [`Nothing here but water and reeds and men who want to kill us.`]: `لا شيء هنا إلّا الماء والقصب ورجال يريدون قتلنا.`, [`And fish. Do not forget the fish.`]: `والسمك. لا تنسَ السمك.`,
  [`The old weir. When it held, this was all fields.`]: `السِّكر القديم. حين كان صامدًا، كان هذا كلّه حقولًا.`, [`When it held, I would have been a farmer.`]: `حين كان صامدًا، كنت سأكون فلّاحًا.`,
  [`The paper-sellers' lane. Jabir wanted me to learn to read here.`]: `سوق الورّاقين. أراد جابر أن أتعلّم القراءة هنا.`, [`You still could. Ash washes off a page.`]: `ما زال بإمكانك. الرماد يُغسل عن الصفحة.`,
  [`Every door on this street is burned. Every one.`]: `كلّ باب في هذا الشارع محترق. كلّ باب.`, [`Not every one. Look, that family is back.`]: `ليس كلّ باب. انظر، تلك العائلة عادت.`,
  [`The square. They held markets here that the whole world came to.`]: `الساحة. كانت تُقام هنا أسواق يأتيها العالم كلّه.`, [`They will again. Markets come back before people do.`]: `ستُقام من جديد. الأسواق تعود قبل الناس.`,
  [`Everything Baghdad eats comes up this river.`]: `كلّ ما تأكله بغداد يصعد في هذا النهر.`, [`And everything it fears goes down it.`]: `وكلّ ما تخافه ينزل فيه.`,
  [`Burned hulks. The Rum fired them so no one could follow.`]: `هياكل محترقة. أحرقها الروم كي لا يلحق بهم أحد.`, [`Then we follow on foot.`]: `إذن نلحق بهم مشيًا.`,
  [`The Bridge of Boats. Jabir would have argued the toll.`]: `جسر السفن. كان جابر سيجادل في المكس.`, [`And won, from what you say of him.`]: `وكان سيربح، ممّا تقوله عنه.`,
  [`The frontier is eight days north. The Pages were nearly there.`]: `الثغر على بعد ثمانية أيّام شمالًا. كادت الأوراق تبلغه.`, [`Nearly is a long way, in these hills.`]: `"كادت" مسافة طويلة، في هذه التلال.`,
  [`Tatzates knows these hills. He picked them.`]: `تاتزاتيس يعرف هذه التلال. هو اختارها.`, [`Then we unpick them, one hold at a time.`]: `إذن نفكّها، حصنًا بعد حصن.`,
  [`The end of the road. I thought it would feel like something.`]: `نهاية الطريق. ظننت أنّي سأشعر بشيء.`, [`It will. Later. It always comes later.`]: `ستشعر. فيما بعد. يأتي ذلك دائمًا فيما بعد.`,

  // ---- the epilogue
  [`A woman called Umayma bought timber from me with your silver. I gave her the good beams at the bad price. Do not tell anyone.`]: `امرأة اسمها أميمة اشترت منّي خشبًا بفضّتك. أعطيتها العوارض الجيّدة بالسعر الرديء. لا تخبر أحدًا.`,
  [`Leave Jabir's spear with me a day. I will wind that grip properly.`]: `اترك رمح جابر عندي يومًا. سألفّ ذلك المقبض كما يجب.`,
  [`No. I will leave it as he made it.`]: `لا. سأتركه كما صنعه.`, [`Good answer.`]: `جواب حسن.`,
  [`They say you let the Rum deserters walk home. All of them. Soft, the camp says. I say it takes more nerve than a spear.`]: `يقولون إنّك تركت فارّي الروم يعودون إلى بيوتهم. كلّهم. ليّن، يقول المعسكر. وأنا أقول إنّ ذلك يحتاج جرأة أكثر من الرمح.`,
  [`Every deserter you found, you gave to the qadi. Hard, but it is the law. The law is a line too.`]: `كلّ فارّ وجدته سلّمته إلى القاضي. قاسٍ، لكنّه القانون. والقانون صفّ أيضًا.`,
  [`A letter came by the prisoners' road, from Constantinople. From Arsaber.`]: `جاءت رسالة من طريق الأسرى، من القسطنطينية. من أرسابر.`,
  [`"Your Pages sit in the palace library. The young men argue over them at night. I think your Teacher would have liked the argument better than the library."`]: `"أوراقكم في خزانة القصر. يتجادل فيها الشبّان ليلًا. أظنّ أنّ معلّمكم كان سيحبّ الجدال أكثر من الخزانة."`,
  [`"I came home with nothing, and was told so for a year. Then I found I could remember whole lines of your Teacher. So I came home with something after all."`]: `"عدت إلى بلادي بلا شيء، وقيل لي ذلك سنة كاملة. ثمّ وجدت أنّي أذكر سطورًا كاملة لمعلّمكم. فعدت بشيء في النهاية."`,
  [`"Tell the guard I have not forgotten the lane. A man who lets his enemy walk is the man I hoped to meet in Baghdad."`]: `"قل للحارس إنّي لم أنسَ الزقاق. الرجل الذي يترك عدوّه يمضي هو الرجل الذي رجوت أن ألقاه في بغداد."`,
  [`"Tell the guard he was right to call the watch. I would have done the same. I still think of the lane."`]: `"قل للحارس إنّه أصاب حين نادى العسس. كنت سأفعل مثله. وما زلت أفكّر في الزقاق."`,
  [`Will you answer him?`]: `هل ستجيبه؟`,
  [`Of course. Scholars always answer letters. It is how wars end, slowly.`]: `طبعًا. العلماء يجيبون الرسائل دائمًا. هكذا تنتهي الحروب، على مهل.`,
  [`Six years later, al-Ma'mun came home to Baghdad, and the House of Wisdom grew into the greatest library of its age.`]: `بعد ستّ سنين عاد المأمون إلى بغداد، وصار بيت الحكمة أعظم خزانة كتب في عصره.`,
  [`Greek, Persian and Indian books were copied there by the thousand, and the Teacher's Pages sat among them, in ten cities at once.`]: `نُسخت فيه كتب اليونان والفرس والهند بالآلاف، وكانت أوراق المعلّم بينها، في عشر مدن في آن واحد.`,
};
