// Round 23: Arabic for the Byzantine mission (merged last into STORY_AR, see story_ar.js, so it wins over older keys)
// The Byzantines are الروم; names are given as the Arabic chroniclers would write Greek names.
export const AR23 = {
  // ---- names: the envoy, his commanders and lieutenants, the rival
  'Arsaber': 'أرسابر', 'Bardanes': 'بردانس', 'Tatzates': 'تاتزاتيس',
  'Photeinos': 'فوتينوس', 'Olbianos': 'أولبيانوس', 'Katakylas': 'كاتاكيلاس', 'Petronas': 'بطرونس', 'Kallinikos': 'كالينيكوس',
  'Narses': 'نرسيس', 'Kalokyros': 'كالوكيروس', 'Krateros': 'كراتيروس', 'Rhentakios': 'رنتاكيوس', 'Skleros': 'سكليروس',
  // story-hold captains
  'Lalakon': 'لالاكون', 'Bryennios': 'بريينيوس', 'Kourkouas': 'قرقواس', 'Tzantzes': 'تزانتزيس', 'Mousele': 'موسيله',
  'Gongylios': 'غونغيليوس', 'Aetios': 'أيتيوس', 'Monomachos': 'مونوماخوس',
  // field captains
  'Kamateros': 'كاماتيروس', 'Argyros': 'أرغيروس', 'Tornikios': 'تورنيكيوس', 'Kontoleon': 'كونتوليون', 'Rhangabes': 'رانغابيس',
  'Kontomytes': 'كونتوميتيس', 'Triphyllios': 'تريفيليوس', 'Tzourakes': 'تزوراكيس', 'Melissenos': 'ميليسينوس',
  'Karteroukas': 'كارتيروكاس', 'Baanes': 'بانيس', 'Doukas': 'دوكاس', 'Chalkoutzes': 'خالكوتزيس', 'Pegonites': 'بيغونيتيس',
  'Kamoulianos': 'كامولييانوس', 'Bourtzes': 'بورتزيس',
  // dungeon and area captains
  'Taronites': 'تارونيتيس', 'Artabasdos': 'أرتاباسدوس', 'Krenites': 'كرينيتيس', 'Rhadenos': 'رادينوس', 'Bringas': 'برينغاس',
  'Xylinites': 'كسيلينيتيس', 'Kourtikios': 'كورتيكيوس', 'Sarantapechos': 'سارانتابيخوس', 'Boilas': 'بويلاس', 'Gabalas': 'غابالاس',
  'Dalassenos': 'دالاسينوس',
  // the Gauntlet and the Hamrin holds
  'Kekaumenos': 'كيكاومينوس', 'Kaballarios': 'كابالاريوس', 'Maniakes': 'مانياكيس', 'Alyates': 'ألياتيس', 'Exazenos': 'إكسازينوس',
  'Phobenos': 'فوبينوس', 'Krambonites': 'كرامبونيتيس', 'Tarchaneiotes': 'طرخانيوتيس', 'Charsianites': 'خرشنيتيس',
  'Apokaukos': 'أبوكافكوس', 'Pankalos': 'بانكالوس', 'Brachamios': 'براخاميوس',
  // elites
  'Bryas': 'برياس', 'Kamytzes': 'كاميتزيس', 'Melias': 'ميلياس', 'Tzirithon': 'تزيريثون', 'Sarantenos': 'سارانتينوس',
  'Mouzalon': 'موزالون', 'Hexamilites': 'هكساميليتيس', 'Kalamanos': 'كالامانوس', 'Choumnos': 'خومنوس',
  // ---- troop types
  'Psilos': 'راجل خفيف', 'Skoutatos': 'صاحب ترس', 'Menavlatos': 'رامح', 'Toxotes': 'رامٍ رومي', 'Trapezites': 'غازٍ من الثغور',
  'Siphon-bearer': 'حامل السيفون', 'Slinger': 'مِقلاعيّ', 'Marine': 'بحّار الأسطول', 'Solenarion Archer': 'رامي المجرى',
  'Mechanikos': 'مهندس المجانيق', 'Kataphraktos': 'فارس مدرّع', 'Unhorsed Kataphraktos': 'فارس مدرّع راجل', 'Mangonel': 'منجنيق',

  // ---- story15.js: the lieutenants' last words, the act cards
  'Bardanes paid me in the envoy\'s gold. Olbianos has the Pages now, at the kilns.': 'دفع لي بردانس من ذهب السفير. الأوراق الآن مع أولبيانوس، عند الأفران.',
  'Olbianos is burning the Pages in the kiln galleries. Stop him.': 'أولبيانوس يحرق الأوراق في دهاليز الأفران. أوقفه.',
  'I chose silver over a dead man\'s words. Bardanes has the rest, at the old arch.': 'اخترتُ الفضّة على كلام رجل ميّت. البقيّة مع بردانس، عند الطاق القديم.',
  'Bardanes has cut off the village\'s water. Find him at the arch.': 'قطع بردانس الماء عن القرية. اعثر عليه عند الطاق.',
  'Kallinikos hid his boats with Petronas, in the drowned village to the east.': 'أخفى كالينيكوس قواربه عند بطرونس، في القرية الغارقة شرقًا.',
  'Take Kallinikos\'s boats from Petronas, so he cannot run.': 'خذ قوارب كالينيكوس من بطرونس، كي لا يهرب.',
  'Kallinikos is at the old weir with the Pages. He sails tonight.': 'كالينيكوس عند السِّكر القديم ومعه الأوراق. يُبحر الليلة.',
  'Kallinikos is waiting for a boat that will not come.': 'كالينيكوس ينتظر قاربًا لن يأتي.',
  'Krateros moved the Pages to the vaults under the paper-sellers\' lane. Kalokyros guards them.': 'نقل كراتيروس الأوراق إلى المخازن تحت سوق الورّاقين. يحرسها كالوكيروس.',
  'Kalokyros guards the Pages in the store-rooms under the paper shops.': 'كالوكيروس يحرس الأوراق في المخازن تحت دكاكين الورق.',
  'Too late. Krateros took them to the square. If he cannot keep them, he will burn them.': 'فات الأوان. أخذها كراتيروس إلى الساحة. إن لم يستطع أن يحتفظ بها أحرقها.',
  'Stop Krateros before he lights the pyre.': 'أوقف كراتيروس قبل أن يُشعل المحرقة.',
  'Arsaber pays us to hold the river. Skleros keeps the copyists\' boat among the burned hulks.': 'يدفع لنا أرسابر لنمسك النهر. سكليروس يحتجز قارب النُّسّاخ بين السفن المحروقة.',
  'Free the copyists\' boat from Skleros.': 'حرّر قارب النُّسّاخ من سكليروس.',
  'The boat is yours. But Arsaber cut the bridge, and his ship waits at its foot.': 'القارب لك. لكنّ أرسابر قطع الجسر، وسفينته تنتظر عند طرفه.',
  'Arsaber means to carry the copies north. Face him at the bridge.': 'يريد أرسابر أن يحمل النسخ إلى الشمال. واجهه عند الجسر.',
  // the bosses
  'Turn back, guard. Those Pages are going to Constantinople.': 'ارجع أيّها الحارس. هذه الأوراق ذاهبة إلى القسطنطينية.',
  'Commander of the envoy\'s company': 'قائد سريّة السفير',
  'Paper, guard? The envoy pays in gold. Name your price.': 'ورق أيّها الحارس؟ السفير يدفع ذهبًا. سمِّ ثمنك.',
  'Master of the liquid-fire siphons': 'صاحب سيفونات النار السائلة',
  'If Constantinople cannot have them, no one will.': 'إن لم تنلها القسطنطينية فلن ينالها أحد.',
  'Arsaber\'s captain in al-Karkh': 'قائد أرسابر في الكرخ',
  'Your caliph\'s sons are busy killing each other, guard. Who will stop me?': 'ابنا خليفتك مشغولان بقتل أحدهما الآخر أيّها الحارس. فمن يوقفني؟',
  'Envoy of Constantinople': 'سفير القسطنطينية',
  'Darts! Hold the bridge!': 'السهام القصيرة! أمسكوا الجسر!',
  'Arsaber fires the bridge. Stay inside the ring.': 'أرسابر يُضرم النار في الجسر. ابقَ داخل الحلقة.',
  // Ishaq in each hub
  'Under my instruments was a cedar chest: the Pages of <b>the Teacher</b>, who died in a prison by the river fourteen years ago. While the caliph\'s sons fight over Baghdad, an envoy from Constantinople, <b>Arsaber</b>, came in under the smoke of their war. He wants the best learning of this city carried north, and the Pages most of all.':
    'تحت آلاتي كان صندوق من خشب الأرز: أوراق <b>المعلّم</b>، الذي مات في سجن على النهر قبل أربع عشرة سنة. وبينما يتنازع ابنا الخليفة على بغداد، دخل سفير من القسطنطينية، <b>أرسابر</b>، تحت دخان حربهما. يريد أن يحمل أفضل علم هذه المدينة إلى الشمال، والأوراقَ قبل كلّ شيء.',
  'His company in the Sawad answers to <b>Bardanes</b>. <b>Photeinos</b> holds the old caravanserai, <b>Olbianos</b> the kilns, and Bardanes the broken arch. Your brother asked you for one thing.':
    'سريّته في السواد تأتمر بأمر <b>بردانس</b>. <b>فوتينوس</b> يمسك الخان القديم، و<b>أولبيانوس</b> الأفران، وبردانس الطاق المهدّم. أخوك طلب منك شيئًا واحدًا.',
  'The fishermen here owe Kallinikos nothing, and they do not like him. They say he paid for boats and silence.': 'الصيّادون هنا لا يدينون لكالينيكوس بشيء، ولا يحبّونه. يقولون إنّه اشترى القوارب والسكوت.',
  '<b>Katakylas</b> holds the reed stockade to the west. <b>Petronas</b> keeps the boats in the drowned village to the east. Without boats, Kallinikos cannot leave.':
    '<b>كاتاكيلاس</b> يمسك حصن القصب غربًا. و<b>بطرونس</b> يحتجز القوارب في القرية الغارقة شرقًا. بلا قوارب لا يستطيع كالينيكوس الرحيل.',
  'Mind the deep water. Wade where it is shallow, and watch the reeds. Their raiders fight from them.': 'احذر الماء العميق. خُض حيث يضحل، وراقب القصب. غزاتهم يقاتلون منه.',
  'Arsaber\'s men here answer to <b>Krateros</b>. <b>Narses</b> holds the burned quarter and <b>Kalokyros</b> the vaults under the paper-sellers\' lane.':
    'رجال أرسابر هنا يأتمرون بأمر <b>كراتيروس</b>. <b>نرسيس</b> يمسك الحيّ المحروق، و<b>كالوكيروس</b> المخازن تحت سوق الورّاقين.',
  '<b>Arsaber</b> himself holds the quays, and a ship waits there to carry the Pages north. <b>Rhentakios</b> keeps the shipyard and <b>Skleros</b> has taken the copyists\' boat among the hulks.':
    '<b>أرسابر</b> نفسه يمسك الأرصفة، وسفينة تنتظر هناك لتحمل الأوراق إلى الشمال. <b>رنتاكيوس</b> يمسك دار الصناعة، و<b>سكليروس</b> أخذ قارب النُّسّاخ بين السفن المحروقة.',
  'Arsaber\'s company came this way, toward the frontier. What is left of it still holds these hills: his own men, and the turncoats he hired.':
    'مرّت سريّة أرسابر من هنا نحو الثغور. وما بقي منها ما زال يمسك هذه التلال: رجاله، والمرتدّون الذين استأجرهم.',
  'They hold four places. The old <b>quarry</b> to the west, the <b>fort</b> on the eastern cliff, the <b>bridge</b> over the gorge to the south, and a hold in the far ravine where <b>Tatzates</b> went to ground.':
    'يمسكون أربعة مواضع. <b>المقلع</b> القديم غربًا، و<b>الحصن</b> على الجرف الشرقي، و<b>الجسر</b> فوق الوادي جنوبًا، ومعقلًا في الشِّعب البعيد حيث اختبأ <b>تاتزاتيس</b>.',
  // ---- scenes.js
  'Riders in Byzantine mail were waiting on the dunes.': 'كان فرسان في دروع الروم ينتظرون على الكثبان.',
  'They attacked the caravan at dusk.': 'هاجموا القافلة عند الغسق.',
  'Jabir did not live to see Baghdad. The raiders had taken the chest.': 'لم يعش جابر ليرى بغداد. كان المغيرون قد أخذوا الصندوق.',
  'The Pages: the writings of my old teacher. A Byzantine envoy came under the smoke of the war. His soldiers took the Pages.': 'الأوراق: كتابات معلّمي القديم. جاء سفير من الروم تحت دخان الحرب. وجنوده أخذوا الأوراق.',
  'Bardanes leads them in the Sawad, and he split the Pages between his men. Get them back. Start with Photeinos, at the old caravanserai.': 'يقودهم في السواد بردانس، وقد قسم الأوراق بين رجاله. استعِدها. ابدأ بفوتينوس، عند الخان القديم.',
  'Bardanes rings the arena with fire. Stay inside it.': 'بردانس يحيط الساحة بالنار. ابقَ داخلها.',
  'Most of the Pages were in Bardanes\'s tent.': 'كانت أكثر الأوراق في خيمة بردانس.',
  'Kallinikos, the master of their fire siphons. He fled east, into the Nahrawan marshes.': 'كالينيكوس، صاحب سيفونات نارهم. فرّ شرقًا إلى أهوار النهروان.',
  'Kallinikos has the last Pages. Follow him into the reeds.': 'آخر الأوراق مع كالينيكوس. اتبعه إلى القصب.',
  'The fishermen say Kallinikos paid for boats, and for silence.': 'يقول الصيّادون إنّ كالينيكوس دفع ثمن القوارب، وثمن السكوت.',
  'Start with Katakylas. His men hold the reed stockade to the west.': 'ابدأ بكاتاكيلاس. رجاله يمسكون حصن القصب غربًا.',
  'And Arsaber?': 'وأرسابر؟',
  'He holds the quays himself, and a ship of his waits there. Start with Rhentakios, at the shipyard.': 'يمسك الأرصفة بنفسه، وسفينة له تنتظر هناك. ابدأ برنتاكيوس، في دار الصناعة.',
  'Arsaber\'s men. Their captain is Krateros. Start with Narses, in the burned quarter.': 'رجال أرسابر. قائدهم كراتيروس. ابدأ بنرسيس، في الحيّ المحروق.',
  'To Krateros, in al-Karkh. He will burn it before he lets your caliph\'s men take it back.': 'إلى كراتيروس، في الكرخ. سيحرقها قبل أن يدع رجال خليفتك يستعيدونها.',
  'That night Kallinikos\'s own boats carried Salim and Ishaq up the canal to Baghdad.': 'في تلك الليلة حملت قوارب كالينيكوس نفسها سالمًا وإسحاق في القناة إلى بغداد.',
  'Krateros will burn the Pages. Get there first.': 'سيحرق كراتيروس الأوراق. اسبقه إليها.',
  'Arsaber means to carry the copies north before they sail.': 'يريد أرسابر أن يحمل النسخ إلى الشمال قبل أن تُبحر.',
  'Arsaber\'s men threw down their bows. The copyists\' barge came down from the yard.': 'ألقى رجال أرسابر أقواسهم. ونزل صندل النُّسّاخ من دار الصناعة.',
  'Let Constantinople try to gather them now.': 'فلتحاول القسطنطينية أن تجمعها الآن.',
  // ---- region.js quests
  'Follow Photeinos into the broken dam behind the caravanserai': 'اتبع فوتينوس إلى السدّ المكسور خلف الخان',
  'Find Olbianos in the galleries under the kiln yard': 'اعثر على أولبيانوس في الدهاليز تحت ساحة الأفران',
  'Face Bardanes at the ruined Persian arch': 'واجه بردانس عند الطاق الفارسي المهدّم',
  'Find Katakylas in the reed stockade to the west': 'اعثر على كاتاكيلاس في حصن القصب غربًا',
  'Take Kallinikos\'s boats from Petronas in the sunken village': 'خذ قوارب كالينيكوس من بطرونس في القرية الغارقة',
  'Face Kallinikos at the old weir': 'واجه كالينيكوس عند السِّكر القديم',
  'Find Narses in the burned quarter behind the suq': 'اعثر على نرسيس في الحيّ المحروق خلف السوق',
  'Drive Kalokyros from the vaults under the paper-sellers\' lane': 'اطرد كالوكيروس من المخازن تحت سوق الورّاقين',
  'Stop Krateros in the square before sunset': 'أوقف كراتيروس في الساحة قبل الغروب',
  'Find Rhentakios in the shipyard by the warehouses': 'اعثر على رنتاكيوس في دار الصناعة بجانب المخازن',
  'Free the copyists\' boat from Skleros among the hulks': 'حرّر قارب النُّسّاخ من سكليروس بين السفن المحروقة',
  'Face Arsaber at the bridge of boats': 'واجه أرسابر عند جسر السفن',
  'Find Tatzates in his hold': 'اعثر على تاتزاتيس في معقله',
  // ---- rivals.js
  'Bardanes paid. I shot. That is all it was.': 'دفع بردانس. فرميتُ. هذا كلّ ما في الأمر.',
  'Not today, guard. The envoy\'s silver does not cover this.': 'ليس اليوم أيّها الحارس. فضّة السفير لا تكفي لهذا.',
  'Kallinikos pays better than Bardanes did.': 'كالينيكوس يدفع أكثر ممّا دفع بردانس.',
  'One more job, and I go north with the envoy.': 'عمل واحد آخر، ثمّ أمضي إلى الشمال مع السفير.',
  'Tatzates Is Gone North': 'رحل تاتزاتيس إلى الشمال',
  // ---- holds.js, hamrin, travel
  'Tatzates\' siphon-master': 'صاحب سيفون تاتزاتيس',
  'A border fort the company holds': 'حصن ثغريّ تمسكه السريّة',
  'Tatzates\' Hold': 'معقل تاتزاتيس',
  'A company far from home needed three things: water, a way out and a place that could be held by a few men. Old quarries, frontier forts and gorges crossed by a single plank way gave all three, which is why the same places were held again and again by whoever came through.': 'سريّة بعيدة عن ديارها تحتاج إلى ثلاثة أشياء: الماء، ومخرج، وموضع يمسكه رجال قليلون. المقالع القديمة وحصون الثغور والوديان التي يعبرها ممرّ واحد من الألواح تعطي الثلاثة، ولذلك أمسك هذه المواضع نفسها مرّة بعد مرّة كلُّ من مرّ بها.',
  'The Hill Camp': 'مخيّم التلال',
  // ---- storyholds.js
  'Bardanes\' man at the caravanserai': 'رجل بردانس في الخان',
  'The copyist who sold the Pages': 'الناسخ الذي باع الأوراق',
  'Kallinikos\' man in the reed stockade': 'رجل كالينيكوس في حصن القصب',
  'Captain of the marines': 'قائد بحّارة الأسطول',
  'Keeper of Kallinikos\' boats': 'حارس قوارب كالينيكوس',
  'Krateros\' man in the burned quarter': 'رجل كراتيروس في الحيّ المحروق',
  'Darts! Put him down!': 'السهام القصيرة! أسقطوه!',
  'He guards the Pages for Krateros': 'يحرس الأوراق لكراتيروس',
  'Arsaber\'s man on the river': 'رجل أرسابر على النهر',
  'The galleries are barred. Find Photeinos first.': 'الدهاليز موصدة. اعثر على فوتينوس أوّلًا.',
  'The way is barred. Find Katakylas first.': 'الطريق موصد. اعثر على كاتاكيلاس أوّلًا.',
  'The vaults are barred. Find Narses first.': 'المخازن موصدة. اعثر على نرسيس أوّلًا.',
  'No boat will take you out yet. Find Rhentakios first.': 'لن يحملك قارب بعد. اعثر على رنتاكيوس أوّلًا.',
  // ---- content.js
  'Vaulted stores beneath Photeinos\' camp': 'مخازن معقودة تحت معسكر فوتينوس',
  'Kamateros took a barid courier\'s satchel into the storerooms under the caravanserai. Recover it.': 'أخذ كاماتيروس حقيبة ساعي البريد إلى المخازن تحت الخان. استعِدها.',
  'Argyros\'s men carried off Bishr\'s Indian steel ingots to the clay pits by the kilns. Bring them back.': 'حمل رجال أرغيروس سبائك الحديد الهندي التي لبشر إلى حُفَر الطين قرب الأفران. أعِدها.',
  'Bardanes has three mangonels on the approach to the arch. Burn them before you face him (0/3).': 'لبردانس ثلاثة مجانيق على الطريق إلى الطاق. أحرقها قبل أن تواجهه (0/3).',
  'Bardanes fights without his engines.': 'بردانس يقاتل بلا مجانيقه.',
  'Forgive me, I cannot stand for long. Byzantine raiders ran down my horse on the road and took my satchel.': 'اعذرني، لا أقوى على الوقوف طويلًا. صدم غزاة من الروم فرسي على الطريق وأخذوا حقيبتي.',
  'Kamateros and his archers hide in the storerooms under the caravanserai. Be careful.': 'كاماتيروس ورماته يختبئون في المخازن تحت الخان. احذر.',
  'Letters for the postmaster in Baghdad: reports on prices and governors, sealed. If they are opened or lost, I lose my post. Kamateros took them into the storerooms under the caravanserai.': 'رسائل لصاحب البريد في بغداد: تقارير عن الأسعار والولاة، مختومة. إن فُتحت أو ضاعت خسرتُ عملي. أخذها كاماتيروس إلى المخازن تحت الخان.',
  'Your ingots, from the clay pits. Argyros will not need them.': 'سبائكك، من حُفَر الطين. أرغيروس لن يحتاجها.',
  'Six ingots of Indian steel, come up from Basra, and Argyros\'s men took them off the cart at the kilns. They will be hiding in the clay pits. Steel like that does not come twice a year.': 'ستّ سبائك من الحديد الهندي، جاءت من البصرة، وأخذها رجال أرغيروس عن العربة عند الأفران. لا بدّ أنّها مخبّأة في حُفَر الطين. حديد كهذا لا يأتي مرّتين في السنة.',
  'I saw the smoke from here. Without his engines, Bardanes is just a big man with a sword. Here, for the road.': 'رأيت الدخان من هنا. بلا مجانيقه، بردانس مجرّد رجل ضخم بسيف. خذ هذا، للطريق.',
  'One more thing, before you go south. Bardanes has mangonels on the road to the arch. If he gets them loosing fire at you, you will burn. Burn them first.': 'أمر آخر قبل أن تمضي جنوبًا. لبردانس مجانيق على الطريق إلى الطاق. إن أطلقها عليك نارًا احترقت. أحرقها أوّلًا.',
  // ---- progression, game
  'Bardanes\' Champion': 'بطل بردانس',
  'Champion': 'بطل',
  'Photeinos Confesses': 'فوتينوس يعترف',
  'The envoy\'s name was Arsaber': 'اسم السفير أرسابر',
  // ---- narrative.js: dialogue, side tasks, new codex
  'The stars do not hurry, Salim, but Bardanes does. What do you need?': 'النجوم لا تستعجل يا سالم، لكنّ بردانس يستعجل. ما حاجتك؟',
  'My best astrolabe, with a rete cut like lace. I made it myself over three winters. The raiders will have dragged it to their tunnels under the kilns. Olbianos\' men hoard brass to melt.': 'أفضل أسطرلاباتي، شبكته مخرّمة كالدانتيل. صنعته بيدي في ثلاثة شتاءات. لا بدّ أنّ المغيرين جرّوه إلى أنفاقهم تحت الأفران. رجال أولبيانوس يكدّسون النحاس ليصهروه.',
  'The \'ayyarun: boys from the poor quarters with reed shields and slings, holding alleys against armoured men. Some of them are on the roads now too, and a few have taken the envoy\'s silver.': 'العيّارون: فتيان من الأحياء الفقيرة بتروس من القصب ومقاليع، يمسكون الأزقّة في وجه رجال مدرّعين. بعضهم على الطرق الآن أيضًا، وقليل منهم أخذوا فضّة السفير.',
  'It was in a chest, among Olbianos\' brass. Not a scratch.': 'كان في صندوق، بين نحاس أولبيانوس. بلا خدش.',
  'The qanat under the well feeds this whole suq. Bardanes\' men camp in its galleries and foul the water on purpose. A man can go a long time without bread, guard. Not without water. Clear them out.': 'القناة تحت البئر تسقي السوق كلّها. رجال بردانس يعسكرون في دهاليزها ويفسدون الماء عمدًا. يصبر الرجل طويلًا على الخبز أيّها الحارس، لا على الماء. أخرجهم.',
  'Gold dinars for the great deals, silver dirhams for bread. And for long roads, a suftaja: a letter my cousin in Basra will honour. Paper weighs less than gold, and raiders cannot spend it.': 'الدنانير الذهبية للصفقات الكبيرة، والدراهم الفضّية للخبز. وللطرق الطويلة سُفتجة: رسالة يصرفها ابن عمّي في البصرة. الورق أخفّ من الذهب، والمغيرون لا يستطيعون إنفاقه.',
  'Bardanes\' captains ride with a golden ring of men around them. Kill three of them in the field, and my purse is yours.': 'قادة بردانس يسيرون وحولهم حلقة ذهبية من الرجال. اقتل ثلاثة منهم في الميدان، وكيسي لك.',
  'Why would Constantinople want the Pages?': 'لماذا تريد القسطنطينية الأوراق؟',
  'Their emperors and ours send embassies back and forth, and the envoys come home with books as often as with treaties. They have scholars of their own who would give a great deal for what we know. Arsaber came for learning the way other men come for gold.': 'ملوكهم وخلفاؤنا يتبادلون السفارات، ويعود السفراء بالكتب كما يعودون بالمعاهدات. ولهم علماء يبذلون الكثير لما نعرف. جاء أرسابر طلبًا للعلم كما يأتي غيره طلبًا للذهب.',
  'And the Teacher\'s Pages?': 'وأوراق المعلّم؟',
  'Words that men copy by hand in secret are worth more than a library. Carried to Constantinople, they would be read there and lost here. That is the loss I fear, Salim: not the burning, the silence after.': 'الكلمات التي ينسخها الناس سرًّا بأيديهم أثمن من مكتبة. لو حُملت إلى القسطنطينية لقُرئت هناك وضاعت هنا. هذه الخسارة التي أخشاها يا سالم: لا الحريق، بل الصمت بعده.',
  'Ishaq\'s finest astrolabe was taken with the caravan. Search the kiln tunnels beneath the yard Olbianos holds.': 'أُخذ أفضل أسطرلابات إسحاق مع القافلة. فتّش أنفاق الأفران تحت الساحة التي يمسكها أولبيانوس.',
  'Bardanes\' men are fouling the qanat that feeds the suq. Clear a descent of the ruined qanats.': 'رجال بردانس يفسدون القناة التي تسقي السوق. طهّر نزلة في القنوات المهدّمة.',
  '\'Amr wagers you cannot defeat three of Arsaber\'s captains (elite foes) in the field.': 'يراهن عمرو أنّك لا تقدر على هزيمة ثلاثة من قادة أرسابر (أعداء نخبة) في الميدان.',
  'The Army of the Romans': 'جيش الروم',
  'The empire ruled from Constantinople called itself Roman; the Arabs called its people al-Rum. Its provinces, the themata, were each held by a strategos with soldiers who were granted land in return for service. Beside them stood the tagmata, paid regiments kept near the capital. Its line infantry fought in lamellar and mail behind large oval shields, with light troops, archers and armoured horsemen around them.': 'كانت الإمبراطورية التي تُحكم من القسطنطينية تسمّي نفسها رومانية، وسمّى العرب أهلها الروم. لكلّ ولاية من ولاياتها، وهي الثيمات، قائد يُدعى الاستراتيغوس، وجنود أُقطعوا أرضًا مقابل الخدمة. وإلى جانبهم التاغماتا، فِرَق مأجورة مقيمة قرب العاصمة. وكان مشاتها يقاتلون في الدروع الصفائحية والزرد خلف تروس بيضوية كبيرة، وحولهم الرجّالة الخفاف والرماة والفرسان المدرّعون.',
  'The Frontier': 'الثغور',
  'Between the caliphate and the Roman empire ran al-Thughur, the frontier marches of the Taurus mountains and northern Syria: a belt of fortified towns, mountain passes and burned fields. Raids crossed it nearly every summer from both sides, and men of the borderlands, Arab, Greek and Armenian, sold their swords to whoever paid.': 'بين الخلافة وإمبراطورية الروم امتدّت الثغور، تخوم جبال طوروس وشمال الشام: حزام من المدن المحصّنة والدروب الجبلية والحقول المحروقة. كانت الغارات تعبره كلّ صيف تقريبًا من الجانبين، وكان رجال الأطراف، عربًا ورومًا وأرمنًا، يبيعون سيوفهم لمن يدفع.',
  'Liquid Fire': 'النار السائلة',
  'The Romans\' most feared weapon was a fire that burned on water. Their own writers called it "liquid" or "sea" fire, and said an architect named Kallinikos, a refugee from Syria, brought the secret to Constantinople around 672. It was pumped through bronze tubes, or siphons, from ships and from hand-held devices. The recipe was a state secret, and it is still not known.': 'أشدّ أسلحة الروم رهبة نار تشتعل على الماء. سمّاها كتّابهم النار "السائلة" أو "البحرية"، وقالوا إنّ مهندسًا اسمه كالينيكوس، فرّ من الشام، حمل سرّها إلى القسطنطينية نحو سنة 672. كانت تُدفع في أنابيب من البرونز، أي السيفونات، من السفن ومن أدوات تُحمل باليد. وكانت تركيبتها سرًّا من أسرار الدولة، وما زالت مجهولة.',
  'Embassies': 'السفارات',
  'Baghdad and Constantinople fought often, but they also wrote to each other. Envoys travelled between the two courts to arrange truces, ransoms and exchanges of prisoners, and they brought back gifts and news. Books passed along the same roads: within a few years of this story the caliph al-Ma\'mun would be asking the emperors for Greek manuscripts to translate.': 'تحاربت بغداد والقسطنطينية كثيرًا، لكنّهما تراسلتا أيضًا. سافر السفراء بين البلاطين ليعقدوا الهدنات والفداء وتبادل الأسرى، وعادوا بالهدايا والأخبار. ومرّت الكتب في الطرق نفسها: بعد سنوات قليلة من هذه القصّة سيطلب الخليفة المأمون من ملوك الروم مخطوطات يونانية ليترجمها.',
  'The Exchange on the Lamis': 'الفداء على اللامس',
  'Prisoners taken on the frontier were ransomed or exchanged on the Lamis, a small river in Cilicia near the coast. Each side brought its captives to its own bank, and they crossed one for one at a bridge. The first recorded exchange there was held under Harun al-Rashid, in 805.': 'كان أسرى الثغور يُفدَون أو يُتبادلون على نهر اللامس، نهر صغير في قيليقية قرب الساحل. يأتي كلّ جانب بأسراه إلى ضفّته، فيعبرون واحدًا بواحد على جسر. وأوّل فداء مذكور هناك كان في عهد هارون الرشيد، سنة 805.',
  'Leo the Mathematician': 'ليون الرياضي',
  'A young scholar of Constantinople in these years, who taught himself geometry, astronomy and philosophy from old books he sought out on the islands of the Aegean. Later Roman writers tell that al-Ma\'mun heard of him from a captured student, and wrote to the emperor offering gold and lasting peace if Leo would come to Baghdad. The emperor kept him at home.': 'عالم شابّ من القسطنطينية في تلك السنين، علّم نفسه الهندسة والفلك والفلسفة من كتب قديمة وجدها في جزر بعيدة. يروي كتّاب الروم المتأخّرون أنّ المأمون سمع به من تلميذ له وقع في الأسر، فكتب إلى ملك الروم يعرض الذهب والصلح الدائم إن جاءه ليون إلى بغداد. فأبقاه الملك عنده.',
  // ---- sidequests.js
  'Olbianos\' raiders took my kiln tools when they took the yard. Without them I am a man who knows how to make pots, and nothing else.': 'أخذ غزاة أولبيانوس أدوات أتوني حين استولوا على الساحة. بدونها أنا رجل يعرف صنع الجرار ولا شيء غير ذلك.',
  'Recover Zayd\'s kiln tools from the raiders at the kiln yard.': 'استرجع أدوات زيد من الغزاة في ساحة الأتون.',
  'Byzantine soldiers robbed me on the east road. They took my ledger: three years of every debt and sale in this village. Without it, honest men cannot prove what they paid.': 'سلبني جنود من الروم على الطريق الشرقي. أخذوا دفتري: ثلاث سنين من كلّ دين وبيع في القرية. بدونه لا يستطيع الشرفاء إثبات ما دفعوا.',
  'Drive off the soldiers on the east road.': 'اطرد الجنود عن الطريق الشرقي.',
  'Find Nadr\'s ledger among the soldiers\' plunder.': 'ابحث عن دفتر النضر بين غنائم الجنود.',
  'My camels bolted when the Byzantine horsemen came. Two of them are standing in the desert east of the road, and the men who scared them are still out there.': 'هربت جمالي حين جاء فرسان الروم. اثنان منها واقفان في البرّية شرق الطريق، والرجال الذين أفزعوها ما زالوا هناك.',
  'Scatter the horsemen near Hudba\'s camels.': 'فرّق الفرسان قرب جمال هدبة.',
  'Kallinikos\' men took my boy Saqr to make me carry their boats. They keep him in a hut on the west causeway. He is eleven.': 'أخذ رجال كالينيكوس ابني صقرًا ليجبروني على حمل قواربهم. يحبسونه في كوخ على الجسر الغربي. عمره أحد عشر عامًا.',
  'Free Saqr from Kallinikos\' men on the west causeway.': 'حرّر صقرًا من رجال كالينيكوس على الجسر الغربي.',
  'Every night someone cuts our nets on the east causeway. Kallinikos\' raiders, hiding in the reeds. A village that cannot fish cannot eat.': 'كلّ ليلة يقطع أحدهم شباكنا على الجسر الشرقي. غزاة كالينيكوس المختبئون في القصب. القرية التي لا تصطاد لا تأكل.',
  'My best buffalo swam off in the night and came ashore by the reed camp road. Kallinikos\' men have her tied, and they are arguing about who eats her.': 'سبحت أفضل جواميسي في الليل وخرجت عند طريق مخيّم القصب. رجال كالينيكوس ربطوها، ويتجادلون في من يأكلها.',
  'Kallinikos bought up the whole village\'s debts when he came, and wrote them all down. His men use that book to take our boats and our reed. Burn it, and we are free.': 'اشترى كالينيكوس ديون القرية كلّها حين جاء، وكتبها جميعًا. رجاله يأخذون بذلك الدفتر قواربنا وقصبنا. احرقه نصبح أحرارًا.',
  'Take Kallinikos\' debt ledger from his clerk\'s guards on the south-east causeway.': 'خذ دفتر ديون كالينيكوس من حرّاس كاتبه على الجسر الجنوبي الشرقي.',
  'Kallinikos\' Debt Ledger': 'دفتر ديون كالينيكوس',
  'The village owes Kallinikos nothing.': 'القرية لا تدين لكالينيكوس بشيء.',
  'Kallinikos\' men have closed the old sluice on the west channel. The water we drink comes down that channel. Three days now, and the children drink from the marsh.': 'أغلق رجال كالينيكوس البوّابة القديمة على الساقية الغربية. الماء الذي نشربه ينزل من تلك الساقية. ثلاثة أيام والأطفال يشربون من الهور.',
  'Drive Kallinikos\' men from the sluice on the west channel.': 'اطرد رجال كالينيكوس عن بوّابة الساقية الغربية.',
  'Every winter the ducks come down to the marsh, and every winter I feed my family with my nets. Kallinikos\' men took them all to their camp in the south-west, to snare men instead of birds.': 'كلّ شتاء تنزل البطّ إلى الهور، وكلّ شتاء أُطعم عيالي بشباكي. أخذها رجال كالينيكوس كلّها إلى معسكرهم في الجنوب الغربي، ليصيدوا بها الرجال بدل الطير.',
  'The great mudhif lost half its roof in the spring flood. I have cut reed enough to mend it, out on the east beds, but Kallinikos\' raiders lie in the reeds there and my buffalo will not go alone.': 'فقدت المضيف الكبيرة نصف سقفها في فيضان الربيع. قطعت من القصب ما يكفي لإصلاحها في المقاصب الشرقية، لكنّ غزاة كالينيكوس يرقدون في القصب هناك وجاموستي لا تمضي وحدها.',
  'Krateros\' soldiers squat in my dye yard by the north lane. They broke half the vats looking for coin. Indigo is worth more than coin, if they only knew.': 'جنود كراتيروس يقيمون في ساحة صباغتي عند الدرب الشمالي. كسروا نصف الأحواض بحثًا عن المال. النيلة أثمن من المال، لو كانوا يعلمون.',
  'Clear the soldiers out of the dye yard on the north lane.': 'اطرد الجنود من ساحة الصباغة على الدرب الشمالي.',
  'Krateros\' men took my pens and my inks, and my best paper, and stacked them in their camp on the east lane. Without pens I cannot copy, and without copying I cannot eat.': 'أخذ رجال كراتيروس أقلامي وأحباري وأجود ورقي، وكدّسوها في معسكرهم على الدرب الشرقي. بلا أقلام لا أنسخ، وبلا نسخ لا آكل.',
  'My two children went looking for our old house, south of the canal. They have not come back, and the lanes there are full of Krateros\' men.': 'ذهب ولداي يبحثان عن بيتنا القديم جنوب النهر. لم يعودا، والدروب هناك مليئة برجال كراتيروس.',
  'Krateros\' men stand on the north bridge and take a dirham from everyone who crosses. From widows, from children, from me. Someone should make them stop.': 'يقف رجال كراتيروس على الجسر الشمالي ويأخذون درهمًا من كلّ عابر. من الأرامل، من الأطفال، منّي. على أحد أن يوقفهم.',
  'The quarter eats from my oven, and Krateros\' men took my flour for their own. Twenty sacks, stacked in their store by the paper-sellers\' lane.': 'الحيّ كلّه يأكل من فرني، وأخذ رجال كراتيروس دقيقي لأنفسهم. عشرون كيسًا مكدّسة في مخزنهم قرب سوق الورّاقين.',
  'I write letters for those who cannot. Families to their sons in Basra, in Kufa, in Khurasan. The courier who carried them was robbed on the east lanes by Krateros\' men.': 'أكتب الرسائل لمن لا يكتب. أُسَر إلى أبنائها في البصرة والكوفة وخراسان. والساعي الذي حملها سلبه رجال كراتيروس في الأزقّة الشرقية.',
  'Find the men who robbed him on the east lanes.': 'اعثر على الرجال الذين سلبوه في الأزقّة الشرقية.',
  'We carry water from the Sarat to every house that has no well. Now Krateros\' men stand on the canal steps and take a coin for every skin we fill.': 'نحمل الماء من الصراة إلى كلّ بيت لا بئر له. والآن يقف رجال كراتيروس على درج النهر ويأخذون درهمًا عن كلّ قربة نملؤها.',
  'Clear Krateros\' men from the canal steps south of the bridge.': 'طهّر درج النهر جنوب الجسر من رجال كراتيروس.',
  'My awls, my bone folders and my presses are in my old shop, under the ash on the south lane. Krateros\' men camp in the ruins there now. Without my tools no book in this quarter gets a cover.': 'مخارزي ومطاوي العظم ومكابسي في دكّاني القديم تحت الرماد في الزقاق الجنوبي. يخيّم رجال كراتيروس في الخرائب هناك الآن. بلا أدواتي لا يُجلَّد كتاب في هذا الحيّ.',
  'Arsaber\'s men took my skiff at the north jetty. They use it to row out and search the barges. Forty years I have ferried this river, and now I stand on the bank like a stranger.': 'أخذ رجال أرسابر زورقي عند الرصيف الشمالي. يجذّفون به ليفتّشوا السفن. أربعون سنة وأنا أعبر هذا النهر، والآن أقف على الضفّة كالغريب.',
  'Drive Arsaber\'s men off the north jetty.': 'اطرد رجال أرسابر عن الرصيف الشمالي.',
  'Without pitch my hulls leak like sieves. Arsaber\'s engineers carried off every jar of it from the yard, to their camp inland. They want the boats to sink.': 'بلا قار تسرّب سفني كالغرابيل. حمل مهندسو أرسابر كلّ جرّة منه من دار الصناعة إلى معسكرهم في الداخل. يريدون للسفن أن تغرق.',
  'We carried bales for the warehouse masters all season. Now Rhentakios holds the quay, and his toll-men beat us off the road. Every porter on the river is owed.': 'حملنا الأحمال لأسياد المخازن طوال الموسم. والآن يمسك رنتاكيوس الشطّ، وجُباته يضربوننا ويطردوننا عن الطريق. كلّ حمّال على النهر له دَين.',
  'Stop the soldiers fouling the well by the kiln road.': 'أوقف الجنود الذين يفسدون البئر عند طريق الأتون.',
  'Krateros\' men set a granary alight on the east lane. Stop them before they carry off the grain.': 'أشعل رجال كراتيروس أهراءً على الدرب الشرقي. أوقفهم قبل أن يحملوا الحنطة.',
  'Krateros\' men are robbing a grain convoy near the north bridge.': 'رجال كراتيروس يسلبون قافلة حنطة قرب الجسر الشمالي.',
  'Arsaber\'s men have fired a warehouse by the quay road. Drive them off before it spreads.': 'أشعل رجال أرسابر مخزنًا قرب طريق الشطّ. اطردهم قبل أن تنتشر النار.',
  'Soldiers of the company have stopped a salt caravan in the western gorge. Drive them off.': 'أوقف جنود السريّة قافلة ملح في الخانق الغربي. اطردهم.',
  'Lekapenos': 'ليكابينوس',
  'Spondyles': 'سبونديليس',
  'Kanabos': 'كانابوس',
  'Apsimar': 'أبسيمار',
  'Garidas': 'غاريداس',
  'Mavrianos': 'مافريانوس',
  'Chalkeus': 'خالكيوس',
  'Barys': 'باريس',
  'Sphenos': 'سفينوس',
  'Pastilas': 'باستيلاس',
  'Tzoulas': 'تزولاس',
  'Kolybas': 'كوليباس',
  'Gouber': 'غوبر',
  'Rodophyles': 'رودوفيليس',
  'Maleses': 'ماليسيس',
  'Petzeas': 'بيتزياس',
  'Chasanes': 'خاسانيس',
  'Zoupas': 'زوباس',
  // ---- misc
  'Old water galleries run for miles under the Sawad, and the envoy\'s men use them. Each descent is a new maze. Clear the deepest gallery to open the next difficulty tier.': 'تمتدّ دهاليز الماء القديمة أميالًا تحت السواد، ورجال السفير يستعملونها. كلّ نزلة متاهة جديدة. طهّر أعمق دهليز لتفتح درجة الصعوبة التالية.',
};
