// Arabic text for the story: dialogue, cutscene lines, tasks and the codex. Keyed by the English text with any
// markup removed (see t() in i18n.js). Missing keys simply fall back to English.
import { AR21 } from './story21_ar.js';
import { AR22 } from './story22_ar.js';
import { AR23 } from './story23_ar.js';
import { AR24 } from './story24_ar.js';
export const STORY_AR = {
  // ---------------------------------------------------------------- names
  'Salim': 'سالم', 'Ishaq': 'إسحاق', 'Ghassan': 'غسّان', 'Farud': 'فرود', 'Hisham': 'هشام', 'Yusuf': 'يوسف', 'Bishr': 'بشر', '\'Amr': 'عمرو',
  'Act I · The Caravan': 'الفصل الأول · القافلة', 'The Sawad, outside Baghdad, in the year 813': 'السواد، خارج بغداد، سنة ٨١٣',
  'Act II · The Kilns': 'الفصل الثاني · الأتون', 'Hisham\'s knife-men wait among the brick stacks': 'رجال هشام بسكاكينهم يتربّصون بين أكوام الآجرّ',
  'Act III · The Broken Arch': 'الفصل الثالث · الطاق المكسور', 'Ghassan holds the road beneath the ruined Persian arch': 'غسّان يمسك الطريق تحت الطاق الفارسي المهدّم',
  'Renegade commander of the siege': 'قائد المتمرّدين من أيام الحصار', 'Renegade commander of the siege of Baghdad': 'قائد المتمرّدين من أيام حصار بغداد',
  'Madinat al-Salam': 'مدينة السلام', 'The City of Peace': 'مدينة السلام', 'Here ends the first chronicle of Salim': 'هنا تنتهي السيرة الأولى لسالم',
  'By nightfall the grain road was open again.': 'ومع حلول الليل عاد طريق الحَبّ مفتوحًا.',

  // ---------------------------------------------------------------- prologue and briefing
  'Too quiet. Even the frogs in the canal have stopped.': 'هدوء مريب. حتى ضفادع النهر سكتت.',
  'Salim! You live. When your caravan did not reach the gate, I feared the worst. I am Ishaq, astronomer of the House of Wisdom, and those were my instruments on your camels.': 'سالم! أنت حيّ. لمّا لم تبلغ قافلتك الباب خشيت الأسوأ. أنا إسحاق، فلكيّ في بيت الحكمة، وتلك كانت آلاتي على جمالكم.',
  'Salim! You live. When your caravan did not reach the gate, I feared the worst. I am Ishaq, astronomer of the Bayt al-Hikma — and those were my instruments on your camels.': 'سالم! أنت حيّ. لمّا لم تبلغ قافلتك الباب خشيت الأسوأ. أنا إسحاق، فلكيّ في بيت الحكمة، وتلك كانت آلاتي على جمالكم.',
  'The siege is over, but its soldiers did not all go home. A renegade named Ghassan gathers deserters at the ruined Persian arch to the south. He means to choke the grain road.': 'انتهى الحصار، لكنّ جنوده لم يعودوا كلّهم إلى بيوتهم. متمرّد اسمه غسّان يجمع الفارّين عند الطاق الفارسي المهدّم في الجنوب، ويريد أن يخنق طريق الحَبّ.',
  'The siege is over, but its soldiers did not all go home. A renegade named Ghassan gathers deserters at the ruined Persian arch to the south, and he means to choke the grain road.': 'انتهى الحصار، لكنّ جنوده لم يعودوا كلّهم إلى بيوتهم. متمرّد اسمه غسّان يجمع الفارّين عند الطاق الفارسي المهدّم في الجنوب، ويريد أن يخنق طريق الحَبّ.',
  'Break his lieutenants first. Farud holds the old caravanserai to the east, and Hisham hides his knife-men in the brick kilns across the canal. Keep your sword arm loose.': 'اكسر قادته أوّلًا. فرود يمسك الخان القديم في الشرق، وهشام يخبّئ رجاله في أفران الآجرّ عبر النهر. وأبقِ ساعدك ليّنًا.',
  'Break his lieutenants first: Farud holds the old caravanserai to the east, and Hisham hides his knife-men in the brick kilns across the canal. Take this sherbet, and keep your sword arm loose.': 'اكسر قادته أوّلًا: فرود يمسك الخان القديم في الشرق، وهشام يخبّئ رجاله في أفران الآجرّ عبر النهر. خذ هذا الشراب، وأبقِ ساعدك ليّنًا.',
  'Then I will bring them back. All of them.': 'إذن سأعيدها. كلّها.',
  'Hisham holds the kilns... he will not kneel as I did.': 'هشام يمسك الأفران... ولن يجثو كما جثوت.',
  'Ghassan waits at the arch. You will break on it.': 'غسّان ينتظر عند الطاق. ستتحطّم عليه.',
  'The siege fed my men for two years. Your grain road will feed them now.': 'أطعم الحصار رجالي عامين. والآن سيطعمهم طريق حَبّك.',
  'Engines! Burn the road!': 'المجانيق! أحرقوا الطريق!',
  'My instruments are home, and the House of Wisdom will hear how a caravan guard held the grain road.': 'عادت آلاتي إلى بيتها، وسيسمع بيت الحكمة كيف حمى حارس قافلة طريق الحَبّ.',
  'The Raiders Scatter': 'تفرّق الغزاة', 'Farud falls among the ruins of the caravanserai': 'سقط فرود بين أطلال الخان',
  'The Kilns Fall Silent': 'سكتت الأفران', 'Hisham\'s deserters flee into the dunes': 'فرّ رجال هشام إلى الكثبان',
  'The Renegade Falls': 'سقط المتمرّد', 'The grain road to Baghdad is open again': 'عاد طريق الحَبّ إلى بغداد مفتوحًا',
  'Ghassan is fallen. The caravans of the Sawad move freely once more.': 'سقط غسّان. وعادت قوافل السواد تسير آمنة.',

  // ---------------------------------------------------------------- Ishaq
  'Salim! Is that... the brass glints in your pack!': 'سالم! أهذا... النحاس يلمع في متاعك!',
  'The stars do not hurry, Salim, but Ghassan does. What do you need?': 'النجوم لا تعجل يا سالم، لكنّ غسّان يعجل. ماذا تحتاج؟',
  'Your astrolabe, teacher. Recovered from the kiln tunnels.': 'أسطرلابك يا معلّم. استعدته من أنفاق الأفران.',
  'You seem troubled. What did the raiders take?': 'تبدو مهمومًا. ماذا أخذ الغزاة؟',
  'Tell me about the House of Wisdom.': 'حدّثني عن بيت الحكمة.',
  'How did the siege come to this?': 'كيف انتهى الحصار إلى هذا؟',
  'Who were the men fighting in the streets?': 'من كان أولئك الذين قاتلوا في الشوارع؟',
  'Farewell.': 'وداعًا.', 'Farewell': 'وداعًا', 'Back.': 'رجوع.',
  'My best astrolabe, with a rete cut like lace. I made it myself over three winters. The raiders will have dragged it to their tunnels under the kilns. Hisham\'s men hoard brass to melt.': 'أفضل أسطرلاب عندي، عنكبوته مخرّمة كالدانتيل. صنعته بيدي في ثلاثة شتاءات. لا بدّ أنّ الغزاة جرّوه إلى أنفاقهم تحت الأفران؛ رجال هشام يكدّسون النحاس ليصهروه.',
  'I will find it.': 'سأجده.', 'Another time, teacher.': 'في وقت آخر يا معلّم.',
  'A library that became a workshop. We copy, we translate Ptolemy and the Indian tables, and we argue about them. The caliph pays for paper; we pay with sleep.': 'خزانة كتب صارت ورشة. ننسخ ونترجم بطليموس والأزياج الهندية ونتجادل فيها. الخليفة يدفع ثمن الورق، ونحن ندفع من نومنا.',
  'Two brothers, one throne. Tahir\'s Khurasanis came from the east. The city was burned street by street. Now al-Amin is dead, and men who learned to loot do not unlearn it.': 'أخوان وعرش واحد. جاء خراسانيّو طاهر من المشرق، وأُحرقت المدينة شارعًا شارعًا. والآن مات الأمين، ومن تعلّم النهب لا ينساه.',
  'The \'ayyarun: boys from the poor quarters with reed shields and slings, holding alleys against armoured men. Some of them are on the roads now too. Not all of them are Ghassan\'s.': 'العيّارون: فتيان من الأحياء الفقيرة بتروس من قصب ومقاليع، يمسكون الأزقّة في وجه رجال مدرّعين. بعضهم على الطرق الآن أيضًا، وليسوا كلّهم من رجال غسّان.',
  'It was in a chest, among Hisham\'s brass. Not a scratch.': 'كان في صندوق بين نحاس هشام. بلا خدش واحد.',
  'Three winters... and the rete is whole. Look, the star-pointers still sit true. You have saved more than brass, Salim.': 'ثلاثة شتاءات... والعنكبوت سليمة. انظر، مؤشّرات النجوم ما زالت في مواضعها. لقد أنقذت أكثر من نحاس يا سالم.',
  'I have little coin. But take this: a sky-chart I drew of the Sawad. With it, no road at night will lose you.': 'ليس معي مال كثير. لكن خذ هذا: خريطة سماء رسمتها للسواد. بها لن يضيّعك طريق في الليل.',
  'Or, if you would rather, I can pay you in dinars from the House\'s purse.': 'أو إن شئت، أدفع لك دنانير من كيس البيت.',
  'The chart. I would rather know the stars.': 'الخريطة. أفضّل أن أعرف النجوم.',
  'Dinars, teacher. The road is expensive.': 'الدنانير يا معلّم. الطريق مكلف.',
  'Ishaq\'s Sky-Chart': 'خريطة سماء إسحاق', 'Ishaq\'s Astrolabe': 'أسطرلاب إسحاق',

  // ---------------------------------------------------------------- Yusuf
  'The galleries are quiet. Whoever was fouling the channel will not be back.': 'الأروقة هادئة. من كان يفسد القناة لن يعود.',
  'Then the cisterns will fill sweet by the end of the week. The suq does not forget: from today my prices are yours at a discount.': 'إذن ستمتلئ الصهاريج عذبة قبل آخر الأسبوع. السوق لا ينسى: من اليوم لك أسعاري مخفّضة.',
  'Peace on your road, guard. Buying, selling... or listening? There is trouble in the water.': 'سلامة في طريقك يا حارس. تشتري أم تبيع... أم تسمع؟ في الماء مشكلة.',
  'Spices from Basra, steel from the Yemen, silk thread from Merv. What will it be?': 'توابل من البصرة، وفولاذ من اليمن، وخيوط حرير من مرو. ماذا تريد؟',
  'Show me your wares.': 'أرني بضاعتك.', 'Trouble in the water?': 'مشكلة في الماء؟', 'How does a merchant pay, out here?': 'كيف يدفع التاجر هنا؟',
  'The qanat under the well feeds this whole suq. Renegades camp in its galleries, and the water comes up foul. Clear them out, and I will remember it.': 'القناة تحت البئر تسقي السوق كلّه. المتمرّدون يخيّمون في أروقتها، فيصعد الماء فاسدًا. أخرجهم وسأحفظ لك ذلك.',
  'I will go down.': 'سأنزل.', 'Not now.': 'ليس الآن.',
  'Gold dinars for the great deals, silver dirhams for bread. And for long roads, a suftaja: a letter my cousin in Basra will honour. Paper weighs less than gold, and bandits cannot spend it.': 'دنانير الذهب للصفقات الكبيرة، ودراهم الفضّة للخبز. وللطرق الطويلة سُفتجة: كتاب يصرفه ابن عمّي في البصرة. الورق أخفّ من الذهب، واللصوص لا يستطيعون إنفاقه.',

  // ---------------------------------------------------------------- 'Amr
  'Three captains! I watched you from the walls, and I have lost good silver. Here. And take my old bayda. It turned a Khurasani lance once.': 'ثلاثة قادة! رأيتك من الأسوار، وخسرت فضّة طيّبة. خذ. وخذ بيضتي القديمة؛ ردّت رمحًا خراسانيًّا ذات مرّة.',
  'A soldier rests his arm between fights, not his mind. Train, change your way, or make a wager?': 'الجنديّ يريح ذراعه بين المعارك لا عقله. تتدرّب، أم تغيّر طريقتك، أم تراهن؟',
  'Training.': 'التدريب.', 'What wager?': 'أيّ رهان؟', 'You fought in the siege?': 'قاتلت في الحصار؟',
  'Ghassan\'s captains ride with a golden ring of men around them. Kill three of them in the field, and my purse is yours.': 'قادة غسّان يسيرون وحولهم حلقة ذهبيّة من الرجال. اقتل ثلاثة منهم في الميدان، وكيسي لك.',
  'Done.': 'اتّفقنا.', 'Not today.': 'ليس اليوم.',
  'On Tahir\'s side. Khurasani archers, mangonels, naft... and still the \'ayyarun held the Harbiyya for weeks. I do not boast about that year.': 'في صفّ طاهر. رماة خراسانيّون ومجانيق ونفط... ومع ذلك أمسك العيّارون الحربيّة أسابيع. لا أفخر بتلك السنة.',
  '\'Amr\'s Dented Bayda': 'بيضة عمرو المثلومة',

  // ---------------------------------------------------------------- tasks
  'The Lost Astrolabe': 'الأسطرلاب الضائع', 'Sweet Water': 'الماء العذب', '\'Amr\'s Wager': 'رهان عمرو',
  'Ishaq\'s finest astrolabe was taken with the caravan. Search the kiln tunnels beneath Hisham\'s yard.': 'أُخذ أفضل أسطرلاب لإسحاق مع القافلة. فتّش أنفاق الأفران تحت ساحة هشام.',
  'You found the astrolabe. Bring it back to Ishaq.': 'وجدت الأسطرلاب. أعده إلى إسحاق.',
  'Ishaq has his astrolabe again.': 'استعاد إسحاق أسطرلابه.',
  'Renegades are fouling the qanat that feeds the suq. Clear a descent of the ruined qanats.': 'المتمرّدون يفسدون القناة التي تسقي السوق. طهّر نزولًا في القنوات المهدّمة.',
  'The galleries are quiet. Tell Yusuf.': 'الأروقة هادئة. أخبر يوسف.',
  'The water runs clean, and the suq owes you.': 'الماء يجري صافيًا، والسوق مدين لك.',
  '\'Amr wagers you cannot defeat three captains of the renegades (elite foes) in the field.': 'يراهن عمرو أنّك لا تقدر على هزيمة ثلاثة من قادة المتمرّدين (أعداء النخبة) في الميدان.',
  'Three captains have fallen. Collect your winnings from \'Amr.': 'سقط ثلاثة قادة. خذ ربحك من عمرو.',
  'You won the wager.': 'ربحت الرهان.',
  'Task complete': 'اكتملت المهمّة', 'New task': 'مهمّة جديدة',

  // ---------------------------------------------------------------- codex
  'History': 'التاريخ', 'Places': 'الأماكن', 'Learning': 'العلم', 'War': 'الحرب', 'Craft': 'الصنعة', 'Trade': 'التجارة', 'People': 'الناس',
  'The Siege of Baghdad, 812–813': 'حصار بغداد، ٨١٢–٨١٣',
  'After Harun al-Rashid died in 809, his sons al-Amin (in Baghdad) and al-Ma\'mun (in Khurasan) fought for the caliphate. Al-Ma\'mun\'s general Tahir ibn al-Husayn besieged Baghdad from August 812. The fighting wrecked whole quarters of the city. It ended in September 813 with al-Amin\'s death. Soldiers of both sides were left loose in the countryside.': 'بعد وفاة هارون الرشيد سنة ٨٠٩ تنازع ابناه الأمين (في بغداد) والمأمون (في خراسان) على الخلافة. حاصر طاهر بن الحسين، قائد المأمون، بغداد من آب ٨١٢، فخرّب القتال أحياء كاملة من المدينة. وانتهى في أيلول ٨١٣ بمقتل الأمين، وبقي جنود الفريقين طلقاء في الريف.',
  'The Round City': 'المدينة المدوّرة',
  'Madinat al-Salam, the "City of Peace", was founded by the caliph al-Mansur in 762 on the west bank of the Tigris. Its plan was a perfect circle about two kilometres across, with double walls, a moat and four gates: the Kufa, Basra, Khurasan and Syria gates. Markets were later moved out to the suburb of al-Karkh. Much of the siege\'s damage fell on these outer quarters.': 'مدينة السلام، أسّسها الخليفة المنصور سنة ٧٦٢ على الضفّة الغربية لدجلة. كان مخطّطها دائرة تامّة قطرها نحو كيلومترين، بسورين وخندق وأربعة أبواب: باب الكوفة وباب البصرة وباب خراسان وباب الشام. ثمّ نُقلت الأسواق إلى ضاحية الكرخ، ووقع كثير من خراب الحصار على هذه الأحياء الخارجية.',
  'The House of Wisdom': 'بيت الحكمة',
  'Bayt al-Hikma began as a palace library under Harun al-Rashid. After al-Ma\'mun entered Baghdad in 819 it grew into a centre for translating Greek, Persian and Indian works on astronomy, mathematics, medicine and philosophy into Arabic. Scholars such as al-Khwarizmi worked in this circle, and in the 820s and 830s his astronomers made observations to check the tables of Ptolemy.': 'بدأ بيت الحكمة خزانةَ كتب في القصر أيام هارون الرشيد. وبعد دخول المأمون بغداد سنة ٨١٩ صار مركزًا لنقل كتب اليونان والفرس والهند في الفلك والرياضيات والطبّ والفلسفة إلى العربية. وعمل في هذه الدائرة علماء مثل الخوارزمي، ورصد فلكيّو المأمون في العشرينيّات والثلاثينيّات من القرن التاسع ليمتحنوا جداول بطليموس.',
  'The Astrolabe': 'الأسطرلاب',
  'A brass instrument that models the sky on a flat plate. By sighting a star or the sun and turning the rete, an astronomer can find the time, latitude and the heights of stars. Abbasid makers refined the Greek design. Treatises on its use, such as the one attributed to Masha\'allah, were among the early scientific works written in Arabic.': 'آلة من النحاس تمثّل السماء على صفيحة مسطّحة. برصد نجم أو الشمس وتدوير العنكبوت يعرف الفلكيّ الوقت والعرض وارتفاع النجوم. وقد أتقن صنّاع العصر العباسي التصميم اليوناني، وكانت رسائل العمل به، كالرسالة المنسوبة إلى ما شاء الله، من أوائل الكتب العلمية بالعربية.',
  'The Sawad': 'السواد',
  '"The Black Land": the dark, irrigated plain of central and lower Iraq between the Tigris and Euphrates, so called for its green fields against the desert. Its canals, date palms and grain fed Baghdad. Its taxes were the treasury\'s backbone, so keeping its roads open mattered to whoever held the city.': '«الأرض السوداء»: سهل العراق الأوسط والأسفل المرويّ بين دجلة والفرات، سُمّي كذلك لخضرة حقوله في وجه الصحراء. قنواته ونخيله وحبوبه أطعمت بغداد، وخراجه عماد بيت المال، فكان فتح طرقه يهمّ كلّ من ملك المدينة.',
  'Qanats': 'القنوات',
  'Underground channels that carry groundwater by gravity over many kilometres. They are marked on the surface by a line of access shafts. The technique came from Iran and spread across the Islamic world. Building and cleaning them took specialists who worked deep below ground by lamplight.': 'مجارٍ تحت الأرض تحمل الماء الجوفيّ بانحدارها كيلومترات كثيرة، وتدلّ عليها فوق الأرض صفوف من الآبار. جاءت التقنية من إيران وانتشرت في البلاد، وكان بناؤها وتنظيفها عمل حذّاق يشتغلون في عمق الأرض على ضوء السُّرُج.',
  'Naft and the Naffatun': 'النفط والنفّاطون',
  'Crude oil from seeps in Iraq and Persia was distilled into "white naft", a fierce incendiary. Specialist troops called naffatun threw it in clay pots or projected it from tubes. They wore protective clothing of felt and leather. Chroniclers record fire and mangonels wrecking whole streets in the siege of Baghdad.': 'كان النفط الخام من منابعه في العراق وفارس يُقطَّر إلى «النفط الأبيض»، وهو حارق شديد. ورماه جنود مختصّون يسمّون النفّاطين في قدور من فخّار أو قذفوه من أنابيب، ولبسوا ثيابًا واقية من اللبّاد والجلد. ويذكر الإخباريّون أنّ النار والمجانيق خرّبت شوارع كاملة في حصار بغداد.',
  'The \'Ayyarun': 'العيّارون',
  'Bands of young men from Baghdad\'s poorer quarters. During the siege of 812–813 they fought for al-Amin, often nearly naked, with little armour, makeshift shields and stones. They were brave street fighters who knew every alley. Chroniclers describe them with a mix of scorn and admiration.': 'جماعات من فتيان أحياء بغداد الفقيرة. قاتلوا للأمين في حصار ٨١٢–٨١٣، وكثيرًا ما كانوا شبه عراة، بلا دروع تقريبًا، بتروس مرتجلة وحجارة. كانوا مقاتلي شوارع شجعانًا يعرفون كلّ زقاق، ويصفهم الإخباريّون بمزيج من الازدراء والإعجاب.',
  'The Khurasani Regiments': 'الفرق الخراسانية',
  'Troops from Khurasan in the far east of the empire, the heartland of the Abbasid revolution of 750. Under Tahir they formed the core of al-Ma\'mun\'s army. They were known for mounted archery and disciplined infantry.': 'جنود من خراسان في أقصى شرق الدولة، موطن الثورة العباسية سنة ٧٥٠. شكّلوا تحت قيادة طاهر قلب جيش المأمون، وعُرفوا برماية الفرسان وانضباط المشاة.',
  'Baked Brick': 'الآجرّ',
  'Mesopotamia has little stone and timber, so it has built in brick for thousands of years. Sun-dried mud brick served for ordinary walls. Kiln-fired brick, harder and costlier, faced palaces, bridges and the gates of the Round City. Kiln yards outside the city burned day and night.': 'قلّ الحجر والخشب في بلاد الرافدين، فبنى أهلها باللبن منذ آلاف السنين. اللبن المجفّف في الشمس للجدران العاديّة، والآجرّ المشويّ في الأتون، وهو أصلب وأغلى، لواجهات القصور والجسور وأبواب المدينة المدوّرة. وكانت ساحات الأفران خارج المدينة تشتعل ليل نهار.',
  'Caravanserais': 'الخانات',
  'Walled inns along the trade roads, built around a courtyard ringed with rooms, storerooms and stables. A single gate could be shut at night. Merchants, couriers and their animals rested in them, roughly a day\'s march apart.': 'نُزُل مسوّرة على طرق التجارة، مبنيّة حول صحن تحيط به الغرف والمخازن والإسطبلات، لها باب واحد يُغلق في الليل. ينزلها التجّار والسعاة ودوابّهم، وبين الواحد والآخر نحو مسيرة يوم.',
  'The Barid': 'البريد',
  'The caliphal post and intelligence service. Relays of horses and couriers carried official letters along the main roads. Its local masters also sent the capital reports on governors, prices and unrest.': 'بريد الخلافة وعيونها. كانت مراحل الخيل والسعاة تحمل الكتب الرسمية على الطرق الكبرى، وكان أصحاب البريد في الأقاليم يرفعون إلى العاصمة أخبار الولاة والأسعار والاضطرابات.',
  'Dinars and Dirhams': 'الدنانير والدراهم',
  'The gold dinar (about 4.25 g) and the silver dirham were the coins of the caliphate. After the reform of the 690s they carried only inscriptions, with no images. Bills of exchange (suftaja) and cheques (sakk) let merchants move money without carrying coin across the empire.': 'الدينار الذهبيّ (نحو ٤٫٢٥ غرام) والدرهم الفضّيّ عملتا الخلافة. وبعد إصلاح التسعينيّات من القرن السابع صارت تحمل كتابة فقط بلا صور. وأتاحت السفاتج والصكوك للتجّار نقل المال دون حمل النقود عبر الدولة.',
  'Paper in Baghdad': 'الورق في بغداد',
  'Papermaking reached the Islamic world from Central Asia. Later writers credit the Barmakid al-Fadl ibn Yahya with founding a paper mill in Baghdad in the 790s. Cheaper than parchment or papyrus, paper fed the bureaucracy, the book markets of the city and, soon, the translators of the House of Wisdom.': 'وصلت صناعة الورق من آسيا الوسطى. وينسب كتّاب متأخّرون إلى البرمكيّ الفضل بن يحيى إنشاء مصنع للورق في بغداد في التسعينيّات من القرن الثامن. وكان الورق أرخص من الرقّ والبرديّ، فغذّى الدواوين وأسواق الورّاقين، ثمّ مترجمي بيت الحكمة.',
  'The Barmakids': 'البرامكة',
  'A family of Persian administrators from Balkh. As viziers under Harun al-Rashid they ran the empire\'s government and patronised scholars and poets. In 803 Harun abruptly had them arrested and their leader Ja\'far executed. The reasons are still debated.': 'أسرة من الكتّاب الفرس من بلخ. تولّوا الوزارة لهارون الرشيد فأداروا الدولة ورعوا العلماء والشعراء. وفي سنة ٨٠٣ قبض عليهم هارون فجأة وقتل جعفرًا كبيرهم، وما زالت أسباب ذلك موضع خلاف.',
  'No tasks yet. The people of the suq may have work.': 'لا مهامّ بعد. لعلّ عند أهل السوق عملًا.',
  '— undiscovered —': '— لم يُكتشف —',

  // ---------------------------------------------------------------- tutorial hints
  'Click the ground to walk. Hold the button to keep moving.': 'انقر الأرض لتمشي. أبقِ الزرّ مضغوطًا لتواصل السير.',
  'Drag on the left of the screen to walk.': 'اسحب على يسار الشاشة لتمشي.',
  'Click a foe to attack. Your discipline sets the weapon.': 'انقر عدوًّا لتهاجمه. فنّك يحدّد سلاحك.',
  'Tap the large button (or a foe) to attack.': 'انقر الزرّ الكبير (أو عدوًّا) لتهاجم.',
  'Space to evade. Evade just as a blade glints and you will parry.': 'المسافة للمراوغة. راوغ لحظة يلمع النصل فتصدّ الضربة.',
  'The curved arrow evades. Evade just as a blade glints and you will parry.': 'السهم المنحني للمراوغة. راوغ لحظة يلمع النصل فتصدّ الضربة.',
  'Right-click and 1, 2, 3 use your skills. Each costs your resource.': 'الزرّ الأيمن و١ و٢ و٣ لمهاراتك. لكلّ منها كلفة من مَددك.',
  'The ring of buttons holds your skills. Each costs your resource.': 'حلقة الأزرار تحمل مهاراتك. لكلّ منها كلفة من مَددك.',
  'Wounded: press Q to drink pomegranate sherbet.': 'جريح: اضغط Q لتشرب شراب الرمّان.',
  'Wounded: tap the red flask to drink sherbet.': 'جريح: انقر القارورة الحمراء لتشرب.',
  'The suq: talk (E) to Yusuf, Bishr and \'Amr. The well leads to the qanats.': 'السوق: كلّم (E) يوسف وبشرًا وعمرًا. والبئر تقود إلى القنوات.',
  'The suq: walk up to Yusuf, Bishr and \'Amr and tap the prompt. The well leads to the qanats.': 'السوق: اقترب من يوسف وبشر وعمرو وانقر الدعوة. والبئر تقود إلى القنوات.',
  'A discipline point to spend: press K.': 'نقطة فنّ لتنفقها: اضغط K.',
  'A discipline point to spend: Menu ☰, then Disciplines.': 'نقطة فنّ لتنفقها: القائمة ☰ ثمّ المهارات.',

  // ---------------------------------------------------------------- Round 10
  'Rafi\'': 'رافع', 'Qays': 'قيس', 'Thabit': 'ثابت', 'Mundhir': 'المنذر', '\'Uqba': 'عقبة', 'Nasr': 'نصر', 'Bakr': 'بكر', 'Hamdan': 'حمدان', 'Rabi\'a': 'ربيعة', 'Jarir': 'جرير',
  'Captain slain': 'سقط قائد', 'Engines burned': 'المجانيق المحروقة', 'New Game+': 'لعبة جديدة+', 'foes are stronger': 'الأعداء أشدّ',
  'Keep your hero, gear and disciplines. The Sawad resets, and its foes grow stronger.': 'احتفظ ببطلك وعتاده وفنونه. يعود السواد من جديد، ويشتدّ أعداؤه.',
  'Go down into the storerooms': 'انزل إلى المخازن', 'Climb down into the clay pits': 'انزل إلى حفر الطين', 'Enter the Sasanian vaults': 'ادخل الأقبية الساسانية', 'Set the engine alight': 'أضرم النار في المنجنيق',
  'The Caravanserai Storerooms': 'مخازن الخان', 'Vaulted stores beneath Farud\'s camp': 'مخازن مقبّبة تحت معسكر فرود',
  'The Clay Pits': 'حفر الطين', 'Where the kiln yard digs its clay': 'حيث تحفر ساحة الأفران طينها',
  'The Sasanian Vaults': 'الأقبية الساسانية', 'Brick halls older than Baghdad': 'قاعات من الآجرّ أقدم من بغداد',
  'The Courier\'s Satchel': 'حقيبة الساعي', 'Indian Steel': 'الفولاذ الهندي', 'Ash for the Engines': 'رماد للمجانيق',
  'Qays took a barid courier\'s satchel into the storerooms under the caravanserai. Recover it.': 'أخذ قيس حقيبة ساعٍ من البريد إلى المخازن تحت الخان. استعدها.',
  'You have the satchel. Return it to Rafi\' in the suq.': 'معك الحقيبة. أعدها إلى رافع في السوق.',
  'The letters reached Baghdad.': 'بلغت الكتب بغداد.',
  'Thabit\'s men carried off Bishr\'s Indian steel ingots to the clay pits by the kilns. Bring them back.': 'حمل رجال ثابت سبائك الفولاذ الهندي لبشر إلى حفر الطين قرب الأفران. أعدها.',
  'You have the ingots. Take them to Bishr.': 'معك السبائك. خذها إلى بشر.',
  'Bishr has his steel again.': 'استعاد بشر فولاذه.',
  'Ghassan has three mangonels on the approach to the arch. Burn them before you face him (0/3).': 'لغسّان ثلاثة مجانيق على الطريق إلى الطاق. أحرقها قبل أن تواجهه (٠/٣).',
  'The engines are ash. Tell \'Amr.': 'صارت المجانيق رمادًا. أخبر عمرًا.',
  'Ghassan fights without his engines.': 'يقاتل غسّان بلا مجانيقه.',
  'The Courier\'s Satchel': 'حقيبة الساعي', 'Indian Steel Ingots': 'سبائك الفولاذ الهندي',
  'Your satchel. The seals are unbroken.': 'حقيبتك. الأختام سليمة.',
  'Unbroken! Then the postmaster in Baghdad will have his reports by tomorrow, and I will keep my post. Take this, and my thanks.': 'سليمة! إذن يصل صاحبَ البريد في بغداد أخبارُه غدًا، وأحفظ أنا عملي. خذ هذا، ولك شكري.',
  'Forgive me, I cannot stand for long. Brigands ran down my horse on the Khurasan road and took my satchel.': 'اعذرني، لا أقدر على الوقوف طويلًا. صدم اللصوص فرسي على طريق خراسان وأخذوا حقيبتي.',
  'The relay horses run again. If you ever need a letter carried, ask for Rafi\'.': 'عادت خيل المراحل تجري. إن احتجت يومًا إلى حمل كتاب فاسأل عن رافع.',
  'Qays and his archers hide in the storerooms under the caravanserai. Be careful.': 'يختبئ قيس ورماته في المخازن تحت الخان. احذر.',
  'What was in it?': 'ماذا كان فيها؟', 'What is the barid?': 'ما البريد؟', 'I will bring it back.': 'سأعيدها.',
  'Letters for the postmaster in Baghdad: reports on prices and governors, sealed. If they are opened or lost, I lose my post. Qays took them into the storerooms under the caravanserai.': 'كتب لصاحب البريد في بغداد: أخبار الأسعار والولاة، مختومة. إن فُتحت أو ضاعت فقدت عملي. أخذها قيس إلى المخازن تحت الخان.',
  'The caliph\'s post. Relays of horses along the great roads, a fresh mount at every station. We carry the state\'s letters, and the postmasters write to Baghdad about everything they see.': 'بريد الخليفة. مراحل من الخيل على الطرق الكبرى، وفرس جديدة عند كلّ محطّة. نحمل كتب الدولة، وأصحاب البريد يكتبون إلى بغداد بكلّ ما يرون.',
  'Your ingots, from the clay pits. Thabit will not need them.': 'سبائكك، من حفر الطين. لن يحتاج إليها ثابت.',
  'Ha! Feel the weight of that. I will forge you something worthy of it, and your next tempering is on my anvil, free.': 'ها! تحسّس ثقلها. سأطرق لك شيئًا يليق بها، وسقيُك القادم على سندانـي بلا أجر.',
  'Mind the sparks. You have the look of someone who could do me a favour.': 'احذر الشرر. تبدو كمن يقدر أن يسدي إليّ معروفًا.',
  'The forge is hot. What do you need?': 'الكور حامٍ. ماذا تحتاج؟',
  'Show me the forge.': 'أرني الكور.', 'What favour?': 'أيّ معروف؟', 'I will get them back.': 'سأستعيدها.',
  'Six ingots of Indian steel, come up from Basra, and Thabit\'s men took them off the cart at the kilns. They will be hiding in the clay pits. Steel like that does not come twice a year.': 'ستّ سبائك من الفولاذ الهندي جاءت من البصرة، وأنزلها رجال ثابت عن العربة عند الأفران. لا بدّ أنّهم يختبئون في حفر الطين. فولاذ كهذا لا يأتي مرّتين في السنة.',
  'I saw the smoke from here. Without his engines, Ghassan is just a big man with a sword. Here, for the road.': 'رأيت الدخان من هنا. بلا مجانيقه ليس غسّان إلّا رجلًا ضخمًا بسيف. خذ، للطريق.',
  'One more thing, before you go south. Ghassan has mangonels on the road to the arch. If he gets them loosing naft at you, you will burn. Burn them first.': 'أمر آخر قبل أن تمضي جنوبًا. لغسّان مجانيق على طريق الطاق. إن رمتك بالنفط احترقت. أحرقها أنت أوّلًا.',
  'Consider it done.': 'اعتبره منتهيًا.', 'Later.': 'لاحقًا.',
  'My engines are ash. Then it is steel, guard. Just you and me.': 'مجانيقي رماد. إذن هو الحديد يا حارس. أنا وأنت فقط.',
  'Enough. No more men, no more engines. Just you and me.': 'كفى. لا رجال ولا مجانيق. أنا وأنت فقط.',
  'Fire rings the broken arch.': 'النار تطوّق الطاق المكسور.',
  'The Arch of Ctesiphon': 'إيوان المدائن',
  'The Sasanian kings\' palace at Ctesiphon, downriver from where Baghdad would rise, was crowned by a vast brick vault, the Taq Kasra, built in the 6th century. Its single span of about 25 metres made it one of the largest brick vaults ever raised. Later writers tell that al-Mansur thought of pulling it down for bricks for his new city, and gave up when the cost of demolition outran the value of the bricks.': 'كان قصر الملوك الساسانيين في المدائن، أسفل النهر من موضع بغداد، يعلوه قبو عظيم من الآجرّ هو طاق كسرى، بُني في القرن السادس. وجعله امتداده الواحد البالغ نحو خمسة وعشرين مترًا من أكبر الأقبية الآجرّية التي رُفعت. ويروي كتّاب متأخّرون أنّ المنصور همّ بهدمه ليأخذ آجرّه لمدينته الجديدة، ثمّ عدل لمّا زادت كلفة الهدم على قيمة الآجرّ.',
  'Mangonels': 'المجانيق',
  'The manjaniq was a beam sling engine worked by teams pulling ropes. It threw stones and pots of naft over walls. Both sides set them up in Baghdad in 812–813, and the chroniclers blame them for much of the damage to houses and markets.': 'المنجنيق آلة رمي بذراع ومقلاع يشغّلها فريق يشدّ الحبال، ترمي الحجارة وقدور النفط فوق الأسوار. نصبها الفريقان في بغداد سنة ٨١٢–٨١٣، ويحمّلها الإخباريّون كثيرًا من خراب البيوت والأسواق.',
  'Crucible steel came west from India and Sri Lanka as small ingots. Smiths prized it for blades that took a hard, keen edge, and its watered pattern became famous. Merchants carried it through the Gulf ports to Basra and up to Baghdad.': 'جاء فولاذ البوتقة غربًا من الهند وسرنديب سبائك صغيرة. وقدّره الحدّادون لنصال تقبل حدًّا صلبًا ماضيًا، واشتهر فرنده المموّج. وحمله التجّار عبر موانئ الخليج إلى البصرة ثمّ إلى بغداد.',
  'You burned my engines? Then my men will do it by hand!': 'أحرقت مجانيقي؟ إذن يفعلها رجالي بأيديهم!',
  'Swift': 'خاطف', 'Ironclad': 'مدرّع', 'Volley': 'رشق', 'Firebrand': 'مُشعِل', 'Rallying': 'مُستنفِر',

  // ---------------------------------------------------------------- Round 11: the Pages
  'Jabir': 'جابر', 'People': 'الناس',
  'Too quiet, brother. Even the frogs in the canal have stopped.': 'هدوء مريب يا أخي. حتى ضفادع النهر سكتت.',
  'Salim... the chest. Do not let them burn it.': 'سالم... الصندوق. لا تدعهم يحرقونه.',
  'Jabir fell on the grain road. The chest was taken. Salim lived.': 'سقط جابر على طريق الحَبّ. وأُخذ الصندوق. وعاش سالم.',
  'You are Jabir\'s brother. I am Ishaq. I hired your caravan, and I am sorry. He was a better man than my coin deserved.': 'أنت أخو جابر. أنا إسحاق. أنا من استأجر قافلتكم، وأنا آسف. كان رجلًا أكرم ممّا يستحقّه مالي.',
  'Under my instruments was a cedar chest: the Pages of the Teacher, who died in a prison by the river fourteen years ago. Someone in Baghdad wants his words to burn. Ghassan was paid to see it done.': 'تحت آلاتي كان صندوق من خشب الأرز: أوراق المعلّم، الذي مات في سجن على النهر قبل أربع عشرة سنة. أحدهم في بغداد يريد أن تحترق كلماته، ودُفع لغسّان ليتمّ ذلك.',
  'Farud holds the old caravanserai, Hisham the kilns, and Ghassan the broken arch. If the Pages still exist, they are between those three. Your brother asked you for one thing.': 'فرود يمسك الخان القديم، وهشام الأفران، وغسّان الطاق المكسور. إن بقيت الأوراق فهي بين هؤلاء الثلاثة. أخوك طلب منك شيئًا واحدًا.',
  'Then I will finish what he asked.': 'إذن سأتمّ ما طلب.',
  'I read one of his pages by firelight... and never slept after. Ghassan paid me. Hisham has the rest.': 'قرأت ورقة من أوراقه على ضوء النار... ولم أنم بعدها. غسّان دفع لي. والباقي عند هشام.',
  'Hisham is feeding the Pages to the kilns, a bundle at a time': 'هشام يطعم الأفران الأوراقَ حزمةً حزمة',
  'I sat at his feet once. Then I chose bread over a dead man\'s words. Tell Ishaq... no. Tell no one.': 'جلست عند قدميه يومًا. ثمّ اخترت الخبز على كلمات رجل ميّت. قل لإسحاق... لا. لا تقل لأحد.',
  'Ghassan has cut the canal. The village is thirsty': 'قطع غسّان النهر. والقرية عطشى',
  'Farud Confesses': 'فرود يعترف', 'The buyer\'s name was Ghassan': 'اسم المشتري غسّان',
  'Some pages were saved from the fire': 'نجت بعض الأوراق من النار',
  'The Silence Is Broken': 'انكسر الصمت', 'The Pages are recovered; the water runs again': 'استُعيدت الأوراق، وعاد الماء يجري',
  'The Pages are recovered. The water runs again.': 'استُعيدت الأوراق. وعاد الماء يجري.',
  'Words make men stubborn, guard. Stubborn men do not pay. Turn back while you can.': 'الكلمات تجعل الرجال عنيدين يا حارس، والعنيد لا يدفع. ارجع ما دمت تقدر.',
  'He sells silence by the bale': 'يبيع الصمت بالأحمال',
  'Engines! Burn the road, and the canal with it!': 'المجانيق! أحرقوا الطريق والنهر معه!',
  'My engines are ash. Then it is steel. Die for paper, then.': 'مجانيقي رماد. إذن هو الحديد. مُت من أجل الورق إذن.',
  'You would die for paper? Then die.': 'تموت من أجل ورق؟ فمُت.',
  'Not for paper. For the ones you silenced, and for my brother.': 'لا من أجل الورق. من أجل الذين أسكتّهم، ومن أجل أخي.',
  'In Ghassan\'s tent, wrapped in a saddle cloth, the Pages were waiting.': 'في خيمة غسّان، ملفوفةً في قماش سرج، كانت الأوراق تنتظر.',
  'At dusk the village set lamps on the water, one for each guard of the caravan.': 'عند الغروب وضع أهل القرية سُرُجًا على الماء، واحدًا لكلّ حارس من حرّاس القافلة.',
  'Jabir.': 'جابر.',
  'The Teacher wrote: injustice lasts an hour, and justice until the end of days. We keep the account until the scales are set right.': 'كتب المعلّم: للظلم ساعة، وللعدل إلى آخر الدهر. ونحن نحفظ الحساب حتّى تستقيم الموازين.',
  'Who was the Teacher?': 'من كان المعلّم؟', 'And my brother died for those pages.': 'ومات أخي من أجل تلك الأوراق.',
  'A quiet man who gave away more than he owned. He told the powerful the truth, gently, and they never forgave him for it. They kept him in a cell by the river until he died. His students say it was poison. We copied what he said so it could not be buried with him.': 'رجل هادئ أعطى أكثر ممّا ملك. قال للأقوياء الحقّ برفق، فلم يغفروا له ذلك. حبسوه في زنزانة على النهر حتّى مات، ويقول تلاميذه إنّه السمّ. نسخنا ما قال كي لا يُدفن معه.',
  'Your brother died so that a dead man\'s words would not die a second time. That is not nothing, Salim. When this is over, we will speak his name aloud, so the people who killed him do not get to write the story.': 'مات أخوك كي لا تموت كلمات رجل ميّت مرّة ثانية. ليس هذا قليلًا يا سالم. وحين ينتهي هذا سننطق اسمه عاليًا، كي لا يكتب قاتلوه الحكاية.',
  'The qanat under the well feeds this whole suq. Ghassan\'s men camp in its galleries and foul the water on purpose. A man can go a long time without bread, guard. Not without water. Clear them out.': 'القناة تحت البئر تسقي السوق كلّه. رجال غسّان يخيّمون في أروقتها ويفسدون الماء عمدًا. يصبر الرجل طويلًا على الخبز يا حارس، لكن لا يصبر على الماء. أخرجهم.',
  'The Teacher': 'المعلّم',
  'Salim never learns his name; his students only ever say "the Teacher". He taught wherever people would listen, lived simply, and spoke plainly to men who preferred flattery. He was held for years in a prison beside the Tigris and died there in 799. His sayings were copied and passed hand to hand, because written words outlive the people who try to silence them.': 'لا يعرف سالم اسمه؛ تلاميذه لا يقولون إلّا «المعلّم». علّم حيثما وجد من يسمع، وعاش بسيطًا، وكلّم بالصراحة رجالًا يؤثرون المديح. حُبس سنين في سجن على دجلة ومات فيه سنة ٧٩٩. ونُسخت أقواله وتناقلتها الأيدي، لأنّ الكلمة المكتوبة تعيش بعد من يحاول إسكاتها.',
  'The Teacher\'s Pages are safe, and the lamps for the fallen still drift on the canal.': 'أوراق المعلّم في أمان، وسُرُج الراحلين ما زالت تطفو على النهر.',
  'Ishaq keeps the account.': 'إسحاق يحفظ الحساب.',
  // round 13: plainer cutscene lines
  'Too quiet, brother. I do not like it.': 'هدوء مريب يا أخي. لا يعجبني هذا.',
  'Salim... the chest. Do not let them burn it.': 'سالم... الصندوق. لا تدعهم يحرقونه.',
  'Bandits ambushed the caravan. Jabir was killed, and they took the chest.': 'هاجم قطّاع الطرق القافلة. قُتل جابر، وأخذوا الصندوق.',
  'I am Ishaq. I hired your caravan. I am sorry about Jabir.': 'أنا إسحاق. استأجرت قافلتكم. أنا آسف على جابر.',
  'He died for that chest. What was in it?': 'مات من أجل ذلك الصندوق. ماذا كان فيه؟',
  'The Pages: the writings of my old teacher. A powerful man in Baghdad wants them burned. He paid a bandit chief, Ghassan, to steal them.': 'الأوراق: كتابات معلّمي القديم. رجل نافذ في بغداد يريد إحراقها. دفع لزعيم قطّاع طرق اسمه غسّان ليسرقها.',
  'Ghassan split the Pages between his men. Get them back. Start with Farud, at the old caravanserai.': 'وزّع غسّان الأوراق على رجاله. استعدها. ابدأ بفرود عند الخان القديم.',
  'Ghassan paid me to take the chest. Hisham has the Pages now, at the kilns.': 'دفع لي غسّان لآخذ الصندوق. الأوراق الآن مع هشام، عند الأفران.',
  'Hisham is burning the Pages in the kilns. Stop him.': 'هشام يحرق الأوراق في الأفران. أوقفه.',
  'I sold the Pages to Ghassan for a bag of silver. He has the rest, at the old arch.': 'بعت الأوراق لغسّان بكيس من الفضّة. البقية معه، عند الطاق القديم.',
  'Ghassan has cut off the village\'s water. Find him at the arch.': 'قطع غسّان الماء عن القرية. جِده عند الطاق.',
  'Turn back, guard. Those Pages are not worth your life.': 'ارجع أيها الحارس. تلك الأوراق لا تستحقّ حياتك.',
  'The man who paid for the ambush': 'الرجل الذي دفع ثمن الكمين',
  'Fire the engines! Burn the road!': 'أطلقوا المجانيق! أحرقوا الطريق!',
  'You burned my engines? Then my men will burn you by hand!': 'أحرقت مجانيقي؟ إذن سيحرقك رجالي بأيديهم!',
  'Ghassan rings the arena with fire. Stay inside it.': 'يطوّق غسّان الساحة بالنار. ابقَ داخلها.',
  'No engines left. Then it is just you and me.': 'لم تبقَ مجانيق. إذن أنا وأنت فقط.',
  'Not for paper. For my brother.': 'ليس من أجل الورق. من أجل أخي.',
  'The last Pages were in Ghassan\'s tent. They were safe.': 'كانت آخر الأوراق في خيمة غسّان. صارت في أمان.',
  'That evening the village floated a lamp on the canal for each guard who died.': 'في ذلك المساء أطلقت القرية سراجًا على القناة لكلّ حارس مات.',
  'Thanks to you, his words will be read. And we will remember Jabir.': 'بفضلك ستُقرأ كلماته. وسنذكر جابرًا.',
  'Two more days to Baghdad, Salim. Then home.': 'يومان آخران إلى بغداد يا سالم. ثمّ إلى البيت.',
  'Riders were waiting on the dunes.': 'كان فرسان ينتظرون على الكثبان.',
  'Bandits attacked the caravan at dusk.': 'هاجم قطّاع الطرق القافلة عند الغروب.',
  'I will bring it back, brother. I promise.': 'سأستعيده يا أخي. أعدك.',
  'Jabir did not live to see Baghdad. The bandits had taken the chest.': 'لم يعش جابر ليرى بغداد. وكان قطّاع الطرق قد أخذوا الصندوق.',
};

// ---------------------------------------------------------------- Round 15: the marshes and al-Karkh
Object.assign(STORY_AR, {
  // names and places
  'Marwan': 'مروان', 'Sahl': 'سهل', 'Rawh': 'روح', '\'Asim': 'عاصم', 'Layth': 'ليث', '\'Utba': 'عتبة', 'Zuhayr': 'زهير', 'Muhriz': 'محرز',
  'Hammad': 'حمّاد', 'Shabib': 'شبيب', 'Ghalib': 'غالب', 'Qutayba': 'قتيبة', 'Hakam': 'الحكم',
  'The Nahrawan marshes': 'أهوار النهروان', 'The Nahrawan Marshes': 'أهوار النهروان', 'Al-Karkh': 'الكرخ', 'The Sawad': 'السواد',
  // tasks
  'Find Marwan in the reed camp to the west': 'اعثر على مروان في مخيّم القصب غربًا',
  'Take Rawh\'s boats from Sahl at the fish racks': 'خذ قوارب روح من سهل عند مناشر السمك',
  'Face Rawh at the old weir': 'واجه روحًا عند السِّكر القديم',
  'Find \'Asim in the burned suq': 'اعثر على عاصم في السوق المحروقة',
  'Drive Layth from the paper-sellers\' lane': 'اطرد ليثًا من سوق الورّاقين',
  'Stop \'Utba in the square before sunset': 'أوقف عتبة في الساحة قبل الغروب',
  // captains fall
  'Rawh paid us to hide his boats. Sahl keeps them at the fish racks, east.': 'دفع لنا روح لنخبّئ قواربه. سهل يحرسها عند مناشر السمك شرقًا.',
  'The Fish Racks': 'مناشر السمك', 'Take Rawh\'s boats from Sahl, so he cannot run.': 'خذ قوارب روح من سهل، فلا يستطيع الفرار.',
  'Rawh is at the old weir with the Pages. He sails for Baghdad tonight.': 'روح عند السِّكر القديم ومعه الأوراق. يبحر إلى بغداد الليلة.',
  'The Old Weir': 'السِّكر القديم', 'Rawh is waiting for a boat that will not come.': 'روح ينتظر قاربًا لن يأتي.',
  '\'Utba moved the Pages to the paper-sellers\' lane. Layth guards them.': 'نقل عتبة الأوراق إلى سوق الورّاقين. ليث يحرسها.',
  'The Paper-Sellers\' Lane': 'سوق الورّاقين', 'Layth guards the Pages among the paper shops.': 'ليث يحرس الأوراق بين دكاكين الورق.',
  'Too late. \'Utba took them to the square. He burns them at sunset.': 'فات الأوان. أخذها عتبة إلى الساحة. سيحرقها عند الغروب.',
  'The Square': 'الساحة', 'Stop \'Utba before he lights the pyre.': 'أوقف عتبة قبل أن يشعل المحرقة.',
  // bosses
  'Paper, guard? My buyer pays in gold. Name your price.': 'ورق يا حارس؟ شاريّ يدفع ذهبًا. سمِّ ثمنك.',
  'Ghassan\'s paymaster': 'صرّاف غسّان', 'Nets! Drag him into the water!': 'الشِّباك! اسحبوه إلى الماء!',
  'Paper burns, guard. So do the men who carry it.': 'الورق يحترق يا حارس. وكذلك من يحمله.',
  'Captain of the buyer\'s men': 'قائد رجال الشاري', 'Archers! Bring him down!': 'أيها الرماة! أسقطوه!',
  'Light the stalls. Let the whole square burn.': 'أشعلوا الدكاكين. لتحترق الساحة كلّها.',
  'The stalls are burning. Stay inside the ring.': 'الدكاكين تحترق. ابقَ داخل الحلقة.',
  // Ishaq in the marshes and in al-Karkh
  'The fishermen here owe Rawh nothing, and they do not like him. They say he paid for boats and silence.': 'صيّادو هذه الأهوار لا يدينون لروح بشيء، ولا يحبّونه. يقولون إنه دفع ثمن القوارب والسكوت.',
  'Marwan hides his boats in the reed camp to the west. Sahl keeps the rest at the fish racks to the east. Without boats, Rawh cannot leave.': 'مروان يخبّئ قواربه في مخيّم القصب غربًا. وسهل يحرس البقية عند مناشر السمك شرقًا. بلا قوارب لا يستطيع روح الرحيل.',
  'Mind the deep water. Wade where it is shallow, and watch the reeds. The marsh men fight from them.': 'احذر الماء العميق. خُض حيث يكون ضحلًا، وراقب القصب. رجال الأهوار يقاتلون من بينه.',
  'This was the greatest market in the world before the siege. Now look at it.': 'كانت هذه أعظم سوق في الدنيا قبل الحصار. انظر إليها الآن.',
  'The buyer\'s men answer to \'Utba. \'Asim holds the burned suq and Layth the paper-sellers\' lane.': 'رجال الشاري يأتمرون بعتبة. عاصم يمسك السوق المحروقة، وليث سوق الورّاقين.',
  'The scholars of the House of Wisdom have promised to copy the Pages. Bring them here, and they are safe for ever.': 'وعد علماء بيت الحكمة بنسخ الأوراق. أحضرها إلى هنا، فتبقى في أمان أبدًا.',
  // the end of Act III now leads on
  'Most of the Pages were in Ghassan\'s tent.': 'كانت معظم الأوراق في خيمة غسّان.',
  'But the chest is light. Some of the Pages are missing.': 'لكنّ الصندوق خفيف. بعض الأوراق مفقود.',
  'Who has them?': 'من أخذها؟',
  'Rawh, Ghassan\'s paymaster. He fled east, into the Nahrawan marshes.': 'روح، صرّاف غسّان. فرّ شرقًا إلى أهوار النهروان.',
  'Act IV · The Marshes': 'الفصل الرابع · الأهوار', 'Rawh has the last Pages. Follow him into the reeds.': 'آخر الأوراق مع روح. اتبعه إلى القصب.',
  // arrivals
  'The Nahrawan, east of Baghdad, two days later': 'النهروان، شرق بغداد، بعد يومين',
  'Where the old canal broke its banks, the land became water and reed.': 'حيث فاض النهر القديم على ضفّتيه، صارت الأرض ماءً وقصبًا.',
  'The fishermen say Rawh paid for boats, and for silence.': 'يقول الصيّادون إن روحًا دفع ثمن القوارب، وثمن السكوت.',
  'Then someone here will talk.': 'إذن سيتكلّم أحدٌ هنا.',
  'Start with Marwan. His men hold the reed camp to the west.': 'ابدأ بمروان. رجاله يمسكون مخيّم القصب غربًا.',
  'Act V · Al-Karkh': 'الفصل الخامس · الكرخ', 'The market quarter outside the Round City, burned in the siege': 'حيّ الأسواق خارج المدينة المدوّرة، احترق في الحصار',
  'A year after the siege, al-Karkh is still black with ash.': 'بعد عام من الحصار، ما زالت الكرخ سوداء من الرماد.',
  'The scholars of the House of Wisdom will keep the Pages safe, if we can get them there.': 'سيحفظ علماء بيت الحكمة الأوراق، إن استطعنا إيصالها إليهم.',
  'Who holds them now?': 'من يمسكها الآن؟',
  'The buyer\'s men. Their captain is \'Utba. Start with \'Asim, in the burned suq.': 'رجال الشاري. قائدهم عتبة. ابدأ بعاصم، في السوق المحروقة.',
  // Rawh falls
  'Too late. I sent the last bundle up the canal at dawn.': 'فات الأوان. أرسلت آخر حزمة في النهر عند الفجر.',
  'To whom?': 'إلى من؟',
  'The buyer\'s men, in al-Karkh. They will burn it where the city can watch.': 'إلى رجال الشاري، في الكرخ. سيحرقونها حيث تراها المدينة.',
  'That night Rawh\'s own boats carried Salim and Ishaq up the canal to Baghdad.': 'في تلك الليلة حملت قوارب روح نفسه سالمًا وإسحاق في النهر إلى بغداد.',
  'The buyer\'s men will burn the Pages. Get there first.': 'رجال الشاري سيحرقون الأوراق. اسبقهم إليها.',
  // the finale
  'The Pages were still on the pyre. Not one had burned.': 'كانت الأوراق ما تزال على المحرقة. لم تحترق ورقة واحدة.',
  'Every page, brought home by a caravan guard and his brother.': 'كلّ ورقة، أعادها حارس قافلة وأخوه.',
  'We will copy them, ten times over, for ten cities.': 'سننسخها عشر مرّات، لعشر مدن.',
  'Then no one can burn them again.': 'إذن لن يستطيع أحد أن يحرقها بعد اليوم.',
  'That evening Salim went down to the canal.': 'في ذلك المساء نزل سالم إلى النهر.',
  'He set a lamp on the water for his brother, and one for each guard of the caravan.': 'وضع سراجًا على الماء لأخيه، وسراجًا لكلّ حارس من حرّاس القافلة.',
  'Jabir. It is done.': 'جابر. تمّ الأمر.',
  'We keep the account.': 'نحن نحفظ الحساب.',
  'Here ends the chronicle of Salim': 'هنا تنتهي سيرة سالم',
  // interiors and toasts
  'The Drowned Granary': 'الأهراء الغارقة', 'Grain stores the floods took': 'مخازن غلال أخذها الفيضان', 'Wade down into the drowned granary': 'انزل خائضًا إلى الأهراء الغارقة',
  'The Merchants\' Cellars': 'أقبية التجّار', 'Vaults under the burned suq': 'أقبية تحت السوق المحروقة', 'Go down into the merchants\' cellars': 'انزل إلى أقبية التجّار',
  'Caught in a net! Evade to tear free': 'علقت في شبكة! راوغ لتتحرّر', 'An engineer is raising a mangonel: break it': 'مهندس ينصب منجنيقاً: حطّمه', 'No camels underground': 'لا جِمال تحت الأرض', 'Kathir': 'كثير', 'Guards for hire': 'حُرّاس للأجرة', 'Guards for Hire': 'حُرّاس للأجرة', 'Ma\'n': 'معن', 'Dirar': 'ضرار', 'Spearman': 'رمّاح', 'Archer': 'رامٍ',
  'Spear and shield. Holds foes off you up close.': 'رمح وترس. يصدّ عنك الأعداء عن قرب.', 'A bowman. Shoots from range and keeps his distance.': 'رامٍ بالقوس. يرمي من بعيد ويحفظ مسافته.',
  'With you': 'معك', 'Hire': 'استأجر', 'Orders': 'الأوامر', 'Follow': 'اتبعني', 'Hold': 'اثبت', 'Attack': 'هاجم', 'Dismiss': 'اصرفه', 'joins you': 'ينضمّ إليك',
  'One fee, and he stays with you until you send him home. He cannot be killed. Give orders with his button or G.': 'أجرة واحدة، ويبقى معك حتى تصرفه. لا يُقتل. أعطه الأوامر بزرّه أو بالحرف G.', 'Not with foes so near': 'ليس والأعداء بهذا القرب', 'Mounted. You climb down by yourself when foes come.': 'ركبتَ. ستنزل وحدك حين يقترب الأعداء.', 'the reeds are full of his men!': 'القصب مليء برجاله!',
  // codex
  'The Nahrawan': 'النهروان',
  'A great canal east of the Tigris, older than Islam, that watered the lands from Samarra down past Baghdad. Its weirs and sluices were Sasanian work. Where its banks failed, the water spread into marsh and reed bed.': 'نهر عظيم شرقيّ دجلة، أقدم من الإسلام، كان يسقي الأرض من سامرّاء إلى ما بعد بغداد. سدوده ومَسَنّياته من عمل الساسانيين. وحيث انهارت ضفّتاه انتشر الماء أهوارًا ومنابت قصب.',
  'Marsh Boats': 'قوارب الأهوار',
  'In the reed country people travelled by water. Their long, narrow canoes were built of wood and sealed with bitumen, so they ride black and low. A man poles one standing, and it slips through channels too narrow for any other craft.': 'في بلاد القصب يتنقّل الناس على الماء. زوارقهم طويلة ضيّقة، من خشب مطليّ بالقار، فتبدو سوداء منخفضة. يدفعها الرجل بالمردي واقفًا، فتنساب في قنوات أضيق من أن يدخلها غيرها.',
  'Reed Halls': 'مضايف القصب',
  'The marsh people built great halls entirely of reed: bundles bent into arches, covered with woven mats. A large one could be raised in days and last for decades. Such halls appear on seals from Sumer, thousands of years before Salim.': 'بنى أهل الأهوار قاعات كبيرة من القصب وحده: حزم تُحنى أقواسًا وتُغطّى بالحُصر المنسوجة. يُرفع الكبير منها في أيام ويبقى عقودًا. وتظهر مثل هذه القاعات على أختام سومر، قبل سالم بآلاف السنين.',
  'The market suburb south-west of the Round City. Al-Mansur moved the markets out of his city in the 770s, and al-Karkh grew into the busiest market in the caliphate. In the siege of 812–813 the fighting and the fires ruined much of it.': 'حيّ الأسواق جنوب غرب المدينة المدوّرة. نقل المنصور الأسواق خارج مدينته في سبعينيات القرن الثامن، فصارت الكرخ أنشط سوق في الخلافة. وفي حصار ٨١٢–٨١٣ خرّب القتال والحرائق كثيرًا منها.',
  'The Paper-Sellers': 'الورّاقون',
  'The warraqin sold paper and copied books to order. By the end of the century the geographer al-Ya\'qubi counted over a hundred of their shops in one market of Baghdad. A book could be had in days, and a scholar could earn his bread by copying.': 'كان الورّاقون يبيعون الورق وينسخون الكتب حسب الطلب. وفي آخر القرن عدّ الجغرافي اليعقوبي أكثر من مئة دكّان لهم في سوق واحدة ببغداد. كان الكتاب يُنال في أيام، وكان العالِم يكسب خبزه بالنسخ.',
});

// ---------------------------------------------------------------- Round 16: side quests, bounties, world events
Object.assign(STORY_AR, {
  'Zayd': 'زيد', 'Nadr': 'النضر', 'Hudba': 'هدبة', 'Hilal': 'هلال', 'Jamil': 'جميل', 'Rabah': 'رباح', 'Bashshar': 'بشّار', '\'Abbad': 'عبّاد', 'Sa\'id': 'سعيد', 'Ma\'mar': 'معمر', 'Nu\'aym': 'نعيم',
  'Saqr': 'صقر', 'Bujayr': 'بجير', 'Kharija': 'خارجة', 'Murra': 'مرّة', 'Tarafa': 'طرفة', 'Zafir': 'ظافر',
  'Ka\'b': 'كعب', 'Hubaysh': 'حبيش', 'Suhaym': 'سحيم', 'Juwayn': 'جوين', 'Qatada': 'قتادة', 'Bistam': 'بسطام', 'Ruzayq': 'رزيق', '\'Umayr': 'عمير', 'Dirar': 'ضرار', 'Sharik': 'شريك',
  'Potter': 'فخّار', 'Scribe': 'كاتب', 'Camel trader': 'تاجر جمال', 'Boatman': 'ملّاح', 'Fisherman': 'صيّاد', 'Herdsman': 'راعي جواميس', 'Reed cutter': 'قاطع قصب', 'Dyer': 'صبّاغ', 'Paper-seller': 'ورّاق', 'Weaver': 'حائك', 'Carter': 'عربجي',
  'I will help.': 'سأساعدك.', 'Renown': 'السمعة', 'Bounty': 'مكافأة', 'Bounty Board': 'لوح المكافآت', 'Bounty taken': 'مكافأة مقبولة', 'Bounty complete': 'اكتملت المكافأة', 'dinars': 'دينار',
  'Done': 'تمّ', 'Taken': 'مقبولة', 'New bounties are posted every day.': 'تُعلَّق مكافآت جديدة كلّ يوم.', 'Read the bounty board': 'اقرأ لوح المكافآت', 'Take back the stolen goods': 'استرجع البضاعة المسروقة',
  'Recover stolen goods from a band on the roads.': 'استرجع بضاعة مسروقة من عصابة على الطرق.',
  'Tracking on the trail': 'الأثر يقود إلى هذه المهمّة', 'Trail follows the story': 'الأثر يتبع القصّة', 'The guards still watch it': 'ما زال الحرّاس يراقبونه',
  'World event': 'حدث في الأرض', 'Event complete': 'انتهى الحدث', 'The raiders got away.': 'فرّ المغيرون.',
  'the ruined qanats': 'القنوات المهدّمة', 'the kiln tunnels': 'أنفاق الأتون', 'the caravanserai storerooms': 'مخازن الخان', 'the drowned granary': 'الأهراء الغارقة', 'the merchants\' cellars': 'أقبية التجّار',
  'caravanserai': 'الخان', 'kiln yard': 'ساحة الأتون', 'reed camp': 'مخيّم القصب', 'fish racks': 'مناشر السمك', 'burned suq': 'السوق المحروقة', 'paper-sellers\' lane': 'سوق الورّاقين',
  // the Sawad
  'The Potter\'s Tools': 'أدوات الفخّار',
  'Hisham\'s knife-men took my kiln tools when they took the yard. Without them I am a man who knows how to make pots, and nothing else.': 'أخذ رجال هشام أدوات أتوني حين استولوا على الساحة. بدونها أنا رجل يعرف صنع الجرار ولا شيء غير ذلك.',
  'Recover Zayd\'s kiln tools from the deserters at the kiln yard.': 'استرجع أدوات زيد من الفارّين في ساحة الأتون.', 'Take the potter\'s tools': 'خذ أدوات الفخّار', 'Bundle of Kiln Tools': 'حزمة أدوات الأتون',
  'Bring the tools back to Zayd.': 'أعد الأدوات إلى زيد.', 'Your tools. The knife-men will not miss them.': 'أدواتك. لن يفتقدها رجال السكاكين.',
  'My father\'s scrapers! Come back in a month, guard. The first good jar from the new firing is yours.': 'مكاشط أبي! عد بعد شهر يا حارس. أوّل جرّة جيّدة من الشيّ الجديد لك.', 'Zayd is firing his kiln again.': 'عاد زيد يوقد أتونه.',
  'The Scribe\'s Ledger': 'دفتر الكاتب',
  'Brigands robbed me on the east road. They took my ledger: three years of every debt and sale in this village. Without it, honest men cannot prove what they paid.': 'سلبني قطّاع الطرق على الطريق الشرقي. أخذوا دفتري: ثلاث سنين من كلّ دين وبيع في القرية. بدونه لا يستطيع الشرفاء إثبات ما دفعوا.',
  'Drive off the brigands on the east road.': 'اطرد قطّاع الطرق عن الطريق الشرقي.', 'Find Nadr\'s ledger among the brigands\' plunder.': 'ابحث عن دفتر النضر بين غنائم قطّاع الطرق.', 'Take the ledger': 'خذ الدفتر', 'Nadr\'s Ledger': 'دفتر النضر',
  'Return the ledger to Nadr.': 'أعد الدفتر إلى النضر.', 'Every page there. You have saved a dozen families from paying twice.': 'كلّ الصفحات هنا. أنقذت عشرات العائلات من الدفع مرّتين.', 'The village\'s accounts are whole again.': 'عادت حسابات القرية كاملة.',
  'The Camel Trader\'s String': 'قطار تاجر الجمال',
  'My camels bolted when the deserters came. Two of them are standing in the desert east of the road, and the men who scared them are still out there.': 'هربت جمالي حين جاء الفارّون. اثنان منها واقفان في البرّية شرق الطريق، والرجال الذين أفزعوها ما زالوا هناك.',
  'Scatter the deserters near Hudba\'s camels.': 'فرّق الفارّين قرب جمال هدبة.', 'Lead Hudba\'s two camels back to the village.': 'قُد جملَي هدبة إلى القرية.', 'Tell Hudba his camels are home.': 'أخبر هدبة أن جماله عادت.',
  'Both of them! And not a scratch. Here: a trader pays his debts.': 'كلاهما! وبلا خدش. خذ: التاجر يوفي ديونه.', 'Hudba\'s camels are safe.': 'جمال هدبة في أمان.',
  'Jabir\'s Spear': 'رمح جابر',
  'The villagers found the place on the dunes where the caravan fell. Jabir\'s spear is still there. You should be the one to bring it home.': 'وجد أهل القرية الموضع على الكثبان حيث سقطت القافلة. رمح جابر ما زال هناك. يجب أن تكون أنت من يعيده.',
  'Go to the dunes north of the village, where the caravan fell.': 'اذهب إلى الكثبان شمال القرية، حيث سقطت القافلة.', 'Kneel by the spear': 'اجثُ عند الرمح', 'Tell Ishaq you have brought it home.': 'أخبر إسحاق أنك أعدته.',
  'I have it. I will carry it to Baghdad, and home after that.': 'معي. سأحمله إلى بغداد، ثم إلى البيت.', 'Then he finishes the journey with you.': 'إذن يُتمّ الرحلة معك.', 'Salim carries his brother\'s spear.': 'سالم يحمل رمح أخيه.',
  'The sand had nearly covered it.': 'كاد الرمل يغطّيه.', 'I said I would bring it back, brother. This too.': 'قلتُ إني سأعيده يا أخي. وهذا أيضًا.', 'He carried the spear back to the village.': 'حمل الرمح عائدًا إلى القرية.',
  'Jabir\'s Spearhead': 'سنان جابر',
  // the marshes
  'The Boatman\'s Son': 'ابن الملّاح',
  'Rawh\'s men took my boy Saqr to make me carry their boats. They keep him in a hut on the west causeway. He is eleven.': 'أخذ رجال روح ابني صقرًا ليجبروني على حمل قواربهم. يحبسونه في كوخ على الجسر الغربي. عمره أحد عشر عامًا.',
  'Free Saqr from Rawh\'s men on the west causeway.': 'حرّر صقرًا من رجال روح على الجسر الغربي.', 'Bring Saqr home to his father.': 'أعد صقرًا إلى أبيه.', 'Speak with Hilal.': 'تحدّث إلى هلال.',
  'Saqr! ... Thank you. My boat is yours, whenever you need it.': 'صقر! ... شكرًا لك. قاربي لك متى احتجته.', 'Saqr is home.': 'عاد صقر إلى البيت.',
  'Cut Nets': 'الشِّباك المقطوعة',
  'Every night someone cuts our nets on the east causeway. Rawh\'s ambushers, hiding in the reeds. A village that cannot fish cannot eat.': 'كلّ ليلة يقطع أحدهم شباكنا على الجسر الشرقي. كمائن روح المختبئة في القصب. القرية التي لا تصطاد لا تأكل.',
  'Root the ambushers out of the reeds on the east causeway.': 'اقتلع الكمائن من القصب على الجسر الشرقي.', 'Tell Jamil the reeds are clear.': 'أخبر جميلًا أن القصب صار آمنًا.',
  'Then tonight we fish. Take some of the catch money. You earned it.': 'إذن نصطاد الليلة. خذ شيئًا من ثمن الصيد. استحققته.', 'The fishermen mend their nets in peace.': 'الصيّادون يرقعون شباكهم في سلام.',
  'The Strayed Buffalo': 'الجاموسة الشاردة',
  'My best buffalo swam off in the night and came ashore by the reed camp road. Rawh\'s men have her tied, and they are arguing about who eats her.': 'سبحت أفضل جواميسي في الليل وخرجت عند طريق مخيّم القصب. رجال روح ربطوها، ويتجادلون في من يأكلها.',
  'Drive the men away from Rabah\'s buffalo, south of the reed camp.': 'اطرد الرجال عن جاموسة رباح، جنوب مخيّم القصب.', 'Lead the buffalo back to Rabah.': 'قُد الجاموسة إلى رباح.', 'Speak with Rabah.': 'تحدّث إلى رباح.',
  'There she is, the old queen. Her milk feeds three families. Take this, and my thanks.': 'ها هي الملكة العجوز. حليبها يطعم ثلاث عائلات. خذ هذا، ولك شكري.', 'The buffalo is home.': 'عادت الجاموسة.',
  'The Debt Ledger': 'دفتر الديون',
  'Rawh lent the whole village money in the bad year, and wrote it all down. His men use that book to take our boats and our reed. Burn it, and we are free.': 'أقرض روح القرية كلّها في سنة القحط، وكتب كلّ شيء. رجاله يأخذون بذلك الدفتر قواربنا وقصبنا. احرقه نصبح أحرارًا.',
  'Take Rawh\'s debt ledger from his clerk\'s guards on the south-east causeway.': 'خذ دفتر ديون روح من حرّاس كاتبه على الجسر الجنوبي الشرقي.', 'Take the debt ledger': 'خذ دفتر الديون', 'Rawh\'s Debt Ledger': 'دفتر ديون روح',
  'Bring the ledger to Bashshar.': 'أحضر الدفتر إلى بشّار.', 'Into the fire with it. ... There. My grandchildren will never know what was owed.': 'إلى النار. ... هكذا. لن يعرف أحفادي ما كان علينا.', 'The village owes Rawh nothing.': 'القرية لا تدين لروح بشيء.',
  // al-Karkh
  'The Dyers\' Vats': 'أحواض الصبّاغين',
  'Looters squat in my dye yard by the north lane. They broke half the vats looking for coin. Indigo is worth more than coin, if they only knew.': 'لصوص يقيمون في ساحة صباغتي عند الدرب الشمالي. كسروا نصف الأحواض بحثًا عن المال. النيلة أثمن من المال، لو كانوا يعلمون.',
  'Clear the looters out of the dye yard on the north lane.': 'اطرد اللصوص من ساحة الصباغة على الدرب الشمالي.', 'Tell \'Abbad his yard is clear.': 'أخبر عبّادًا أن ساحته صارت خالية.',
  'Then the blue comes back to al-Karkh. Take this. A dyer remembers his friends.': 'إذن يعود الأزرق إلى الكرخ. خذ هذا. الصبّاغ لا ينسى أصدقاءه.', '\'Abbad\'s vats are filling again.': 'أحواض عبّاد تمتلئ من جديد.',
  'The Copyist\'s Pens': 'أقلام الناسخ',
  'The buyer\'s men took my pens and my inks, and my best paper, and stacked them in their camp on the east lane. Without pens I cannot copy, and without copying I cannot eat.': 'أخذ رجال الشاري أقلامي وأحباري وأجود ورقي، وكدّسوها في معسكرهم على الدرب الشرقي. بلا أقلام لا أنسخ، وبلا نسخ لا آكل.',
  'Take back Sa\'id\'s pens and inks from the camp on the east lane.': 'استرجع أقلام سعيد وأحباره من المعسكر على الدرب الشرقي.', 'Take the pens and inks': 'خذ الأقلام والأحبار', 'Reed Pens and Inks': 'أقلام القصب والأحبار',
  'Bring the pens to Sa\'id.': 'أحضر الأقلام إلى سعيد.', 'My good reeds, and the iron-gall ink! I will copy you anything you like, for free, for as long as I live.': 'أقلامي الجيّدة، والحبر العفصي! سأنسخ لك ما تشاء، بلا مقابل، ما حييت.', 'Sa\'id is copying again.': 'عاد سعيد ينسخ.',
  'Lost in the Ruins': 'تائهون في الخرائب',
  'My two children went looking for our old house, south of the canal. They have not come back, and the lanes there are full of the buyer\'s men.': 'ذهب ولداي يبحثان عن بيتنا القديم جنوب النهر. لم يعودا، والدروب هناك مليئة برجال الشاري.',
  'Find Ma\'mar\'s children south of the bridge, and drive off the men around them.': 'اعثر على ولدَي معمر جنوب الجسر، واطرد الرجال من حولهما.', 'Lead the two children back to the khan.': 'قُد الولدين إلى الخان.', 'Speak with Ma\'mar.': 'تحدّث إلى معمر.',
  'You found them. You found them both. I have nothing worth giving you, but take this.': 'وجدتهما. وجدتهما كليهما. لا أملك شيئًا يليق بك، لكن خذ هذا.', 'The children are home.': 'عاد الولدان.',
  'The Bridge Toll': 'مكس الجسر',
  'The buyer\'s men stand on the north bridge and take a dirham from everyone who crosses. From widows, from children, from me. Someone should make them stop.': 'يقف رجال الشاري على الجسر الشمالي ويأخذون درهمًا من كلّ عابر. من الأرامل، من الأطفال، منّي. على أحد أن يوقفهم.',
  'Throw the toll-takers off the north bridge.': 'ألقِ جباة المكس عن الجسر الشمالي.', 'Tell Nu\'aym the bridge is free.': 'أخبر نعيمًا أن الجسر صار حرًّا.',
  'Free! I will tell every carter in the quarter whose name to bless. Here, for the road.': 'حرّ! سأخبر كلّ عربجي في الحيّ باسم من يدعو له. خذ، للطريق.', 'Anyone may cross the north bridge.': 'يعبر الجسر الشمالي من شاء.',
  // world events
  'A caravan under attack': 'قافلة تحت الهجوم', 'Help the caravan on the road before the raiders take it.': 'أنجد القافلة على الطريق قبل أن يأخذها المغيرون.',
  'A well being fouled': 'بئر تُفسَد', 'Stop the deserters fouling the well by the kiln road.': 'أوقف الفارّين الذين يفسدون البئر عند طريق الأتون.',
  'An ambush on the water': 'كمين على الماء', 'Fishermen are ambushed on the west causeway. Break the ambush.': 'صيّادون في كمين على الجسر الغربي. اكسر الكمين.',
  'The reed stacks are burning': 'أكوام القصب تحترق', 'Raiders fired the reed stacks on the east causeway. Drive them off.': 'أحرق المغيرون أكوام القصب على الجسر الشرقي. اطردهم.',
  'A granary on fire': 'أهراء تحترق', 'Looters set a granary alight on the east lane. Stop them before they carry off the grain.': 'أشعل اللصوص أهراءً على الدرب الشرقي. أوقفهم قبل أن يحملوا الحنطة.',
  'A grain convoy ambushed': 'قافلة حنطة في كمين', 'The buyer\'s men are robbing a grain convoy near the north bridge.': 'رجال الشاري يسلبون قافلة حنطة قرب الجسر الشمالي.',
  'Water Buffalo': 'الجاموس',
  'The marsh people kept water buffalo for milk, butter and dung fuel. The animals spend the hot hours almost under water and graze on the reed beds. A family\'s herd was its wealth, passed from parent to child.': 'ربّى أهل الأهوار الجاموس للحليب والزبد ووقود الروث. تقضي الحيوانات ساعات الحرّ غارقة في الماء تقريبًا وترعى في منابت القصب. كان قطيع العائلة ثروتها، يُورَث من الأب إلى الابن.',
  'Someone is waiting for this.': 'أحدهم ينتظر هذا.', 'Carried the whole road home.': 'حُمل طوال الطريق إلى البيت.',
  // Round 17: dungeons, contracts, renown
  'The Old Cistern': 'الصهريج القديم', 'The water rises and falls here. Keep to the stone landings.': 'يعلو الماء هنا ويهبط. الزم المصاطب الحجرية.', 'Go down into the old cistern': 'انزل إلى الصهريج القديم',
  'The Lower Kilns': 'الأتاتين السفلى', 'Vents breathe hot smoke. Smoke hides you, and burns.': 'تنفث الفتحات دخانًا حارًّا. الدخان يخفيك، ويحرق.', 'Descend into the lower kilns': 'انزل إلى الأتاتين السفلى',
  'The Granary Vaults': 'أقبية الأهراء', 'Strike a grain stack to bring it down on your foes.': 'اضرب كومة الحبّ لتُسقطها على أعدائك.', 'Go down into the granary vaults': 'انزل إلى أقبية الأهراء',
  'The Reed Warren': 'متاهة القصب', 'Fire runs from hut to hut. Watch for smoke.': 'تجري النار من كوخ إلى كوخ. راقب الدخان.', 'Enter the reed warren': 'ادخل متاهة القصب',
  'The Salt Workings': 'مقالع الملح', 'Light through the roof cracks dazzles. Step out of it.': 'الضوء من شقوق السقف يُبهر. ابتعد عنه.', 'Go down into the salt workings': 'انزل إلى مقالع الملح',
  'The Palace Cellars': 'سراديب القصر', 'Cracked tiles hide triggers. Foes set them off too.': 'تخفي البلاطات المشقوقة فخاخًا. يطلقها الأعداء أيضًا.', 'Go down into the palace cellars': 'انزل إلى سراديب القصر',
  'the old cistern': 'الصهريج القديم', 'the lower kilns': 'الأتاتين السفلى', 'the granary vaults': 'أقبية الأهراء', 'the reed warren': 'متاهة القصب', 'the salt workings': 'مقالع الملح', 'the palace cellars': 'سراديب القصر',
  'Wahb': 'وهب', 'Bujayr': 'بجير', 'Hurayth': 'حريث', 'Sinan': 'سنان', 'Unays': 'أنيس', 'Habib': 'حبيب',
  'The water is rising': 'الماء يرتفع', 'Dazzled!': 'انبهرت!',
  'Read the captains\' contracts': 'اقرأ عقود القادة', 'Captains\' Contracts': 'عقود القادة', 'Captain': 'قائد', 'Ground': 'الموضع', 'Conditions': 'الشروط', 'Contract': 'عقد',
  'Take the contract': 'اقبل العقد', 'Contract fulfilled': 'وُفّي العقد', 'Foes level': 'مستوى الأعداء', 'extra treasure': 'كنز إضافي',
  'Pick a captain, the ground, and up to three conditions. Harder conditions pay more. Contracts never run out.': 'اختر قائدًا والموضع وحتى ثلاثة شروط. الشروط الأصعب تدفع أكثر. العقود لا تنفد.',
  'No contracts yet. Defeat a named captain in the field or in a dungeon, and the board will post a contract for his return.': 'لا عقود بعد. اهزم قائدًا مسمّى في البرّية أو في سرداب، فيُعلَّق على اللوح عقد لعودته.',
  'Hardened': 'صُلب', 'Foes have 40% more life': 'للأعداء حياة أكثر بـ40%', 'Swift': 'سريع', 'Foes move 20% faster': 'يتحرّك الأعداء أسرع بـ20%', 'Ironclad': 'مدرّع', 'Foes carry shields': 'يحمل الأعداء تروسًا',
  'Naft Seeps': 'نزّ النفط', 'Burning naft seeps from the floor': 'نفط مشتعل ينزّ من الأرض', 'Bad Air': 'هواء فاسد', 'Your maximum life is 25% lower': 'حياتك القصوى أقلّ بـ25%',
  'Gilded': 'مذهّب', 'Chests hold more treasure': 'في الصناديق كنز أكثر', 'Veterans': 'محاربون قدامى', 'Foes are two levels higher': 'الأعداء أعلى بمستويين',
  'Renown is earned from bounties, events, side quests and contracts. What you learn here stays with you.': 'تُنال السمعة من المكافآت والأحداث والمهامّ الجانبية والعقود. ما تتعلّمه هنا يبقى معك.',
  'Learn': 'تعلّم', 'Mastered': 'أُتقن',
  'Open Hand': 'اليد المبسوطة', '+10% dinars found': '+10% من الدنانير', 'Deep Flask': 'القربة العميقة', '+1 sherbet carried': '+1 شربة تُحمل',
  'Light Step': 'الخطوة الخفيفة', '+8% evade distance': '+8% مسافة المراوغة', 'Keen Eye': 'العين الحادّة', '+4% chance a magic find is rare': '+4% أن يصير الغنم السحري نادرًا',
  'Hardy': 'الجَلَد', '+5% maximum life': '+5% من الحياة القصوى', 'Whetstone': 'المِسَنّ', '+4% damage': '+4% ضرر',
  'Road-worn': 'ابن الطريق', '+3% movement speed': '+3% سرعة الحركة', 'Quick Study': 'سريع التعلّم', '+8% experience': '+8% خبرة',
  'Layered Mail': 'الدرع المضاعف', '+6% armour': '+6% درع', 'Second Wind': 'النفس الثاني', '+1 life regained per second': '+1 حياة تُستعاد كلّ ثانية',
  'Rosewater': 'ماء الورد', 'Sherbet heals 15% more': 'الشربة تشفي أكثر بـ15%', 'Captain-Hunter': 'صائد القادة', '+8% damage to captains and elites': '+8% ضرر على القادة والنخبة',
  // Round 18: skills, aspects, sets, gems, stash
  'A Fifth Skill': 'مهارة خامسة', 'A new skill slot opens. Choose your skills in Disciplines.': 'انفتحت خانة مهارة جديدة. اختر مهاراتك في الفنون.', 'New skill': 'مهارة جديدة',
  'Skills': 'المهارات', 'Tap a slot, then a skill to put in it': 'المس خانة، ثم مهارة لتضعها فيها', 'Now pick a skill for this slot': 'اختر الآن مهارة لهذه الخانة', 'A fifth slot opens at level': 'تنفتح خانة خامسة في المستوى', 'Level': 'المستوى', 'level': 'المستوى',
  'Rallying Cry': 'صيحة الحشد', '+25% damage and +20 armour for 6 seconds': '+25% ضرر و+20 درع لستّ ثوانٍ', 'Sweeping Cut': 'الضربة الكاسحة', 'A wide cut through every foe in front of you': 'ضربة عريضة تشقّ كلّ عدوّ أمامك',
  'Pinning Shot': 'رمية التثبيت', 'A heavy arrow that pins a foe in place for 2.5 seconds': 'سهم ثقيل يثبّت العدوّ مكانه ثانيتين ونصفًا', 'Scatter Volley': 'الرشقة المتفرّقة', 'Seven arrows loosed in a wide fan': 'سبعة أسهم تنطلق في مروحة عريضة',
  'Naft Mortar': 'قاذف النفط', 'Three pots fall in turn on the target ground': 'ثلاث جرار تسقط تباعًا على الموضع', 'Burning Brand': 'الجمرة المتّقدة', 'For 8 seconds every hit sets the foe alight': 'لثماني ثوانٍ تُشعل كلّ ضربة العدوّ',
  'Death Mark': 'علامة الهلاك', 'Marked foe takes 35% more damage for 8 seconds': 'العدوّ المعلَّم ينال ضررًا أكثر بـ35% لثماني ثوانٍ', 'Blinding Powder': 'ذرور العمى', 'A cloud of powder that dazes every foe in front of you': 'سحابة ذرور تُدهش كلّ عدوّ أمامك',
  'Chipped Ruby': 'ياقوت مثلوم', 'Flawless Ruby': 'ياقوت صافٍ', 'Royal Ruby': 'ياقوت ملكي', 'Chipped Lapis': 'لازورد مثلوم', 'Flawless Lapis': 'لازورد صافٍ', 'Royal Lapis': 'لازورد ملكي',
  'Chipped Carnelian': 'عقيق مثلوم', 'Flawless Carnelian': 'عقيق صافٍ', 'Royal Carnelian': 'عقيق ملكي',
  'Empty socket': 'تجويف فارغ', 'No socket': 'بلا تجويف', 'Cut a socket': 'احفر تجويفًا', 'Remove gem': 'انزع الحجر', 'Combine 3': 'ادمج 3', 'worn': 'ملبوس', 'A socket is cut': 'حُفر التجويف', 'Not enough dinars': 'لا دنانير كافية',
  'No gems yet. They come from dungeon chests, contracts and captains.': 'لا أحجار بعد. تأتي من صناديق السراديب والعقود والقادة.', 'No rare, set or legendary items to work on.': 'لا قطع نادرة أو طقمية أو أسطورية للعمل عليها.',
  'Bishr can cut a socket into a rare, set or legendary item, and set a gem in it. In a weapon: ruby adds damage, lapis fire damage, carnelian critical strike. In armour or jewellery: ruby adds life, lapis armour and guards against burning, carnelian finds more dinars.': 'يحفر بشر تجويفًا في القطعة النادرة أو الطقمية أو الأسطورية ويرصّع فيه حجرًا. في السلاح: الياقوت يزيد الضرر، واللازورد ضرر النار، والعقيق الضربة القاضية. في الدرع والحليّ: الياقوت يزيد الحياة، واللازورد الدرع ويقي الحريق، والعقيق يجد دنانير أكثر.',
});

// ---------------------------------------------------------------- Round 20: Act VI, the river quays
Object.assign(STORY_AR, {
  'Benchmark': 'اختبار الأداء', 'frames per second': 'إطار في الثانية', 'Slowest 1%': 'أبطأ ١٪', 'Frame time': 'زمن الإطار', 'Draw calls': 'نداءات الرسم', 'Apply suggestion': 'طبّق الاقتراح', 'Applied': 'طُبّق',
  'Start the benchmark from the overworld, outside a fight.': 'ابدأ اختبار الأداء من الخارج، بعيدًا عن القتال.', 'Run benchmark (30 s)': 'شغّل اختبار الأداء (٣٠ ث)', 'A short fly-through and fight that measures this device and suggests settings.': 'جولة قصيرة وقتال يقيسان هذا الجهاز ويقترحان الإعدادات.',
  'Runs smoothly. Keep High quality and Smooth sharpness.': 'يعمل بسلاسة. أبقِ الجودة العالية والحدّة الناعمة.', 'Good. High quality with Balanced sharpness gives headroom in big fights.': 'جيّد. الجودة العالية مع الحدّة المتوازنة تمنح هامشًا في المعارك الكبيرة.',
  'Playable. Fast sharpness will steady the frame rate.': 'قابل للعب. الحدّة السريعة ستثبّت معدّل الإطارات.', 'Heavy for this device. Low quality and Fast sharpness are recommended.': 'ثقيل على هذا الجهاز. يُنصح بالجودة المنخفضة والحدّة السريعة.',
  'Forge': 'اصنع', 'Property': 'الخاصيّة', 'Forge it': 'اطرقه', 'Forged': 'طُرق',
  'Bishr forges a rare to order: pick what, and the one property you cannot do without. He rolls it in the top third; the rest is up to the fire.': 'يطرق بشر قطعة نادرة حسب الطلب: اختر ما تريد، والخاصيّة الواحدة التي لا غنى لك عنها. يجعلها في أعلى ثلثها، والباقي على النار.',
  'Damage': 'الضرر', 'Maximum Life': 'أقصى الحياة', 'Maximum Resource': 'أقصى المورد', 'Critical Strike Chance': 'فرصة الضربة القاضية', 'Attack Speed': 'سرعة الهجوم', 'Life per Hit': 'حياة لكلّ ضربة',
  'Movement Speed': 'سرعة الحركة', 'Naft (Fire) Damage': 'ضرر النفط (النار)', 'Resource Regeneration/s': 'تجدّد المورد/ث', 'Cooldowns': 'أزمنة التبريد', 'Sherbet Healing': 'شفاء الشراب', 'Sherbet Carried': 'الشراب المحمول', 'Sherbet restores Resource': 'الشراب يعيد المورد',
  'Girdle of the Water-Carrier': 'منطقة السقّاء', 'Cloth Sash': 'زنّار قماش', 'Leather Mintaqa': 'منطقة جلد', 'Studded Mintaqa': 'منطقة مرصّعة',
  'Siege Trials': 'محن الحصار', 'Siege Trial': 'محنة الحصار', 'Read the siege trials': 'اقرأ لوح محن الحصار', 'Tier': 'الدرجة', 'Time': 'الوقت', 'a gem': 'حجر كريم', 'Your best': 'أفضل وقت لك',
  'Begin the trial': 'ابدأ المحنة', 'Your last trials': 'محنك الأخيرة', 'No trials run yet.': 'لم تخض أيّ محنة بعد.', 'Trial abandoned': 'تُركت المحنة', 'Trial cleared': 'اجتزت المحنة', 'Too slow': 'بطيء جدًّا', 'New best!': 'أفضل وقت جديد!', 'opened': 'فُتحت',
  'Clear the rooms and break the captain before time runs out.': 'طهّر الغرف واكسر القائد قبل أن ينفد الوقت.',
  'Five rooms from every dungeon in the chronicle, and a captain at the end. Break him inside four minutes to clear the tier and open the next.': 'خمس غرف من كلّ سراديب الحكاية، وقائد في آخرها. اكسره في أقلّ من أربع دقائق لتجتاز الدرجة وتفتح التي تليها.',
  'Hudhayl': 'هذيل', 'Sharik': 'شريك', 'Muzahim': 'مزاحم', 'Zufar': 'زفر', 'Labid': 'لبيد', 'Mutarrif': 'مطرّف',
  'The River Quays': 'الشطّ', 'The river quays': 'الشطّ', 'The Quay Khan': 'خان الشطّ', 'The Warehouses': 'المخازن',
  'Find Bilal among the river warehouses': 'اعثر على بلال بين مخازن النهر',
  'Free the copyists\' boat from Mus\'ab at the boatyard': 'حرّر قارب النُّسّاخ من مصعب في دار الصناعة',
  'Face Ghanim at the bridge of boats': 'واجه غانمًا عند جسر السفن',
  'Bilal': 'بلال', 'Mus\'ab': 'مصعب', 'Ghanim': 'غانم', 'Kulayb': 'كليب', 'Dhuhl': 'ذهل', 'Sawwar': 'سوّار', 'Hubaysh': 'حبيش', 'Mudrik': 'مدرك', 'Qurra': 'قرّة',
  'Yazid': 'يزيد', 'Ma\'qil': 'معقل', 'Jundub': 'جندب', 'Wasil': 'واصل', 'Ferryman': 'معدّاوي', 'Shipwright': 'صانع سفن', 'Porter': 'حمّال', 'Copyist': 'ناسخ',
  'Ghanim pays us to hold the river. Mus\'ab keeps the copyists\' boat at the yard.': 'غانم يدفع لنا لنمسك النهر. ومصعب يحتجز قارب النُّسّاخ في دار الصناعة.',
  'The Boatyard': 'دار الصناعة', 'Free the copyists\' boat from Mus\'ab.': 'حرّر قارب النُّسّاخ من مصعب.',
  'The boat is yours. But Ghanim cut the bridge, and he waits at its foot.': 'القارب لك. لكنّ غانمًا قطع الجسر، وهو ينتظر عند رأسه.',
  'The Bridge of Boats': 'جسر السفن', 'Ghanim will not let the copies sail. Face him at the bridge.': 'لن يدع غانم النُّسَخ تُبحر. واجهه عند الجسر.',
  'Copies, guard? Then I will sink every boat on the river.': 'نُسَخ يا حارس؟ إذن سأُغرق كلّ قارب في النهر.',
  'The buyer\'s steward': 'وكيل المشتري', 'Crossbows! Hold the bridge!': 'القسيّ! أمسكوا الجسر!',
  'No one sails tonight. Not you, not your paper.': 'لن يُبحر أحد الليلة. لا أنت ولا ورقك.',
  'Ghanim fires the bridge. Stay inside the ring.': 'غانم يُشعل الجسر. ابقَ داخل الحلقة.',
  'Hakam\'s copyists worked through the night. The first copies are to go downriver, to Wasit and Basra, at dawn.': 'عمل نُسّاخ الحكم طوال الليل. النُّسَخ الأولى تنحدر في النهر إلى واسط والبصرة عند الفجر.',
  'The buyer\'s steward, Ghanim, holds the quays. Bilal keeps the warehouses and Mus\'ab has taken the copyists\' boat at the yard.': 'وكيل المشتري، غانم، يمسك الشطّ. بلال يحرس المخازن، ومصعب استولى على قارب النُّسّاخ في دار الصناعة.',
  'Ten cities, Salim. Once the copies are on the water, no one can gather them all again.': 'عشر مدن يا سالم. متى صارت النُّسَخ على الماء، لن يجمعها أحد كلّها أبدًا.',
  // places and dungeons
  'The Customs Vaults': 'أقبية المكوس', 'Bonded stores under the river warehouses': 'مخازن محجوزة تحت مخازن النهر', 'Go down into the customs vaults': 'انزل إلى أقبية المكوس',
  'The Flooded Undercroft': 'السرداب المغمور', 'The river seeps in and out of these vaults. Keep to the stone landings.': 'يتسرّب النهر إلى هذه الأقبية ويخرج منها. الزم المصاطب الحجرية.', 'Go down into the flooded undercroft': 'انزل إلى السرداب المغمور',
  'The Wharf Vaults': 'أقبية المرفأ', 'Strike a stack of bales to bring it down on your foes.': 'اضرب كومة الأحمال لتسقطها على أعدائك.', 'Go down into the wharf vaults': 'انزل إلى أقبية المرفأ',
  'the customs vaults': 'أقبية المكوس', 'warehouses': 'المخازن', 'boatyard': 'دار الصناعة',
  // codex
  'The Tigris at Baghdad': 'دجلة عند بغداد',
  'Baghdad was built on both banks of the Tigris, where the river runs close to the Euphrates and canals such as the Sarat and the \'Isa join the two. Boats brought grain, dates, timber and goods of the Gulf upriver from Basra to the quays of al-Karkh, and others came down from Mosul and the north.': 'بُنيت بغداد على ضفّتي دجلة، حيث يقترب النهر من الفرات وتصل بينهما أنهار كالصراة وعيسى. كانت السفن تحمل الحبوب والتمر والخشب وبضائع الخليج صاعدةً من البصرة إلى شطّ الكرخ، وأخرى تنحدر من الموصل والشمال.',
  'The Bridges of Boats': 'جسور السفن',
  'The two halves of Baghdad were joined by pontoon bridges: boats moored side by side and chained, with a road of planks laid over them. Al-Mansur had one laid when he founded the city, and later writers count two or three. A bridge of boats could be cut in an hour, which made them prizes in any fighting in the city.': 'كان شطرا بغداد يتّصلان بجسور من السفن: قوارب مربوطة جنبًا إلى جنب بالسلاسل، فوقها طريق من الألواح. أمر المنصور بعقد واحد منها حين بنى المدينة، ويعدّ الكتّاب بعده اثنين أو ثلاثة. وكان جسر السفن يُقطع في ساعة، فكان غنيمة في كلّ قتال في المدينة.',
  'River Craft': 'سفن النهر',
  'Tigris craft ran from small skiffs to broad cargo barges with a cabin aft and a single sail. They were rowed or hauled upstream and carried down by the current. Their seams were caulked with bitumen, much of it from the springs near Hit on the Euphrates.': 'كانت سفن دجلة من الزوارق الصغيرة إلى السفن العريضة للحمل، لها مقصورة في المؤخّرة وشراع واحد. كانت تُجذَّف أو تُجرّ صعودًا ويحملها التيّار نزولًا. وكانت شقوقها تُطلى بالقار، وأكثره من عيون هيت على الفرات.',
  'Copies and Copyists': 'النُّسَخ والنُّسّاخ',
  'A book was made by hand: a scholar\'s students or a warraq copied it, more and more often onto paper rather than costly parchment. A work that existed in many copies, in many cities, could no longer be destroyed by any one man, and scholars sent what they valued far and wide.': 'كان الكتاب يُصنع باليد: ينسخه تلاميذ العالم أو ورّاق، وعلى الورق أكثر فأكثر بدل الرَّقّ الغالي. والكتاب الذي توجد منه نسخ كثيرة في مدن كثيرة لا يقدر رجل واحد على إتلافه، فكان العلماء يبعثون بما يعزّ عليهم إلى كلّ مكان.',
  // side quests
  'The Ferryman\'s Skiff': 'زورق المعدّاوي', 'Pitch for the Hulls': 'قار للبدن', 'The Porters\' Wages': 'أجور الحمّالين', 'The Copyist\'s Daughter': 'ابنة الناسخ',
  'Ghanim\'s men took my skiff at the north jetty. They use it to row out and search the barges. Forty years I have ferried this river, and now I stand on the bank like a stranger.': 'أخذ رجال غانم زورقي عند الرصيف الشمالي. يجذّفون به ليفتّشوا السفن. أربعون سنة وأنا أعبر هذا النهر، والآن أقف على الضفّة كالغريب.',
  'Drive Ghanim\'s men off the north jetty.': 'اطرد رجال غانم عن الرصيف الشمالي.', 'Tell Yazid his skiff is free.': 'أخبر يزيد أنّ زورقه حرّ.',
  'My skiff! Then I will row the copyists across myself, if they ask. Take this, with an old man\'s thanks.': 'زورقي! إذن سأعبر بالنُّسّاخ بنفسي إن طلبوا. خذ هذا مع شكر شيخ كبير.', 'Yazid ferries the river again.': 'يزيد يعبر النهر من جديد.',
  'Without pitch my hulls leak like sieves. Ghanim\'s engineers carried off every jar of it from the yard, to their camp inland. They want the boats to sink.': 'بلا قار تسرّب سفني كالغرابيل. حمل مهندسو غانم كلّ جرّة منه من دار الصناعة إلى معسكرهم في الداخل. يريدون للسفن أن تغرق.',
  'Take back the pitch jars from the engineers\' camp inland.': 'استعد جرار القار من معسكر المهندسين في الداخل.', 'Take the pitch jars': 'خذ جرار القار', 'Jars of Pitch': 'جرار القار', 'Bring the pitch to Ma\'qil.': 'احمل القار إلى معقل.',
  'Good black pitch from Hit. The copyists\' boat will ride dry all the way to Basra.': 'قار أسود جيّد من هيت. سيمضي قارب النُّسّاخ جافًّا حتى البصرة.', 'Ma\'qil\'s hulls are tight again.': 'سفن معقل محكمة من جديد.',
  'We carried bales for Bilal\'s masters all season, and when we asked for our wages his toll-men beat us off the quay road. Every porter on the river is owed.': 'حملنا الأحمال لأسياد بلال طوال الموسم، ولمّا طلبنا أجورنا ضربنا جُباته وطردونا عن طريق الشطّ. كلّ حمّال على النهر له دَين.',
  'Break the toll-men on the quay road by the warehouses.': 'اكسر الجباة على طريق الشطّ عند المخازن.', 'Tell Jundub the road is open.': 'أخبر جندبًا أنّ الطريق مفتوح.',
  'The road is ours again. The porters made a purse for whoever did this. It is yours.': 'الطريق لنا من جديد. جمع الحمّالون صرّة لمن فعل هذا. هي لك.', 'The porters are paid.': 'نال الحمّالون أجورهم.',
  'My daughter carries my finished quires to Hakam each night. Last night she did not come home. Someone saw her hiding in the old lanes to the south-west.': 'ابنتي تحمل كراريسي المنسوخة إلى الحكم كلّ ليلة. البارحة لم تعد إلى البيت. رآها أحدهم مختبئة في الأزقّة القديمة جنوبًا غربًا.',
  'Find Wasil\'s daughter in the south-west lanes and drive off the men around her.': 'اعثر على ابنة واصل في الأزقّة الجنوبية الغربية واطرد الرجال من حولها.', 'Lead her back to the khan.': 'قُدها إلى الخان.', 'Speak with Wasil.': 'كلّم واصلًا.',
  'And the quires are safe in her bag, every one. You have saved two things I love tonight.': 'والكراريس سالمة في حقيبتها، كلّها. أنقذت الليلة شيئين أحبّهما.', 'Wasil\'s daughter is home.': 'ابنة واصل في البيت.',
  'A warehouse on fire': 'مخزن يحترق', 'Ghanim\'s men have fired a warehouse by the quay road. Drive them off before it spreads.': 'أشعل رجال غانم مخزنًا قرب طريق الشطّ. اطردهم قبل أن تنتشر النار.',
  'Porters ambushed': 'حمّالون في كمين', 'A file of porters is being robbed on the quay road, south of the warehouses.': 'صفّ من الحمّالين يُسلب على طريق الشطّ جنوب المخازن.',
  // scenes
  'Act VI · The River Quays': 'الفصل السادس · الشطّ', 'The quays of al-Karkh on the Tigris, at dawn': 'شطّ الكرخ على دجلة، عند الفجر',
  'Everything Baghdad eats or sells comes up this river, or goes down it.': 'كلّ ما تأكله بغداد أو تبيعه يصعد في هذا النهر أو ينحدر فيه.',
  'Hakam\'s copyists worked all night. The first copies sail at dawn, for Wasit and Basra.': 'عمل نُسّاخ الحكم الليل كلّه. النُّسَخ الأولى تُبحر عند الفجر إلى واسط والبصرة.',
  'And the buyer?': 'والمشتري؟', 'His steward, Ghanim, holds the quays. Start with Bilal, at the warehouses.': 'وكيله غانم يمسك الشطّ. ابدأ ببلال عند المخازن.',
  'Hakam\'s copyists began that night. By dawn the first copies were bound for the river.': 'بدأ نُسّاخ الحكم تلك الليلة. ومع الفجر كانت النُّسَخ الأولى في طريقها إلى النهر.',
  'The buyer\'s steward means to sink the copies before they sail.': 'وكيل المشتري ينوي أن يُغرق النُّسَخ قبل أن تُبحر.',
  'Ghanim\'s men threw down their crossbows. The copyists\' barge came down from the yard.': 'ألقى رجال غانم قسيّهم. ونزلت سفينة النُّسّاخ من دار الصناعة.',
  'Two copies to Wasit, two to Basra. The rest go north when the river allows.': 'نسختان إلى واسط، ونسختان إلى البصرة. والبقية تصعد شمالًا حين يأذن النهر.',
  'Let him try to gather them now.': 'فليحاول أن يجمعها الآن.',
  'The barge took the current, and was gone around the bend by noon.': 'أخذ التيّار السفينة، وغابت وراء المنعطف قبل الظهر.',
  'That evening he set a lamp on the river for his brother, and one for each guard of the caravan.': 'في المساء وضع على النهر سراجًا لأخيه، وسراجًا لكلّ حارس من حرّاس القافلة.',
});

// ---------------------------------------------------------------- Round 20: eight more side quests (marshes, al-Karkh)
Object.assign(STORY_AR, {
  'Mazin': 'مازن', 'Water-keeper': 'حارس الماء', 'Asad': 'أسد', 'Fowler': 'صيّاد الطير', '\'Umayr': 'عمير', 'Reed builder': 'بنّاء القصب', 'Aws': 'أوس', 'Healer': 'طبيب', 'Shamir': 'شامر',
  'Fadl': 'فضل', 'Baker': 'خبّاز', 'Hayyan': 'حيّان', 'Letter-writer': 'كاتب الرسائل', 'Rufay\'': 'رفيع', 'Water-carrier': 'سقّاء', 'Hawshab': 'حوشب', 'Thumama': 'ثمامة', 'Bookbinder': 'مجلّد',
  'The Dry Channel': 'الساقية الجافّة', 'The Fowler\'s Nets': 'شباك صيّاد الطير', 'Reed for the Roof': 'قصب للسقف', 'Bitter Water': 'الماء المرّ',
  'The Baker\'s Flour': 'دقيق الخبّاز', 'The Letter-Writer': 'كاتب الرسائل', 'The Water-Carriers': 'السقّاؤون', 'The Bookbinder\'s Tools': 'أدوات المجلّد',
  'Rawh\'s men have closed the old sluice on the west channel. The water we drink comes down that channel. Three days now, and the children drink from the marsh.': 'أغلق رجال روح البوّابة القديمة على الساقية الغربية. الماء الذي نشربه ينزل من تلك الساقية. ثلاثة أيام والأطفال يشربون من الهور.',
  'Drive Rawh\'s men from the sluice on the west channel.': 'اطرد رجال روح عن بوّابة الساقية الغربية.', 'Tell Mazin the channel runs again.': 'أخبر مازنًا أنّ الساقية تجري من جديد.',
  'I hear it already. Sweet water, coming home. Take this, and drink first, guard.': 'أسمعه منذ الآن. ماء عذب يعود إلى البيت. خذ هذا، واشرب أوّلًا يا حارس.', 'The west channel runs again.': 'الساقية الغربية تجري من جديد.',
  'Every winter the ducks come down to the marsh, and every winter I feed my family with my nets. Rawh\'s men took them all to their camp in the south-west, to snare men instead of birds.': 'كلّ شتاء تنزل البطّ إلى الهور، وكلّ شتاء أُطعم عيالي بشباكي. أخذها رجال روح كلّها إلى معسكرهم في الجنوب الغربي، ليصيدوا بها الرجال بدل الطير.',
  'Take back Asad\'s nets from the camp in the south-west.': 'استعد شباك أسد من المعسكر في الجنوب الغربي.', 'Take the fowler\'s nets': 'خذ شباك الصيّاد', 'Fowling Nets': 'شباك صيد الطير', 'Bring the nets to Asad.': 'احمل الشباك إلى أسد.',
  'Torn here and here, but I can mend them. The ducks will not know what happened. Here, for your trouble.': 'ممزّقة هنا وهنا، لكنّي أقدر على رتقها. لن يدري البطّ ما جرى. خذ هذا لقاء تعبك.', 'Asad is fowling again.': 'أسد يصيد الطير من جديد.',
  'The great mudhif lost half its roof in the spring flood. I have cut reed enough to mend it, out on the east beds, but Rawh\'s ambushers lie in the reeds there and my buffalo will not go alone.': 'فقدت المضيف الكبيرة نصف سقفها في فيضان الربيع. قطعت من القصب ما يكفي لإصلاحها في المقاصب الشرقية، لكنّ كمائن روح ترقد في القصب هناك وجاموستي لا تمضي وحدها.',
  'Clear the ambushers from the east reed beds.': 'طهّر المقاصب الشرقية من الكمائن.', 'Lead the laden buffalo back to the village.': 'قُد الجاموسة المحمّلة إلى القرية.', 'Speak with \'Umayr.': 'كلّم عميرًا.',
  'Enough for the whole roof, and some left over for my sister\'s. The guest hall will stand another twenty years.': 'يكفي للسقف كلّه ويزيد لبيت أختي. ستقوم المضيف عشرين سنة أخرى.', 'The mudhif has its roof again.': 'عاد إلى المضيف سقفها.',
  'Half the village has the flux. Someone has been fouling the sweet-water tank by the reed camp road with dead fish. I know who pays them.': 'نصف القرية مصاب بالإسهال. أحدهم يُفسد خزّان الماء العذب على طريق مخيّم القصب بالسمك الميّت. وأعرف من يدفع لهم.',
  'Catch the men fouling the water tank on the reed camp road.': 'أمسك بالرجال الذين يُفسدون خزّان الماء على طريق مخيّم القصب.', 'Tell Aws the tank is safe.': 'أخبر أوسًا أنّ الخزّان سالم.',
  'Then I can clean it, and in a week no one will be sick. To deny a village water. There is no lower thing a man can do.': 'إذن أستطيع تنظيفه، وبعد أسبوع لن يمرض أحد. أن تمنع قرية من الماء! ليس شيء أخسّ من ذلك يفعله إنسان.', 'The sweet water is clean again.': 'الماء العذب نظيف من جديد.',
  'The quarter eats from my oven, and the buyer\'s men took my flour for their own. Twenty sacks, stacked in their store by the paper-sellers\' lane.': 'الحيّ كلّه يأكل من فرني، وأخذ رجال المشتري دقيقي لأنفسهم. عشرون كيسًا مكدّسة في مخزنهم قرب سوق الورّاقين.',
  'Take back Fadl\'s flour from the store near the paper-sellers\' lane.': 'استعد دقيق فضل من المخزن قرب سوق الورّاقين.', 'Take the flour sacks': 'خذ أكياس الدقيق', 'Sacks of Flour': 'أكياس الدقيق', 'Bring the flour to Fadl.': 'احمل الدقيق إلى فضل.',
  'Bread tomorrow, for everyone. The first loaf is yours, and this as well.': 'خبز للجميع غدًا. الرغيف الأوّل لك، وهذا أيضًا.', 'Fadl\'s oven is lit.': 'فرن فضل مشتعل.',
  'I write letters for those who cannot. Families to their sons in Basra, in Kufa, in Khurasan. The courier who carried them was robbed on the east lanes.': 'أكتب الرسائل لمن لا يكتب. أُسَر إلى أبنائها في البصرة والكوفة وخراسان. والساعي الذي حملها سُلب في الأزقّة الشرقية.',
  'Find the robbers on the east lanes.': 'اعثر على اللصوص في الأزقّة الشرقية.', 'Bring the letters back to Hayyan.': 'أعد الرسائل إلى حيّان.',
  'Not one opened. These mothers will hear from their sons, and their sons from them. Thank you.': 'لم تُفتح واحدة. ستسمع هؤلاء الأمّهات من أبنائهنّ، ويسمع الأبناء منهنّ. شكرًا لك.', 'The letters go out again.': 'الرسائل تخرج من جديد.',
  'We carry water from the Sarat to every house that has no well. Now the buyer\'s men stand on the canal steps and take a coin for every skin we fill.': 'نحمل الماء من الصراة إلى كلّ بيت لا بئر له. والآن يقف رجال المشتري على درج النهر ويأخذون درهمًا عن كلّ قربة نملؤها.',
  'Clear the buyer\'s men from the canal steps south of the bridge.': 'طهّر درج النهر جنوب الجسر من رجال المشتري.', 'Tell Rufay\' the steps are free.': 'أخبر رفيعًا أنّ الدرج حرّ.',
  'Free water for al-Karkh. My father carried water in the siege, and no one taxed it even then.': 'ماء حرّ للكرخ. كان أبي يحمل الماء في الحصار، ولم يأخذ عليه أحد شيئًا حتى يومها.', 'The water-carriers fill their skins for nothing.': 'السقّاؤون يملؤون قِرَبهم بلا مقابل.',
  'My awls, my bone folders and my presses are in my old shop, under the ash on the south lane. Thieves camp in the ruins there now. Without my tools no book in this quarter gets a cover.': 'مخارزي ومطاوي العظم ومكابسي في دكّاني القديم تحت الرماد في الزقاق الجنوبي. يخيّم اللصوص في الخرائب هناك الآن. بلا أدواتي لا يُجلَّد كتاب في هذا الحيّ.',
  'Recover Thumama\'s tools from the ruins on the south lane.': 'استعد أدوات ثمامة من خرائب الزقاق الجنوبي.', 'Take the bookbinder\'s tools': 'خذ أدوات المجلّد', 'Bookbinding Tools': 'أدوات التجليد', 'Bring the tools to Thumama.': 'احمل الأدوات إلى ثمامة.',
  'My press! Hakam\'s copies will need covers, and now they shall have the best in Baghdad.': 'مكبسي! ستحتاج نُسَخ الحكم إلى جلود، والآن ستنال أفضلها في بغداد.', 'Thumama is binding again.': 'ثمامة يجلّد من جديد.',
  'Sluices and Channels': 'البوّابات والسواقي',
  'The land between the rivers lived by its channels. Each village took water from a larger canal through a sluice of brick or timber, and the men who kept the sluices decided who drank and whose fields were watered. To close a village\'s sluice was the oldest way to bring it to its knees.': 'عاشت الأرض بين النهرين بسواقيها. كانت كلّ قرية تأخذ الماء من نهر أكبر عبر بوّابة من آجرّ أو خشب، والرجال الذين يحرسون البوّابات يقرّرون من يشرب وأيّ الحقول تُسقى. وكان إغلاق بوّابة قرية أقدم طريقة لإخضاعها.',
  'Bread in Baghdad': 'الخبز في بغداد',
  'Grain came down the Tigris and Euphrates to Baghdad\'s markets, and most households bought their bread from the bakers of their quarter rather than baking it at home. When the siege cut the grain boats, the price of bread was the first sign of hunger in the city.': 'كانت الحبوب تنحدر في دجلة والفرات إلى أسواق بغداد، وكانت أكثر البيوت تشتري خبزها من خبّازي حيّها بدل أن تخبزه في البيت. ولمّا قطع الحصار سفن الحبوب كان سعر الخبز أوّل علامات الجوع في المدينة.',
});
Object.assign(STORY_AR, AR21);
Object.assign(STORY_AR, AR22);
Object.assign(STORY_AR, AR23);
Object.assign(STORY_AR, AR24);
