// Round 22: Arabic for the story holds (merged into STORY_AR, see story_ar.js)
export const AR22 = {
  // the holds
  'The Broken Dam': 'السدّ المكسور', 'Old sluices behind the caravanserai': 'نواظم قديمة خلف الخان',
  'The Kiln Galleries': 'دهاليز الأفران', 'Firing lanes under the kiln yard': 'ممرّات الشيّ تحت ساحة الأفران',
  'The Reed Stockade': 'حصن القصب', 'An island fort in the reed beds': 'حصن على جزيرة بين منابت القصب',
  'The Sunken Village': 'القرية الغارقة', 'Drowned houses by the fish racks': 'بيوت غارقة قرب مناشر السمك',
  'The Burned Quarter': 'الحيّ المحروق', 'Lanes still smouldering behind the suq': 'أزقّة ما زالت تدخّن خلف السوق',
  'The Warehouse Vaults': 'مخازن الورّاقين', 'Store-rooms under the paper-sellers\' lane': 'مخازن تحت سوق الورّاقين',
  'The Shipyard': 'دار الصناعة', 'Slips and sheds beside the warehouses': 'مزالق وسقائف بجانب المخازن',
  'The Hulks': 'السفن المحروقة', 'Burned barges moored in mid-river': 'صنادل محروقة راسية وسط النهر',
  // who holds them
  'Durayd': 'دريد', 'Keeper of the sluices': 'حارس النواظم', 'Bring the old wall down on him!': 'أسقطوا الجدار القديم عليه!',
  'Ghassan\'s man at the caravanserai': 'رجل غسّان في الخان', 'To me! Hold him!': 'إليّ! أمسكوه!',
  'Mazin': 'مازن', 'The stoker of the kilns': 'وقّاد الأفران', 'Feed the fires!': 'زيدوا النار وقودًا!',
  'The kiln-master who sold the Pages': 'صاحب الأفران الذي باع الأوراق', 'Into the fire with you!': 'إلى النار معك!',
  'Farqad': 'فرقد', 'Warden of the causeways': 'حارس الجسور', 'Out of the reeds, all of you!': 'اخرجوا من القصب، كلّكم!',
  'Rawh\'s man in the reed camp': 'رجل روح في مخيّم القصب', 'The reeds, now!': 'القصب، الآن!',
  'Shibl': 'شبل', 'The boatmen\'s headman': 'كبير المعدّية', 'Sink him in the mud!': 'أغرقوه في الطين!',
  'Keeper of Rawh\'s boats': 'حارس قوارب روح', 'You will drown here.': 'ستغرق هنا.',
  'Hajib': 'حاجب', 'Captain of the burned lanes': 'قائد الأزقّة المحروقة', 'Let the roofs fall!': 'دعوا السقوف تسقط!',
  '\'Utba\'s man in the burned suq': 'رجل عتبة في السوق المحروقة', 'Guards! Burn the lane!': 'يا حرس! أحرقوا الزقاق!',
  'Ghiyath': 'غياث', 'Keeper of the store-rooms': 'حارس المخازن', 'Bolts! Put him down!': 'السهام! أسقطوه!',
  'He guards the Pages for \'Utba': 'يحرس الأوراق لعتبة', 'Then let it all burn.': 'إذن فليحترق كلّ شيء.',
  'Hawtha': 'حوثة', 'Master of the slips': 'شيخ المزالق', 'Drop the timbers on him!': 'أسقطوا الأخشاب عليه!',
  'Ghanim\'s man on the river': 'رجل غانم على النهر', 'Drop the loads on him!': 'أسقطوا الأحمال عليه!',
  'Murra': 'مرّة', 'Keeper of the moorings': 'حارس المراسي', 'Cut the gangplanks!': 'اقطعوا الألواح!',
  'He keeps the copyists\' boat': 'يحتجز قارب النُّسّاخ', 'Over the side with him!': 'ألقوه من فوق الحافّة!',
  // the doors
  'The galleries are barred. Find Farud first.': 'الدهاليز موصدة. اعثر على فرود أوّلًا.',
  'The way is barred. Find Marwan first.': 'الطريق موصد. اعثر على مروان أوّلًا.',
  'The vaults are barred. Find \'Asim first.': 'المخازن موصدة. اعثر على عاصم أوّلًا.',
  'No boat will take you out yet. Find Bilal first.': 'لن يحملك قارب إلى هناك بعد. اعثر على بلال أوّلًا.',
  'Not yet': 'ليس بعد', 'barred': 'موصد',
  'Close quarters: the camera follows behind you. Tap ◎ to lock on to a foe.': 'قتال قريب: الكاميرا تتبعك من الخلف. المس ◎ لتثبّت على عدوّ.',
  'Close quarters: the camera follows behind you. Tab or F locks on to a foe.': 'قتال قريب: الكاميرا تتبعك من الخلف. Tab أو F للتثبيت على عدوّ.',
  // the story, as it now runs
  'Follow Farud into the broken dam behind the caravanserai': 'اتبع فرود إلى السدّ المكسور خلف الخان',
  'Find Hisham in the galleries under the kiln yard': 'اعثر على هشام في الدهاليز تحت ساحة الأفران',
  'Find Marwan in the reed stockade to the west': 'اعثر على مروان في حصن القصب غربًا',
  'Take Rawh\'s boats from Sahl in the sunken village': 'خذ قوارب روح من سهل في القرية الغارقة',
  'Find \'Asim in the burned quarter behind the suq': 'اعثر على عاصم في الحيّ المحروق خلف السوق',
  'Drive Layth from the vaults under the paper-sellers\' lane': 'اطرد ليثًا من المخازن تحت سوق الورّاقين',
  'Find Bilal in the shipyard by the warehouses': 'اعثر على بلال في دار الصناعة قرب المخازن',
  'Free the copyists\' boat from Mus\'ab among the hulks': 'حرّر قارب النُّسّاخ من مصعب بين السفن المحروقة',
  'Rawh paid us to hide his boats. Sahl keeps them in the drowned village, east.': 'دفع لنا روح لنخفي قواربه. سهل يحتفظ بها في القرية الغارقة، شرقًا.',
  '\'Utba moved the Pages to the vaults under the paper-sellers\' lane. Layth guards them.': 'نقل عتبة الأوراق إلى المخازن تحت سوق الورّاقين. ليث يحرسها.',
  'Layth guards the Pages in the store-rooms under the paper shops.': 'ليث يحرس الأوراق في المخازن تحت دكاكين الورق.',
  'Ghanim pays us to hold the river. Mus\'ab keeps the copyists\' boat among the burned hulks.': 'غانم يدفع لنا لنمسك النهر. مصعب يحتجز قارب النُّسّاخ بين السفن المحروقة.',
  'Hisham is burning the Pages in the kiln galleries. Stop him.': 'هشام يحرق الأوراق في دهاليز الأفران. أوقفه.',
  // codex
  'Dams and Sluices': 'السدود والنواظم',
  'The Sasanian kings raised the rivers of the Sawad into its canals with weirs and dams of brick and stone. Each sluice had its keeper. When a dam was left to crack, the canals behind it silted up and the villages along them emptied.': 'رفع ملوك الساسانيين مياه أنهار السواد إلى قنواته بسدود ونواظم من الآجرّ والحجر. ولكلّ ناظم حارسه. فإذا تُرك السدّ يتشقّق، طُمرت القنوات خلفه بالطمي وخلت القرى على ضفافها.',
  'The Brick-Makers': 'صنّاع الآجرّ',
  'Brick was made by gangs: diggers cut the clay, moulders pressed it into wooden frames, carriers stacked the dried bricks in the kiln, and the firemen kept it burning for days. A single firing could hold tens of thousands of bricks, and a kiln yard was a small town of its own, black with smoke.': 'كان الآجرّ يُصنع على أيدي جماعات: الحفّارون يقطعون الطين، والضرّابون يكبسونه في قوالب من خشب، والحمّالون يرصّون اللَّبِن الجافّ في الأتون، والوقّادون يُبقونه مشتعلًا أيّامًا. وقد تسع الشيّة الواحدة عشرات الآلاف من الآجرّ، وكانت ساحة الأفران بلدة صغيرة قائمة بذاتها، سوداء من الدخان.',
  'Reed Islands': 'جزر القصب',
  'The marsh people built on platforms of reed and mud laid down layer on layer, and fenced their islands with reed. Such places were hard to reach for anyone without a boat and a guide, and the marshes sheltered rebels and runaways for centuries.': 'بنى أهل البطائح على مصاطب من القصب والطين تُرصف طبقة فوق طبقة، وسيّجوا جزرهم بالقصب. وكان بلوغ هذه الأماكن عسيرًا على من لا قارب له ولا دليل، فآوت البطائح الثائرين والفارّين قرونًا.',
  'Drowned Villages': 'القرى الغارقة',
  'When the dykes failed, whole villages of the lower marsh went under. People came back by boat to their roofs and granary mounds, and some places were lived in half-drowned for a generation before the water was let out again, if it ever was.': 'حين انهارت السدود الترابية غرقت قرى كاملة في البطائح السفلى. فعاد الناس بالقوارب إلى سطوحهم وتلال مخازن غلالهم، وسُكنت بعض الأماكن نصف غارقة جيلًا كاملًا قبل أن يُصرف الماء عنها، إن صُرف.',
  'The Burning of al-Karkh': 'حريق الكرخ',
  'The histories of the siege of 812 to 813 tell of fighting from street to street in western Baghdad, of engines throwing stones and naft into the quarters, and of houses and markets burned or pulled down to open lines of fire. Al-Karkh, the great market suburb, suffered as badly as any.': 'تروي أخبار حصار سنتي 812 و813 قتالًا من شارع إلى شارع في غربي بغداد، ومجانيق ترمي الحجارة والنفط على الأحياء، وبيوتًا وأسواقًا أُحرقت أو هُدمت لفتح طرق الرمي. وأصاب الكرخ، ضاحية الأسواق الكبرى، ما أصاب أشدّها.',
  'Merchants\' Store-rooms': 'مخازن التجّار',
  'Paper, ink, cloth and grain were kept in brick store-rooms behind the shops, often half below the ground to stay cool and dry, and barred from inside. A merchant\'s wealth lay as much in what he had stored as in what he sold that day.': 'كان الورق والحبر والقماش والحبوب تُحفظ في مخازن من الآجرّ خلف الدكاكين، كثيرًا ما تكون نصف مطمورة تحت الأرض لتبقى باردة جافّة، وتوصد من الداخل. وكانت ثروة التاجر فيما خزنه بقدر ما كانت فيما باعه يومه.',
  'River Boats': 'سفن النهر',
  'Boats for the Tigris were built of planks on frames, their seams stuffed with fibre and sealed with pitch or bitumen from the springs of the middle Euphrates. Yards along the bank built and mended them; timber came down the rivers from the north.': 'كانت سفن دجلة تُبنى من ألواح على أضلاع، تُحشى فواصلها بالليف وتُختم بالزفت أو القار من عيون الفرات الأوسط. وكانت دور على الضفّة تبنيها وتصلحها، والخشب ينحدر في الأنهار من الشمال.',
  'Burned Boats': 'السفن المحروقة',
  'In the fighting for Baghdad the river itself was a battlefield. Boats were burned at their moorings and the bridges of boats were cut. The hulks were often left where they lay, and men hid and lived in them.': 'في القتال على بغداد صار النهر نفسه ساحة حرب. أُحرقت السفن في مراسيها وقُطعت جسور القوارب. وكثيرًا ما تُركت الهياكل حيث هي، فاختبأ فيها الرجال وسكنوها.',
};
