// Round 36: Arabic for Season Two (the marshes, drama36.js) and Season One's plants. Merged last in story_ar.js.
// Backtick strings, so apostrophes and quotes stay as they are in the English.
export const AR36 = {
  // ---- Season One: the plants
  [`Then how did a Rum envoy know to ask for you by name?`]: `فكيف عرف رسولٌ من الروم أن يطلبك باسمك؟`,
  [`...Few knew. Fewer than should have.`]: `...قليلون كانوا يعلمون. أقلّ ممّا ينبغي.`,
  [`Ishaq's lamp was out. His sandals by the door were wet with canal mud.`]: `كان سراج إسحاق مطفأً. ونعلاه عند الباب مبلّلتان بطين القناة.`,
  [`You went out. I told you not to leave the village.`]: `خرجتَ. قلتُ لك ألّا تغادر القرية.`,
  [`Only to the canal. I wanted to see the water for myself.`]: `إلى القناة فقط. أردتُ أن أرى الماء بعيني.`,
  [`And a man came to Bardanes there, at night. I never saw his face. Bardanes called him the friend.`]: `وجاء رجلٌ إلى بردانس هناك، ليلًا. لم أرَ وجهه قطّ. كان بردانس يسمّيه الصديق.`,
  [`You owe me an answer, Ishaq. About the letters.`]: `لي عندك جوابٌ يا إسحاق. عن الرسائل.`,
  [`In Baghdad, when the Pages are safe. You will have all of it. I swear it.`]: `في بغداد، حين تصير الأوراق في أمان. ستسمعه كلّه. أُقسم على ذلك.`,
  // ---- cards
  [`Season Two`]: `الموسم الثاني`,
  [`Season Two · The Marshes`]: `الموسم الثاني · الأهوار`,
  [`Who is the friend who writes to the envoy?`]: `من هو الصديق الذي يكاتب الرسول؟`,
  [`The Nahrawan marshes, 813`]: `أهوار النهروان، ٨١٣`,
  [`End of Season Two`]: `نهاية الموسم الثاني`,
  [`Three days earlier`]: `قبل ثلاثة أيام`,
  [`The Light Chest`]: `الصندوق الخفيف`,
  [`The Reed Stockade`]: `حصن القصب`,
  [`The Boatwoman`]: `صاحبة القارب`,
  [`The Last Quire`]: `الكرّاس الأخير`,
  [`The Drowned Village`]: `القرية الغارقة`,
  [`The Weir`]: `السِّكر`,
  [`Season Three · Al-Karkh`]: `الموسم الثالث · الكرخ`,
  [`No one alive writes that hand. Except one.`]: `لا أحد من الأحياء يكتب بهذا الخطّ. إلّا واحدًا.`,
  [`A woman carries the letters. And Rabab is gone.`]: `امرأةٌ تحمل الرسائل. ورباب قد اختفت.`,
  [`The friend sleeps in Salim's own camp.`]: `الصديق ينام في مخيّم سالم نفسه.`,
  [`The last quire is gone. So is Ishaq.`]: `الكرّاس الأخير اختفى. وإسحاق كذلك.`,
  [`Last night, Ishaq was not in his tent.`]: `ليلة أمس، لم يكن إسحاق في خيمته.`,
  [`Ishaq owes Salim an answer.`]: `على إسحاق جوابٌ لسالم.`,
  // ---- previously
  [`Rabab the boatwoman poled Salim into the marshes.`]: `حملت رباب صاحبةُ القارب سالمًا إلى الأهوار.`,
  [`The chest was light. Kallinikos has the rest of the Pages.`]: `كان الصندوق خفيفًا. بقية الأوراق مع كالينيكوس.`,
  [`Then an arrow brought a message in the Teacher's cipher. Only Ishaq writes it.`]: `ثم جاء سهمٌ برسالةٍ بشيفرة المعلّم. لا يكتبها إلّا إسحاق.`,
  [`Three men learned the cipher. Only Ishaq still lives.`]: `ثلاثةٌ تعلّموا الشيفرة. لم يبقَ منهم حيًّا إلّا إسحاق.`,
  [`Katakylas fell in the reed stockade. A woman poles the letters, he said.`]: `سقط كاتاكيلاس في حصن القصب. قال إن امرأةً تحمل الرسائل في قاربها.`,
  [`And Rabab's boat was gone.`]: `ثم اختفى قارب رباب.`,
  [`Rabab carried the letters so they would let her see her son.`]: `حملت رباب الرسائل كي يدعوها ترى ابنها.`,
  [`Salim trusted her.`]: `وثق بها سالم.`,
  [`Salim bound her, for Ishaq to judge.`]: `قيّدها سالم، ليحكم فيها إسحاق.`,
  [`The letters are left a stone's throw from Salim's own fire.`]: `تُترك الرسائل على رمية حجرٍ من نار سالم نفسه.`,
  [`Ishaq told what the last quire holds: the names of the men who poisoned the Teacher.`]: `قال إسحاق ما في الكرّاس الأخير: أسماء الرجال الذين سمّموا المعلّم.`,
  [`Fire-arrows came down on the camp.`]: `نزلت سهامُ النار على المخيّم.`,
  [`Then the last quire was gone. And so was Ishaq.`]: `ثم اختفى الكرّاس الأخير. واختفى إسحاق معه.`,
  [`Ishaq came back at dawn. He had hidden the quire, he said.`]: `عاد إسحاق عند الفجر. قال إنه خبّأ الكرّاس.`,
  [`Petronas fell in the drowned village.`]: `سقط بترونس في القرية الغارقة.`,
  [`The friend went to the weir himself, last night. The night Ishaq was gone.`]: `ذهب الصديق إلى السِّكر بنفسه، ليلة أمس. الليلة التي غاب فيها إسحاق.`,
  // ---- the cold open
  [`Your friend in the camp writes a fine hand, guard.`]: `صديقك في المخيّم خطّه جميل، أيّها الحارس.`,
  [`What friend?`]: `أيّ صديق؟`,
  // ---- Episode One
  [`The Nahrawan marshes, east of Baghdad. Three days after the arch.`]: `أهوار النهروان، شرقيّ بغداد. بعد الطاق بثلاثة أيام.`,
  [`Keep your hands inside the boat, guard. Things bite out here.`]: `أبقِ يديك داخل القارب أيّها الحارس. في هذا المكان أشياء تعضّ.`,
  [`Snakes?`]: `أفاعٍ؟`,
  [`Tax men.`]: `جُباة الخراج.`,
  [`You pole these channels like you were born on them.`]: `تدفعين القارب في هذه المجاري كأنك وُلدتِ عليها.`,
  [`I was. Every channel, every reed bed, as far as the weir.`]: `وُلدتُ عليها. كلّ مجرى، وكلّ أجمة قصب، حتى السِّكر.`,
  [`The chest from Bardanes' tent. It weighed less than it should.`]: `الصندوق من خيمة بردانس. كان أخفّ ممّا ينبغي.`,
  [`Eleven quires. There were twenty.`]: `أحد عشر كرّاسًا. كانت عشرين.`,
  [`Kallinikos has the rest?`]: `والبقية مع كالينيكوس؟`,
  [`Most of them. And the last.`]: `أكثرها. والأخير.`,
  [`Ishaq closed the lid. Quickly.`]: `أغلق إسحاق الغطاء. بسرعة.`,
  [`In the vault, a man came to Bardanes at night. I never saw his face. Bardanes called him the friend.`]: `في القبو، كان رجلٌ يأتي إلى بردانس ليلًا. لم أرَ وجهه قطّ. كان بردانس يسمّيه الصديق.`,
  [`Photeinos said it too. Ishaq has a friend who writes to the envoy.`]: `قالها فوتينوس أيضًا. لإسحاق صديقٌ يكاتب الرسول.`,
  [`I have very few friends, Salim. Fewer every year.`]: `أصدقائي قليلون جدًّا يا سالم. ويقلّون كلّ عام.`,
  [`He coughs all night in this damp. Make him sleep, little brother.`]: `يسعل الليل كلّه في هذه الرطوبة. اجعله ينام يا أخي الصغير.`,
  [`The fishermen say Kallinikos' reed-men raid the landing at dusk. Be there first.`]: `يقول الصيّادون إن رجال القصب التابعين لكالينيكوس يغيرون على المرسى عند الغسق. كن هناك قبلهم.`,
  [`Reed-men are raiding the landing. Drive them off.`]: `رجال القصب يغيرون على المرسى. اطردهم.`,
  [`They came for the boats. Or for us.`]: `جاؤوا من أجل القوارب. أو من أجلنا.`,
  [`That night, something came out of the dark and struck the post by Jabir's pallet.`]: `في تلك الليلة، خرج شيءٌ من الظلام وانغرس في العمود بجانب فراش جابر.`,
  [`The same marks, Salim. Like the arrow on the dune.`]: `العلامات نفسها يا سالم. مثل سهم الكثيب.`,
  [`Read it.`]: `اقرأها.`,
  [`Ishaq read it twice. He did not read it aloud the first time.`]: `قرأها إسحاق مرّتين. لم يقرأها بصوتٍ عالٍ في المرّة الأولى.`,
  [`It says the rest of the Pages burn at the weir, unless I come.`]: `تقول إن بقيّة الأوراق ستُحرق عند السِّكر، إلّا إذا جئت.`,
  [`It is your teacher's cipher. Who else writes it?`]: `هذه شيفرة معلّمك. من غيرك يكتبها؟`,
  [`No one. No one alive.`]: `لا أحد. لا أحد من الأحياء.`,
  // ---- Episode Two
  [`No one alive writes that hand, you said. Then who wrote it?`]: `قلتَ إنه لا أحد من الأحياء يكتب بهذا الخطّ. فمن كتبه إذن؟`,
  [`Three of us learned it from him. Olbianos copied it without understanding it, and he is dead.`]: `تعلّمها منه ثلاثةٌ منّا. أولبيانوس نسخها دون أن يفهمها، وقد مات.`,
  [`The third was a boy called Rafi'. The siege took him. I watched his street burn.`]: `والثالث فتًى اسمه رافع. أخذه الحصار. رأيتُ شارعه يحترق.`,
  [`So a dead man writes letters.`]: `إذن رجلٌ ميّتٌ يكتب الرسائل.`,
  [`Or a living one learned it from a dead man's papers.`]: `أو رجلٌ حيٌّ تعلّمها من أوراق رجلٍ ميّت.`,
  [`Or someone in this camp is lying.`]: `أو أنّ أحدًا في هذا المخيّم يكذب.`,
  [`Nobody answered him.`]: `لم يُجبه أحد.`,
  [`The fishermen say the letters go through the reed stockade. Katakylas holds it.`]: `يقول الصيّادون إن الرسائل تمرّ عبر حصن القصب. وكاتاكيلاس يمسكه.`,
  [`Then Katakylas can tell me who carries them.`]: `إذن سيخبرني كاتاكيلاس من يحملها.`,
  [`Take the reed stockade to the west. Find out who carries the letters.`]: `استولِ على حصن القصب في الغرب. اعرف من يحمل الرسائل.`,
  [`The letters come by boat, from your own camp. A woman poles it.`]: `الرسائل تأتي بالقارب، من مخيّمك نفسه. وامرأةٌ تدفع القارب.`,
  [`When Salim came back to the landing, Rabab's boat was gone. Her pole was floating in the reeds.`]: `حين عاد سالم إلى المرسى، كان قارب رباب قد اختفى. ومِردَيُها يطفو بين القصب.`,
  [`She knew every channel. Of course she did.`]: `كانت تعرف كلّ مجرى. طبعًا كانت تعرف.`,
  // ---- Episode Three
  [`Ask Layla, the mat-weaver in the village, where Rabab goes`]: `اسأل ليلى، ناسجة الحُصر في القرية، إلى أين تذهب رباب`,
  [`The boatwoman, Rabab. Where does she go?`]: `صاحبة القارب، رباب. إلى أين تذهب؟`,
  [`East, every night, to the drowned village. Since the soldiers took her boy.`]: `شرقًا، كلّ ليلة، إلى القرية الغارقة. منذ أن أخذ الجنود ولدها.`,
  [`Her boy?`]: `ولدها؟`,
  [`Hani. Twelve years old. They make him row for Kallinikos. She would carry fire in her hands to see him.`]: `هانئ. في الثانية عشرة. يجبرونه على التجديف لكالينيكوس. كانت لتحمل النار في كفّيها لتراه.`,
  [`Do not hurt her, guard. Half this marsh would have done the same.`]: `لا تؤذِها أيّها الحارس. نصف أهل هذا الهور كانوا سيفعلون مثلها.`,
  [`Kallinikos' men watch the shore below the drowned village`]: `رجال كالينيكوس يراقبون الشاطئ تحت القرية الغارقة`,
  [`Find Rabab on the shore`]: `جِد رباب على الشاطئ`,
  [`On the shore below the drowned village, Rabab was packing bread into a basket.`]: `على الشاطئ تحت القرية الغارقة، كانت رباب تضع الخبز في سلّة.`,
  [`You carried their letters.`]: `حملتِ رسائلهم.`,
  [`They have my son. Hani. He rows Kallinikos' boat.`]: `ابني عندهم. هانئ. يجدّف في قارب كالينيكوس.`,
  [`I cannot read, guard. I never could. I carry what I find, and they let me see him for an hour.`]: `لا أعرف القراءة أيّها الحارس. لم أعرفها قطّ. أحمل ما أجده، فيدعونني أراه ساعة.`,
  [`Who gives you the letters?`]: `من يعطيكِ الرسائل؟`,
  [`No one gives them. They are left under a stone at the old mooring post. With a silver coin.`]: `لا أحد يعطيني إيّاها. تُترك تحت حجرٍ عند وتد المرسى القديم. ومعها درهم فضّة.`,
  [`Rabab waits to hear what you think she is.`]: `تنتظر رباب أن تسمع ما تظنّه فيها.`,
  [`Then take me to your son.`]: `إذن خذيني إلى ابنك.`,
  [`You will answer to Ishaq.`]: `ستُسألين أمام إسحاق.`,
  [`The drowned village has a back way in. I will show you.`]: `للقرية الغارقة مدخلٌ خلفيّ. سأريك إيّاه.`,
  [`Then tie me. But tie me where I can see the water.`]: `إذن قيّدني. لكن قيّدني حيث أرى الماء.`,
  [`The old mooring post. That is by our camp.`]: `وتد المرسى القديم. إنه بجانب مخيّمنا.`,
  [`A stone's throw from your own fire.`]: `على رمية حجرٍ من نارك أنت.`,
  [`Then the friend sleeps in our camp.`]: `إذن الصديق ينام في مخيّمنا.`,
  // ---- Episode Four
  [`Go back to the camp. Ishaq has some answering to do.`]: `عُد إلى المخيّم. على إسحاق أن يجيب.`,
  [`The letters are left a stone's throw from our fire. Tell me what is in that chest, Ishaq. All of it.`]: `تُترك الرسائل على رمية حجرٍ من نارنا. أخبرني بما في هذا الصندوق يا إسحاق. كلّه.`,
  [`The sayings. The letters. And one more quire. The last.`]: `الأقوال. الرسائل. وكرّاسٌ آخر. الأخير.`,
  [`In the prison, he wrote down how he was dying. And the names of the men who poisoned him.`]: `في السجن، كتب كيف كان يموت. وأسماء الرجال الذين سمّموه.`,
  [`Some of them sit at court today.`]: `بعضهم يجلس في البلاط اليوم.`,
  [`So the envoy does not want wisdom. He wants a knife at Baghdad's throat.`]: `إذن الرسول لا يريد الحكمة. يريد سكّينًا على عنق بغداد.`,
  [`The envoy wants to hold it over them. The court wants it burned. And the man who can read it.`]: `الرسول يريد أن يمسكه فوق رؤوسهم. والبلاط يريده محروقًا. ومعه الرجل الذي يقرؤه.`,
  [`You told Bardanes you would bring me. For a moment I believed you. I would have gone.`]: `قلتَ لبردانس إنك ستأتي بي. صدّقتك للحظة. وكنتُ سأذهب.`,
  [`I would not have let you.`]: `ما كنتُ لأدعك.`,
  [`You would not trade me for your brother. I never thanked you. I do not know that I deserve to.`]: `رفضتَ أن تبادلني بأخيك. لم أشكرك قطّ. ولا أدري إن كنتُ أستحقّ ذلك.`,
  [`Thank Jabir. He would never have forgiven me.`]: `اشكر جابرًا. ما كان ليغفر لي أبدًا.`,
  [`Jabir pushed himself up off the pallet. And stood.`]: `اتّكأ جابر ورفع نفسه عن الفراش. ووقف.`,
  [`Then we carry it the rest of the way. All of us.`]: `إذن نحمله بقيّة الطريق. كلّنا.`,
  [`Sit down before you fall down, brother.`]: `اجلس قبل أن تقع يا أخي.`,
  [`Fire-arrows came out of the reeds.`]: `خرجت سهامُ النار من القصب.`,
  [`Fire-arrows on the camp! Drive the raiders out of the reeds.`]: `سهام النار على المخيّم! اطرد المغيرين من القصب.`,
  [`When the last fire was out, Salim went to Ishaq's place. The chest stood open.`]: `حين انطفأت آخر نار، ذهب سالم إلى مكان إسحاق. كان الصندوق مفتوحًا.`,
  [`The last quire is gone.`]: `الكرّاس الأخير اختفى.`,
  [`So is Ishaq.`]: `وإسحاق كذلك.`,
  // ---- Episode Five
  [`At first light Ishaq came up from the water. Wet to the knee. Ash on his fingers.`]: `عند أوّل الضوء صعد إسحاق من الماء. مبلّلًا حتى الركبة. وعلى أصابعه رماد.`,
  [`Where is it?`]: `أين هو؟`,
  [`Where no fire can reach it. Do not ask me where. What you do not know, no one can make you tell.`]: `حيث لا تبلغه نار. لا تسألني أين. ما لا تعرفه، لا يستطيع أحدٌ أن يجبرك على قوله.`,
  [`You went out alone. Again.`]: `خرجتَ وحدك. مرّةً أخرى.`,
  [`Again?`]: `مرّةً أخرى؟`,
  [`In the Sawad, the night before the canal went black. Your sandals were wet then too.`]: `في السواد، في الليلة التي سبقت اسوداد القناة. كان نعلاك مبلّلين يومها أيضًا.`,
  [`And you knew the water was fouled before anyone told you.`]: `وكنتَ تعرف أن الماء قد لُوّث قبل أن يخبرك أحد.`,
  [`Ishaq did not answer.`]: `لم يُجب إسحاق.`,
  [`Salim. The boy first. Then the questions.`]: `سالم. الفتى أوّلًا. ثم الأسئلة.`,
  [`In the night someone had untied Rabab. Ishaq, she said. "A mother is not a thief," he had told her.`]: `في الليل حلّ أحدهم وثاق رباب. إسحاق، قالت. «الأمّ ليست لصّة»، هكذا قال لها.`,
  [`Rabab is waiting at the landing. She knows the back way into the drowned village.`]: `رباب تنتظر عند المرسى. تعرف المدخل الخلفيّ إلى القرية الغارقة.`,
  [`The back way is through the old fish weirs. Stay close to the reeds.`]: `المدخل الخلفيّ عبر حواجز السمك القديمة. ابقَ قريبًا من القصب.`,
  [`Go into the drowned village. Petronas holds Kallinikos' boats.`]: `ادخل القرية الغارقة. بترونس يمسك قوارب كالينيكوس.`,
  [`Your friend came to the weir himself, last night. An old man, coughing in the damp.`]: `صديقك جاء إلى السِّكر بنفسه، ليلة أمس. رجلٌ عجوز، يسعل في الرطوبة.`,
  [`An old man, coughing in the damp. Last night.`]: `رجلٌ عجوز، يسعل في الرطوبة. ليلة أمس.`,
  // ---- Episode Six
  [`You think it is Ishaq.`]: `تظنّه إسحاق.`,
  [`I think he has lied to me twice. And he is the only man alive who writes that hand.`]: `أظنّه كذب عليّ مرّتين. وهو الوحيد من الأحياء الذي يكتب بهذا الخطّ.`,
  [`He kept me alive in his account, all through the Sawad. Ask him after. Not before a fight.`]: `أبقاني حيًّا في حسابه، طوال السواد. اسأله بعد. لا قبل القتال.`,
  [`The year of the flood, I came back for you.`]: `في سنة الطوفان، عدتُ من أجلك.`,
  [`And at the arch, I came back for you.`]: `وعند الطاق، عدتُ أنا من أجلك.`,
  [`So we are even. Go and bring that boy back to his mother.`]: `إذن تعادلنا. اذهب وأعِد ذلك الفتى إلى أمّه.`,
  [`Salim. When you come back, ask me. I will answer. All of it.`]: `سالم. حين تعود، اسألني. سأجيب. عن كلّ شيء.`,
  [`Keep the lamp lit, Ishaq. I will hold you to that.`]: `أبقِ السراج مضاءً يا إسحاق. سأحاسبك على كلمتك.`,
  [`When you come back, ask me. I will answer.`]: `حين تعود، اسألني. سأجيب.`,
  [`The reed village`]: `قرية القصب`,
  [`Reach the old weir before dawn. Kallinikos has Hani.`]: `بلغ السِّكر القديم قبل الفجر. هانئ عند كالينيكوس.`,
  [`Smoke over the weir. Faster.`]: `دخانٌ فوق السِّكر. أسرع.`,
  [`Dawn, guard. The reed village is already burning.`]: `الفجر أيّها الحارس. قرية القصب تحترق منذ الآن.`,
  [`Your friend in the camp writes a fine hand, guard. Did he not tell you?`]: `صديقك في المخيّم خطّه جميل، أيّها الحارس. ألم يخبرك؟`,
  [`Hani was in Kallinikos' boat, under the nets. Rabab had him out before Salim reached the water.`]: `كان هانئ في قارب كالينيكوس، تحت الشباك. أخرجته رباب قبل أن يبلغ سالم الماء.`,
  [`Hani was in Kallinikos' boat, under the nets. Salim carried him to the shore himself.`]: `كان هانئ في قارب كالينيكوس، تحت الشباك. حمله سالم إلى الشاطئ بنفسه.`,
  [`In Kallinikos' satchel: a bundle of letters. Every one in the marks Salim had seen on the arrow.`]: `في حقيبة كالينيكوس: رزمة رسائل. كلّها بالعلامات التي رآها سالم على السهم.`,
  [`Only one man alive writes this hand.`]: `رجلٌ واحدٌ من الأحياء يكتب بهذا الخطّ.`,
  // ---- the doors
  [`Not yet. Find out who sent the arrow first.`]: `ليس بعد. اعرف أوّلًا من أرسل السهم.`,
  [`Not yet. You do not know the way in.`]: `ليس بعد. لا تعرف طريق الدخول.`,
};
