// Round 29: Arabic for the new troops, the new side quests and the epilogue (merged last in story_ar.js)
export const AR29 = {
  // troops
  'Akontistes': 'رامي الحراب', 'Kontaratos': 'صاحب القناة', 'Caltrop Thrower': 'رامي الحسك', 'Deputatos': 'المُسعِف',
  'Javelin men: keep moving across their line': 'رماة الحراب: لا تتوقّف وتحرّك عرضًا عن خطّهم',
  'A braced spear: never dash into its point. Go round, or wait it out': 'رمح مُثبَّت: لا تندفع نحو سنانه. التفّ حوله أو انتظر حتى يرفعه',
  'Caltrops: step off the iron points': 'حسك: ابتعد عن الأشواك الحديدية',
  'A field surgeon binds their wounded: cut him down first': 'مُسعِف يضمّد جرحاهم: اقضِ عليه أوّلًا',
  'The surgeon. Him first, or they get up again.': 'المُسعِف. هو أوّلًا، وإلّا قاموا من جديد.',
  'Skewered!': 'طُعِنت!', 'Braced!': 'رمح مُثبَّت!', 'Interrupted': 'قُطِع',

  // side quests
  'Deal with the men around first': 'تخلّص من الرجال حوله أوّلًا',
  'Seed for the Sowing': 'بذار الزرع', 'Rifa\'a': 'رفاعة', 'Miller': 'طحّان', 'Sa\'d': 'سعد', 'Farmer': 'مزارع',
  'Someone emptied my storehouse in the night: the village\'s seed grain, kept back for the autumn sowing. Without it there is no harvest next year. The tracks go west.': 'أفرغ أحدهم مخزني في الليل: بذار القرية الذي حفظناه لزرع الخريف. من دونه لا حصاد في العام القادم. الآثار تتّجه غربًا.',
  'Follow the tracks west and drive off the foragers with the grain cart.': 'اتبع الآثار غربًا واطرد الجُباة مع عربة الحبوب.',
  'The cart was already empty. Find the farmer the foragers spoke of, south-west of the road.': 'كانت العربة فارغة. ابحث عن المزارع الذي تحدّث عنه الجُباة، جنوب غرب الطريق.',
  'Speak with Sa\'d': 'كلّم سعدًا',
  'Yes, I took it. The Rum burned my fields to the root, and I have four children who ate grass last week.': 'نعم، أخذته. أحرق الروم حقولي حتى الجذور، ولي أربعة أطفال أكلوا العشب الأسبوع الماضي.',
  'Rifa\'a has a village behind him too.': 'ورفاعة وراءه قرية أيضًا.',
  'Then take it back. Half is buried by the old well. The soldiers dug up the rest and kept it.': 'فخذه إذن. نصفه مدفون عند البئر القديمة. والباقي نبشه الجند واحتفظوا به.',
  'Take the rest of the seed back from the soldiers\' camp to the south.': 'استعد باقي البذار من معسكر الجند في الجنوب.',
  'Take the seed sacks': 'خذ أكياس البذار', 'Sacks of Seed Grain': 'أكياس البذار',
  'Bring the seed to Rifa\'a, and tell him about Sa\'d.': 'أعد البذار إلى رفاعة، وأخبره عن سعد.',
  'Your seed. Half of it was taken by a man whose fields were burned. He told me where the rest was.': 'هذا بذارك. أخذ نصفه رجل أُحرقت حقوله. وهو من دلّني على الباقي.',
  'A thief who gives back half is a neighbour. ... Send him to me. He can sow beside us this autumn, and we will see how the bread comes out.': 'السارق الذي يردّ النصف جار. ... أرسله إليّ. يزرع بجانبنا هذا الخريف، ونرى كيف يخرج الخبز.',
  'Rifa\'a and Sa\'d will sow the same fields.': 'سيزرع رفاعة وسعد الحقول نفسها.',
  'The Missing Mashuf': 'المشحوف المفقود', 'Khalaf': 'خلف', 'Boat-builder': 'صانع القوارب', 'Dahir': 'ظاهر', 'Moschos': 'موسخوس',
  'My new mashuf is gone from the landing: forty days of work, the pitch still soft. Someone saw it poled west into the reeds at dawn.': 'اختفى مشحوفي الجديد من المرسى: أربعون يومًا من العمل، والقار لم يجفّ بعد. رآه أحدهم يُدفع غربًا إلى القصب عند الفجر.',
  'Search the reeds to the west for Khalaf\'s boat.': 'ابحث في القصب غربًا عن قارب خلف.',
  'Someone is hiding in the reeds nearby. Find him.': 'أحدهم يختبئ في القصب القريب. جده.',
  'Speak with the boy': 'كلّم الصبي',
  'Do not tell Khalaf it was me! Kallinikos\' men said they would burn our hut if I did not bring them a boat.': 'لا تخبر خلفًا أنّه أنا! قال رجال كالينيكوس إنّهم سيحرقون كوخنا إن لم آتهم بقارب.',
  'Where is it now?': 'وأين هو الآن؟',
  'At their landing in the south. They load it with what they take from the villages.': 'عند مرساهم في الجنوب. يحمّلونه بما ينهبونه من القرى.',
  'Take the mashuf\'s pole and paddle from the raiders\' landing in the south.': 'خذ مردي المشحوف ومجدافه من مرسى المغيرين في الجنوب.',
  'Take the pole and paddle': 'خذ المردي والمجداف', 'Khalaf\'s Punting Pole': 'مردي خلف',
  'Tell Khalaf where his boat is, and who took it.': 'أخبر خلفًا أين قاربه، ومن أخذه.',
  'Your boat is at their landing; you can pole it home now. A boy took it, because they threatened his family.': 'قاربك عند مرساهم، ويمكنك أن تعيده الآن. أخذه صبي لأنّهم هدّدوا أهله.',
  'Dahir. His father taught me to bend reed. ... Tell him he can come and learn the pitch from me. A boy who can steal a mashuf can build one.': 'ظاهر. أبوه علّمني ثني القصب. ... قل له أن يأتي ويتعلّم القار منّي. الصبي الذي يسرق مشحوفًا يستطيع أن يبنيه.',
  'Dahir is learning to build boats.': 'ظاهر يتعلّم بناء القوارب.',
  'The Bath-Keeper\'s Copper': 'نحاس صاحب الحمّام', 'Hammad': 'حمّاد', 'Bath-keeper': 'صاحب الحمّام', 'Ghalib': 'غالب', 'Coppersmith': 'نحّاس', 'Doukitzes': 'دوكيتزس',
  'Krateros\' men tore the great copper boiler out of my bathhouse and carted it off. A quarter that cannot wash cannot stay well. They went east.': 'انتزع رجال كراتيروس المرجل النحاسي الكبير من حمّامي وحملوه على عربة. الحيّ الذي لا يغتسل لا يبقى معافى. ذهبوا شرقًا.',
  'Catch the men who carted off the boiler, east of the khan.': 'الحق بالرجال الذين حملوا المرجل، شرق الخان.',
  'The boiler was sold. Find the coppersmith who bought it, in the south lanes.': 'بيع المرجل. ابحث عن النحّاس الذي اشتراه في الأزقّة الجنوبية.',
  'Speak with Ghalib': 'كلّم غالبًا',
  'I paid good silver for that boiler, and I did not know whose it was. Now the same men come back each week for more.': 'دفعت فضّة جيّدة ثمن ذلك المرجل، ولم أعرف لمن هو. والآن يعود الرجال أنفسهم كلّ أسبوع يطلبون المزيد.',
  'Then they will not come back again.': 'إذن لن يعودوا بعد اليوم.',
  'If they do not, Hammad can have his boiler for the price of the cart. They wait for me by the old wall.': 'إن لم يعودوا، فليأخذ حمّاد مرجله بثمن العربة. إنّهم ينتظرونني عند السور القديم.',
  'Drive off the men who squeeze Ghalib, by the old wall.': 'اطرد الرجال الذين يبتزّون غالبًا عند السور القديم.',
  'Tell Hammad his boiler is coming home.': 'أخبر حمّادًا أنّ مرجله عائد.',
  'Ghalib is an honest man, then. I will pay the cart and his trouble.': 'غالب رجل أمين إذن. سأدفع ثمن العربة وتعبه.',
  'Come and wash when it is hot again, guard. The first bath is yours.': 'تعال واغتسل حين يسخن من جديد يا حارس. أوّل حمّام لك.',
  'The bathhouse is warm again.': 'الحمّام دافئ من جديد.',
  'The Pilot\'s Lantern': 'فانوس الدليل', 'Bakr': 'بكر', 'River pilot': 'دليل النهر', 'Mundhir': 'منذر', 'Lamplighter': 'موقد المصابيح',
  'My brother-in-law Mundhir went to the far boatyard with a lantern last night and did not come back. His wife has not slept.': 'ذهب صهري منذر إلى دار القوارب البعيدة بفانوس الليلة الماضية ولم يعد. زوجته لم تنم.',
  'Search the boatyard east of the quays.': 'فتّش دار القوارب شرق الأرصفة.',
  'His lantern lay broken on the slip. Follow the trail into the warehouse lanes.': 'وُجد فانوسه مكسورًا على المزلق. اتبع الأثر إلى أزقّة المخازن.',
  'Speak with Mundhir': 'كلّم منذرًا',
  'I saw them loading stolen bales onto a barge, and they saw me. I have been hiding here since.': 'رأيتهم يحمّلون بالات مسروقة على مركب، ورأوني. وأنا مختبئ هنا منذ ذلك الحين.',
  'Can you walk?': 'أتستطيع المشي؟',
  'If you walk beside me. They will be watching the quays.': 'إن مشيت بجانبي. سيراقبون الأرصفة.',
  'Bring Mundhir home to the quays.': 'أعد منذرًا إلى بيته عند الأرصفة.',
  'Speak with Bakr.': 'كلّم بكرًا.',
  'Home, and on his own feet. My sister will cry for an hour and then shout at him for two.': 'عاد إلى البيت على قدميه. ستبكي أختي ساعة ثمّ تصرخ عليه ساعتين.',
  'Any boat on this river will carry you, guard. Say my name.': 'أيّ قارب على هذا النهر سيحملك يا حارس. اذكر اسمي.',
  'Mundhir is home.': 'منذر في بيته.',
  'The Shepherd\'s Flock': 'قطيع الراعي', 'Ghaylan': 'غيلان', 'Shepherd': 'راعٍ', 'Niketas': 'نيكيتاس',
  'Tatzates\' men drove my flock into the western gorges when they came through. Three hundred head. Someone has been watering them; I see the tracks at the springs.': 'ساق رجال تاتزاتس قطيعي إلى الوديان الغربية حين مرّوا. ثلاثمئة رأس. أحدهم يسقيها؛ أرى الآثار عند العيون.',
  'Clear the men holding the western pass.': 'أخلِ الممرّ الغربي من الرجال الذين يحرسونه.',
  'Find whoever has been watering the flock, up the gorge.': 'جد من يسقي القطيع، أعلى الوادي.',
  'Speak with the old soldier': 'كلّم الجندي العجوز',
  'The sheep? I have kept them alive. Thirty years I have marched for the Rum. I am done with it.': 'الغنم؟ أبقيتها حيّة. ثلاثون عامًا وأنا أسير مع الروم. اكتفيت.',
  'Your company will hang you if they find you.': 'سيشنقك رفاقك إن وجدوك.',
  'Then walk me to the east road, Baghdadi, and I will tell your shepherd where every ewe is penned.': 'فامشِ معي إلى الطريق الشرقي يا بغدادي، وسأخبر راعيك أين حُبست كلّ نعجة.',
  'Walk Niketas to the east road. His old company is looking for him.': 'امشِ مع نيكيتاس إلى الطريق الشرقي. رفاقه القدامى يبحثون عنه.',
  'Tell Ghaylan where his flock is penned.': 'أخبر غيلان أين حُبس قطيعه.',
  'In the old fold under the cliff fort. A Rum soldier kept them alive, and then went home.': 'في الحظيرة القديمة تحت حصن الجرف. جندي رومي أبقاها حيّة، ثمّ عاد إلى بيته.',
  'Then there is one less soldier in the world, and three hundred more sheep. A good trade.': 'إذن في الدنيا جندي أقلّ وثلاثمئة شاة أكثر. صفقة رابحة.',
  'Ghaylan\'s flock is home.': 'قطيع غيلان في حظيرته.',
};
