// Round 26: Arabic for the new troops, Hamrin content, the Hamrin story, boss phases and the camp's own stories (merged last in story_ar.js)
export const AR26 = {
  // ---- the new troops
  'Bandophoros': 'حامل الراية', 'Skoutatos of the Wall': 'جنديّ جدار الدروع', 'Hippotoxotes': 'رامي الخيل', 'Unhorsed Hippotoxotes': 'رامي خيل راجل',
  'A standard rallies his men: cut him down first': 'رايةٌ تشدّ أزر رجاله: أسقِط حاملها أولًا',
  'The standard. Take the standard.': 'الراية. أسقِطوا الراية.',
  'The standard falls: his men waver': 'سقطت الراية: تزعزع رجاله',
  'A shield wall: get round it, or break a guard with heavy blows': 'جدار من الدروع: التفّ حوله، أو اكسر دفاع أحدهم بضربات ثقيلة',
  'A horse archer circles: close in as he passes': 'رامي خيل يدور حولك: انقضّ عليه حين يمرّ',
  'Guard broken!': 'انكسر دفاعه!',
  // ---- the bosses' second half
  'Bardanes calls up his standard': 'بردانس يستدعي رايته',
  'Again!': 'مرّة أخرى!', 'Fire on the water!': 'نار على الماء!', 'Burning beams!': 'جذوع مشتعلة!', 'Feint!': 'خدعة!',
  'A feint: wait for the second glint': 'خدعة: انتظر اللمعة الثانية',
  'Cart!': 'عربة!', 'Marked': 'مُستهدَف',
  // ---- the Hamrin hills: letters and the champion
  'Tatzates\' quiver lid': 'غطاء جعبة تاتزاتيس',
  'All fifteen found. The Teacher\'s Inkwell is yours.': 'وجدتَها الخمس عشرة كلّها. محبرة المعلّم لك.',
  'A letter in a soldier\'s hand: "The frontier is eight days off. Tatzates says the hill men will let us through for silver. We have no silver left. We have the Pages, and they eat nothing."': 'رسالة بخطّ جندي: «الثغر على ثمانية أيام. يقول تاتزاتيس إن أهل الجبال سيدعوننا نمرّ مقابل الفضة. لم يبقَ معنا فضة. معنا الصحائف، ولا تأكل شيئًا.»',
  'A leaf of the Pages, pressed flat in a saddlebag: "Count the stars you can name. Then count the ones you cannot. Begin with the second number."': 'ورقة من الصحائف، مضغوطة في خُرج: «عُدَّ النجوم التي تعرف أسماءها. ثم عُدَّ التي لا تعرفها. وابدأ بالعدد الثاني.»',
  'A quiver lid scratched with a bowman\'s tally, marks in rows of five. Beside one mark, cut later and deeper: "the boy on the dune."': 'غطاء جعبة حُفرت عليه عدّة رامٍ، خطوط في صفوف من خمسة. وبجانب خطّ منها، حُفر لاحقًا وأعمق: «الفتى على الكثيب.»',
  'Varazes': 'فارازيس',
  'The frontier is three days north. You will not see it.': 'الثغر على ثلاثة أيام شمالًا. لن تراه.',
  // ---- the Hamrin story
  'Scout': 'الطليعة',
  'The hill men brought this one in at dawn. One of Tatzates\' scouts.': 'جاء به أهل الجبال عند الفجر. واحد من طلائع تاتزاتيس.',
  'He holds the frontier road. Four holds, and his ravine is the last. He will not run again.': 'إنه يمسك طريق الثغر. أربعة حصون، ووادِيه آخرها. لن يهرب هذه المرّة.',
  'Good. Neither will I.': 'حسنًا. ولا أنا.',
  'Salim. Whatever waits at the end of that road, it will not give Jabir back.': 'يا سالم. مهما كان في آخر ذلك الطريق، فلن يردّ إليك جابرًا.',
  'I know. I am not going for Jabir. I am going so that it ends.': 'أعلم. لستُ ذاهبًا من أجل جابر. أنا ذاهب كي ينتهي الأمر.',
  'An arrow strikes the ground beside Salim. A strip of cloth is tied to the shaft.': 'يرتكز سهمٌ في الأرض بجانب سالم. على قصبته شريط من قماش.',
  '"Two holds. You are better than I was paid to expect. Come to the ravine, guard. I will not hide from you."': '«حصنان. أنت أمهر مما دُفع لي لأتوقّع. تعالَ إلى الوادي يا حارس. لن أختبئ منك.»',
  'He wants me angry.': 'يريدني غاضبًا.',
  'Then go to him calm. Anger misses.': 'فاذهب إليه هادئًا. الغضب يُخطئ الرمية.',
  'The boy on the dune. I remember the wind that day. Not his face.': 'الفتى على الكثيب. أذكر الريح ذلك اليوم. لا أذكر وجهه.',
  'I remember it for both of us.': 'أنا أذكره عنّا كلينا.',
  'Tatzates is beaten. His arrow killed Jabir. What becomes of him?': 'هُزم تاتزاتيس. سهمه قتل جابرًا. ما مصيره؟',
  'Bind him. Baghdad will judge him.': 'قيّده. بغداد ستحكم فيه.',
  'Cut his bowstring and let him walk.': 'اقطع وتر قوسه ودعه يمضي.',
  'Baghdad will hear every name you were paid for. Jabir\'s first.': 'ستسمع بغداد كلّ اسم قبضتَ ثمنه. واسم جابر أوّلها.',
  'And when it is done, guard, the dune will still be there.': 'وحين ينتهي الأمر يا حارس، سيبقى الكثيب حيث هو.',
  'No more arrows. Walk north, and do not turn round.': 'لا سهام بعد اليوم. امضِ شمالًا، ولا تلتفت.',
  'You let me live. I do not know what to do with that.': 'تركتني أعيش. لا أدري ما أصنع بذلك.',
  'The bowman was taken down the Diyala to Baghdad in chains, to answer before the qadi.': 'حُمل الرامي في ديالى إلى بغداد مقيّدًا، ليجيب أمام القاضي.',
  'Tatzates walked north toward the frontier with a cut bowstring. No one on the Diyala saw him again.': 'مضى تاتزاتيس شمالًا نحو الثغر بوترٍ مقطوع. ولم يره أحد على ديالى بعدها.',
  'That night Salim set a lamp on the Diyala for Jabir, and let the current take it.': 'في تلك الليلة وضع سالم سراجًا على ديالى لجابر، وترك التيّار يحمله.',
  'Tatzates will answer before the qadi in Baghdad.': 'سيجيب تاتزاتيس أمام القاضي في بغداد.',
  'Tatzates walks north with a cut bowstring.': 'يمضي تاتزاتيس شمالًا بوترٍ مقطوع.',
  'A qadi, not a blade. Jabir would have argued for the same.': 'قاضٍ لا سيف. كان جابر سيجادل في الشيء نفسه.',
  'You let him walk. Good. We keep the account by remembering, not by killing.': 'تركته يمضي. حسنًا. نحفظ الحساب بالتذكّر، لا بالقتل.',
};
