// Round 35: Arabic for Season One rebuilt (Jabir taken alive, the trade, the rescue) and the later lines that changed
// with it. Merged last in story_ar.js. Backtick strings, so apostrophes and quotes stay as they are in the English.
export const AR35 = {
  // ---- the cards
  [`Why keep a wounded guard alive?`]: `لماذا يُبقون حارسًا جريحًا على قيد الحياة؟`,
  [`The voice in the dark knows where Jabir is.`]: `الصوت في الظلام يعرف أين جابر.`,
  [`The kilns are burning. Jabir is inside.`]: `الأتونات تحترق. وجابرٌ في داخلها.`,
  [`Ishaq, for Jabir. At dawn.`]: `إسحاق، مقابل جابر. عند الفجر.`,
  [`One hour earlier`]: `قبل ساعة`,
  // ---- previously (only when a saved chronicle is resumed)
  [`On the dune, the raiders wounded Jabir and took him alive, with the cedar chest.`]: `على الكثيب، جرح المغيرون جابرًا وأخذوه حيًّا، ومعه صندوق الأرز.`,
  [`They left a message tied to an arrow: "The astronomer, for your brother."`]: `وتركوا رسالةً مربوطة بسهم: «الفلكيّ، مقابل أخيك.»`,
  [`The chest held the Pages, in Ishaq's own cipher. Only he can read them.`]: `كان في الصندوق الأوراق، مكتوبةً بشيفرة إسحاق نفسه. لا يقرؤها أحدٌ غيره.`,
  [`The riders carried Jabir east, to the old caravanserai.`]: `حمل الفرسان جابرًا شرقًا، إلى الخان القديم.`,
  [`At the broken dam, a voice in the dark knew Salim's name.`]: `وعند السدّ المكسور، عرف صوتٌ في الظلام اسم سالم.`,
  [`Photeinos fell in the broken dam.`]: `سقط فوتينوس في السدّ المكسور.`,
  [`He said Jabir was at the kilns, and that someone close to Ishaq writes to the envoy.`]: `قال إن جابرًا في الأتونات، وإن أحد المقرّبين من إسحاق يكاتب الموفد.`,
  [`Then the kilns began to burn.`]: `ثم بدأت الأتونات تحترق.`,
  [`Salim fought through the burning kilns. Jabir was already gone.`]: `شقّ سالم طريقه عبر الأتونات المحترقة. كان جابر قد نُقل.`,
  [`Ishaq confessed: he put the chest on Jabir's mules on purpose.`]: `اعترف إسحاق: وضع الصندوق على بغال جابر عن قصد.`,
  [`Bardanes fouled the canal, and named his price: Ishaq for Jabir, at the old arch, at dawn.`]: `لوّث بردانس القناة، وسمّى ثمنه: إسحاق مقابل جابر، عند الطاق القديم، عند الفجر.`,
  [`Salim sent word that they would come.`]: `أرسل سالم أنهما سيأتيان.`,
  [`Salim sent word: no trade.`]: `أرسل سالم: لا مقايضة.`,
  // ---- Episode One: the caravan, the arrow, the night raid, waking
  [`The Sawad, outside Baghdad, in the year 813. The caliph's sons are at war. The roads belong to no one.`]: `السواد، خارج بغداد، سنة ٨١٣. ابنا الخليفة في حرب. والطرق لا صاحب لها.`,
  [`The arrow took him under the ribs. Then the dark came, and the raiders came back with it.`]: `أصابه السهم تحت الأضلاع. ثم جاء الظلام، وعاد المغيرون معه.`,
  [`Leave me, Salim. Run!`]: `اتركني يا سالم. اهرب!`,
  [`Not without you.`]: `ليس من دونك.`,
  [`They took Jabir alive. And the cedar chest.`]: `أخذوا جابرًا حيًّا. وصندوق الأرز.`,
  [`Easy. You were struck from behind. Do not stand yet.`]: `على مهلك. ضُربت من الخلف. لا تقم بعد.`,
  [`Jabir. Where is Jabir?`]: `جابر. أين جابر؟`,
  [`They took him. Alive. And the chest.`]: `أخذوه. حيًّا. والصندوق معه.`,
  [`They left this in the sand, where the chest had stood.`]: `وتركوا هذا في الرمل، حيث كان الصندوق.`,
  [`An arrow, with a strip of linen tied to the shaft. Salim could not read it.`]: `سهم، رُبطت إلى عوده قطعة كتّان. لم يكن سالم يقرأ.`,
  [`What does it say?`]: `ماذا تقول؟`,
  [`"The astronomer, for your brother."`]: `«الفلكيّ، مقابل أخيك.»`,
  // ---- Episode Two
  [`Who knew the chest was in our caravan?`]: `من كان يعلم أن الصندوق في قافلتنا؟`,
  [`East, to the old caravanserai by the broken dam.`]: `شرقًا، إلى الخان القديم عند السدّ المكسور.`,
  [`Why would they want you?`]: `ولماذا يريدونك أنت؟`,
  [`Because the chest never held instruments. It held the Pages of my teacher. There is no other copy in the world.`]: `لأن الصندوق لم يكن فيه آلات قط. كانت فيه أوراق أستاذي. وليس في الدنيا نسخةٌ غيرها.`,
  [`He wrote them in a cipher of his own. I am the only man alive who can read it.`]: `كتبها بشيفرةٍ من وضعه. وأنا الحيّ الوحيد الذي يقرؤها.`,
  [`So the Pages are worthless to them without you. And my brother is the price.`]: `إذن لا قيمة للأوراق عندهم من دونك. وأخي هو الثمن.`,
  [`An envoy from Constantinople came under the smoke of this war. His men want the book, and the man who reads it.`]: `جاء موفدٌ من القسطنطينية تحت دخان هذه الحرب. يريد رجاله الكتاب، والرجل الذي يقرؤه.`,
  [`Do not leave this village, astronomer. If you run, I will find you before they do.`]: `لا تغادر هذه القرية أيها الفلكيّ. إن هربت، وجدتُك قبلهم.`,
  [`Riders, at first light. A mule with a cedar chest. And a man tied over a horse, bleeding through his shirt.`]: `فرسان، مع أول الضوء. بغلٌ عليه صندوق أرز. ورجلٌ مربوط على ظهر فرس، ينزف من خلال قميصه.`,
  [`Alive?`]: `حيّ؟`,
  [`He lifted his head when they passed the well. He was looking back down the road. For you, I think.`]: `رفع رأسه حين مرّوا بالبئر. كان ينظر خلفه إلى الطريق. يبحث عنك، فيما أظن.`,
  [`Where did they take him?`]: `إلى أين أخذوه؟`,
  [`And one stayed behind. He sat his horse on the rise and watched your tent all morning.`]: `وبقي واحدٌ منهم. وقف بفرسه على الربوة يراقب خيمتك طوال الصباح.`,
  [`Then he can show me the way.`]: `إذن سيدلّني على الطريق.`,
  [`He knew which tent was mine. They know who I am.`]: `كان يعرف أيّ خيمةٍ خيمتي. إنهم يعرفون من أنا.`,
  [`Follow Jabir to the broken dam behind the caravanserai`]: `اتبع أثر جابر إلى السدّ المكسور خلف الخان`,
  [`Tied to the door of the broken dam: a headcloth, stiff with blood.`]: `مربوطة إلى باب السدّ المكسور: عمامةٌ يبست بالدم.`,
  [`Jabir's.`]: `عمامة جابر.`,
  [`You are the brother.`]: `أنت الأخ.`,
  [`He is alive. Come in, and I will tell you for how long.`]: `إنه حيّ. ادخل، وسأخبرك إلى متى.`,
  // ---- Episodes Three and Four
  [`Enter the Broken Dam. Make the voice in the dark talk.`]: `ادخل السدّ المكسور. واجعل الصوت في الظلام يتكلّم.`,
  [`Your brother is at the kilns, with Olbianos. And your astronomer has a friend who writes to the envoy.`]: `أخوك في الأتونات، عند أولبيانوس. ولفلكيّك صديقٌ يكاتب الموفد.`,
  [`They are burning the Pages. And Jabir is in there.`]: `إنهم يحرقون الأوراق. وجابرٌ هناك.`,
  [`Get into the kiln galleries. Jabir and the Pages are inside.`]: `ادخل دهاليز الأتونات. جابر والأوراق في داخلها.`,
  [`Your brother left an hour ago, for Bardanes. I copied for Ishaq once. I know how he hides things. A guard's mules.`]: `غادر أخوك قبل ساعة، إلى بردانس. كنت أنسخ لإسحاق يومًا. أعرف كيف يخبّئ الأشياء. بغال حارس.`,
  [`The last cell in the galleries was empty. Scratched into the wall with a buckle: a spear, and Salim's name.`]: `كانت آخر زنزانةٍ في الدهاليز فارغة. وعلى الجدار، محفورٌ بإبزيم: رمح، واسم سالم.`,
  [`He came out with {n} scorched leaves held against his chest. Jabir was gone. Olbianos had said where: to Bardanes.`]: `خرج وقد ضمّ إلى صدره {n} ورقة محروقة. كان جابر قد نُقل. وقد قال أولبيانوس إلى أين: إلى بردانس.`,
  // ---- Episode Five
  [`Go back to the camp. Ishaq has some answering to do.`]: `عُد إلى المخيّم. على إسحاق أن يجيب.`,
  [`Olbianos copied for you once. He said you put the chest on Jabir's mules. On purpose.`]: `كان أولبيانوس ينسخ لك يومًا. قال إنك وضعت الصندوق على بغال جابر. عن قصد.`,
  [`Bardanes has fouled the canal above the village. He wants them thirsty enough to hand me over.`]: `لوّث بردانس القناة فوق القرية. يريدهم عطاشى حتى يسلّموني.`,
  [`A Rum deserter hides by the kiln yard. He may know where Jabir is held.`]: `فارٌّ من الروم يختبئ قرب ساحة الأتونات. لعلّه يعرف أين يُحتجز جابر.`,
  [`Your brother is alive. Bardanes keeps him in the vault under the old arch. He will not trade fairly. He never has.`]: `أخوك حيّ. يحتجزه بردانس في القبو تحت الطاق القديم. لن يقايض بإنصاف. لم يفعل قط.`,
  [`From Bardanes, to the guard. The astronomer, for your brother. At the old arch, at dawn.`]: `من بردانس، إلى الحارس. الفلكيّ مقابل أخيك. عند الطاق القديم، عند الفجر.`,
  [`Bring him, and the village drinks again. Come without him, and your brother does not see the sun.`]: `أحضِره، وتشرب القرية من جديد. تعالَ من دونه، ولن يرى أخوك الشمس.`,
  [`Behind you, Ishaq has heard every word.`]: `خلفك، سمع إسحاق كلّ كلمة.`,
  [`Tell Bardanes we will come. Both of us.`]: `قل لبردانس إننا سنأتي. كلانا.`,
  [`Tell Bardanes there is no trade.`]: `قل لبردانس: لا مقايضة.`,
  [`Tell him we will be there.`]: `قل له إننا سنكون هناك.`,
  [`No trade. Tell him I am coming for my brother. Alone.`]: `لا مقايضة. قل له إنني آتٍ من أجل أخي. وحدي.`,
  [`Then I will tell him.`]: `إذن سأبلغه.`,
  // ---- Episode Six
  [`Four names. Not five. Not Jabir.`]: `أربعة أسماء. لا خمسة. ليس جابر.`,
  [`That evening the village children learned four names, and said them at the water.`]: `في ذلك المساء حفظ أطفال القرية أربعة أسماء، وردّدوها عند الماء.`,
  [`You told him we would both come. Did you mean it?`]: `قلتَ له إننا سنأتي كلانا. أكنت تعني ذلك؟`,
  [`You walk with me until I say stop. Then you run, and you do not look back.`]: `تمشي معي حتى أقول قف. ثم تركض، ولا تلتفت.`,
  [`You could have traded me. No one would have blamed you.`]: `كان بوسعك أن تقايض بي. ما كان أحدٌ ليلومك.`,
  [`Jabir would. He would never forgive me.`]: `جابر كان سيلومني. ما كان ليغفر لي أبدًا.`,
  [`Bring yourself back, Salim. And bring him.`]: `عُد يا سالم. وأعِده معك.`,
  [`Light a lamp. I will bring him home before it burns down.`]: `أشعل سراجًا. سأعيده قبل أن ينطفئ.`,
  [`Reach the old arch before dawn. Bardanes has Jabir.`]: `بلّغ الطاق القديم قبل الفجر. جابر عند بردانس.`,
  [`You came, guard. But where is the astronomer? No matter. I will take him after you.`]: `جئتَ أيها الحارس. لكن أين الفلكيّ؟ لا يهمّ. سآخذه بعدك.`,
  [`No trade, then. Your brother said you were stubborn. I will take you both.`]: `لا مقايضة إذن. قال أخوك إنك عنيد. سآخذكما كليكما.`,
  [`Dawn, guard. You are late. Your brother has been watching the sky.`]: `الفجر أيها الحارس. تأخّرت. أخوك يراقب السماء منذ حين.`,
  [`Where is my brother?`]: `أين أخي؟`,
  [`Under the arch, in a vault that smelled of lamp oil, Salim found him.`]: `تحت الطاق، في قبوٍ تفوح منه رائحة زيت السُّرج، وجده سالم.`,
  [`You took your time, little brother.`]: `تأخّرت يا أخي الصغير.`,
  [`You came back for me once, in the flood. I owed you.`]: `عدتَ من أجلي مرّة، في الفيضان. كان دَينًا عليّ.`,
  [`Ka'b. Sinan. 'Awf. Mazin.`]: `كعب. سنان. عوف. مازن.`,
  [`Thanks to you, his words will be read. And your brother will see Baghdad after all.`]: `بفضلك ستُقرأ كلماته. وسيرى أخوك بغداد في آخر الأمر.`,
  [`I heard them, in the vault. The rest went east by boat, into the marshes.`]: `سمعتهم في القبو. ذهب الباقي شرقًا بالقوارب، إلى الأهوار.`,
  [`Kallinikos has them. And he has the fire.`]: `هي عند كالينيكوس. وعنده النار.`,
  // ---- the later acts
  [`The raiders took Jabir alive. And the chest.`]: `أخذ المغيرون جابرًا حيًّا. والصندوق.`,
  [`I am Ishaq. I hired your caravan. They took your brother alive, and I am sorry.`]: `أنا إسحاق. استأجرتُ قافلتكم. أخذوا أخاك حيًّا، وأنا آسف.`,
  [`Tatzates is beaten. His arrow nearly killed Jabir. What becomes of him?`]: `هُزم تاتزاتيس. كاد سهمه يقتل جابرًا. ما مصيره؟`,
  [`That night Salim set four lamps on the Diyala, one for each guard of the caravan, and let the current take them.`]: `في تلك الليلة وضع سالم أربعة سُرج على ديالى، واحدًا لكل حارسٍ من القافلة، وترك التيار يأخذها.`,
  [`Jabir always wanted to see Baghdad. I am glad he is not seeing it like this.`]: `كان جابر يتمنّى دائمًا أن يرى بغداد. يسرّني أنه لا يراها هكذا.`,
  [`Salim. Whatever waits at the end of that road, it will not heal Jabir any faster.`]: `يا سالم. أيًّا كان ما ينتظر في آخر ذلك الطريق، فلن يشفي جابرًا أسرع.`,
  [`I nearly cost you a brother. I will spend the rest of my life on that account.`]: `كدتُ أكلّفك أخاك. سأقضي ما بقي من عمري في هذا الحساب.`,
  [`You were a caravan guard. Baghdad needs safe roads more than it needs one more scholar. Go home first. Your brother is waiting for you on the quays.`]: `كنتَ حارس قوافل. بغداد تحتاج إلى طرقٍ آمنة أكثر مما تحتاج إلى عالمٍ آخر. اذهب إلى بيتك أولًا. أخوك ينتظرك على الشطّ.`,
  [`That evening Salim and Jabir set a lamp on the river for each guard of the caravan. Jabir could stand by then.`]: `في ذلك المساء وضع سالم وجابر على النهر سراجًا لكل حارسٍ من القافلة. كان جابر يقوى على الوقوف حينها.`,
  [`You are Jabir's brother. I am <b>Ishaq</b>. I hired your caravan. He is alive, and he is on my account now: I mean to bring him home.`]: `أنت أخو جابر. أنا <b>إسحاق</b>. استأجرتُ قافلتكم. إنه حيّ، وهو في ذمّتي الآن: أعتزم أن أعيده إلى بيته.`,
  [`By the fire, Salim thinks of Jabir on his pallet in the camp, complaining about the food. It is the best sound he knows.`]: `عند النار، يفكّر سالم في جابر على فراشه في المخيّم، يتذمّر من الطعام. لا يعرف صوتًا أحبّ إليه من ذلك.`,
  [`A qadi, not a blade. Jabir will say the same.`]: `قاضٍ، لا سيف. وجابر سيقول الشيء نفسه.`,
  [`The other brother. Bardanes wanted one of you alive and one dead. I only managed the first.`]: `الأخ الآخر. أراد بردانس أحدكما حيًّا والآخر ميتًا. لم أُنجز إلا الأولى.`,
  [`Your brother bled for a dead man's words, and he lived, because you would not let him go. When he can walk, I will take him through the House of Wisdom and show him every shelf. He says he will be bored. He is lying.`]: `نزف أخوك من أجل كلمات رجلٍ ميت، وعاش، لأنك لم تتخلَّ عنه. حين يقدر على المشي، سآخذه إلى بيت الحكمة وأريه كلّ رفّ. يقول إنه سيضجر. إنه يكذب.`,
  [`Then it is yours. A trophy belongs with the man it was taken from, not with the men who took it.`]: `إذن هو لك. الغنيمة تعود إلى من أُخذت منه، لا إلى من أخذها.`,
  [`He will want it back. He will say I carried it wrong.`]: `سيريد استعادته. وسيقول إنني حملته على غير وجهه.`,
  [`Salim tied his brother's spear behind his saddle, to give back to him on the quays.`]: `ربط سالم رمح أخيه خلف سرجه، ليردّه إليه على الشطّ.`,
  [`We were meant to sleep at this khan the night they took Jabir.`]: `كان يُفترض أن ننام في هذا الخان الليلة التي أخذوا فيها جابرًا.`,
  [`"The Arab guard killed Doukas at the kilns. He fought like a man with nothing to lose. They say we took his brother on the road."`]: `«قتل الحارس العربي دوكاس عند الأتونات. قاتل كمن لا شيء لديه ليخسره. يقولون إننا أخذنا أخاه على الطريق.»`,
  // ---- Jabir in the camp (story35.js)
  [`Your brother, healing`]: `أخوك، يتعافى`, [`Your brother`]: `أخوك`, [`Jabir`]: `جابر`,
  [`Look at me. Standing. Ishaq says I can ride by the new moon.`]: `انظر إليّ. واقفٌ على قدميّ. يقول إسحاق إنني أستطيع الركوب مع الهلال الجديد.`,
  [`Then we ride home together.`]: `إذن نركب إلى البيت معًا.`,
  [`Two more days to Baghdad, I said. It took a little longer.`]: `يومان آخران إلى بغداد، قلتُ. استغرق الأمر أطول قليلًا.`,
  [`A little.`]: `قليلًا.`,
  [`Go and say your farewells. I will be here. I am not going anywhere without you again.`]: `اذهب وودّع. سأكون هنا. لن أذهب إلى أي مكانٍ من دونك بعد اليوم.`,
  [`Boats. You brought me into a marsh, on a boat, with a hole in my side.`]: `قوارب. جئتَ بي إلى هور، في قارب، وفي جنبي ثقب.`,
  [`You hate boats. I remember.`]: `تكره القوارب. أذكر ذلك.`,
  [`Water keeps no promises. Go and get the rest of the Pages, and come back dry.`]: `الماء لا يفي بوعد. اذهب وأحضر بقية الأوراق، وعُد جافًّا.`,
  [`So this is Baghdad. I thought it would be taller.`]: `إذن هذه بغداد. ظننتها أعلى.`,
  [`It was, before the siege.`]: `كانت كذلك، قبل الحصار.`,
  [`Then we will see it again when they build it back. Go on. Ishaq says Krateros means to burn what is left.`]: `إذن سنراها ثانيةً حين يعيدون بناءها. امضِ. يقول إسحاق إن كراتيروس ينوي إحراق ما بقي.`,
  [`I walked to the end of the quay this morning. Ishaq nearly fainted.`]: `مشيت إلى آخر الرصيف هذا الصباح. كاد إسحاق يُغمى عليه.`,
  [`You are supposed to be lying down.`]: `يُفترض أن تكون مستلقيًا.`,
  [`I have lain down for a month. Finish it, little brother. Then we both rest.`]: `استلقيت شهرًا كاملًا. أتمَّ الأمر يا أخي الصغير. ثم نستريح كلانا.`,
  [`They tell me the bowman from the dune is up in these hills.`]: `يقولون لي إن رامي الكثيب في هذه التلال.`,
  [`Tatzates. He is the last of them.`]: `تاتزاتيس. إنه آخرهم.`,
  [`Then do not make it about me. Make it about the road. A road should be safe for the next caravan.`]: `إذن لا تجعل الأمر من أجلي. اجعله من أجل الطريق. على الطريق أن يكون آمنًا للقافلة التالية.`,
  [`It is done, then. Good. Now the road is safe for the next caravan.`]: `انتهى الأمر إذن. حسنًا. صار الطريق آمنًا للقافلة التالية.`,
  [`My side itches. Ishaq says that is the healing. I say it is the reeds.`]: `جنبي يحكّني. يقول إسحاق إنه الشفاء. وأقول إنه القصب.`,
  [`Bring me a book from the paper-sellers. I will pretend to read it.`]: `أحضر لي كتابًا من الورّاقين. سأتظاهر بقراءته.`,
  [`Count the barges for me. Somebody should argue the tolls.`]: `عُدَّ المراكب عنّي. لا بدّ أن يجادل أحدٌ في المكوس.`,
  [`I will be on my feet by the time you come down from the hills. Then you can give me back my spear.`]: `سأكون على قدميّ حين تنزل من التلال. وعندها تردّ إليّ رمحي.`,
};
