// Round 34: Arabic for the chronicle's episodes (drama34.js). Merged last in story_ar.js.
// Backtick strings, so apostrophes and quotes stay as they are in the English.
export const AR34 = {
  // ---- the cards
  [`Episode`]: `الحلقة`, [`One`]: `الأولى`, [`Two`]: `الثانية`, [`Three`]: `الثالثة`, [`Four`]: `الرابعة`, [`Five`]: `الخامسة`, [`Six`]: `السادسة`,
  [`Previously`]: `في ما سبق`, [`To be continued`]: `يُتبَع`, [`Next`]: `التالي`, [`End of Season One`]: `نهاية الموسم الأول`,
  [`Tap to continue`]: `المس للمتابعة`, [`Tap to begin`]: `المس للبدء`,
  [`The Sawad, outside Baghdad, 813`]: `السواد، خارج بغداد، سنة ٨١٣`,
  [`Dusk on the Dune`]: `غسقٌ على الكثيب`, [`The Cedar Chest`]: `صندوق الأرز`, [`The Broken Dam`]: `السدّ المكسور`,
  [`Ash in the Kilns`]: `رمادٌ في الأتون`, [`Thirst`]: `العطش`, [`The Arch`]: `الطاق`, [`Season Two · The Marshes`]: `الموسم الثاني · الأهوار`,
  [`Two more days to Baghdad. Jabir will not see them.`]: `يومان آخران إلى بغداد. لن يراهما جابر.`,
  [`What is worth a brother?`]: `ما الذي يساوي أخًا؟`,
  [`Someone in the dark has been waiting for Salim.`]: `أحدٌ في الظلام ينتظر سالمًا.`,
  [`Every heartbeat, another page burns.`]: `مع كل نبضة، تحترق صفحة أخرى.`,
  [`Ishaq has answers. Salim may not want them.`]: `عند إسحاق أجوبة. وقد لا يريدها سالم.`,
  [`Dawn is coming. So is Salim.`]: `الفجر قادم. وسالمٌ قادم.`,
  [`Kallinikos has the last Pages. And he has the fire.`]: `عند كالينيكوس آخر الأوراق. وعنده النار.`,
  // ---- previously
  [`Jabir fell on the dune, to an arrow no one saw loosed.`]: `سقط جابر على الكثيب بسهمٍ لم يرَ أحدٌ من رماه.`,
  [`The raiders took the cedar chest he died for.`]: `وأخذ المغيرون صندوق الأرز الذي مات من أجله.`,
  [`And Ishaq said: it was never the instruments they wanted.`]: `وقال إسحاق: لم تكن الآلات ما يريدون.`,
  [`The chest held the Pages: the only copy of a dead teacher's words.`]: `كان في الصندوق الأوراق: النسخة الوحيدة من كلام معلّمٍ راحل.`,
  [`A watcher on the rise knew Salim by sight.`]: `وكان رقيبٌ على الربوة يعرف سالمًا بوجهه.`,
  [`At the broken dam, a voice in the dark was waiting for him.`]: `وعند السدّ المكسور، كان صوتٌ في الظلام ينتظره.`,
  [`Photeinos fell in the broken dam, and named the envoy's men.`]: `سقط فوتينوس في السدّ المكسور، وسمّى رجال السفير.`,
  [`Salim let him go.`]: `فأطلقه سالم.`,
  [`Salim bound him for the qadi.`]: `فقيّده سالم للقاضي.`,
  [`Then the smoke rose over the kiln yard. Olbianos is burning the Pages.`]: `ثم ارتفع الدخان فوق ساحة الأتون. أولبيانوس يحرق الأوراق.`,
  [`Salim fought through the kiln galleries to the fire.`]: `شقّ سالم طريقه في دهاليز الأتون إلى النار.`,
  [`He pulled {n} leaves out of the kiln mouth. The rest were ash.`]: `انتشل {n} ورقة من فم الأتون. وصار الباقي رمادًا.`,
  [`Olbianos died with a name in his mouth: Ishaq.`]: `ومات أولبيانوس واسمٌ على لسانه: إسحاق.`,
  [`Ishaq confessed: he chose Jabir's road for the chest.`]: `اعترف إسحاق: هو من اختار طريق جابر للصندوق.`,
  [`Bardanes fouled the canal. The village is dying of thirst.`]: `أفسد بردانس النهر. والقرية تموت عطشًا.`,
  [`His herald gave the elders until dawn to give Salim up.`]: `وأمهل رسوله الشيوخ حتى الفجر ليسلّموا سالمًا.`,
  // ---- objectives and the clock
  [`Hold the caravan. Drive off the riders.`]: `احمِ القافلة. اطرد الفرسان.`,
  [`Ask Khawla at the village well what she saw`]: `اسأل خولة عند بئر القرية عمّا رأت`,
  [`The watcher rides out to meet you`]: `الرقيب يخرج للقائك`,
  [`Follow the chest to the broken dam behind the caravanserai`]: `اتبع الصندوق إلى السدّ المكسور خلف الخان`,
  [`Enter the Broken Dam. Find the voice in the dark.`]: `ادخل السدّ المكسور. اعثر على الصوت في الظلام.`,
  [`Get to the kiln galleries before the Pages burn`]: `بلّغ دهاليز الأتون قبل أن تحترق الأوراق`,
  [`Go back to the camp. Ishaq has answers to give.`]: `عُد إلى المخيّم. على إسحاق أجوبة.`,
  [`A family on the canal road has had no clean water in two days`]: `عائلة على طريق النهر بلا ماءٍ نظيف منذ يومين`,
  [`A Rum deserter hides by the kiln yard. He may know where Bardanes is.`]: `فارٌّ من الروم يختبئ قرب ساحة الأتون. لعلّه يعرف مكان بردانس.`,
  [`Reach the old arch before dawn. Bardanes waits there.`]: `بلّغ الطاق القديم قبل الفجر. بردانس ينتظر هناك.`,
  [`The Pages are burning`]: `الأوراق تحترق`, [`{n} leaves left`]: `بقي {n} ورقة`, [`Dawn`]: `الفجر`,
  [`Not yet. Find out who took the chest first.`]: `ليس بعد. اعرف أولًا من أخذ الصندوق.`,
  [`The sky is going grey. Faster.`]: `السماء تشهب. أسرع.`,
  [`He was waiting for me. They know who I am.`]: `كان ينتظرني. إنهم يعرفون من أنا.`,
  [`The Watcher`]: `الرقيب`, [`Herald`]: `الرسول`, [`A voice in the dark`]: `صوتٌ في الظلام`,
  // ---- Episode 1
  [`The Sawad, outside Baghdad, in the year 813. The war between the caliph's sons is almost over.`]: `السواد، خارج بغداد، سنة ٨١٣. الحرب بين ابنَي الخليفة توشك أن تنتهي.`,
  [`Two more days to Baghdad, Salim. Then home.`]: `يومان آخران إلى بغداد يا سالم. ثم البيت.`,
  [`Too quiet, brother. I do not like it.`]: `هدوءٌ زائد يا أخي. لا يعجبني.`,
  [`Ishaq checks that cedar chest every hour. Star-glasses do not need that much love.`]: `إسحاق يتفقّد صندوق الأرز كل ساعة. مناظير النجوم لا تحتاج كل هذا الحنان.`,
  [`Then do not ask him what is in it.`]: `فلا تسأله ما فيه.`,
  [`Riders in Byzantine mail were waiting on the dunes.`]: `كان فرسانٌ في دروع الروم ينتظرون على الكثبان.`,
  [`Riders! Guard the camels, Salim!`]: `فرسان! احمِ الجمال يا سالم!`,
  [`Ha! Is that all the Rum could send?`]: `ها! أهذا كلّ ما أرسله الروم؟`,
  [`Jabir!`]: `جابر!`,
  [`The raiders came back over the dune while Salim held his brother.`]: `عاد المغيرون من وراء الكثيب وسالمٌ يضمّ أخاه.`,
  [`Jabir did not live to see Baghdad. The raiders had taken the cedar chest.`]: `لم يعش جابر ليرى بغداد. وكان المغيرون قد أخذوا صندوق الأرز.`,
  [`You are awake. Good. Listen to me, guard.`]: `صحوت. حسنًا. اسمعني أيها الحارس.`,
  [`It was never the instruments they wanted.`]: `لم تكن الآلات ما يريدون.`,
  // ---- Episode 2
  [`I am Ishaq. I hired your caravan. I am sorry about Jabir.`]: `أنا إسحاق. أنا من استأجر قافلتكم. يؤسفني ما جرى لجابر.`,
  [`He died for a chest of star-glasses?`]: `مات من أجل صندوق مناظير؟`,
  [`Not star-glasses. Pages. The writings of my old teacher. There is no other copy in the world.`]: `ليست مناظير. أوراق. كتابات معلّمي القديم. ولا نسخة أخرى منها في الدنيا.`,
  [`My brother is dead for a book.`]: `مات أخي من أجل كتاب.`,
  [`For the only copy of one. An envoy from Constantinople came under the smoke of the war, and his soldiers took it.`]: `من أجل النسخة الوحيدة منه. جاء سفيرٌ من القسطنطينية تحت دخان الحرب، وأخذه جنوده.`,
  [`Who knew it was in our caravan?`]: `من كان يعلم أنه في قافلتنا؟`,
  [`...Few. Fewer than should have.`]: `...قليلون. أقلّ ممّا ينبغي.`,
  [`Khawla, at the village well, saw riders pass at first light. Start with her.`]: `خولة، عند بئر القرية، رأت فرسانًا يمرّون مع أول الضوء. ابدأ بها.`,
  [`Riders, at first light. A mule with a cedar chest, and a man walking beside it like it was his child.`]: `فرسان، مع أول الضوء. بغلٌ عليه صندوق أرز، ورجلٌ يمشي بجانبه كأنه ولده.`,
  [`Where did they go?`]: `إلى أين ذهبوا؟`,
  [`East, to the old caravanserai, where the dam is broken.`]: `شرقًا، إلى الخان القديم، حيث السدّ المكسور.`,
  [`And one stayed. He sat his horse on the rise and watched the village all morning. He watched your tent, guard.`]: `وبقي واحد. وقف بفرسه على الربوة يراقب القرية طوال الصباح. كان يراقب خيمتك أيها الحارس.`,
  [`Then he is still out there.`]: `إذن ما زال هناك.`,
  [`You are the brother. Jabir's brother.`]: `أنت الأخ. أخو جابر.`,
  [`Come in, then. I have been waiting to meet the man who keeps coming.`]: `ادخل إذن. كنت أنتظر أن ألقى الرجل الذي لا يكفّ عن المجيء.`,
  // ---- Episode 3
  [`Black smoke over the kiln yard. Not brick smoke. Paper.`]: `دخانٌ أسود فوق ساحة الأتون. ليس دخان طوب. ورق.`,
  [`They are burning them.`]: `إنهم يحرقونها.`,
  [`Bardanes paid me in the envoy's gold. Olbianos has the Pages at the kilns. He means to burn them.`]: `دفع لي بردانس من ذهب السفير. الأوراق عند أولبيانوس في الأتون. ينوي أن يحرقها.`,
  // ---- Episode 4
  [`Ishaq always hid things where no one would look. A guard's mules. I knew him. I told them where to look.`]: `كان إسحاق يخبّئ الأشياء حيث لا ينظر أحد. بغال حارس. كنت أعرفه. فدللتهم أين ينظرون.`,
  [`Salim came out of the galleries with {n} scorched leaves held against his chest.`]: `خرج سالم من الدهاليز و{n} ورقة محروقة الأطراف مضمومة إلى صدره.`,
  [`A guard's mules. Ishaq knew. He put the chest on my brother's mules.`]: `بغال حارس. إسحاق كان يعلم. وضع الصندوق على بغال أخي.`,
  // ---- Episode 5
  [`Olbianos named you before he died. The chest rode on Jabir's mules because you put it there.`]: `سمّاك أولبيانوس قبل أن يموت. ركب الصندوق بغال جابر لأنك وضعته هناك.`,
  [`Yes.`]: `نعم.`,
  [`No one searches a caravan guard's mules. I chose your brother's road for the Pages. I did not know about the envoy.`]: `لا أحد يفتّش بغال حارس القافلة. اخترت طريق أخيك للأوراق. ولم أكن أعلم بالسفير.`,
  [`He asked me what was in the crates. I told him not to ask.`]: `سألني ما في الصناديق. قلت له لا تسأل.`,
  [`Ishaq waits. He does not look away.`]: `إسحاق ينتظر. لا يشيح بوجهه.`,
  [`You should have told us.`]: `كان عليك أن تخبرنا.`,
  [`Jabir would have carried it anyway.`]: `كان جابر سيحمله على أي حال.`,
  [`Ishaq! The canal! The water has gone black, and the goats will not drink it!`]: `يا إسحاق! النهر! صار الماء أسود، والمعز لا تشربه!`,
  [`Bardanes. He has fouled the canal above the village. Without water, the village has days. Not weeks.`]: `بردانس. أفسد النهر فوق القرية. بلا ماء، أمام القرية أيام. لا أسابيع.`,
  [`Bardanes waits at the old arch. He fouled the canal so the village would give you up to him. By dawn, they will.`]: `بردانس ينتظر عند الطاق القديم. أفسد النهر لتسلّمك القرية إليه. وقبل الفجر، ستفعل.`,
  [`A rider came up the canal road under a white cloth.`]: `صعد فارسٌ طريق النهر تحت راية بيضاء.`,
  [`From Bardanes, to the guard. The village drinks again on the day the guard is given up.`]: `من بردانس إلى الحارس. تشرب القرية من جديد يوم يُسلَّم الحارس.`,
  [`The elders have until dawn to choose. So do you.`]: `أمام الشيوخ حتى الفجر ليختاروا. وأمامك كذلك.`,
  // ---- Episode 6
  [`When this is done, I will tell the qadi what I did. All of it.`]: `حين ينتهي هذا، سأخبر القاضي بما فعلت. بكلّه.`,
  [`Bring yourself back, Salim. I cannot carry two of you.`]: `عُد بنفسك يا سالم. لا أقدر أن أحمل اثنين منكما.`,
  [`Light a lamp for him. I will be back before it burns down.`]: `أوقد له سراجًا. سأعود قبل أن ينطفئ.`,
  [`So the village did not give you up. Then I will take you myself.`]: `إذن لم تسلّمك القرية. سآخذك بنفسي.`,
  [`Dawn, guard. You are late, and the village is thirsty.`]: `الفجر أيها الحارس. تأخّرت، والقرية عطشى.`,
};
