// Round 21: Arabic for the text added this round (merged into STORY_AR, see story_ar.js)
export const AR21 = {
  // hired guards
  'Tamim': 'تميم', 'Talha': 'طلحة', 'Naft-thrower': 'رامي النفط', '\'Ayyar': 'عيّار',
  'Throws pots of naft that burn where they land. Fights from a few paces back.': 'يرمي جِرار النفط فتشتعل حيث تقع. يقاتل من خطوات إلى الوراء.',
  'Two knives and quick feet. Slips round to the foe\'s back and cuts.': 'سكّينان وقدمان خفيفتان. يتسلّل إلى ظهر العدوّ ويطعن.',
  'One fee, and he stays with you until you send him home. If he is beaten down, stand beside him to help him up. Give orders with his button or G.': 'أجرة واحدة، ويبقى معك حتى تصرفه. إن سقط فقف بجانبه لتُنهضه. أعطه الأوامر بزرّه أو بالحرف G.',
  'is down. Stand beside him to help him up.': 'سقط. قف بجانبه لتُنهضه.', 'is back on his feet': 'نهض على قدميه',
  // the rival and the lieutenants (Round 21)
  'Zubayr': 'زبير', 'The bowman on the dune': 'الرامي على الكثيب',
  'So the brother lived. I was paid for one arrow, not two.': 'إذن نجا الأخ. دُفع لي ثمن سهم واحد، لا سهمين.', 'You loosed it?': 'أنت رميتَه؟',
  'Ghassan paid. I shot. That is all it was.': 'دفع غسّان، ورميتُ. هذا كلّ ما في الأمر.',
  'Not today, guard. Ghassan\'s silver does not cover this.': 'ليس اليوم يا حارس. فضّة غسّان لا تكفي لهذا.',
  'Rawh pays better than Ghassan did.': 'روح يدفع أكثر ممّا دفع غسّان.', 'Then he wasted his silver.': 'إذن أضاع فضّته.',
  'The reeds will hide me. They hide everyone.': 'سيخفيني القصب. إنّه يخفي الجميع.',
  'One more job, and I go north for good.': 'عمل واحد بعد، ثمّ أمضي إلى الشمال إلى غير رجعة.', 'Then I will follow you north.': 'إذن سأتبعك إلى الشمال.',
  'If you want me, look for me in the Hamrin hills.': 'إن أردتني فابحث عنّي في جبال حمرين.',
  'Zubayr Is Gone North': 'رحل زبير إلى الشمال', 'He waits in the Hamrin hills': 'إنّه ينتظر في جبال حمرين',
  'Hooked! Evade as he strikes to slip the blow': 'علقتَ بالخطّاف! راوغ حين يضرب لتفلت من الضربة',
  'He is in the smoke. Watch for the glint, and evade': 'إنّه في الدخان. راقب البريق، وراوغ', 'Evaded': 'تفاديت',
  'No horses underground': 'لا خيل تحت الأرض', 'Horse (V)': 'الحصان (V)',
  // the Hamrin hills (Round 21)
  'The Hamrin Hills': 'جبال حمرين', 'The Hamrin hills': 'جبال حمرين', 'The Deserters\' Camp': 'مخيّم الفارّين', 'Holds in the Hills': 'معاقل في الجبال',
  'Ride north to the Hamrin hills': 'اركب شمالًا إلى جبال حمرين', 'North, to the Hamrin hills': 'شمالًا، إلى جبال حمرين', 'Ride back to the river quays': 'عُد راكبًا إلى أرصفة النهر',
  'The road north can wait until the copies have sailed': 'طريق الشمال ينتظر حتى تُبحر النُّسخ',
  'These hills were full of deserters after the siege: men from both armies, with nowhere to go and nothing to lose.': 'امتلأت هذه الجبال بالفارّين بعد الحصار: رجال من الجيشين، لا مأوى لهم ولا شيء يخسرونه.',
  'Rest by the fires inside, Salim. The men there will not fight fair, and the ground is worse.': 'استرح عند النيران في الداخل يا سالم. الرجال هناك لا يقاتلون بإنصاف، والأرض أسوأ منهم.',
  'Clear the Quarry Galleries': 'طهّر دهاليز المقلع', 'Take the Cliff Fort': 'استولِ على حصن الجُرف', 'Cross the Gorge Bridge': 'اعبر جسر الخانق', 'Find Zubayr in his hold': 'جِد زبيرًا في معقله',
  'Every hold is broken': 'سقطت المعاقل كلّها', 'Jabir\'s account is kept': 'حُفظ حساب جابر',
  'Asbagh': 'أصبغ', 'Kahmas': 'كهمس',
  'Salt traders waylaid': 'تجّار ملح في كمين', 'Deserters have stopped a salt caravan in the western gorge. Drive them off.': 'أوقف الفارّون قافلة ملح في الخانق الغربي. اطردهم.',
  'The shepherds\' fold is burning': 'حظيرة الرعاة تحترق', 'Raiders fired a fold in the southern valley to drive off the flock.': 'أضرم المغيرون النار في حظيرة بالوادي الجنوبي ليسوقوا القطيع.',
  'After the Siege': 'بعد الحصار', 'The Diyala': 'ديالى', 'Stone and Brick': 'الحجر والآجرّ',
  'A long, low ridge of limestone and sandstone north-east of Baghdad, cut by gorges where winter rain runs off to the Diyala. Shepherds grazed its valleys in spring; in bad years it gave shelter to anyone who did not want to be found.': 'سلسلة طويلة منخفضة من الحجر الجيري والرملي شماليّ شرق بغداد، تشقّها خوانق يجري فيها مطر الشتاء إلى ديالى. رعى الرعاة وديانها في الربيع، وفي السنين العجاف آوت كلّ من لا يريد أن يُعثر عليه.',
  'When Baghdad fell in 813 the armies that had fought over it did not simply go home. Unpaid soldiers of both sides, and the street fighters who had held the city, drifted into the countryside in bands. For years afterward the roads were not safe.': 'حين سقطت بغداد سنة 813 لم تعُد الجيوش التي تقاتلت عليها إلى ديارها ببساطة. جنود من الطرفين لم يُدفع لهم، ومقاتلو الأزقّة الذين أمسكوا المدينة، تفرّقوا في الريف عصاباتٍ. وظلّت الطرق غير آمنة سنين بعدها.',
  'The river comes down out of the Zagros, breaks through the Hamrin hills in a gorge and joins the Tigris below Baghdad. Canals off its lower course watered some of the richest land in the Sawad.': 'ينحدر النهر من جبال زاغروس، ويشقّ جبال حمرين في خانق، ويلتقي بدجلة أسفل بغداد. سقت القنوات المتفرّعة من مجراه الأدنى بعضًا من أخصب أراضي السواد.',
  'Baghdad was built of mud-brick and baked brick, but stone was quarried where it lay near the surface, for foundations, thresholds, millstones and the bases of columns. Cut blocks were levered out along their beds and dragged to the nearest water.': 'بُنيت بغداد باللَّبِن والآجرّ، لكنّ الحجر كان يُقطع حيث يقرب من سطح الأرض، للأسس والعتبات وأحجار الرحى وقواعد الأعمدة. كانت الكتل المقطوعة تُرفع بالعَتَلات على طول طبقاتها وتُجرّ إلى أقرب ماء.',
  'A band of deserters needed three things: water, a way out and a place that could be held by a few men. Old quarries, frontier forts and gorges crossed by a single plank way gave all three, which is why the same places were held again and again by whoever came through.': 'احتاجت عصابة الفارّين إلى ثلاثة أشياء: الماء، ومخرج، ومكان يحميه رجال قليلون. وكانت المقالع القديمة وحصون الثغور والخوانق التي يعبرها ممرّ خشبيّ واحد تعطي الثلاثة، ولذلك تداول السيطرةَ على الأماكن نفسها كلُّ من مرّ بها.',
  // the holds
  'The Quarry Galleries': 'دهاليز المقلع', 'Old workings in the western cliff': 'أشغال قديمة في الجرف الغربي', 'The Cliff Fort': 'حصن الجُرف', 'A border fort the deserters hold': 'حصن ثغر يمسكه الفارّون',
  'The Gorge Bridge': 'جسر الخانق', 'Plank ways across the ravine of the Diyala': 'ممرّات خشبية فوق وادي ديالى', 'Zubayr\'s Hold': 'معقل زبير', 'The bowman\'s ravine': 'وادي الرامي',
  'Sakhr': 'صخر', 'Master of the quarry gangs': 'سيّد عصابات المقلع', 'Ghaylan': 'غيلان', 'Overseer of the galleries': 'ناظر الدهاليز',
  'Shaddad': 'شدّاد', 'The shield of the fort': 'ترس الحصن', 'Jabala': 'جبلة', 'Commander of the cliff fort': 'قائد حصن الجُرف',
  'Dhuayb': 'ذؤيب', 'Keeper of the bridge': 'حارس الجسر', 'Hanzala': 'حنظلة', 'Master of the gorge': 'سيّد الخانق',
  'Nahshal': 'نهشل', 'Zubayr\'s naft-master': 'نفّاط زبير', 'The last of the men from the dune': 'آخر الرجال الذين كانوا على الكثيب',
  'Bring the face down on him!': 'أسقطوا الجرف عليه!', 'Every man to me!': 'كلّ رجل إليّ!', 'Close the wall!': 'سُدّوا الصفّ!', 'Archers! Fire on the yard!': 'أيّها الرماة! ارموا الساحة!',
  'Break the boards under him!': 'اكسروا الألواح تحته!', 'Cut the ropes. Let the gorge have him.': 'اقطعوا الحبال. ليأخذه الخانق.', 'Burn it all!': 'أحرقوا كلّ شيء!',
  'You will not see the next one coming.': 'لن ترى السهم القادم.', 'All this way, for one arrow?': 'كلّ هذا الطريق، من أجل سهم واحد؟', 'For my brother.': 'من أجل أخي.',
  'It was only ever the pay.': 'لم يكن الأمر إلّا الأجرة.', 'Another day.': 'يوم آخر.',
  'Defeat': 'اهزم', 'Enter': 'ادخل', 'cleared': 'طُهّر', 'Travel': 'انتقل', 'Leave': 'غادر', 'Leave the hold': 'غادر المعقل', 'Climb back out of the hold': 'اصعد خارج المعقل',
  'Campfire': 'نار المخيّم', 'Light the campfire': 'أشعل النار', 'Light the campfire ahead': 'أشعل النار التي أمامك', 'Rest at the campfire': 'استرح عند النار',
  'Campfire lit. You will wake here if you fall.': 'اشتعلت النار. ستصحو هنا إن سقطت.',
  'You rest. Wounds bound, sherbet filled. His men are back at their posts.': 'تستريح. ضُمّدت الجراح ومُلئ الشراب. وعاد رجاله إلى مواقعهم.',
  'Break through the cracked wall': 'اخترق الجدار المتصدّع', 'A hidden chamber': 'حجرة خفيّة', 'Lift the bar from the gate': 'ارفع المزلاج عن البوّابة',
  'Barred from the other side': 'مُغلقة من الجهة الأخرى', 'A shortcut back to the entrance': 'طريق مختصر إلى المدخل',
  'The way on is open. A fire waits ahead.': 'الطريق مفتوح. نار تنتظر أمامك.', 'The master of the hold still stands': 'سيّد المعقل ما زال واقفًا',
  'Open the master\'s chest': 'افتح صندوق السيّد', 'The hold is broken. Its master\'s chest is yours.': 'سقط المعقل. صندوق سيّده لك.',
  'Keep to the middle': 'الزم الوسط', 'The ropes are cut. Keep to the middle': 'قُطعت الحبال. الزم الوسط', 'Stunned': 'مصعوق',
  'Lock on (Tab)': 'التصويب (Tab)', 'Nothing to lock on to': 'لا شيء للتصويب عليه', 'Camel (V)': 'الجمل (V)', 'A cut gem': 'جوهرة مصقولة',
  // rift seasons, trial legendaries, recipes
  'This week': 'هذا الأسبوع', 'Season': 'الموسم', 'Season best': 'أفضل وقت في الموسم', 'a chance at a trial legendary': 'فرصة لأسطوريّة من التجارب',
  'Iron Ranks': 'صفوف الحديد', 'Foes have 30% more life': 'للأعداء حياة أكثر بنسبة 30%', 'Forced March': 'المسير الشاقّ',
  'Shield Wall': 'جدار التروس', 'Foes who fight hand to hand carry shields': 'من يقاتل من الأعداء عن قرب يحمل ترسًا',
  'Old Soldiers': 'الجنود القدامى', 'Foes are two levels higher, and pay 25% more': 'الأعداء أعلى بمستويين، ويدفعون أكثر بنسبة 25%',
  'Blood Price': 'ثمن الدم', 'Foes strike 25% harder; dinars +40%': 'يضرب الأعداء أشدّ بنسبة 25%؛ الدنانير +40%',
  'Short Fuse': 'الفتيل القصير', 'Twenty seconds less on the clock; Renown +10': 'عشرون ثانية أقلّ على الساعة؛ الصيت +10',
  'Hard Men': 'رجال أشدّاء', 'Foes are hard to stagger': 'يصعب ترنيح الأعداء',
  'Edge of the Breach': 'حدّ الثُّغرة', 'Coat of the Last Gate': 'درع الباب الأخير', 'Ring of the Water-Clock': 'خاتم الساعة المائية', 'Sapper\'s Cord': 'حبل النقّاب',
  '"It went first through the gap in the wall, and came back."': '«دخل الثغرة في السور أوّلًا، وعاد.»',
  '"The Khurasan gate held a day longer than the rest."': '«صمد باب خراسان يومًا أكثر من سائر الأبواب.»',
  '"Measured out in drops, like the clock the caliph sent to the Franks."': '«يُقاس قطرةً قطرة، كالساعة التي أهداها الخليفة إلى الفرنجة.»',
  '"Knotted by the men who dug under the walls."': '«عقده الرجال الذين نقبوا تحت الأسوار.»',
  'Aspect of the Breach': 'سمة الثُّغرة', 'You deal 40% more damage to captains and their like.': 'تُلحق ضررًا أكبر بنسبة 40% بالقادة ومن في منزلتهم.',
  'Aspect of the Last Gate': 'سمة الباب الأخير', 'Below 30% life you take 40% less damage.': 'تحت 30% من الحياة تتلقّى ضررًا أقلّ بنسبة 40%.',
  'Aspect of the Water-Clock': 'سمة الساعة المائية', 'Each kill takes 1 second off every skill.': 'كلّ قتلة تُنقص ثانية من كلّ مهارة.',
  'Aspect of the Sapper': 'سمة النقّاب', 'Drinking sherbet throws back and staggers foes within 4 metres.': 'شرب الشراب يدفع الأعداء ضمن 4 أمتار ويرنّحهم.',
  'Hindi Sayf': 'سيف هندي', 'Lamellar Jawshan': 'جوشن صفائحي', 'Silver Signet': 'خاتم فضّي',
  'Recipe': 'وصفة', 'recipes': 'وصفات', 'Set pieces': 'قطع الطقم', 'Forge the piece': 'اطرق القطعة', 'Bishr can now forge': 'يستطيع بشر الآن أن يطرق',
  'Captains, hold masters and dungeon chests sometimes carry recipe scrolls. Bring them here and Bishr will forge the set pieces they describe.': 'يحمل القادة وأسياد المعاقل وصناديق السراديب أحيانًا لفائف وصفات. أحضرها إلى هنا وسيطرق بشر قطع الطقم التي تصفها.',
  // hub life
  'The kennel and mews': 'المِربَض والمَصقَر', 'Saluki': 'سلوقي', 'Saker falcon': 'صقر حرّ',
  'A hunting hound of the desert Arabs: fast, quiet, and fond of anything that shines. He keeps clear of a fight and brings back the dinars that fall.': 'كلب صيد عند عرب البادية: سريع، هادئ، مولع بكلّ ما يلمع. يبتعد عن القتال ويعيد الدنانير التي تسقط.',
  'Sits on your arm in camp. In the country she circles overhead and marks men hiding in the reeds, and archers.': 'تجلس على ذراعك في المخيّم. وفي البرّية تحوم فوقك وتدلّ على المختبئين في القصب وعلى الرماة.',
  'Buy the saluki': 'اشترِ السلوقي', 'Buy the falcon': 'اشترِ الصقر', 'Bring him along': 'خذه معك', 'Leave him at the kennel': 'اتركه في المربض',
  'Take her with you': 'خذها معك', 'Leave her on the block': 'اتركها على مجثمها',
  'Cream': 'قشديّ', 'Red fawn': 'أحمر ظبيي', 'Black and tan': 'أسود وأسمر', 'Grizzle': 'أشهب',
  'The falcon marks men you cannot see': 'يدلّ الصقر على رجال لا تراهم',
  'The camp\'s needs': 'حاجات المخيّم', 'Ishaq keeps the camp\'s accounts. What you build here goes with the company to every camp.': 'يمسك إسحاق حسابات المخيّم. ما تبنيه هنا يرافق الجماعة إلى كلّ مخيّم.',
  'Mend the well': 'أصلح البئر', 'A new frame, rope and buckets. Carry one more sherbet; sherbet heals 15% more.': 'إطار جديد وحبل ودلاء. تحمل شرابًا إضافيًّا؛ ويشفي الشراب أكثر بنسبة 15%.',
  'Raise the stalls': 'أقم الدكاكين', 'Awnings and rugs for the traders. Yusuf\'s prices fall by a tenth.': 'مظلّات وبُسُط للتجّار. تنخفض أسعار يوسف بمقدار العُشر.',
  'Rebuild the forge': 'أعد بناء الكور', 'A brick hearth and bellows for Bishr. Tempering and forging cost a quarter less.': 'موقد من آجرّ ومنفاخ لبشر. يكلّف التطويع والطرق ربعًا أقلّ.',
  'Build': 'ابنِ', 'Done': 'تمّ', 'done': 'تمّ',
  'Fishing': 'الصيد', 'Fish here': 'اصطد هنا', 'Cast a line': 'ألقِ الخيط', 'Your catch': 'صيدك', 'Nothing caught yet.': 'لم تصطد شيئًا بعد.', 'Yusuf buys fish at the camp.': 'يشتري يوسف السمك في المخيّم.',
  'Cast, and wait for the float to go under. Strike at once, then play the fish: tap when the needle is in the green. Three good pulls land it; two bad ones and it is gone.': 'ألقِ الخيط وانتظر حتى تغوص العوّامة. اجذب فورًا، ثمّ صارع السمكة: انقر حين يكون المؤشّر في الأخضر. ثلاث جذبات جيّدة تُخرجها؛ وجذبتان سيّئتان تُفلتها.',
  'Grill and eat': 'اشوِ وكُل', 'Grilled': 'مشويًّا', 'min': 'د', 'You have eaten': 'أكلت', 'The meal has worn off': 'زال أثر الوجبة',
  'Wait for a bite…': 'انتظر أن تعضّ السمكة…', 'A bite! Strike!': 'عضّة! اجذب!', 'Strike': 'اجذب', 'Pull': 'اسحب', 'Play the fish!': 'صارع السمكة!', 'Landed': 'اصطدت',
  'Too soon: it took fright': 'مبكرًا جدًّا: فزعت', 'Too slow: it took the bait and went': 'بطيئًا جدًّا: أخذت الطُّعم ومضت', 'The line went slack: it got away': 'ارتخى الخيط: أفلتت',
  'Himri': 'حِمري', 'Bunni': 'بُنّي', 'Shilig': 'شِلِك', 'Shabbut': 'شَبّوط',
  '+3 regeneration': '+3 تجدّد', '+10% maximum life': '+10% أقصى الحياة', '+8% movement': '+8% سرعة الحركة', '+12% damage': '+12% ضرر',
  // the five item sets and their pieces (Rounds 6 and 18), the Craft switch, the map walk
  'Garb of the Barid': 'زيّ البريد', 'Courier\'s Qaba': 'قباء البريدي', 'Courier\'s Qalansuwa': 'قلنسوة البريدي', 'Courier\'s Seal': 'خاتم البريدي', 'Courier\'s Token': 'شارة البريدي',
  'Harness of Khurasan': 'عُدّة خراسان', 'Khurasani Jawshan': 'جوشن خراساني', 'Khurasani Bayda': 'بيضة خراسانية', 'Khurasani Ring': 'خاتم خراساني', 'Khurasani Pendant': 'قلادة خراسانية',
  'Panoply of the Abna\'': 'عُدّة الأبناء', 'Abna\' Lamellar': 'صفائح الأبناء', 'Abna\' Bayda': 'بيضة الأبناء', 'Abna\' Signet': 'ختم الأبناء', 'Abna\' Badge': 'شارة الأبناء',
  'Outfit of the Basra Nakhuda': 'كسوة ناخذاة البصرة', 'Nakhuda\'s Coat': 'قباء الناخذاة', 'Nakhuda\'s Turban': 'عمامة الناخذاة', 'Nakhuda\'s Seal': 'خاتم الناخذاة', 'Nakhuda\'s Compass-stone': 'حجر الهداية للناخذاة',
  'Tools of the Warraq': 'أدوات الورّاق', 'Warraq\'s Apron': 'مئزر الورّاق', 'Warraq\'s Cap': 'طاقية الورّاق', 'Warraq\'s Pen-ring': 'خاتم قلم الورّاق', 'Warraq\'s Inkwell': 'محبرة الورّاق',
  'Rare to order': 'نادرة حسب الطلب', 'Walking': 'في الطريق', 'Walking to the marker': 'إلى العلامة',
};
