// Round 22: Arabic for the text added this round (merged into STORY_AR, see story_ar.js)
export const AR22 = {
  // the act holds
  'The Sand-Choked Khan': 'الخان الذي ابتلعه الرمل', 'A caravan station the dunes took back': 'محطّة قوافل استعادتها الكثبان',
  'The Kiln Pits': 'حُفَر الأتون', 'Clay pits under the kilns, where the Pages burn': 'حُفَر الطين تحت الأتون، حيث تحترق الأوراق',
  'The Reed Islands': 'جزر القصب', 'Reed halls on mounds above the channels': 'مضايف من القصب على تلال فوق القنوات',
  'The Sunken Weir': 'السدّ الغارق', 'The broken Sasanian dam and the race below it': 'السدّ الساساني المكسور والمجرى تحته',
  'The Burned Lanes': 'الأزقّة المحترقة', 'Gutted houses behind the paper-sellers': 'بيوت محترقة خلف الورّاقين',
  'The Merchants\' Undercroft': 'أقبية التجّار', 'Brick vaults under the burned khans': 'أقبية من الآجرّ تحت الخانات المحترقة',
  'The Beached Hulk': 'السفينة الجانحة', 'A river hulk run aground by the boatyard': 'سفينة نهرية قديمة جنحت عند دار الصناعة',
  'The Bale Stores': 'مخازن البالات', 'Warehouses of bales and timber on the quay': 'مخازن البالات والخشب على الرصيف',
  // their captains
  'Jasir': 'جاسر', 'Who strips the caravans': 'الذي يسلب القوافل', 'Daghfal': 'دغفل', 'Master of the sand-choked khan': 'سيّد الخان الذي ابتلعه الرمل',
  'Kurz': 'كرز', 'Foreman of the kiln fires': 'رئيس نيران الأتون', 'Khalaf': 'خلف', 'Keeper of the clay pits': 'حارس حُفَر الطين',
  'Ruhm': 'رُهم', 'Who nets the channels': 'الذي ينصب الشباك في القنوات', 'Bakkar': 'بكّار', 'Headman of the reed islands': 'شيخ جزر القصب',
  'Qa\'nab': 'قعنب', 'Keeper of the sluices': 'حارس البوّابات', 'Jahdar': 'جحدر', 'Master of the weir': 'سيّد السدّ',
  'Nawfal': 'نوفل', 'Who torched the lane': 'الذي أحرق الزقاق', 'Dirgham': 'ضرغام', 'Captain of the burned lanes': 'قائد الأزقّة المحترقة',
  'Musawir': 'مساور', 'Who keeps the vault keys': 'حافظ مفاتيح الأقبية', 'Raddad': 'ردّاد', 'Master of the undercroft': 'سيّد الأقبية',
  'Shuja\'': 'شجاع', 'Bosun of the hulk': 'نوتيّ السفينة', 'Tha\'laba': 'ثعلبة', 'Master of the hulk': 'سيّد السفينة',
  'Hurmuz': 'هرمز', 'Keeper of the bale stores': 'حارس مخازن البالات', 'Marzuq': 'مرزوق', 'Master of the warehouses': 'سيّد المخازن',
  'Bring the roof down on him!': 'أسقطوا السقف عليه!', 'Up on the walls! Shoot!': 'إلى الأسوار! ارموا!', 'Feed the fires!': 'أطعموا النيران!',
  'Break the ground under him!': 'اكسروا الأرض تحته!', 'Into the water with him!': 'ألقوه في الماء!', 'Burn the reeds behind him!': 'أحرقوا القصب خلفه!',
  'Open the sluice!': 'افتحوا البوّابة!', 'Men of the weir, to me!': 'يا رجال السدّ، إليّ!', 'Let it all burn again!': 'لتحترق كلّها من جديد!',
  'Bring the house down!': 'أسقطوا البيت!', 'Bar the doors!': 'أغلقوا الأبواب!', 'Drop the vault on him!': 'أسقطوا القبو عليه!',
  'Cut him loose into the river!': 'اقطعوا الحبال وألقوه في النهر!', 'Crossbows, from the rail!': 'النشّابون، من الحاجز!', 'Bring the stacks down!': 'أسقطوا الأكوام!', 'Fire the bales!': 'أشعلوا البالات!',
  // puzzles
  'Pull the lever': 'اسحب الرافعة', 'Push the loose stones': 'ادفع الحجارة المخلخلة', 'The stones give way. A hidden way': 'انهارت الحجارة. ممرّ خفيّ',
  'Somewhere a portcullis grinds up': 'في مكان ما ترتفع بوّابة حديدية', 'Boards rise out of the drop': 'ترتفع الألواح من الهوّة',
  // the old set pieces (Rounds 6 and 18), still English until now
  'Garb of the Barid': 'لباس البريد', 'Courier\'s Qaba': 'قباء البريدي', 'Courier\'s Qalansuwa': 'قلنسوة البريدي', 'Courier\'s Seal': 'خاتم البريدي', 'Courier\'s Token': 'علامة البريدي',
  'Harness of Khurasan': 'عدّة خراسان', 'Khurasani Jawshan': 'جوشن خراساني', 'Khurasani Bayda': 'بيضة خراسانية', 'Khurasani Ring': 'خاتم خراساني', 'Khurasani Pendant': 'قلادة خراسانية',
  'Panoply of the Abna\'': 'عدّة الأبناء', 'Abna\' Lamellar': 'درع الأبناء', 'Abna\' Bayda': 'بيضة الأبناء', 'Abna\' Signet': 'خاتم الأبناء', 'Abna\' Badge': 'شارة الأبناء',
  'Outfit of the Basra Nakhuda': 'ثياب ناخذة البصرة', 'Nakhuda\'s Coat': 'معطف الناخذة', 'Nakhuda\'s Turban': 'عمامة الناخذة', 'Nakhuda\'s Seal': 'خاتم الناخذة', 'Nakhuda\'s Compass-stone': 'حجر بوصلة الناخذة',
  'Tools of the Warraq': 'أدوات الورّاق', 'Warraq\'s Apron': 'مئزر الورّاق', 'Warraq\'s Cap': 'قلنسوة الورّاق', 'Warraq\'s Pen-ring': 'خاتم قلم الورّاق', 'Warraq\'s Inkwell': 'محبرة الورّاق',
  'Walking': 'في الطريق', 'Rawh\'s boatmaster': 'رئيس قوارب روح', 'Holder of the copyists\' boat': 'حابس قارب النسّاخ',
  'Find Hisham at the bottom of the kiln pits': 'اعثر على هشام في قاع حُفَر الأتون', 'Take Rawh\'s boats from Sahl on the reed islands': 'خذ قوارب روح من سهل في جزر القصب',
  'Drive Layth from the burned lanes behind the paper-sellers': 'اطرد ليثًا من الأزقّة المحترقة خلف الورّاقين', 'Free the copyists\' boat from Mus\'ab on the beached hulk': 'حرّر قارب النسّاخ من مصعب على السفينة الجانحة',
  // gameplay (Round 22)
  'Leader': 'قائد', 'They falter': 'تزعزعوا', 'Hookman': 'صاحب الكلّاب', 'Shield-bearer': 'حامل الترس', 'Sling-lad': 'فتى المقلاع', 'Hooked': 'علقتَ', 'Guard broken': 'انكسر دفاعه',
  'Camera': 'الكاميرا', 'Overhead': 'من الأعلى', 'Close (behind the shoulder)': 'قريبة (خلف الكتف)', 'Difficulty': 'الصعوبة', 'Story': 'القصّة', 'Normal': 'عادية', 'Hard': 'صعبة',
  // level-25 skills
  'Shield Rush': 'اندفاعة الترس', 'Rush 7 m behind your shield, knocking foes aside and staggering them': 'اندفع سبعة أمتار خلف ترسك فتُزيح الأعداء وتزعزعهم',
  'Piercing Shot': 'الرمية النافذة', 'A heavy arrow that passes through every foe in a line': 'سهم ثقيل ينفذ من كلّ عدوّ في خطّ واحد',
  'Wall of Fire': 'جدار النار', 'Naft poured in a line across the ground, burning for 5 seconds': 'نفط يُسكب في خطّ على الأرض ويحترق خمس ثوانٍ',
  'Shadow Step': 'خطوة الظلّ', 'Step through the shadows to a foe\'s back and strike a sure critical blow': 'اعبر الظلال إلى ظهر عدوّ واضرب ضربة حاسمة أكيدة',
  // codex
  'Khans on the Road': 'خانات الطريق', 'Clay for the Kilns': 'طين الأتون', 'Islands of Reed': 'جزر القصب', 'The Old Weirs': 'السدود القديمة',
  'After the Fire': 'بعد الحريق',
  'Along the main roads stood walled stations where caravans could water their animals and sleep behind a gate. When trade stopped, as it did in the years of the siege, the sand and the thieves moved in.': 'على الطرق الكبرى قامت محطّات مسوّرة تسقي فيها القوافل دوابّها وتبيت خلف بوّابة. فلمّا توقّفت التجارة، كما حدث في سنوات الحصار، دخلها الرمل واللصوص.',
  'Brick-makers dug their clay close to the kilns, leaving deep pits that filled with water in winter. Old pits were often used as dumps, or as hiding places by men who knew the ground.': 'حفر صنّاع الآجرّ طينهم قرب الأتون، فتركوا حُفَرًا عميقة تمتلئ بالماء في الشتاء. وكثيرًا ما صارت الحُفَر القديمة مطارح للنفايات، أو مخابئ لرجال يعرفون الأرض.',
  'In the marshes villages stood on mounds built up from layers of reed and mud. A family could raise a new island in a season; whole settlements moved as the water rose and fell.': 'في البطائح قامت القرى على تلال من طبقات القصب والطين. كانت الأسرة تبني جزيرة جديدة في موسم واحد، وكانت مستوطنات كاملة تنتقل مع ارتفاع الماء وانخفاضه.',
  'Sasanian engineers dammed the rivers of the Sawad with weirs of fired brick and stone, raising the water to feed the canals. Many were broken in the floods and wars of later centuries and never mended.': 'سدّ مهندسو الساسانيين أنهار السواد بسدود من الآجرّ والحجر، يرفعون بها الماء ليغذّي القنوات. وتكسّر كثير منها في فيضانات القرون اللاحقة وحروبها ولم يُرمَّم قطّ.',
  'The siege of 812–813 left whole quarters of western Baghdad burned. Survivors came back to roofless houses and fallen cellars, and for a time the ruins belonged to whoever held them.': 'خلّف حصار 812–813 أحياءً كاملة من غرب بغداد محترقة. عاد الناجون إلى بيوت بلا سقوف وأقبية منهارة، وصارت الخرائب حينًا لمن يمسكها.',
  'Merchants stored their goods in brick vaults beneath the khans, cool in summer and safe from fire. When the buildings above burned, the vaults often survived, full of whatever had been left behind.': 'خزّن التجّار بضائعهم في أقبية من الآجرّ تحت الخانات، باردة في الصيف آمنة من النار. فلمّا احترقت المباني فوقها بقيت الأقبية غالبًا، مملوءة بما تُرك فيها.',
  'Old river craft that could no longer be trusted on the water were run aground and used as stores, workshops or homes. Their timber was worth more than the rest of the boat.': 'كانت المراكب النهرية القديمة التي لم يعد يُؤمن عليها في الماء تُجنَّح وتُتّخذ مخازن أو مشاغل أو بيوتًا. وكان خشبها أثمن من بقيّة المركب.',
  'Cotton, linen and wool came down the Tigris in bales and were stacked in warehouses on the quays. A warehouse of bales was a fortune, and a fire risk, in equal measure.': 'كان القطن والكتّان والصوف تنحدر في دجلة بالات تُرصّ في المخازن على الأرصفة. وكان مخزن البالات ثروة، وخطر حريق، بالقدر نفسه.',
  'Trade': 'تجارة', 'Craft': 'صنعة', 'Places': 'أماكن', 'War': 'حرب',
 'Under the Khans': 'تحت الخانات', 'River Hulks': 'السفن الجانحة', 
};
