// Round 30: Arabic for the phone pass, the map markers, the camp men's tasks, the new troops and grounds (merged last in story_ar.js)
export const AR30 = {
  // map markers
  'A task is offered here': 'هنا مهمّة تُعرَض', 'Someone to meet': 'شخص تلقاه', 'Return here': 'عُد إلى هنا', 'The task leads here': 'المهمّة تقود إلى هنا',
  'Track': 'تتبّع', 'Stop tracking': 'أوقف التتبّع',
  // the big map had never been translated
  'No way there': 'لا طريق إلى هناك', 'Waypoint found': 'وجدتَ محطّة', 'Tap to walk · tap a waypoint to travel': 'المس لتمشي · المس محطّة لتسافر إليها',
  'Walk there': 'امشِ إلى هناك', 'Fast travel': 'سفر سريع', 'Not yet found': 'لم تجدها بعد', 'Qanat Shaft': 'بئر القناة', 'Contracts Board': 'لوح العقود',
  'falls': 'يسقط',
  'The Village': 'القرية', 'Old Caravanserai': 'الخان القديم', 'Kiln Yard': 'ساحة الأفران', 'Persian Arch': 'الطاق الفارسي',
  'Reed Village': 'قرية القصب', 'Reed Camp': 'مخيّم القصب', 'Fish Racks': 'مناشر السمك', 'Old Weir': 'السدّ القديم',
  'The Khan': 'الخان', 'Burned Suq': 'السوق المحروق', 'Paper-Sellers\' Lane': 'درب الورّاقين',
  // the camp men's own tasks
  'Not now. Show me your trade.': 'ليس الآن. أرني بضاعتك.',
  'The Ledger of Debts': 'دفتر الديون', 'Iron for the Bridge': 'حديد للجسر', 'The Last Line': 'الصفّ الأخير',
  'Under the floor of my old stall in the burned suq I kept a ledger. Every debt in this quarter, forty years of them. Krateros\' men are digging the ruins for silver. If they find that book, they will sell the debts to the worst men in Baghdad.': 'تحت أرضيّة دكّاني القديم في السوق المحروق خبّأت دفترًا. كلّ دَين في هذا الحيّ، أربعون سنة منها. رجال كراتيروس ينبشون الخرائب بحثًا عن الفضّة. إن وجدوا ذلك الدفتر باعوا الديون لأسوأ رجال بغداد.',
  'Drive Krateros\' diggers out of the ruins of Yusuf\'s stall in the burned suq.': 'اطرد نبّاشي كراتيروس من خرائب دكّان يوسف في السوق المحروق.',
  'The floor was dug up and the ledger is gone. A water-carrier was seen running from the ruins; find him.': 'نُبشت الأرضيّة وذهب الدفتر. شوهد سقّاء يركض من الخرائب؛ جِده.',
  'Speak with \'Abbad': 'كلّم عبّادًا', '\'Abbad': 'عبّاد', 'Water-carrier': 'سقّاء',
  'The ledger? I have it. I pulled it out before the soldiers came.': 'الدفتر؟ هو معي. أخرجته قبل أن يأتي الجند.',
  'My own name is in it. Twelve dirhams, for my daughter\'s wedding, two years ago. I meant to burn that page. I could not do it.': 'اسمي فيه أيضًا. اثنا عشر درهمًا لعرس ابنتي، قبل سنتين. أردت أن أحرق تلك الصفحة. لم أقدر.',
  'Yusuf asked for his book back, not for your debt.': 'يوسف طلب دفتره، لا دَينك.',
  'Then let him read it himself. But the diggers\' captain knows I took it. His men are camped by the canal.': 'فليقرأه بنفسه إذن. لكنّ قائد النبّاشين يعرف أنّي أخذته. رجاله مخيّمون عند النهر.',
  'Break the diggers\' camp by the canal before they hunt the water-carrier down.': 'فرّق مخيّم النبّاشين عند النهر قبل أن يطاردوا السقّاء.',
  'Bring Yusuf his ledger, and tell him who saved it.': 'أعِد إلى يوسف دفتره، وأخبره من أنقذه.',
  'Your ledger. A water-carrier, \'Abbad, saved it from the diggers. His name is in it.': 'دفترك. سقّاء اسمه عبّاد أنقذه من النبّاشين. اسمه فيه.',
  'Twelve dirhams, for a wedding. ... Forty years of debts, and half the people in this book are dead, or ruined by the siege.': 'اثنا عشر درهمًا لعرس... أربعون سنة من الديون، ونصف من في هذا الدفتر ماتوا أو أفقرهم الحصار.',
  'Hand me that lamp. ... There. Now nobody in al-Karkh owes Yusuf a single dirham. It is the best trade I ever made.': 'ناولني ذلك المصباح... هكذا. الآن لا أحد في الكرخ يدين ليوسف بدرهم واحد. إنّها أربح تجارة عقدتها.',
  'Yusuf burned his ledger. The quarter owes him nothing.': 'أحرق يوسف دفتره. لا يدين له الحيّ بشيء.',
  'The Bridge of Boats has been held together with rope since the siege. Its chains went into Tahir\'s engines. There is a barge of iron bars at the boatyard, and Arsaber\'s men sit on it like hens on eggs. Bring me that iron and I will forge the bridge new chains.': 'جسر السفن مربوط بالحبال منذ الحصار. ذهبت سلاسله إلى مجانيق طاهر. في دار الصناعة صندل محمّل بقضبان الحديد، ورجال أرسابر جاثمون عليه كالدجاج على البيض. أحضر لي ذلك الحديد وسأطرق للجسر سلاسل جديدة.',
  'Take the barge of iron bars back from Arsaber\'s men at the boatyard.': 'استردّ صندل الحديد من رجال أرسابر في دار الصناعة.',
  'Take the iron bars': 'خذ قضبان الحديد', 'Iron Bars': 'قضبان الحديد',
  'Bishr will need hands. Find the old chain-maker who lives by the warehouses.': 'سيحتاج بشر إلى أيدٍ. جِد صانع السلاسل العجوز الساكن عند المخازن.',
  'Speak with Mukhariq': 'كلّم مُخارقًا', 'Mukhariq': 'مُخارق', 'Chain-maker': 'صانع السلاسل',
  'Bishr has iron? Then he will need hands. I made the old bridge chains, before the siege took them for the engines.': 'عند بشر حديد؟ إذن سيحتاج إلى أيدٍ. أنا صنعت سلاسل الجسر القديمة، قبل أن يأخذها الحصار للمجانيق.',
  'Then come and make them again.': 'فتعال واصنعها من جديد.',
  'My tools are in my old shop by the south slips. Arsaber\'s men keep it as a guardhouse now.': 'أدواتي في دكّاني القديم عند المزالق الجنوبيّة. رجال أرسابر جعلوه مخفرًا.',
  'Clear Arsaber\'s guardhouse out of the chain-maker\'s shop by the south slips.': 'أخلِ مخفر أرسابر من دكّان صانع السلاسل عند المزالق الجنوبيّة.',
  'Bring Bishr his iron and a chain-maker with his tools.': 'أحضر لبشر حديده وصانع سلاسل بأدواته.',
  'Your iron. And a chain-maker, with his tools.': 'حديدك. وصانع سلاسل بأدواته.',
  'Mukhariq! I thought the river had you, with the rest of them.': 'مُخارق! ظننت النهر أخذك مع الباقين.',
  'Twelve links a day, the two of us. The bridge will hold by the spring floods. Then this city can walk to work again.': 'اثنتا عشرة حلقة في اليوم، نحن الاثنين. سيصمد الجسر قبل فيضان الربيع. وتمشي هذه المدينة إلى أعمالها من جديد.',
  'Bishr and Mukhariq forge the bridge\'s chains.': 'بشر ومُخارق يطرقان سلاسل الجسر.',
  'There is a man in these hills who stood beside me at the Anbar gate. Hasan. We held a line for al-Amin together, and when it broke he ran north. The shepherds say he leads a band on the salt road now. Find him before the company does. I want to speak to him once.': 'في هذه التلال رجل وقف إلى جانبي عند باب الأنبار. حسن. ثبتنا معًا في الصفّ للأمين، ولمّا انكسر الصفّ هرب شمالًا. يقول الرعاة إنّه يقود عصابة على طريق الملح الآن. جِده قبل أن تجده الكتيبة. أريد أن أكلّمه مرّة واحدة.',
  'Find Hasan, \'Amr\'s old comrade, in the western hills.': 'جِد حسنًا، رفيق عمرو القديم، في التلال الغربيّة.',
  'Speak with Hasan': 'كلّم حسنًا', 'Hasan': 'حسن', 'Deserter': 'فارّ من الجند',
  '\'Amr sent you? Tell him I am not coming down to be lectured.': 'عمرو أرسلك؟ قل له إنّي لن أنزل لأسمع موعظة.',
  'He wants to talk. That is all.': 'يريد أن يتكلّم. هذا كلّ شيء.',
  'My men are not my men. They take what they want, and I keep them from taking worse. Durayd and his lot in the gorge are the worst. While they ride, I cannot leave.': 'رجالي ليسوا رجالي. يأخذون ما يريدون، وأمنعهم من أخذ ما هو أسوأ. دُريد وجماعته في الوادي أسوأهم. ما داموا يركبون لا أستطيع الرحيل.',
  'Break Durayd\'s riders in the western gorge, so Hasan can leave his band.': 'اكسر فرسان دُريد في الوادي الغربيّ، ليستطيع حسن ترك عصابته.',
  'Durayd': 'دُريد',
  'Tell \'Amr that Hasan is free to come down.': 'أخبر عمرًا أنّ حسنًا حرّ في النزول.',
  'Durayd\'s riders are broken. Hasan can come down, if he wants to.': 'انكسر فرسان دُريد. يستطيع حسن أن ينزل، إن شاء.',
  'He came to the camp at dawn. We did not say much. We stood at the drill post and watched Nasim hold a line.': 'جاء إلى المخيّم عند الفجر. لم نقل الكثير. وقفنا عند عمود التدريب نراقب نسيمًا يثبت في الصفّ.',
  'He will teach the shepherds\' boys the sling. Two old men, holding something worth holding. Thank you, Salim.': 'سيعلّم صبيان الرعاة المقلاع. عجوزان يثبتان على شيء يستحقّ الثبات. شكرًا يا سالم.',
  '\'Amr and Hasan teach the camp\'s boys together.': 'عمرو وحسن يعلّمان صبيان المخيّم معًا.',
  'Trypes': 'تريبيس', 'Maleinos': 'مالينوس', 'Kamytzes': 'كاميتزيس',
  // their farewells in the epilogue
  'I keep a new ledger now. One page. It says: nobody owes Yusuf anything. \'Abbad the water-carrier brings me a jar every morning anyway.': 'عندي دفتر جديد الآن. صفحة واحدة. مكتوب فيها: لا أحد يدين ليوسف بشيء. ومع ذلك يأتيني عبّاد السقّاء بجرّة كلّ صباح.',
  'Mukhariq and I hung the last chain on the Bridge of Boats yesterday. Walk across it on your way home. Slowly. Admire it.': 'علّقت أنا ومُخارق آخر سلسلة على جسر السفن أمس. اعبره في طريقك إلى البيت. على مهل. وتأمّله.',
  'Hasan sends his greeting. He would not come into the city. Some men hold a line better from the hills.': 'حسن يبعث بسلامه. لم يرضَ أن يدخل المدينة. بعض الرجال يثبتون في الصفّ أحسن من التلال.',
  // the new troops
  'Kontophoros': 'الرامح الفارس', 'Kynegos': 'صاحب الكلاب', 'War Dog': 'كلب الحرب', 'Unhorsed Kontophoros': 'رامح فارس سقط عن فرسه',
  'A lancer charges down a marked lane: step out of it, then strike as he wheels': 'الرامح الفارس يندفع في ممرّ معلَّم: اخرج منه، ثمّ اضرب وهو يستدير',
  'A dog handler: cut him down and his dogs will run': 'صاحب كلاب: أسقطه وتهرب كلابه', 'Ridden down!': 'دهسه الفرس!',
};
